/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Accessibility module

 (c) 2010-2019 Highsoft AS
 Author: Oystein Moseng

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/modules/accessibility",["highcharts"],function(n){f(n);f.Highcharts=n;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function n(d,f,l,h){d.hasOwnProperty(f)||(d[f]=h.apply(null,l))}f=f?f._modules:{};n(f,"modules/accessibility/KeyboardNavigationHandler.js",[f["parts/Globals.js"]],function(d){function f(d,b){this.chart=d;this.keyCodeMap=
b.keyCodeMap||[];this.validate=b.validate;this.init=b.init;this.terminate=b.terminate;this.response={success:1,prev:2,next:3,noHandler:4,fail:5}}var l=d.find;f.prototype={run:function(d){var b=d.which||d.keyCode,a=this.response.noHandler,c=l(this.keyCodeMap,function(a){return-1<a[0].indexOf(b)});c?a=c[1].call(this,b,d):9===b?a=this.response[d.shiftKey?"prev":"next"]:27===b&&(this.chart&&this.chart.tooltip&&this.chart.tooltip.hide(0),a=this.response.success);return a}};return f});n(f,"modules/accessibility/AccessibilityComponent.js",
[f["parts/Globals.js"]],function(d){function f(){}var l=d.win,h=l.document,b=d.merge,a=d.addEvent;f.prototype={initBase:function(a){this.chart=a;this.eventRemovers=[];this.domElements=[];this.keyCodes={left:37,right:39,up:38,down:40,enter:13,space:32,esc:27,tab:9};this.hiddenStyle={position:"absolute",width:"1px",height:"1px",overflow:"hidden"}},addEvent:function(){var a=d.addEvent.apply(d,arguments);this.eventRemovers.push(a);return a},createElement:function(){var a=d.win.document.createElement.apply(d.win.document,
arguments);this.domElements.push(a);return a},cloneMouseEvent:function(a){if("function"===typeof l.MouseEvent)return new l.MouseEvent(a.type,a);if(h.createEvent){var b=h.createEvent("MouseEvent");if(b.initMouseEvent)return b.initMouseEvent(a.type,a.canBubble,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.button,a.relatedTarget),b;b=h.createEvent("Event");if(b.initEvent)return b.initEvent(a.type,!0,!0),b}},fakeClickEvent:function(a){if(a&&
a.onclick&&h.createEvent){var b=h.createEvent("Event");b.initEvent("click",!0,!1);a.onclick(b)}},createProxyButton:function(c,e,k,d,g){var m=c.element,v=this,p=this.createElement("button"),h=b({"aria-label":m.getAttribute("aria-label")},k);if(c=this.getElementPosition(d||c))return Object.keys(h).forEach(function(a){null!==h[a]&&p.setAttribute(a,h[a])}),b(!0,p.style,{"border-width":0,"background-color":"transparent",position:"absolute",width:(c.width||1)+"px",height:(c.height||1)+"px",display:"block",
cursor:"pointer",overflow:"hidden",outline:"none",opacity:.001,filter:"alpha(opacity\x3d1)","-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity\x3d1)",zIndex:999,padding:0,margin:0,left:c.x+"px",top:c.y-this.chart.containerHeight+"px"}),g&&a(p,"click",g),["click","mouseover","mouseenter","mouseleave","mouseout"].forEach(function(g){a(p,g,function(a){var b=v.cloneMouseEvent(a);if(m)if(b)m.fireEvent?m.fireEvent(b):m.dispatchEvent&&m.dispatchEvent(b);else if(m["on"+g])m["on"+g](a)})}),e.appendChild(p),
h["aria-hidden"]||this.unhideElementFromScreenReaders(p),p},getElementPosition:function(a){var b=a.element;if((a=this.chart.renderTo)&&b&&b.getBoundingClientRect)return b=b.getBoundingClientRect(),a=a.getBoundingClientRect(),{x:b.left-a.left,y:b.top-a.top,width:b.right-b.left,height:b.bottom-b.top}},addProxyGroup:function(a){var b=this.chart;b.a11yProxyContainer||(b.a11yProxyContainer=h.createElement("div"),b.a11yProxyContainer.style.position="relative");b.container.nextSibling!==b.a11yProxyContainer&&
b.renderTo.insertBefore(b.a11yProxyContainer,b.container.nextSibling);var c=this.createElement("div");Object.keys(a||{}).forEach(function(b){null!==a[b]&&c.setAttribute(b,a[b])});b.a11yProxyContainer.appendChild(c);return c},removeElement:function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},unhideElementFromScreenReaders:function(a){a.setAttribute("aria-hidden",!1);a!==this.chart.renderTo&&a.parentNode&&(Array.prototype.forEach.call(a.parentNode.childNodes,function(a){a.hasAttribute("aria-hidden")||
a.setAttribute("aria-hidden",!0)}),this.unhideElementFromScreenReaders(a.parentNode))},destroyBase:function(){var a=this;this.removeElement((this.chart||{}).a11yProxyContainer);this.eventRemovers.forEach(function(a){a()});this.domElements.forEach(function(b){a.removeElement(b)});this.eventRemovers=[];this.domElements=[]},stripTags:function(a){return"string"===typeof a?a.replace(/<\/?[^>]+(>|$)/g,""):a},htmlencode:function(a){return a.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,
"\x26quot;").replace(/'/g,"\x26#x27;").replace(/\//g,"\x26#x2F;")},init:function(){},getKeyboardNavigation:function(){},onChartUpdate:function(){},onChartRender:function(){},destroy:function(){this.destroyBase()}};return f});n(f,"modules/accessibility/KeyboardNavigation.js",[f["parts/Globals.js"],f["modules/accessibility/KeyboardNavigationHandler.js"]],function(d,f){function l(a,b,c){this.init(a,b,c)}var h=d.merge,b=d.addEvent,a=d.win,c=a.document;l.prototype={init:function(a,k){var e=this;this.chart=
a;this.components=k;this.modules=[];this.currentModuleIx=0;a.container.hasAttribute("tabIndex")||a.container.setAttribute("tabindex","0");this.addExitAnchor();this.unbindKeydownHandler=b(a.renderTo,"keydown",function(a){e.onKeydown(a)});this.unbindMouseUpHandler=b(c,"mouseup",function(){e.onMouseUp()});this.update();this.modules.length&&this.modules[0].init(1)},update:function(a){var b=this.chart.options.accessibility,b=b&&b.keyboardNavigation,c=this.components;b&&b.enabled&&a&&a.length?this.modules=
a.reduce(function(a,b){b=c[b].getKeyboardNavigation();return b.length?a.concat(b):(a.push(b),a)},[new f(this.chart,{})]):(this.modules=[],this.currentModuleIx=0)},onMouseUp:function(){if(!(this.keyboardReset||this.chart.pointer&&this.chart.pointer.chartPosition)){var a=this.chart,b=this.modules&&this.modules[this.currentModuleIx||0];b&&b.terminate&&b.terminate();a.focusElement&&a.focusElement.removeFocusBorder();this.currentModuleIx=0;this.keyboardReset=!0}},onKeydown:function(b){b=b||a.event;var c,
e=this.modules&&this.modules.length&&this.modules[this.currentModuleIx];this.keyboardReset=!1;if(e){var g=e.run(b);g===e.response.success?c=!0:g===e.response.prev?c=this.prev():g===e.response.next&&(c=this.next());c&&b.preventDefault()}},prev:function(){return this.move(-1)},next:function(){return this.move(1)},move:function(a){var b=this.modules&&this.modules[this.currentModuleIx];b&&b.terminate&&b.terminate(a);this.chart.focusElement&&this.chart.focusElement.removeFocusBorder();this.currentModuleIx+=
a;if(b=this.modules&&this.modules[this.currentModuleIx]){if(b.validate&&!b.validate())return this.move(a);if(b.init)return b.init(a),!0}this.currentModuleIx=0;0<a?(this.exiting=!0,this.exitAnchor.focus()):this.chart.renderTo.focus();return!1},addExitAnchor:function(){var e=this.chart,k=this.exitAnchorWrapper=c.createElement("div"),d=this.exitAnchor=c.createElement("h6"),g=this,m=e.langFormat("accessibility.svgContainerEnd",{chart:e});k.setAttribute("aria-hidden","false");k.setAttribute("class","highcharts-exit-anchor-wrapper");
k.style.position="relative";k.style.outline="none";d.setAttribute("tabindex","0");d.setAttribute("aria-label",m);d.setAttribute("aria-hidden",!1);h(!0,d.style,{position:"absolute",width:"1px",height:"1px",bottom:"5px",zIndex:0,overflow:"hidden",outline:"none"});k.appendChild(d);e.renderTo.appendChild(k);this.unbindExitAnchorUpdate=b(e,"render",function(){this.renderTo.appendChild(k)});this.unbindExitAnchorFocus=b(d,"focus",function(b){b=b||a.event;g.exiting?g.exiting=!1:(e.renderTo.focus(),b.preventDefault(),
g.modules&&g.modules.length&&(g.currentModuleIx=g.modules.length-1,(b=g.modules[g.currentModuleIx])&&b.validate&&!b.validate()?g.prev():b&&b.init(-1)))})},destroy:function(){this.unbindExitAnchorFocus&&(this.unbindExitAnchorFocus(),delete this.unbindExitAnchorFocus);this.unbindExitAnchorUpdate&&(this.unbindExitAnchorUpdate(),delete this.unbindExitAnchorUpdate);this.exitAnchorWrapper&&this.exitAnchorWrapper.parentNode&&(this.exitAnchorWrapper.parentNode.removeChild(this.exitAnchorWrapper),delete this.exitAnchor,
delete this.exitAnchorWrapper);this.unbindKeydownHandler&&this.unbindKeydownHandler();this.unbindMouseUpHandler&&this.unbindMouseUpHandler()}};return l});n(f,"modules/accessibility/components/LegendComponent.js",[f["parts/Globals.js"],f["modules/accessibility/AccessibilityComponent.js"],f["modules/accessibility/KeyboardNavigationHandler.js"]],function(d,f,l){d.Chart.prototype.highlightLegendItem=function(b){var a=this.legend.allItems,c=this.highlightedLegendItemIx;return a[b]?(a[c]&&d.fireEvent(a[c].legendGroup.element,
"mouseout"),void 0!==a[b].pageIx&&a[b].pageIx+1!==this.legend.currentPage&&this.legend.scroll(1+a[b].pageIx-this.legend.currentPage),this.setFocusToElement(a[b].legendItem,a[b].a11yProxyElement),d.fireEvent(a[b].legendGroup.element,"mouseover"),!0):!1};d.addEvent(d.Legend,"afterColorizeItem",function(b){var a=b.item;this.chart.options.accessibility.enabled&&a&&a.a11yProxyElement&&a.a11yProxyElement.setAttribute("aria-pressed",b.visible?"false":"true")});var h=function(b){this.initBase(b)};h.prototype=
new f;d.extend(h.prototype,{onChartRender:function(){var b=this.chart,a=b.options.accessibility,c=b.legend&&b.legend.allItems,e=this;e.legendProxyButtonClicked?delete e.legendProxyButtonClicked:(this.removeElement(this.legendProxyGroup),!c||!c.length||b.colorAxis&&b.colorAxis.length||!b.options.legend.accessibility.enabled||(this.legendProxyGroup=this.addProxyGroup({"aria-label":b.langFormat("accessibility.legendLabel"),role:"all"===a.landmarkVerbosity?"region":null}),c.forEach(function(a){a.legendItem&&
a.legendItem.element&&(a.a11yProxyElement=e.createProxyButton(a.legendItem,e.legendProxyGroup,{tabindex:-1,"aria-pressed":!a.visible,"aria-label":b.langFormat("accessibility.legendItem",{chart:b,itemName:e.stripTags(a.name)})},a.legendGroup.div?a.legendItem:a.legendGroup,function(){e.legendProxyButtonClicked=!0}))})))},getKeyboardNavigation:function(){var b=this.keyCodes,a=this,c=this.chart,e=c.options.accessibility;return new l(c,{keyCodeMap:[[[b.left,b.right,b.up,b.down],function(k){k=k===b.left||
k===b.up?-1:1;return c.highlightLegendItem(a.highlightedLegendItemIx+k)?(a.highlightedLegendItemIx+=k,this.response.success):1<c.legend.allItems.length&&e.keyboardNavigation.wrapAround?(this.init(k),this.response.success):this.response[0<k?"next":"prev"]}],[[b.enter,b.space],function(){var b=c.legend.allItems[a.highlightedLegendItemIx];b&&b.a11yProxyElement&&d.fireEvent(b.a11yProxyElement,"click");return this.response.success}]],validate:function(){var a=c.options.legend;return c.legend&&c.legend.allItems&&
c.legend.display&&!(c.colorAxis&&c.colorAxis.length)&&a&&a.accessibility&&a.accessibility.enabled&&a.accessibility.keyboardNavigation&&a.accessibility.keyboardNavigation.enabled},init:function(b){b=0<b?0:c.legend.allItems.length-1;c.highlightLegendItem(b);a.highlightedLegendItemIx=b}})}});return h});n(f,"modules/accessibility/components/MenuComponent.js",[f["parts/Globals.js"],f["modules/accessibility/AccessibilityComponent.js"],f["modules/accessibility/KeyboardNavigationHandler.js"]],function(d,
f,l){d.Chart.prototype.showExportMenu=function(){this.exportSVGElements&&this.exportSVGElements[0]&&(this.exportSVGElements[0].element.onclick(),this.highlightExportItem(0))};d.Chart.prototype.hideExportMenu=function(){var b=this.exportDivElements;b&&this.exportContextMenu&&(b.forEach(function(a){if("highcharts-menu-item"===a.className&&a.onmouseout)a.onmouseout()}),this.highlightedExportItemIx=0,this.exportContextMenu.hideMenu(),this.container.focus())};d.Chart.prototype.highlightExportItem=function(b){var a=
this.exportDivElements&&this.exportDivElements[b],c=this.exportDivElements&&this.exportDivElements[this.highlightedExportItemIx],e;if(a&&"DIV"===a.tagName&&(!a.children||!a.children.length)){e=!!(this.renderTo.getElementsByTagName("g")[0]||{}).focus;a.focus&&e&&a.focus();if(c&&c.onmouseout)c.onmouseout();if(a.onmouseover)a.onmouseover();this.highlightedExportItemIx=b;return!0}};d.Chart.prototype.highlightLastExportItem=function(){var b;if(this.exportDivElements)for(b=this.exportDivElements.length;b--;)if(this.highlightExportItem(b))return!0;
return!1};var h=function(b){this.initBase(b);this.init()};h.prototype=new f;d.extend(h.prototype,{init:function(){this.addEvent(this.chart,"exportMenuHidden",function(){var b=this.exportContextMenu;b&&b.setAttribute("aria-hidden",!0)})},onChartRender:function(){var b=this,a=this.chart,c=a.options.accessibility;this.removeElement(this.exportProxyGroup);if(a.options.exporting&&!1!==a.options.exporting.enabled&&a.options.exporting.accessibility&&a.options.exporting.accessibility.enabled&&a.exportSVGElements&&
a.exportSVGElements[0]&&a.exportSVGElements[0].element){var e=a.exportSVGElements[0],k=e.element,d=k.onclick;this.wrappedButton!==k&&(k.onclick=function(){d.apply(this,Array.prototype.slice.call(arguments));b.addAccessibleContextMenuAttribs();a.highlightExportItem(0)},this.wrappedButton=k);this.exportProxyGroup=this.addProxyGroup("all"===c.landmarkVerbosity?{"aria-label":a.langFormat("accessibility.exporting.exportRegionLabel",{chart:a}),role:"region"}:null);this.exportButtonProxy=this.createProxyButton(e,
this.exportProxyGroup,{"aria-label":a.langFormat("accessibility.exporting.menuButtonLabel",{chart:a})})}},addAccessibleContextMenuAttribs:function(){var b=this.chart,a=b.exportDivElements,c=b.exportContextMenu;a&&a.length&&(a.forEach(function(a){"DIV"!==a.tagName||a.children&&a.children.length||(a.setAttribute("role","menuitem"),a.setAttribute("tabindex",-1))}),a[0].parentNode.setAttribute("role","menu"),a[0].parentNode.setAttribute("aria-label",b.langFormat("accessibility.exporting.chartMenuLabel",
{chart:b})));c&&this.unhideElementFromScreenReaders(c)},getKeyboardNavigation:function(){var b=this.keyCodes,a=this.chart,c=a.options.accessibility,e=this;return new l(a,{keyCodeMap:[[[b.left,b.up],function(){for(var b=a.highlightedExportItemIx||0;b--;)if(a.highlightExportItem(b))return this.response.success;return c.keyboardNavigation.wrapAround?(a.highlightLastExportItem(),this.response.success):this.response.prev}],[[b.right,b.down],function(){for(var b=(a.highlightedExportItemIx||0)+1;b<a.exportDivElements.length;++b)if(a.highlightExportItem(b))return this.response.success;
return c.keyboardNavigation.wrapAround?(a.highlightExportItem(0),this.response.success):this.response.next}],[[b.enter,b.space],function(){e.fakeClickEvent(a.exportDivElements[a.highlightedExportItemIx]);return this.response.success}],[[b.esc],function(){return this.response.prev}]],validate:function(){return a.exportChart&&!1!==a.options.exporting.enabled&&!1!==a.options.exporting.accessibility.enabled},init:function(b){a.showExportMenu();0>b&&a.highlightLastExportItem()},terminate:function(){a.hideExportMenu()}})}});
return h});n(f,"modules/accessibility/components/SeriesComponent.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["modules/accessibility/AccessibilityComponent.js"],f["modules/accessibility/KeyboardNavigationHandler.js"]],function(d,f,l,h){function b(a){var b=a.index,g=a.series.points,c=g.length;if(g[b]!==a)for(;c--;){if(g[c]===a)return c}else return b}function a(a){var b=a.chart.options.accessibility,g=a.options.accessibility||{},c=g.keyboardNavigation;return c&&!1===c.enabled||!1===g.enabled||
!1===a.options.enableMouseTracking||!a.visible||b.pointNavigationThreshold&&b.pointNavigationThreshold<=a.points.length}function c(b){var g=b.series.chart.options.accessibility;return b.isNull&&g.keyboardNavigation.skipNullPoints||!1===b.visible||a(b.series)}var e=f.isNumber,k=d.merge,t=d.pick;d.Series.prototype.keyboardMoveVertical=!0;["column","pie"].forEach(function(a){d.seriesTypes[a]&&(d.seriesTypes[a].prototype.keyboardMoveVertical=!1)});d.addEvent(d.Series,"render",function(){var a=this.options,
b=this.chart.options.accessibility||{},c=this.points||[],e=c.length,d=this.resetA11yMarkerOptions;if(b.enabled&&!1!==(a.accessibility&&a.accessibility.enabled)&&(e<b.pointDescriptionThreshold||!1===b.pointDescriptionThreshold||e<b.pointNavigationThreshold||!1===b.pointNavigationThreshold)){if(a.marker&&!1===a.marker.enabled&&(this.a11yMarkersForced=!0,k(!0,this.options,{marker:{enabled:!0,states:{normal:{opacity:0}}}})),this._hasPointMarkers&&this.points&&this.points.length)for(a=e;a--;)b=c[a].options,
b.marker&&(b.marker.enabled?k(!0,b.marker,{states:{normal:{opacity:b.marker.states&&b.marker.states.normal&&b.marker.states.normal.opacity||1}}}):k(!0,b.marker,{enabled:!0,states:{normal:{opacity:0}}}))}else this.a11yMarkersForced&&d&&(delete this.a11yMarkersForced,k(!0,this.options,{marker:{enabled:d.enabled,states:{normal:{opacity:d.states&&d.states.normal&&d.states.normal.opacity}}}}))});d.addEvent(d.Series,"afterSetOptions",function(a){this.resetA11yMarkerOptions=k(a.options.marker||{},this.userOptions.marker||
{})});d.Point.prototype.highlight=function(){var a=this.series.chart;if(this.isNull)a.tooltip&&a.tooltip.hide(0);else this.onMouseOver();this.graphic&&a.setFocusToElement(this.graphic);a.highlightedPoint=this;return this};d.Chart.prototype.highlightAdjacentPoint=function(g){var m=this.series,e=this.highlightedPoint,d=e&&b(e)||0,k=e&&e.series.points,h=this.series&&this.series[this.series.length-1],h=h&&h.points&&h.points[h.points.length-1];if(!m[0]||!m[0].points)return!1;if(e){if(m=m[e.series.index+
(g?1:-1)],d=k[d+(g?1:-1)],!d&&m&&(d=m.points[g?0:m.points.length-1]),!d)return!1}else d=g?m[0].points[0]:h;return c(d)?(m=d.series,a(m)?this.highlightedPoint=g?m.points[m.points.length-1]:m.points[0]:this.highlightedPoint=d,this.highlightAdjacentPoint(g)):d.highlight()};d.Series.prototype.highlightFirstValidPoint=function(){var a=this.chart.highlightedPoint,e=(a&&a.series)===this?b(a):0,a=this.points,d=a.length;if(a&&d){for(var k=e;k<d;++k)if(!c(a[k]))return a[k].highlight();for(;0<=e;--e)if(!c(a[e]))return a[e].highlight()}return!1};
d.Chart.prototype.highlightAdjacentSeries=function(b){var g,c,e=this.highlightedPoint,d=(g=this.series&&this.series[this.series.length-1])&&g.points&&g.points[g.points.length-1];if(!this.highlightedPoint)return g=b?this.series&&this.series[0]:g,(c=b?g&&g.points&&g.points[0]:d)?c.highlight():!1;g=this.series[e.series.index+(b?-1:1)];if(!g)return!1;var d=Infinity,k,h=g.points.length;if(void 0===e.plotX||void 0===e.plotY)c=void 0;else{for(;h--;)k=g.points[h],void 0!==k.plotX&&void 0!==k.plotY&&(k=(e.plotX-
k.plotX)*(e.plotX-k.plotX)*4+(e.plotY-k.plotY)*(e.plotY-k.plotY)*1,k<d&&(d=k,c=h));c=void 0!==c&&g.points[c]}if(!c)return!1;if(a(g))return c.highlight(),b=this.highlightAdjacentSeries(b),b?b:(e.highlight(),!1);c.highlight();return c.series.highlightFirstValidPoint()};d.Chart.prototype.highlightAdjacentPointVertical=function(b){var g=this.highlightedPoint,e=Infinity,d;if(void 0===g.plotX||void 0===g.plotY)return!1;this.series.forEach(function(m){a(m)||m.points.forEach(function(a){if(void 0!==a.plotY&&
void 0!==a.plotX&&a!==g){var k=a.plotY-g.plotY,h=Math.abs(a.plotX-g.plotX),h=Math.abs(k)*Math.abs(k)+h*h*4;m.yAxis.reversed&&(k*=-1);!(0>=k&&b||0<=k&&!b||5>h||c(a))&&h<e&&(e=h,d=a)}})});return d?d.highlight():!1};d.Point.prototype.getA11yTimeDescription=function(){var a=this.series,b=a.chart,c=b.options.accessibility;if(a.xAxis&&a.xAxis.isDatetimeAxis)return b.time.dateFormat(c.pointDateFormatter&&c.pointDateFormatter(this)||c.pointDateFormat||d.Tooltip.prototype.getXDateFormat.call({getDateFormat:d.Tooltip.prototype.getDateFormat,
chart:b},this,b.options.tooltip,a.xAxis),this.x)};f=function(a){this.initBase(a);this.init()};f.prototype=new l;d.extend(f.prototype,{init:function(){var a=this;this.addEvent(d.Series,"destroy",function(){var b=this.chart;b===a.chart&&b.highlightedPoint&&b.highlightedPoint.series===this&&(delete b.highlightedPoint,b.focusElement&&b.focusElement.removeFocusBorder())});this.addEvent(d.Tooltip,"refresh",function(){this.chart===a.chart&&this.label&&this.label.element&&this.label.element.setAttribute("aria-hidden",
!0)});this.addEvent(this.chart,"afterDrawSeriesLabels",function(){this.series.forEach(function(a){a.labelBySeries&&a.labelBySeries.attr("aria-hidden",!0)})});this.initAnnouncer()},onChartRender:function(){var a=this;this.chart.series.forEach(function(b){a[!1!==(b.options.accessibility&&b.options.accessibility.enabled)?"addSeriesDescription":"hideSeriesFromScreenReader"](b)})},getKeyboardNavigation:function(){var a=this.keyCodes,b=this.chart,c=b.inverted,e=b.options.accessibility,d=function(a){return b.highlightAdjacentPoint(a)?
this.response.success:e.keyboardNavigation.wrapAround?this.init(a?1:-1):this.response[a?"next":"prev"]};return new h(b,{keyCodeMap:[[[c?a.up:a.left,c?a.down:a.right],function(b){return d.call(this,b===a.right||b===a.down)}],[[c?a.left:a.up,c?a.right:a.down],function(c){c=c===a.down||c===a.right;var g=e.keyboardNavigation;if(g.mode&&"serialize"===g.mode)return d.call(this,c);b[b.highlightedPoint&&b.highlightedPoint.series.keyboardMoveVertical?"highlightAdjacentPointVertical":"highlightAdjacentSeries"](c);
return this.response.success}],[[a.enter,a.space],function(){b.highlightedPoint&&b.highlightedPoint.firePointEvent("click")}]],init:function(a){var c=b.series.length,g=0<a?0:c;if(0<a)for(delete b.highlightedPoint;g<c&&!(a=b.series[g].highlightFirstValidPoint());)++g;else for(;g--&&!(b.highlightedPoint=b.series[g].points[b.series[g].points.length-1],a=b.series[g].highlightFirstValidPoint()););return this.response.success},terminate:function(){b.tooltip&&b.tooltip.hide(0);delete b.highlightedPoint}})},
isPointClickable:function(a){var b=a.series.options||{},b=b.point&&b.point.events;return a&&a.graphic&&a.graphic.element&&(a.hcEvents&&a.hcEvents.click||b&&b.click||a.options&&a.options.events&&a.options.events.click)},initAnnouncer:function(){var a=this.chart,b=a.options.accessibility,c=this;this.lastAnnouncementTime=0;this.dirty={allSeries:{}};this.announceRegion=this.createElement("div");this.announceRegion.setAttribute("aria-hidden",!1);this.announceRegion.setAttribute("aria-live",b.announceNewData.interruptUser?
"assertive":"polite");k(!0,this.announceRegion.style,this.hiddenStyle);a.renderTo.insertBefore(this.announceRegion,a.renderTo.firstChild);this.addEvent(this.chart,"afterDrilldown",function(){a.highlightedPoint=null;if(a.options.accessibility.announceNewData.enabled){if(this.series&&this.series.length){var b=c.getSeriesElement(this.series[0]);b.focus&&b.getAttribute("aria-label")?b.focus():this.series[0].highlightFirstValidPoint()}c.lastAnnouncementTime=0;a.focusElement&&a.focusElement.removeFocusBorder()}});
this.addEvent(d.Series,"updatedData",function(){this.chart===a&&this.chart.options.accessibility.announceNewData.enabled&&(c.dirty.hasDirty=!0,c.dirty.allSeries[this.name+this.index]=this)});this.addEvent(a,"afterAddSeries",function(a){this.options.accessibility.announceNewData.enabled&&(a=a.series,c.dirty.hasDirty=!0,c.dirty.allSeries[a.name+a.index]=a,c.dirty.newSeries=void 0===c.dirty.newSeries?a:null)});this.addEvent(d.Series,"addPoint",function(b){this.chart===a&&this.chart.options.accessibility.announceNewData.enabled&&
(c.dirty.newPoint=void 0===c.dirty.newPoint?b.point:null)});this.addEvent(a,"redraw",function(){if(this.options.accessibility.announceNewData&&c.dirty.hasDirty){var a=c.dirty.newPoint,b;a&&(b=a.series.data.filter(function(b){return b.x===a.x&&b.y===a.y}),a=1===b.length?b[0]:a);c.announceNewData(Object.keys(c.dirty.allSeries).map(function(a){return c.dirty.allSeries[a]}),c.dirty.newSeries,a);c.dirty={allSeries:{}}}})},announceNewData:function(a,b,c){var e=this.chart.options.accessibility.announceNewData;
if(e.enabled){var g=this,d=+new Date,e=Math.max(0,e.minAnnounceInterval-(d-this.lastAnnouncementTime));if(this.queuedAnnouncement){var k=(this.queuedAnnouncement.series||[]).concat(a).reduce(function(a,b){a[b.name+b.index]=b;return a},{});a=Object.keys(k).map(function(a){return k[a]})}else a=[].concat(a);if(b=this.buildAnnouncementMessage(a,b,c))this.queuedAnnouncement&&clearTimeout(this.queuedAnnouncementTimer),this.queuedAnnouncement={time:d,message:b,series:a},g.queuedAnnouncementTimer=setTimeout(function(){g&&
g.announceRegion&&(g.lastAnnouncementTime=+new Date,g.announceRegion.innerHTML=g.queuedAnnouncement.message,g.clearAnnouncementContainerTimer&&clearTimeout(g.clearAnnouncementContainerTimer),g.clearAnnouncementContainerTimer=setTimeout(function(){g.announceRegion.innerHTML="";delete g.clearAnnouncementContainerTimer},1E3),delete g.queuedAnnouncement,delete g.queuedAnnouncementTimer)},e)}},buildAnnouncementMessage:function(a,b,c){var e=this.chart,g=e.options.accessibility.announceNewData;if(g.announcementFormatter&&
(a=g.announcementFormatter(a,b,c),!1!==a))return a.length?a:null;a=d.charts&&1<d.charts.length?"Multiple":"Single";return e.langFormat("accessibility.announceNewData."+(b?"newSeriesAnnounce"+a:c?"newPointAnnounce"+a:"newDataAnnounce"),{chartTitle:this.stripTags(e.options.title.text||e.langFormat("accessibility.defaultChartTitle",{chart:e})),seriesDesc:b?this.defaultSeriesDescriptionFormatter(b):null,pointDesc:c?this.defaultPointDescriptionFormatter(c):null,point:c,series:b})},reverseChildNodes:function(a){for(var b=
a.childNodes.length;b--;)a.appendChild(a.childNodes[b])},getSeriesFirstPointElement:function(a){return a.points&&a.points.length&&a.points[0].graphic&&a.points[0].graphic.element},getSeriesElement:function(a){var b=this.getSeriesFirstPointElement(a);return b&&b.parentNode||a.graph&&a.graph.element||a.group&&a.group.element},hideSeriesFromScreenReader:function(a){(a=this.getSeriesElement(a))&&a.setAttribute("aria-hidden",!0)},addSeriesDescription:function(a){var b=this,c=a.chart,e=c.options.accessibility,
g=a.options.accessibility||{},d=b.getSeriesFirstPointElement(a),k=b.getSeriesElement(a),h=a.points&&(a.points.length<e.pointDescriptionThreshold||!1===e.pointDescriptionThreshold)&&!g.exposeAsGroupOnly,f=a.points&&(a.points.length<e.pointNavigationThreshold||!1===e.pointNavigationThreshold);k&&(k.lastChild===d&&b.reverseChildNodes(k),b.unhideElementFromScreenReaders(k),(h||f)&&a.points.forEach(function(a){var c=a.graphic&&a.graphic.element;c&&(c.setAttribute("tabindex","-1"),h?(c.setAttribute("role",
"img"),c.setAttribute("aria-label",b.stripTags(g.pointDescriptionFormatter&&g.pointDescriptionFormatter(a)||e.pointDescriptionFormatter&&e.pointDescriptionFormatter(a)||b.defaultPointDescriptionFormatter(a)))):c.setAttribute("aria-hidden",!0))}),1<c.series.length||e.describeSingleSeries?(g.exposeAsGroupOnly?k.setAttribute("role","img"):"all"===e.landmarkVerbosity&&k.setAttribute("role","region"),k.setAttribute("tabindex","-1"),k.setAttribute("aria-label",b.stripTags(e.seriesDescriptionFormatter&&
e.seriesDescriptionFormatter(a)||b.defaultSeriesDescriptionFormatter(a)))):k.setAttribute("aria-label",""))},defaultSeriesDescriptionFormatter:function(a){var b=a.chart,c=(a.options.accessibility||{}).description,c=c&&b.langFormat("accessibility.series.description",{description:c,series:a}),e=b.langFormat("accessibility.series.xAxisDescription",{name:a.xAxis&&a.xAxis.getDescription(),series:a}),d=b.langFormat("accessibility.series.yAxisDescription",{name:a.yAxis&&a.yAxis.getDescription(),series:a}),
k={name:a.name||"",ix:a.index+1,numSeries:b.series&&b.series.length,numPoints:a.points&&a.points.length,series:a},g=b.types&&1<b.types.length?"Combination":"";return(b.langFormat("accessibility.series.summary."+a.type+g,k)||b.langFormat("accessibility.series.summary.default"+g,k))+(c?" "+c:"")+(b.yAxis&&1<b.yAxis.length&&this.yAxis?" "+d:"")+(b.xAxis&&1<b.xAxis.length&&this.xAxis?" "+e:"")},defaultPointDescriptionFormatter:function(a){var b=a.series,c=b.chart,k=c.options.accessibility,g=a.series.tooltipOptions||
{},h=k.pointValuePrefix||g.valuePrefix||"",f=k.pointValueSuffix||g.valueSuffix||"",l=a.options&&a.options.accessibility&&a.options.accessibility.description,n=a.getA11yTimeDescription(),r=function(a){if(e(a)){var b=d.defaultOptions.lang;return d.numberFormat(a,k.pointValueDecimals||g.valueDecimals||-1,b.decimalPoint,b.accessibility.thousandsSep||b.thousandsSep)}return a},w=t(b.xAxis&&b.xAxis.options.accessibility&&b.xAxis.options.accessibility.enabled,!c.angular),u=b.xAxis&&b.xAxis.categories&&void 0!==
a.category&&""+a.category,n=a.name||n||u&&u.replace("\x3cbr/\x3e"," ")||(a.id&&0>a.id.indexOf("highcharts-")?a.id:"x, "+a.x),u=a.series.pointArrayMap?a.series.pointArrayMap.reduce(function(b,c){return b+(b.length?", ":"")+c+": "+h+r(t(a[c],a.options[c]))+f},""):void 0!==a.value?h+r(a.value)+f:h+r(a.y)+f;return(void 0!==a.index?a.index+1+". ":"")+(w?n+", ":"")+u+"."+(l?" "+l:"")+(1<c.series.length&&b.name?" "+b.name:"")}});return f});n(f,"modules/accessibility/components/ZoomComponent.js",[f["parts/Globals.js"],
f["modules/accessibility/AccessibilityComponent.js"],f["modules/accessibility/KeyboardNavigationHandler.js"]],function(d,f,l){d.Axis.prototype.panStep=function(b,a){var c=a||3;a=this.getExtremes();var e=(a.max-a.min)/c*b,c=a.max+e,e=a.min+e,k=c-e;0>b&&e<a.dataMin?(e=a.dataMin,c=e+k):0<b&&c>a.dataMax&&(c=a.dataMax,e=c-k);this.setExtremes(e,c)};var h=function(b){this.initBase(b);this.init()};h.prototype=new f;d.extend(h.prototype,{init:function(){var b=this,a=this.chart;["afterShowResetZoom","afterDrilldown",
"drillupall"].forEach(function(c){b.addEvent(a,c,function(){b.updateProxyOverlays()})})},onChartUpdate:function(){var b=this.chart,a=this;b.mapNavButtons&&b.mapNavButtons.forEach(function(c,e){a.unhideElementFromScreenReaders(c.element);c.element.setAttribute("tabindex",-1);c.element.setAttribute("role","button");c.element.setAttribute("aria-label",b.langFormat("accessibility.mapZoom"+(e?"Out":"In"),{chart:b}))})},onChartRender:function(){this.updateProxyOverlays()},updateProxyOverlays:function(){var b=
this,a=this.chart,c=function(a,c,d,g){b.removeElement(b[d]);b[d]=b.addProxyGroup();b[c]=b.createProxyButton(a,b[d],{"aria-label":g,tabindex:-1})};b.removeElement(b.drillUpProxyGroup);b.removeElement(b.resetZoomProxyGroup);a.resetZoomButton&&c(a.resetZoomButton,"resetZoomProxyButton","resetZoomProxyGroup",a.langFormat("accessibility.resetZoomButton",{chart:a}));a.drillUpButton&&c(a.drillUpButton,"drillUpProxyButton","drillUpProxyGroup",a.langFormat("accessibility.drillUpButton",{chart:a,buttonText:a.getDrilldownBackText()}))},
getMapZoomNavigation:function(){var b=this.keyCodes,a=this.chart,c=this;return new l(a,{keyCodeMap:[[[b.up,b.down,b.left,b.right],function(c){a[c===b.up||c===b.down?"yAxis":"xAxis"][0].panStep(c===b.left||c===b.up?-1:1);return this.response.success}],[[b.tab],function(b,d){a.mapNavButtons[c.focusedMapNavButtonIx].setState(0);if(d.shiftKey&&!c.focusedMapNavButtonIx||!d.shiftKey&&c.focusedMapNavButtonIx)return a.mapZoom(),this.response[d.shiftKey?"prev":"next"];c.focusedMapNavButtonIx+=d.shiftKey?-1:
1;b=a.mapNavButtons[c.focusedMapNavButtonIx];a.setFocusToElement(b.box,b.element);b.setState(2);return this.response.success}],[[b.space,b.enter],function(){c.fakeClickEvent(a.mapNavButtons[c.focusedMapNavButtonIx].element);return this.response.success}]],validate:function(){return a.mapZoom&&a.mapNavButtons&&2===a.mapNavButtons.length},init:function(b){var e=a.mapNavButtons[0],d=a.mapNavButtons[1],e=0<b?e:d;a.setFocusToElement(e.box,e.element);e.setState(2);c.focusedMapNavButtonIx=0<b?0:1}})},simpleButtonNavigation:function(b,
a,c){var e=this.keyCodes,d=this,h=this.chart;return new l(h,{keyCodeMap:[[[e.tab,e.up,e.down,e.left,e.right],function(a,b){return this.response[a===this.tab&&b.shiftKey||a===e.left||a===e.up?"prev":"next"]}],[[e.space,e.enter],function(){c(h);return this.response.success}]],validate:function(){return h[b]&&h[b].box&&d[a]},init:function(){h.setFocusToElement(h[b].box,d[a])}})},getKeyboardNavigation:function(){return[this.simpleButtonNavigation("resetZoomButton","resetZoomProxyButton",function(b){b.zoomOut()}),
this.simpleButtonNavigation("drillUpButton","drillUpProxyButton",function(b){b.drillUp()}),this.getMapZoomNavigation()]}});return h});n(f,"modules/accessibility/components/RangeSelectorComponent.js",[f["parts/Globals.js"],f["modules/accessibility/AccessibilityComponent.js"],f["modules/accessibility/KeyboardNavigationHandler.js"]],function(d,f,l){d.Chart.prototype.highlightRangeSelectorButton=function(b){var a=this.rangeSelector.buttons;a[this.highlightedRangeSelectorItemIx]&&a[this.highlightedRangeSelectorItemIx].setState(this.oldRangeSelectorItemState||
0);this.highlightedRangeSelectorItemIx=b;return a[b]?(this.setFocusToElement(a[b].box,a[b].element),this.oldRangeSelectorItemState=a[b].state,a[b].setState(2),!0):!1};var h=function(b){this.initBase(b)};h.prototype=new f;d.extend(h.prototype,{onChartUpdate:function(){var b=this.chart,a=this,c=b.rangeSelector;c&&(c.buttons&&c.buttons.length&&c.buttons.forEach(function(c){a.unhideElementFromScreenReaders(c.element);c.element.setAttribute("tabindex","-1");c.element.setAttribute("role","button");c.element.setAttribute("aria-label",
b.langFormat("accessibility.rangeSelectorButton",{chart:b,buttonText:c.text&&c.text.textStr}))}),c.maxInput&&c.minInput&&["minInput","maxInput"].forEach(function(e,d){c[e]&&(a.unhideElementFromScreenReaders(c[e]),c[e].setAttribute("tabindex","-1"),c[e].setAttribute("role","textbox"),c[e].setAttribute("aria-label",b.langFormat("accessibility.rangeSelector"+(d?"MaxInput":"MinInput"),{chart:b})))}))},getRangeSelectorButtonNavigation:function(){var b=this.chart,a=this.keyCodes,c=b.options.accessibility,
e=this;return new l(b,{keyCodeMap:[[[a.left,a.right,a.up,a.down],function(e){e=e===a.left||e===a.up?-1:1;if(!b.highlightRangeSelectorButton(b.highlightedRangeSelectorItemIx+e))return c.keyboardNavigation.wrapAround?(this.init(e),this.response.success):this.response[0<e?"next":"prev"]}],[[a.enter,a.space],function(){3!==b.oldRangeSelectorItemState&&e.fakeClickEvent(b.rangeSelector.buttons[b.highlightedRangeSelectorItemIx].element)}]],validate:function(){return b.rangeSelector&&b.rangeSelector.buttons&&
b.rangeSelector.buttons.length},init:function(a){b.highlightRangeSelectorButton(0<a?0:b.rangeSelector.buttons.length-1)}})},getRangeSelectorInputNavigation:function(){var b=this.chart,a=this.keyCodes;return new l(b,{keyCodeMap:[[[a.tab,a.up,a.down],function(c,e){c=c===a.tab&&e.shiftKey||c===a.up?-1:1;e=b.highlightedInputRangeIx+=c;if(1<e||0>e)return this.response[0<c?"next":"prev"];b.rangeSelector[e?"maxInput":"minInput"].focus();return this.response.success}]],validate:function(){return b.rangeSelector&&
b.rangeSelector.inputGroup&&"hidden"!==b.rangeSelector.inputGroup.element.getAttribute("visibility")&&!1!==b.options.rangeSelector.inputEnabled&&b.rangeSelector.minInput&&b.rangeSelector.maxInput},init:function(a){b.highlightedInputRangeIx=0<a?0:1;b.rangeSelector[b.highlightedInputRangeIx?"maxInput":"minInput"].focus()},terminate:function(){var a=b.rangeSelector;a&&a.maxInput&&a.minInput&&(a.hideInput("max"),a.hideInput("min"))}})},getKeyboardNavigation:function(){return[this.getRangeSelectorButtonNavigation(),
this.getRangeSelectorInputNavigation()]}});return h});n(f,"modules/accessibility/components/InfoRegionComponent.js",[f["parts/Globals.js"],f["modules/accessibility/AccessibilityComponent.js"]],function(d,f){var l=d.merge,h=d.pick;d.Chart.prototype.getTypeDescription=function(a){a=a[0];var b=this.series&&this.series[0]||{},e=b.mapTitle,b={numSeries:this.series.length,numPoints:b.points&&b.points.length,chart:this,mapTitle:e};if(!a)return this.langFormat("accessibility.chartTypes.emptyChart",b);if("map"===
a)return e?this.langFormat("accessibility.chartTypes.mapTypeDescription",b):this.langFormat("accessibility.chartTypes.unknownMap",b);if(1<this.types.length)return this.langFormat("accessibility.chartTypes.combinationChart",b);var e=this.langFormat("accessibility.seriesTypeDescriptions."+a,{chart:this}),d=this.series&&1===this.series.length?"Single":"Multiple";return(this.langFormat("accessibility.chartTypes."+a+d,b)||this.langFormat("accessibility.chartTypes.default"+d,b))+(e?" "+e:"")};var b=function(a){this.initBase(a);
this.init()};b.prototype=new f;d.extend(b.prototype,{init:function(){var a=this.chart,b=this;this.addEvent(a,"afterGetTable",function(c){a.options.accessibility.enabled&&(b.tableAnchor.setAttribute("aria-expanded",!0),c.html=c.html.replace("\x3ctable ",'\x3ctable tabindex\x3d"0" summary\x3d"'+a.langFormat("accessibility.tableSummary",{chart:a})+'"'))});this.addEvent(a,"afterViewData",function(a){setTimeout(function(){var b=a&&a.getElementsByTagName("table")[0];b&&b.focus&&b.focus()},300)})},onChartUpdate:function(){var a=
this.chart,b=a.options.accessibility,e="highcharts-information-region-"+a.index,d=this.screenReaderRegion=this.screenReaderRegion||this.createElement("div"),h=this.tableHeading=this.tableHeading||this.createElement("h6"),g=this.tableAnchor=this.tableAnchor||this.createElement("a"),f=this.chartHeading=this.chartHeading||this.createElement("h6");d.setAttribute("id",e);"all"===b.landmarkVerbosity&&d.setAttribute("role","region");d.setAttribute("aria-label",a.langFormat("accessibility.screenReaderRegionLabel",
{chart:a}));d.innerHTML=b.screenReaderSectionFormatter?b.screenReaderSectionFormatter(a):this.defaultScreenReaderSectionFormatter(a);a.getCSV&&a.options.accessibility.addTableShortcut&&(b="highcharts-data-table-"+a.index,g.innerHTML=a.langFormat("accessibility.viewAsDataTable",{chart:a}),g.href="#"+b,g.setAttribute("tabindex","-1"),g.setAttribute("role","button"),g.setAttribute("aria-expanded",!1),g.onclick=a.options.accessibility.onTableAnchorClick||function(){a.viewData()},h.appendChild(g),d.appendChild(h));
f.innerHTML=a.langFormat("accessibility.chartHeading",{chart:a});f.setAttribute("aria-hidden",!1);a.renderTo.insertBefore(f,a.renderTo.firstChild);a.renderTo.insertBefore(d,a.renderTo.firstChild);this.unhideElementFromScreenReaders(d);l(!0,f.style,this.hiddenStyle);l(!0,d.style,this.hiddenStyle)},defaultScreenReaderSectionFormatter:function(){var a=this.chart,b=a.options,e=a.types,d=this.getAxesDescription();return"\x3ch5\x3e"+(b.accessibility.typeDescription||a.getTypeDescription(e))+"\x3c/h5\x3e"+
(b.subtitle&&b.subtitle.text?"\x3cdiv\x3e"+this.htmlencode(b.subtitle.text)+"\x3c/div\x3e":"")+(b.accessibility.description?"\x3cdiv\x3e"+b.accessibility.description+"\x3c/div\x3e":"")+(d.xAxis?"\x3cdiv\x3e"+d.xAxis+"\x3c/div\x3e":"")+(d.yAxis?"\x3cdiv\x3e"+d.yAxis+"\x3c/div\x3e":"")},getAxesDescription:function(){var a=this.chart,b=this,e=a.xAxis,d=1<e.length||e[0]&&h(e[0].options.accessibility&&e[0].options.accessibility.enabled,!a.angular&&a.hasCartesianSeries&&0>a.types.indexOf("map")),f=a.yAxis,
g=1<f.length||f[0]&&h(f[0].options.accessibility&&f[0].options.accessibility.enabled,a.hasCartesianSeries&&0>a.types.indexOf("map")),l={};d&&(l.xAxis=a.langFormat("accessibility.axis.xAxisDescription"+(1<e.length?"Plural":"Singular"),{chart:a,names:a.xAxis.map(function(a){return a.getDescription()}),ranges:a.xAxis.map(function(a){return b.getAxisRangeDescription(a)}),numAxes:e.length}));g&&(l.yAxis=a.langFormat("accessibility.axis.yAxisDescription"+(1<f.length?"Plural":"Singular"),{chart:a,names:a.yAxis.map(function(a){return a.getDescription()}),
ranges:a.yAxis.map(function(a){return b.getAxisRangeDescription(a)}),numAxes:f.length}));return l},getAxisRangeDescription:function(a){var b=this.chart,e=a.options||{};if(e.accessibility&&void 0!==e.accessibility.rangeDescription)return e.accessibility.rangeDescription;if(a.categories)return b.langFormat("accessibility.axis.rangeCategories",{chart:b,axis:a,numCategories:a.dataMax-a.dataMin+1});if(a.isDatetimeAxis&&(0===a.min||0===a.dataMin)){var d={},h="Seconds";d.Seconds=(a.max-a.min)/1E3;d.Minutes=
d.Seconds/60;d.Hours=d.Minutes/60;d.Days=d.Hours/24;["Minutes","Hours","Days"].forEach(function(a){2<d[a]&&(h=a)});d.value=d[h].toFixed("Seconds"!==h&&"Minutes"!==h?1:0);return b.langFormat("accessibility.axis.timeRange"+h,{chart:b,axis:a,range:d.value.replace(".0","")})}e=b.options.accessibility;return b.langFormat("accessibility.axis.rangeFromTo",{chart:b,axis:a,rangeFrom:a.isDatetimeAxis?b.time.dateFormat(e.axisRangeDateFormat,a.min):a.min,rangeTo:a.isDatetimeAxis?b.time.dateFormat(e.axisRangeDateFormat,
a.max):a.max})}});return b});n(f,"modules/accessibility/components/ContainerComponent.js",[f["parts/Globals.js"],f["modules/accessibility/AccessibilityComponent.js"]],function(d,f){var l=d.win.document,h=function(b){this.initBase(b)};h.prototype=new f;d.extend(h.prototype,{onChartUpdate:function(){var b=this.chart,a=b.options.accessibility,c,d="highcharts-title-"+b.index,h=b.options.title.text||b.langFormat("accessibility.defaultChartTitle",{chart:b}),f=this.stripTags(b.langFormat("accessibility.svgContainerTitle",
{chartTitle:h})),g=this.stripTags(b.langFormat("accessibility.svgContainerLabel",{chartTitle:h}));f.length&&(c=this.svgTitleElement=this.svgTitleElement||l.createElementNS("http://www.w3.org/2000/svg","title"),c.textContent=f,c.id=d,b.renderTo.insertBefore(c,b.renderTo.firstChild));b.renderer.box&&g.length&&b.renderer.box.setAttribute("aria-label",g);"disabled"!==a.landmarkVerbosity?b.renderTo.setAttribute("role","region"):b.renderTo.removeAttribute("role");b.renderTo.setAttribute("aria-label",b.langFormat("accessibility.chartContainerLabel",
{title:this.stripTags(h),chart:b}))},destroy:function(){this.chart.renderTo.setAttribute("aria-hidden",!0);this.destroyBase()}});return h});n(f,"modules/accessibility/high-contrast-mode.js",[f["parts/Globals.js"]],function(d){var f=d.isMS,l=d.win,h=l.document;return{isHighContrastModeActive:function(){if(l.matchMedia&&f&&/Edge\/\d./i.test(l.navigator.userAgent))return l.matchMedia("(-ms-high-contrast: active)").matches;if(f&&l.getComputedStyle){var b=h.createElement("div");b.style.backgroundImage=
"url(#)";h.body.appendChild(b);var a=(b.currentStyle||l.getComputedStyle(b)).backgroundImage;h.body.removeChild(b);return"none"===a}return!1},setHighContrastTheme:function(b){b.highContrastModeActive=!0;var a=b.options.accessibility.highContrastTheme;b.update(a,!1);b.series.forEach(function(b){var c=a.plotOptions[b.type]||{};b.update({color:c.color||"windowText",colors:[c.color||"windowText"],borderColor:c.borderColor||"window"});b.points.forEach(function(a){a.options&&a.options.color&&a.update({color:c.color||
"windowText",borderColor:c.borderColor||"window"},!1)})});b.redraw()}}});n(f,"modules/accessibility/high-contrast-theme.js",[],function(){return{chart:{backgroundColor:"window"},title:{style:{color:"windowText"}},subtitle:{style:{color:"windowText"}},colorAxis:{minColor:"windowText",maxColor:"windowText",stops:null},colors:["windowText"],xAxis:{gridLineColor:"windowText",labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},
yAxis:{gridLineColor:"windowText",labels:{style:{color:"windowText"}},lineColor:"windowText",minorGridLineColor:"windowText",tickColor:"windowText",title:{style:{color:"windowText"}}},tooltip:{backgroundColor:"window",borderColor:"windowText",style:{color:"windowText"}},plotOptions:{series:{lineColor:"windowText",fillColor:"window",borderColor:"windowText",edgeColor:"windowText",borderWidth:1,dataLabels:{connectorColor:"windowText",color:"windowText",style:{color:"windowText",textOutline:"none"}},
marker:{lineColor:"windowText",fillColor:"windowText"}},pie:{color:"window",colors:["window"],borderColor:"windowText",borderWidth:1},boxplot:{fillColor:"window"},candlestick:{lineColor:"windowText",fillColor:"window"},errorbar:{fillColor:"window"}},legend:{backgroundColor:"window",itemStyle:{color:"windowText"},itemHoverStyle:{color:"windowText"},itemHiddenStyle:{color:"#555"},title:{style:{color:"windowText"}}},credits:{style:{color:"windowText"}},labels:{style:{color:"windowText"}},drilldown:{activeAxisLabelStyle:{color:"windowText"},
activeDataLabelStyle:{color:"windowText"}},navigation:{buttonOptions:{symbolStroke:"windowText",theme:{fill:"window"}}},rangeSelector:{buttonTheme:{fill:"window",stroke:"windowText",style:{color:"windowText"},states:{hover:{fill:"window",stroke:"windowText",style:{color:"windowText"}},select:{fill:"#444",stroke:"windowText",style:{color:"windowText"}}}},inputBoxBorderColor:"windowText",inputStyle:{backgroundColor:"window",color:"windowText"},labelStyle:{color:"windowText"}},navigator:{handles:{backgroundColor:"window",
borderColor:"windowText"},outlineColor:"windowText",maskFill:"transparent",series:{color:"windowText",lineColor:"windowText"},xAxis:{gridLineColor:"windowText"}},scrollbar:{barBackgroundColor:"#444",barBorderColor:"windowText",buttonArrowColor:"windowText",buttonBackgroundColor:"window",buttonBorderColor:"windowText",rifleColor:"windowText",trackBackgroundColor:"window",trackBorderColor:"windowText"}}});n(f,"modules/accessibility/options.js",[],function(){return{accessibility:{enabled:!0,pointDescriptionThreshold:200,
pointNavigationThreshold:!1,addTableShortcut:!0,axisRangeDateFormat:"%Y-%m-%d %H:%M:%S",describeSingleSeries:!1,landmarkVerbosity:"all",keyboardNavigation:{enabled:!0,skipNullPoints:!0,focusBorder:{enabled:!0,hideBrowserFocusOutline:!0,style:{color:"#335cad",lineWidth:2,borderRadius:3},margin:2},order:["series","zoom","rangeSelector","chartMenu","legend"],wrapAround:!0},announceNewData:{enabled:!1,minAnnounceInterval:5E3,interruptUser:!1}},legend:{accessibility:{enabled:!0,keyboardNavigation:{enabled:!0}}},
exporting:{accessibility:{enabled:!0}}}});n(f,"modules/accessibility/a11y-i18n.js",[f["parts/Globals.js"]],function(d){function f(d,b){var a=d.indexOf("#each("),c=d.indexOf("#plural("),e=d.indexOf("["),f=d.indexOf("]");if(-1<a){var e=d.slice(a).indexOf(")")+a,h=d.substring(0,a),c=d.substring(e+1),e=d.substring(a+6,e).split(","),a=Number(e[1]);d="";if(b=b[e[0]])for(a=isNaN(a)?b.length:a,a=0>a?b.length+a:Math.min(a,b.length),e=0;e<a;++e)d+=h+b[e]+c;return d.length?d:""}if(-1<c){h=d.slice(c).indexOf(")")+
c;d=d.substring(c+8,h).split(",");switch(Number(b[d[0]])){case 0:d=l(d[4],d[1]);break;case 1:d=l(d[2],d[1]);break;case 2:d=l(d[3],d[1]);break;default:d=d[1]}d?(b=d,b=b.trim&&b.trim()||b.replace(/^\s+|\s+$/g,"")):b="";return b}return-1<e?(c=d.substring(0,e),d=Number(d.substring(e+1,f)),b=b[c],!isNaN(d)&&b&&(0>d?(h=b[b.length+d],void 0===h&&(h=b[0])):(h=b[d],void 0===h&&(h=b[b.length-1]))),void 0!==h?h:""):"{"+d+"}"}var l=d.pick;d.i18nFormat=function(h,b,a){var c=function(a,b){a=a.slice(b||0);var c=
a.indexOf("{"),d=a.indexOf("}");if(-1<c&&d>c)return{statement:a.substring(c+1,d),begin:b+c+1,end:b+d}},e=[],k,l;l=0;do k=c(h,l),l=h.substring(l,k&&k.begin-1),l.length&&e.push({value:l,type:"constant"}),k&&e.push({value:k.statement,type:"statement"}),l=k&&k.end+1;while(k);e.forEach(function(a){"statement"===a.type&&(a.value=f(a.value,b))});return d.format(e.reduce(function(a,b){return a+b.value},""),b,a)};d.Chart.prototype.langFormat=function(f,b,a){f=f.split(".");for(var c=this.options.lang,e=0;e<
f.length;++e)c=c&&c[f[e]];return"string"===typeof c&&d.i18nFormat(c,b,a)};d.setOptions({lang:{accessibility:{screenReaderRegionLabel:"Chart screen reader information.",defaultChartTitle:"Chart",viewAsDataTable:"View as data table.",chartHeading:"Chart graphic.",chartContainerLabel:"{title}. Interactive chart.",svgContainerLabel:"Interactive chart",rangeSelectorMinInput:"Select start date.",rangeSelectorMaxInput:"Select end date.",tableSummary:"Table representation of chart.",mapZoomIn:"Zoom chart",
mapZoomOut:"Zoom out chart",resetZoomButton:"Reset zoom",drillUpButton:"{buttonText}",rangeSelectorButton:"Select range {buttonText}",legendLabel:"Toggle series visibility",legendItem:"Toggle visibility of {itemName}",thousandsSep:",",svgContainerTitle:"",svgContainerEnd:"End of interactive chart",announceNewData:{newDataAnnounce:"Updated data for chart {chartTitle}",newSeriesAnnounceSingle:"New data series: {seriesDesc}",newPointAnnounceSingle:"New data point: {pointDesc}",newSeriesAnnounceMultiple:"New data series in chart {chartTitle}: {seriesDesc}",
newPointAnnounceMultiple:"New data point in chart {chartTitle}: {pointDesc}"},seriesTypeDescriptions:{boxplot:"Box plot charts are typically used to display groups of statistical data. Each data point in the chart can have up to 5 values: minimum, lower quartile, median, upper quartile, and maximum.",arearange:"Arearange charts are line charts displaying a range between a lower and higher value for each point.",areasplinerange:"These charts are line charts displaying a range between a lower and higher value for each point.",
bubble:"Bubble charts are scatter charts where each data point also has a size value.",columnrange:"Columnrange charts are column charts displaying a range between a lower and higher value for each point.",errorbar:"Errorbar series are used to display the variability of the data.",funnel:"Funnel charts are used to display reduction of data in stages.",pyramid:"Pyramid charts consist of a single pyramid with item heights corresponding to each point value.",waterfall:"A waterfall chart is a column chart where each column contributes towards a total end value."},
chartTypes:{emptyChart:"Empty chart",mapTypeDescription:"Map of {mapTitle} with {numSeries} data series.",unknownMap:"Map of unspecified region with {numSeries} data series.",combinationChart:"Combination chart with {numSeries} data series.",defaultSingle:"Chart with {numPoints} data {#plural(numPoints, points, point)}.",defaultMultiple:"Chart with {numSeries} data series.",splineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",splineMultiple:"Line chart with {numSeries} lines.",
lineSingle:"Line chart with {numPoints} data {#plural(numPoints, points, point)}.",lineMultiple:"Line chart with {numSeries} lines.",columnSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",columnMultiple:"Bar chart with {numSeries} data series.",barSingle:"Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.",barMultiple:"Bar chart with {numSeries} data series.",pieSingle:"Pie chart with {numPoints} {#plural(numPoints, slices, slice)}.",pieMultiple:"Pie chart with {numSeries} pies.",
scatterSingle:"Scatter chart with {numPoints} {#plural(numPoints, points, point)}.",scatterMultiple:"Scatter chart with {numSeries} data series.",boxplotSingle:"Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotMultiple:"Boxplot with {numSeries} data series.",bubbleSingle:"Bubble chart with {numPoints} {#plural(numPoints, bubbles, bubble)}.",bubbleMultiple:"Bubble chart with {numSeries} data series."},axis:{xAxisDescriptionSingular:"The chart has 1 X axis displaying {names[0]}. {ranges[0]}",
xAxisDescriptionPlural:"The chart has {numAxes} X axes displaying {#each(names, -1) }and {names[-1]}.",yAxisDescriptionSingular:"The chart has 1 Y axis displaying {names[0]}. {ranges[0]}",yAxisDescriptionPlural:"The chart has {numAxes} Y axes displaying {#each(names, -1) }and {names[-1]}.",timeRangeDays:"Range: {range} days.",timeRangeHours:"Range: {range} hours.",timeRangeMinutes:"Range: {range} minutes.",timeRangeSeconds:"Range: {range} seconds.",rangeFromTo:"Range: {rangeFrom} to {rangeTo}.",rangeCategories:"Range: {numCategories} categories."},
exporting:{chartMenuLabel:"Chart export",menuButtonLabel:"View export menu",exportRegionLabel:"Chart export menu"},series:{summary:{"default":"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",defaultCombination:"{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",line:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",lineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",
spline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",splineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",column:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",columnCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",bar:"{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.",
barCombination:"{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.",pie:"{name}, pie {ix} of {numSeries} with {numPoints} {#plural(numPoints, slices, slice)}.",pieCombination:"{name}, series {ix} of {numSeries}. Pie with {numPoints} {#plural(numPoints, slices, slice)}.",scatter:"{name}, scatter plot {ix} of {numSeries} with {numPoints} {#plural(numPoints, points, point)}.",scatterCombination:"{name}, series {ix} of {numSeries}, scatter plot with {numPoints} {#plural(numPoints, points, point)}.",
boxplot:"{name}, boxplot {ix} of {numSeries} with {numPoints} {#plural(numPoints, boxes, box)}.",boxplotCombination:"{name}, series {ix} of {numSeries}. Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.",bubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",bubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}.",map:"{name}, map {ix} of {numSeries} with {numPoints} {#plural(numPoints, areas, area)}.",
mapCombination:"{name}, series {ix} of {numSeries}. Map with {numPoints} {#plural(numPoints, areas, area)}.",mapline:"{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.",maplineCombination:"{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.",mapbubble:"{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.",mapbubbleCombination:"{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}."},
description:"{description}",xAxisDescription:"X axis, {name}",yAxisDescription:"Y axis, {name}"}}}})});n(f,"modules/accessibility/accessibility.js",[f["parts/Globals.js"],f["modules/accessibility/KeyboardNavigationHandler.js"],f["modules/accessibility/AccessibilityComponent.js"],f["modules/accessibility/KeyboardNavigation.js"],f["modules/accessibility/components/LegendComponent.js"],f["modules/accessibility/components/MenuComponent.js"],f["modules/accessibility/components/SeriesComponent.js"],f["modules/accessibility/components/ZoomComponent.js"],
f["modules/accessibility/components/RangeSelectorComponent.js"],f["modules/accessibility/components/InfoRegionComponent.js"],f["modules/accessibility/components/ContainerComponent.js"],f["modules/accessibility/high-contrast-mode.js"],f["modules/accessibility/high-contrast-theme.js"],f["modules/accessibility/options.js"]],function(d,f,l,h,b,a,c,e,k,n,g,m,v,p){function r(a){this.init(a)}var q=d.addEvent,t=d.win.document,x=d.pick,y=d.merge,z=d.extend,w=d.error;y(!0,d.defaultOptions,p,{accessibility:{highContrastTheme:v}});
d.KeyboardNavigationHandler=f;d.AccessibilityComponent=l;d.extend(d.SVGElement.prototype,{addFocusBorder:function(a,b){this.focusBorder&&this.removeFocusBorder();var c=this.getBBox();a=x(a,3);c.x+=this.translateX?this.translateX:0;c.y+=this.translateY?this.translateY:0;this.focusBorder=this.renderer.rect(c.x-a,c.y-a,c.width+2*a,c.height+2*a,b&&b.borderRadius).addClass("highcharts-focus-border").attr({zIndex:99}).add(this.parentGroup);this.renderer.styledMode||this.focusBorder.attr({stroke:b&&b.stroke,
"stroke-width":b&&b.strokeWidth})},removeFocusBorder:function(){this.focusBorder&&(this.focusBorder.destroy(),delete this.focusBorder)}});d.Chart.prototype.setFocusToElement=function(a,b){var c=this.options.accessibility.keyboardNavigation.focusBorder;(b=b||a.element)&&b.focus&&(b.hcEvents&&b.hcEvents.focusin||q(b,"focusin",function(){}),b.focus(),c.hideBrowserFocusOutline&&(b.style.outline="none"));c.enabled&&(this.focusElement&&this.focusElement.removeFocusBorder(),a.addFocusBorder(c.margin,{stroke:c.style.color,
strokeWidth:c.style.lineWidth,borderRadius:c.style.borderRadius}),this.focusElement=a)};d.Axis.prototype.getDescription=function(){return this.userOptions&&this.userOptions.accessibility&&this.userOptions.accessibility.description||this.axisTitle&&this.axisTitle.textStr||this.options.id||this.categories&&"categories"||this.isDatetimeAxis&&"Time"||"values"};r.prototype={init:function(d){var f=d.options.accessibility;this.chart=d;if(t.addEventListener&&d.renderer.isSVG){this.copyDeprecatedOptions();
var l=this.components={container:new g(d),infoRegion:new n(d),legend:new b(d),chartMenu:new a(d),rangeSelector:new k(d),series:new c(d),zoom:new e(d)};f.customComponents&&z(this.components,f.customComponents);this.keyboardNavigation=new h(d,l);this.update()}else d.renderTo.setAttribute("aria-hidden",!0)},update:function(){var a=this.components,b=this.chart,c=b.options.accessibility;b.types=this.getChartTypes();Object.keys(a).forEach(function(b){a[b].onChartUpdate()});this.keyboardNavigation.update(c.keyboardNavigation.order);
!b.highContrastModeActive&&m.isHighContrastModeActive(b)&&m.setHighContrastTheme(b)},destroy:function(){var a=this.chart||{},b=this.components;Object.keys(b).forEach(function(a){b[a].destroy()});this.keyboardNavigation&&this.keyboardNavigation.destroy();a.renderTo&&a.renderTo.setAttribute("aria-hidden",!0);a.focusElement&&a.focusElement.removeFocusBorder()},getChartTypes:function(){var a={};this.chart.series.forEach(function(b){a[b.type]=1});return Object.keys(a)},copyDeprecatedOptions:function(){var a=
this.chart,b=function(b,c){w("Highcharts: Deprecated option "+b+" used. Use "+c+" instead.",!1,a)},c={description:["accessibility","description"],exposeElementToA11y:["accessibility","exposeAsGroupOnly"],pointDescriptionFormatter:["accessibility","pointDescriptionFormatter"],skipKeyboardNavigation:["accessibility","keyboardNavigation","enabled"]},d=a.options.chart||{},e=a.options.accessibility||{};["description","typeDescription"].forEach(function(a){d[a]&&(e[a]=d[a],b("chart."+a,"accessibility."+
a))});a.axes.forEach(function(a){(a=a.options)&&a.description&&(a.accessibility=a.accessibility||{},a.accessibility.description=a.description,b("axis.description","axis.accessibility.description"))});a.series&&a.series.forEach(function(a){Object.keys(c).forEach(function(d){var e=a.options[d];if(void 0!==e){for(var e="skipKeyboardNavigation"===d?!e:e,f=c[d],g=a.options,h,k=0;k<f.length-1;++k)h=f[k],g=g[h]=x(g[h],{});g[f[f.length-1]]=e;b("series."+d,"series."+c[d].join("."))}});a.points&&a.points.forEach(function(a){a.options&&
a.options.description&&(a.options.accessibility=a.options.accessibility||{},a.options.accessibility.description=a.options.description,b("point.description","point.accessibility.description"))})})}};q(d.Chart,"render",function(a){var b=this.accessibility;if(this.a11yDirty&&this.renderTo){delete this.a11yDirty;var c=this.options.accessibility;c&&c.enabled?b?b.update():this.accessibility=b=new r(this):b?(b.destroy&&b.destroy(),delete this.accessibility):this.renderTo.setAttribute("aria-hidden",!0)}b&&
Object.keys(b.components).forEach(function(c){b.components[c].onChartRender(a)})});q(d.Chart,"update",function(a){if(a=a.options.accessibility)a.customComponents&&(this.options.accessibility.customComponents=a.customComponents,delete a.customComponents),y(!0,this.options.accessibility,a),this.accessibility&&this.accessibility.destroy&&(this.accessibility.destroy(),delete this.accessibility);this.a11yDirty=!0});q(d.Point,"update",function(){this.series.chart.accessibility&&(this.series.chart.a11yDirty=
!0)});["addSeries","init"].forEach(function(a){q(d.Chart,a,function(){this.a11yDirty=!0})});["update","updatedData","remove"].forEach(function(a){q(d.Series,a,function(){this.chart.accessibility&&(this.chart.a11yDirty=!0)})});["afterDrilldown","drillupall"].forEach(function(a){q(d.Chart,a,function(){this.accessibility&&this.accessibility.update()})});q(d.Chart,"destroy",function(){this.accessibility&&this.accessibility.destroy()})});n(f,"masters/modules/accessibility.src.js",[],function(){})});
//# sourceMappingURL=accessibility.js.map