/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Annotations module

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(t){c(t);c.Highcharts=t;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function t(b,c,a,g){b.hasOwnProperty(c)||(b[c]=g.apply(null,a))}c=c?c._modules:{};t(c,"annotations/eventEmitterMixin.js",[c["parts/Globals.js"]],function(b){var c=b.fireEvent;return{addEvents:function(){var a=
this;b.addEvent(a.graphic.element,"mousedown",function(b){a.onMouseDown(b)});b.objectEach(a.options.events,function(g,d){var h=function(h){"click"===d&&a.cancelClick||g.call(a,a.chart.pointer.normalize(h),a.target)};if(-1===b.inArray(d,a.nonDOMEvents||[]))a.graphic.on(d,h);else b.addEvent(a,d,h)});a.options.draggable&&(b.addEvent(a,"drag",a.onDrag),a.graphic.renderer.styledMode||a.graphic.css({cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[a.options.draggable]}));a.isUpdating||c(a,"add")},removeDocEvents:function(){this.removeDrag&&
(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(a){var g=this,d=g.chart.pointer,h,e;a.preventDefault&&a.preventDefault();2!==a.button&&(a=d.normalize(a),h=a.chartX,e=a.chartY,g.cancelClick=!1,g.removeDrag=b.addEvent(b.doc,"mousemove",function(a){g.hasDragged=!0;a=d.normalize(a);a.prevChartX=h;a.prevChartY=e;c(g,"drag",a);h=a.chartX;e=a.chartY}),g.removeMouseUp=b.addEvent(b.doc,"mouseup",function(h){g.cancelClick=g.hasDragged;
g.hasDragged=!1;c(b.pick(g.target,g),"afterUpdate");g.onMouseUp(h)}))},onMouseUp:function(){var a=this.chart,b=this.target||this,d=a.options.annotations,a=a.annotations.indexOf(b);this.removeDocEvents();d[a]=b.options},onDrag:function(a){if(this.chart.isInsidePlot(a.chartX-this.chart.plotLeft,a.chartY-this.chart.plotTop)){var b=this.mouseMoveToTranslation(a);"x"===this.options.draggable&&(b.y=0);"y"===this.options.draggable&&(b.x=0);this.points.length?this.translate(b.x,b.y):(this.shapes.forEach(function(a){a.translate(b.x,
b.y)}),this.labels.forEach(function(a){a.translate(b.x,b.y)}));this.redraw(!1)}},mouseMoveToRadians:function(a,b,d){var h=a.prevChartY-d,e=a.prevChartX-b;d=a.chartY-d;a=a.chartX-b;this.chart.inverted&&(b=e,e=h,h=b,b=a,a=d,d=b);return Math.atan2(d,a)-Math.atan2(h,e)},mouseMoveToTranslation:function(a){var b=a.chartX-a.prevChartX;a=a.chartY-a.prevChartY;var d;this.chart.inverted&&(d=a,a=b,b=d);return{x:b,y:a}},mouseMoveToScale:function(a,b,d){b=(a.chartX-b||1)/(a.prevChartX-b||1);a=(a.chartY-d||1)/
(a.prevChartY-d||1);this.chart.inverted&&(d=a,a=b,b=d);return{x:b,y:a}},destroy:function(){this.removeDocEvents();b.removeEvent(this);this.hcEvents=null}}});t(c,"annotations/ControlPoint.js",[c["parts/Globals.js"],c["annotations/eventEmitterMixin.js"]],function(b,c){function a(a,d,h,e){this.chart=a;this.target=d;this.options=h;this.index=b.pick(h.index,e)}b.extend(a.prototype,c);a.prototype.nonDOMEvents=["drag"];a.prototype.setVisibility=function(a){this.graphic.attr("visibility",a?"visible":"hidden");
this.options.visible=a};a.prototype.render=function(){var a=this.chart,b=this.options;this.graphic=a.renderer.symbol(b.symbol,0,0,b.width,b.height).add(a.controlPointsGroup).css(b.style);this.setVisibility(b.visible);this.addEvents()};a.prototype.redraw=function(a){this.graphic[a?"animate":"attr"](this.options.positioner.call(this,this.target))};a.prototype.destroy=function(){c.destroy.call(this);this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};a.prototype.update=
function(a){var d=this.chart,h=this.target,e=this.index;a=b.merge(!0,this.options,a);this.destroy();this.constructor(d,h,a,e);this.render(d.controlPointsGroup);this.redraw()};return a});t(c,"annotations/MockPoint.js",[c["parts/Globals.js"]],function(b){function c(a,g,d){this.series={visible:!0,chart:a,getPlotBox:b.Series.prototype.getPlotBox};this.target=g||null;this.options=d;this.applyOptions(this.getOptions())}c.fromPoint=function(a){return new c(a.series.chart,null,{x:a.x,y:a.y,xAxis:a.series.xAxis,
yAxis:a.series.yAxis})};c.pointToPixels=function(a,b){var d=a.series,h=d.chart,e=a.plotX,m=a.plotY;h.inverted&&(a.mock?(e=a.plotY,m=a.plotX):(e=h.plotWidth-a.plotY,m=h.plotHeight-a.plotX));d&&!b&&(a=d.getPlotBox(),e+=a.translateX,m+=a.translateY);return{x:e,y:m}};c.pointToOptions=function(a){return{x:a.x,y:a.y,xAxis:a.series.xAxis,yAxis:a.series.yAxis}};b.extend(c.prototype,{mock:!0,hasDynamicOptions:function(){return"function"===typeof this.options},getOptions:function(){return this.hasDynamicOptions()?
this.options(this.target):this.options},applyOptions:function(a){this.command=a.command;this.setAxis(a,"x");this.setAxis(a,"y");this.refresh()},setAxis:function(a,g){g+="Axis";a=a[g];var d=this.series.chart;this.series[g]=a instanceof b.Axis?a:b.defined(a)?d[g][a]||d.get(a):null},toAnchor:function(){var a=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(a[0]=this.plotY,a[1]=this.plotX);return a},getLabelConfig:function(){return{x:this.x,y:this.y,point:this}},isInsidePane:function(){var a=
this.plotX,g=this.plotY,d=this.series.xAxis,h=this.series.yAxis,e=!0;d&&(e=b.defined(a)&&0<=a&&a<=d.len);h&&(e=e&&b.defined(g)&&0<=g&&g<=h.len);return e},refresh:function(){var a=this.series,b=a.xAxis,a=a.yAxis,d=this.getOptions();b?(this.x=d.x,this.plotX=b.toPixels(d.x,!0)):(this.x=null,this.plotX=d.x);a?(this.y=d.y,this.plotY=a.toPixels(d.y,!0)):(this.y=null,this.plotY=d.y);this.isInside=this.isInsidePane()},translate:function(a,b,d,h){this.hasDynamicOptions()||(this.plotX+=d,this.plotY+=h,this.refreshOptions())},
scale:function(a,b,d,h){if(!this.hasDynamicOptions()){var e=this.plotY*h;this.plotX=(1-d)*a+this.plotX*d;this.plotY=(1-h)*b+e;this.refreshOptions()}},rotate:function(a,b,d){if(!this.hasDynamicOptions()){var h=Math.cos(d);d=Math.sin(d);var e=this.plotX,m=this.plotY,e=e-a,m=m-b;this.plotX=e*h-m*d+a;this.plotY=e*d+m*h+b;this.refreshOptions()}},refreshOptions:function(){var a=this.series,b=a.xAxis,a=a.yAxis;this.x=this.options.x=b?this.options.x=b.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=
a?a.toValue(this.plotY,!0):this.plotY}});return c});t(c,"annotations/controllable/controllableMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["annotations/ControlPoint.js"],c["annotations/MockPoint.js"]],function(b,c,a,g){var d=c.isString;return{init:function(a,b,m){this.annotation=a;this.chart=a.chart;this.options=b;this.points=[];this.controlPoints=[];this.index=m;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var a=
this.options;return a.points||a.point&&b.splat(a.point)},attrsFromOptions:function(a){var b=this.constructor.attrsMap,h={},d,q,c=this.chart.styledMode;for(d in a)q=b[d],!q||c&&-1!==["fill","stroke","stroke-width"].indexOf(q)||(h[q]=a[d]);return h},anchor:function(a){var e=a.series.getPlotBox();a=a.mock?a.toAnchor():b.Tooltip.prototype.getAnchor.call({chart:a.series.chart},a);a={x:a[0]+(this.options.x||0),y:a[1]+(this.options.y||0),height:a[2]||0,width:a[3]||0};return{relativePosition:a,absolutePosition:b.merge(a,
{x:a.x+e.translateX,y:a.y+e.translateY})}},point:function(a,e){if(a&&a.series)return a;e&&null!==e.series||(b.isObject(a)?e=new g(this.chart,this,a):d(a)?e=this.chart.get(a)||null:"function"===typeof a&&(e=a.call(e,this),e=e.series?e:new g(this.chart,this,a)));return e},linkPoints:function(){var a=this.getPointsOptions(),b=this.points,d=a&&a.length||0,n,c;for(n=0;n<d;n++){c=this.point(a[n],b[n]);if(!c){b.length=0;return}c.mock&&c.refresh();b[n]=c}return b},addControlPoints:function(){var h=this.options.controlPoints;
(h||[]).forEach(function(e,d){e=b.merge(this.options.controlPointOptions,e);e.index||(e.index=d);h[d]=e;this.controlPoints.push(new a(this.chart,this,e))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(){this.controlPoints.forEach(function(a){a.render()})},redraw:function(a){this.controlPoints.forEach(function(b){b.redraw(a)})},transform:function(a,b,d,c,q){if(this.chart.inverted){var e=b;b=d;d=e}this.points.forEach(function(e,h){this.transformPoint(a,b,d,c,q,h)},this)},
transformPoint:function(a,b,d,c,q,r){var e=this.points[r];e.mock||(e=this.points[r]=g.fromPoint(e));e[a](b,d,c,q)},translate:function(a,b){this.transform("translate",null,null,a,b)},translatePoint:function(a,b,d){this.transformPoint("translate",null,null,a,b,d)},translateShape:function(a,b){var e=this.annotation.chart,d=this.annotation.userOptions,h=e.annotations.indexOf(this.annotation),e=e.options.annotations[h];this.translatePoint(a,b,0);e[this.collection][this.index].point=this.options.point;
d[this.collection][this.index].point=this.options.point},rotate:function(a,b,d){this.transform("rotate",a,b,d)},scale:function(a,b,d,c){this.transform("scale",a,b,d,c)},setControlPointsVisibility:function(a){this.controlPoints.forEach(function(b){b.setVisibility(a)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());this.controlPoints.forEach(function(a){a.destroy()});this.options=this.controlPoints=this.points=this.chart=null;
this.annotation&&(this.annotation=null)},update:function(a){var e=this.annotation;a=b.merge(!0,this.options,a);var d=this.graphic.parentGroup;this.destroy();this.constructor(e,a);this.render(d);this.redraw()}}});t(c,"annotations/controllable/markerMixin.js",[c["parts/Globals.js"]],function(b){var c={arrow:{tagName:"marker",render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},"reverse-arrow":{tagName:"marker",render:!1,
id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};b.SVGRenderer.prototype.addMarker=function(a,d){var h={id:a},e={stroke:d.color||"none",fill:d.color||"rgba(0, 0, 0, 0.75)"};h.children=d.children.map(function(a){return b.merge(e,a)});d=this.definition(b.merge(!0,{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},d,h));d.id=a;return d};var a=function(a){return function(b){this.attr(a,"url(#"+b+")")}},a={markerEndSetter:a("marker-end"),
markerStartSetter:a("marker-start"),setItemMarkers:function(a){var d=a.options,h=a.chart,e=h.options.defs,m=d.fill,c=b.defined(m)&&"none"!==m?m:d.stroke;["markerStart","markerEnd"].forEach(function(m){var n=d[m],f,k,l;if(n){for(l in e)if(f=e[l],n===f.id&&"marker"===f.tagName){k=f;break}k&&(n=a[m]=h.renderer.addMarker((d.id||b.uniqueKey())+"-"+k.id,b.merge(k,{color:c})),a.attr(m,n.attr("id")))}})}};b.SVGRenderer.prototype.definition=function(a){function d(a,m){var e;b.splat(a).forEach(function(a){var c=
h.createElement(a.tagName),f={};b.objectEach(a,function(a,b){"tagName"!==b&&"children"!==b&&"textContent"!==b&&(f[b]=a)});c.attr(f);c.add(m||h.defs);a.textContent&&c.element.appendChild(b.doc.createTextNode(a.textContent));d(a.children||[],c);e=c});return e}var h=this;return d(a)};b.addEvent(b.Chart,"afterGetContainer",function(){this.options.defs=b.merge(c,this.options.defs||{});b.objectEach(this.options.defs,function(a){"marker"===a.tagName&&!1!==a.render&&this.renderer.addMarker(a.id,a)},this)});
return a});t(c,"annotations/controllable/ControllablePath.js",[c["parts/Globals.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/markerMixin.js"]],function(b,c,a){function g(a,b,d){this.init(a,b,d);this.collection="shapes"}var d="rgba(192,192,192,"+(b.svg?.0001:.002)+")";g.attrsMap={dashStyle:"dashstyle",strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};b.merge(!0,g.prototype,c,{type:"path",setMarkers:a.setItemMarkers,toD:function(){var a=this.options.d;
if(a)return"function"===typeof a?a.call(this):a;for(var b=this.points,d=b.length,c=d,q=b[0],g=c&&this.anchor(q).absolutePosition,f=0,k=2,a=g&&["M",g.x,g.y];++f<d&&c;)q=b[f],c=q.command||"L",g=this.anchor(q).absolutePosition,"Z"===c?a[++k]=c:(c!==b[f-1].command&&(a[++k]=c),a[++k]=g.x,a[++k]=g.y),c=q.series.visible;return c?this.chart.renderer.crispLine(a,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return c.shouldBeDrawn.call(this)||!!this.options.d},render:function(h){var e=this.options,
m=this.attrsFromOptions(e);this.graphic=this.annotation.chart.renderer.path(["M",0,0]).attr(m).add(h);e.className&&this.graphic.addClass(e.className);this.tracker=this.annotation.chart.renderer.path(["M",0,0]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(h);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:d,fill:d,"stroke-width":this.graphic.strokeWidth()+2*e.snap});c.render.call(this);b.extend(this.graphic,{markerStartSetter:a.markerStartSetter,markerEndSetter:a.markerEndSetter});
this.setMarkers(this)},redraw:function(a){var b=this.toD(),d=a?"animate":"attr";b?(this.graphic[d]({d:b}),this.tracker[d]({d:b})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));this.graphic.placed=this.tracker.placed=!!b;c.redraw.call(this,a)}});return g});t(c,"annotations/controllable/ControllableRect.js",[c["parts/Globals.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"]],function(b,c,a){function g(a,b,
e){this.init(a,b,e);this.collection="shapes"}g.attrsMap=b.merge(a.attrsMap,{width:"width",height:"height"});b.merge(!0,g.prototype,c,{type:"rect",translate:c.translateShape,render:function(a){var b=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(b).add(a);c.render.call(this)},redraw:function(a){var b=this.anchor(this.points[0]).absolutePosition;if(b)this.graphic[a?"animate":"attr"]({x:b.x,y:b.y,width:this.options.width,height:this.options.height});
else this.attr({x:0,y:-9E9});this.graphic.placed=!!b;c.redraw.call(this,a)}});return g});t(c,"annotations/controllable/ControllableCircle.js",[c["parts/Globals.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"]],function(b,c,a){function g(a,b,e){this.init(a,b,e);this.collection="shapes"}g.attrsMap=b.merge(a.attrsMap,{r:"r"});b.merge(!0,g.prototype,c,{type:"circle",translate:c.translateShape,render:function(a){var b=this.attrsFromOptions(this.options);
this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(b).add(a);c.render.call(this)},redraw:function(a){var b=this.anchor(this.points[0]).absolutePosition;if(b)this.graphic[a?"animate":"attr"]({x:b.x,y:b.y,r:this.options.r});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!b;c.redraw.call(this,a)},setRadius:function(a){this.options.r=a}});return g});t(c,"annotations/controllable/ControllableLabel.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["annotations/controllable/controllableMixin.js"],
c["annotations/MockPoint.js"]],function(b,c,a,g){function d(a,b,d){this.init(a,b,d);this.collection="labels"}var h=c.isNumber;d.shapesWithoutBackground=["connector"];d.alignedPosition=function(a,b){var d=a.align,c=a.verticalAlign,e=(b.x||0)+(a.x||0),f=(b.y||0)+(a.y||0),k,l;"right"===d?k=1:"center"===d&&(k=2);k&&(e+=(b.width-(a.width||0))/k);"bottom"===c?l=1:"middle"===c&&(l=2);l&&(f+=(b.height-(a.height||0))/l);return{x:Math.round(e),y:Math.round(f)}};d.justifiedOptions=function(a,b,d,c){var e=d.align,
f=d.verticalAlign,k=b.box?0:b.padding||0,l=b.getBBox();b={align:e,verticalAlign:f,x:d.x,y:d.y,width:b.width,height:b.height};d=c.x-a.plotLeft;var p=c.y-a.plotTop;c=d+k;0>c&&("right"===e?b.align="left":b.x=-c);c=d+l.width-k;c>a.plotWidth&&("left"===e?b.align="right":b.x=a.plotWidth-c);c=p+k;0>c&&("bottom"===f?b.verticalAlign="top":b.y=-c);c=p+l.height-k;c>a.plotHeight&&("top"===f?b.verticalAlign="bottom":b.y=a.plotHeight-c);return b};d.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",
zIndex:"zIndex",borderRadius:"r",padding:"padding"};b.merge(!0,d.prototype,a,{translatePoint:function(b,d){a.translatePoint.call(this,b,d,0)},translate:function(a,b){var d=this.annotation.chart,c=this.annotation.userOptions,e=d.annotations.indexOf(this.annotation),e=d.options.annotations[e];d.inverted&&(d=a,a=b,b=d);this.options.x+=a;this.options.y+=b;e[this.collection][this.index].x=this.options.x;e[this.collection][this.index].y=this.options.y;c[this.collection][this.index].x=this.options.x;c[this.collection][this.index].y=
this.options.y},render:function(b){var c=this.options,e=this.attrsFromOptions(c),h=c.style;this.graphic=this.annotation.chart.renderer.label("",0,-9999,c.shape,null,null,c.useHTML,null,"annotation-label").attr(e).add(b);this.annotation.chart.styledMode||("contrast"===h.color&&(h.color=this.annotation.chart.renderer.getContrast(-1<d.shapesWithoutBackground.indexOf(c.shape)?"#FFFFFF":c.backgroundColor)),this.graphic.css(c.style).shadow(c.shadow));c.className&&this.graphic.addClass(c.className);this.graphic.labelrank=
c.labelrank;a.render.call(this)},redraw:function(c){var d=this.options,e=this.text||d.format||d.text,h=this.graphic,g=this.points[0];h.attr({text:e?b.format(e,g.getLabelConfig(),this.annotation.chart.time):d.formatter.call(g,this)});d=this.anchor(g);(e=this.position(d))?(h.alignAttr=e,e.anchorX=d.absolutePosition.x,e.anchorY=d.absolutePosition.y,h[c?"animate":"attr"](e)):h.attr({x:0,y:-9999});h.placed=!!e;a.redraw.call(this,c)},anchor:function(){var b=a.anchor.apply(this,arguments),c=this.options.x||
0,d=this.options.y||0;b.absolutePosition.x-=c;b.absolutePosition.y-=d;b.relativePosition.x-=c;b.relativePosition.y-=d;return b},position:function(a){var c=this.graphic,e=this.annotation.chart,h=this.points[0],r=this.options,f=a.absolutePosition,k=a.relativePosition,l;if(a=h.series.visible&&g.prototype.isInsidePane.call(h))r.distance?l=b.Tooltip.prototype.getPosition.call({chart:e,distance:b.pick(r.distance,16)},c.width,c.height,{plotX:k.x,plotY:k.y,negative:h.negative,ttBelow:h.ttBelow,h:k.height||
k.width}):r.positioner?l=r.positioner.call(this):(h={x:f.x,y:f.y,width:0,height:0},l=d.alignedPosition(b.extend(r,{width:c.width,height:c.height}),h),"justify"===this.options.overflow&&(l=d.alignedPosition(d.justifiedOptions(e,c,r,l),h))),r.crop&&(r=l.x-e.plotLeft,h=l.y-e.plotTop,a=e.isInsidePlot(r,h)&&e.isInsidePlot(r+c.width,h+c.height));return a?l:null}});b.SVGRenderer.prototype.symbols.connector=function(a,b,c,d,g){var f=g&&g.anchorX;g=g&&g.anchorY;var k,e,p=c/2;h(f)&&h(g)&&(k=["M",f,g],e=b-g,
0>e&&(e=-d-e),e<c&&(p=f<a+c/2?e:c-e),g>b+d?k.push("L",a+p,b+d):g<b?k.push("L",a+p,b):f<a?k.push("L",a,b+d/2):f>a+c&&k.push("L",a+c,b+d/2));return k||[]};return d});t(c,"annotations/controllable/ControllableImage.js",[c["parts/Globals.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllableLabel.js"]],function(b,c,a){function g(a,b,c){this.init(a,b,c);this.collection="shapes"}g.attrsMap={width:"width",height:"height",zIndex:"zIndex"};b.merge(!0,g.prototype,c,
{type:"image",translate:c.translateShape,render:function(a){var b=this.attrsFromOptions(this.options),d=this.options;this.graphic=this.annotation.chart.renderer.image(d.src,0,-9E9,d.width,d.height).attr(b).add(a);this.graphic.width=d.width;this.graphic.height=d.height;c.render.call(this)},redraw:function(b){var d=this.anchor(this.points[0]);if(d=a.prototype.position.call(this,d))this.graphic[b?"animate":"attr"]({x:d.x,y:d.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!d;c.redraw.call(this,
b)}});return g});t(c,"annotations/annotations.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllableRect.js"],c["annotations/controllable/ControllableCircle.js"],c["annotations/controllable/ControllablePath.js"],c["annotations/controllable/ControllableImage.js"],c["annotations/controllable/ControllableLabel.js"],c["annotations/eventEmitterMixin.js"],c["annotations/MockPoint.js"],c["annotations/ControlPoint.js"]],
function(b,c,a,g,d,h,e,m,n,q,r){var f=c.isString,k=b.merge,l=b.addEvent,p=b.fireEvent,y=b.defined,u=b.erase,w=b.find,x=b.pick,z=b.reduce,A=b.splat,t=b.destroyObjectProperties;c=b.Chart.prototype;var v=b.Annotation=function(a,b){var c;this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=b;this.userOptions=k(!0,{},b);c=this.getLabelsAndShapesOptions(this.userOptions,b);this.userOptions.labels=c.labels;this.userOptions.shapes=c.shapes;this.init(a,
b)};k(!0,v.prototype,a,n,{nonDOMEvents:["add","afterUpdate","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",borderRadius:3,borderWidth:1,className:"",crop:!1,formatter:function(){return y(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",
strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},events:{},zIndex:6},init:function(){this.linkPoints();this.addControlPoints();this.addShapes();this.addLabels();this.addClipPaths();this.setLabelCollector()},getLabelsAndShapesOptions:function(a,b){var c={};["labels","shapes"].forEach(function(d){a[d]&&(c[d]=A(b[d]).map(function(b,c){return k(a[d][c],b)}))});return c},
addShapes:function(){(this.options.shapes||[]).forEach(this.initShape,this)},addLabels:function(){(this.options.labels||[]).forEach(this.initLabel,this)},addClipPaths:function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))},setClipAxes:function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=z((this.options.labels||[]).concat(this.options.shapes||[]),function(c,d){return[a[d&&d.point&&d.point.xAxis]||c[0],b[d&&d.point&&d.point.yAxis]||
c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]},getClipBox:function(){return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}},setLabelCollector:function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)},setOptions:function(a){this.options=k(this.defaultOptions,a)},redraw:function(b){this.linkPoints();this.graphic||
this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());this.redrawItems(this.shapes,b);this.redrawItems(this.labels,b);a.redraw.call(this,b)},redrawItems:function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)},render:function(){var b=this.chart.renderer;this.graphic=b.g("annotation").attr({zIndex:this.options.zIndex,visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=b.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);this.labelsGroup=
b.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.clipRect&&this.graphic.clip(this.clipRect);this.addEvents();a.render.call(this)},setVisibility:function(a){var b=this.options;a=x(a,!b.visible);this.graphic.attr("visibility",a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a},setControlPointsVisibility:function(b){var c=function(a){a.setControlPointsVisibility(b)};a.setControlPointsVisibility.call(this,b);this.shapes.forEach(c);this.labels.forEach(c)},
destroy:function(){var b=this.chart,c=function(a){a.destroy()};this.labels.forEach(c);this.shapes.forEach(c);this.clipYAxis=this.clipXAxis=null;u(b.labelCollectors,this.labelCollector);n.destroy.call(this);a.destroy.call(this);t(this,b)},remove:function(){return this.chart.removeAnnotation(this)},update:function(a){var c=this.chart,d=this.getLabelsAndShapesOptions(this.userOptions,a),k=c.annotations.indexOf(this);a=b.merge(!0,this.userOptions,a);a.labels=d.labels;a.shapes=d.shapes;this.destroy();
this.constructor(c,a);c.options.annotations[k]=a;this.isUpdating=!0;this.redraw();this.isUpdating=!1;p(this,"afterUpdate")},initShape:function(a,b){a=k(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new v.shapesMap[a.type](this,a,b);b.itemType="shape";this.shapes.push(b);return b},initLabel:function(a,b){a=k(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new m(this,a,b);b.itemType="label";this.labels.push(b);return b},redrawItem:function(a,
c){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(b.pick(c,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)},adjustVisibility:function(a){var b=!1,c=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===c.visibility&&c.show():c.hide()},destroyItem:function(a){u(this[a.itemType+"s"],a);a.destroy()},renderItem:function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)}});v.shapesMap=
{rect:g,circle:d,path:h,image:e};v.types={};v.MockPoint=q;v.ControlPoint=r;b.extendAnnotation=function(a,b,c,d){b=b||v;k(!0,a.prototype,b.prototype,c);a.prototype.defaultOptions=k(a.prototype.defaultOptions,d||{})};b.extend(c,{initAnnotation:function(a){var c=v.types[a.type]||v;a=b.merge(c.prototype.defaultOptions,a);c=new c(this,a);this.annotations.push(c);return c},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);x(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=
this.annotations,c=f(a)?w(b,function(b){return b.options.id===a}):a;c&&(p(c,"remove"),u(this.options.annotations,c.options),u(b,c),c.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});c.collectionsWithUpdate.push("annotations");c.collectionsWithInit.annotations=[c.addAnnotation];c.callbacks.push(function(a){a.annotations=[];a.options.annotations||(a.options.annotations=[]);a.plotBoxClip=this.renderer.clipRect(this.plotBox);
a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();a.options.annotations.forEach(function(b,c){b=a.initAnnotation(b);a.options.annotations[c]=b.options});a.drawAnnotations();l(a,"redraw",a.drawAnnotations);l(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()})})});t(c,"mixins/navigation.js",[],function(){return{initUpdate:function(b){b.navigation||(b.navigation={updates:[],update:function(b,a){this.updates.forEach(function(c){c.update.call(c.context,
b,a)})}})},addUpdate:function(b,c){c.navigation||this.initUpdate(c);c.navigation.updates.push({update:b,context:c})}}});t(c,"annotations/navigationBindings.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["mixins/navigation.js"]],function(b,c,a){function g(a){var c=a.prototype.defaultOptions.events&&a.prototype.defaultOptions.events.click;b.merge(!0,a.prototype.defaultOptions.events,{click:function(a){var b=this,d=b.chart.navigationBindings,p=d.activeAnnotation;c&&c.click.call(b,a);p!==b?(d.deselectAnnotation(),
d.activeAnnotation=b,b.setControlPointsVisibility(!0),f(d,"showPopup",{annotation:b,formType:"annotation-toolbar",options:d.annotationToFields(b),onSubmit:function(a){var c={};"remove"===a.actionType?(d.activeAnnotation=!1,d.chart.removeAnnotation(b)):(d.fieldsToOptions(a.fields,c),d.deselectAnnotation(),a=c.typeOptions,"measure"===b.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),b.update(c))}})):(d.deselectAnnotation(),f(d,"closePopup"));
a.activeAnnotation=!0}})}var d=c.isArray,h=c.isNumber,e=b.doc,m=b.win,n=b.addEvent,q=b.pick,r=b.merge;c=b.extend;var f=b.fireEvent,k=b.isObject,l=b.objectEach;b.NavigationBindings=function(a,b){this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=e.getElementsByClassName(this.options.bindingsClassName)};b.NavigationBindings.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill",
"strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill","strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background",
"line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[]};b.NavigationBindings.annotationsNonEditable={rectangle:["crosshairX","crosshairY","label"]};c(b.NavigationBindings.prototype,{initEvents:function(){var a=this,c=a.chart,d=a.container,k=a.options;a.boundClassNames={};l(k.bindings,function(b){a.boundClassNames[b.className]=b});[].forEach.call(d,function(b){a.eventsToUnbind.push(n(b,"click",function(b){var c=a.getButtonEvents(d,b);c&&a.bindingsButtonClick(c.button,
c.events,b)}))});l(k.events||{},function(c,d){b.isFunction(c)&&a.eventsToUnbind.push(n(a,d,c))});a.eventsToUnbind.push(n(c.container,"click",function(b){!c.cancelClick&&c.isInsidePlot(b.chartX-c.plotLeft,b.chartY-c.plotTop)&&a.bindingsChartClick(this,b)}));a.eventsToUnbind.push(n(c.container,"mousemove",function(b){a.bindingsContainerMouseMove(this,b)}))},initUpdate:function(){var b=this;a.addUpdate(function(a){b.update(a)},this.chart)},bindingsButtonClick:function(a,b,c){var d=this.chart;this.selectedButtonElement&&
(f(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&d.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=b;this.selectedButtonElement=a;f(this,"selectButton",{button:a});b.init&&b.init.call(this,a,c);(b.start||b.steps)&&d.renderer.boxWrapper.addClass("highcharts-draw-mode")},bindingsChartClick:function(a,b){a=this.selectedButton;var c=this.chart.renderer.boxWrapper,
d;if(d=this.activeAnnotation&&!b.activeAnnotation&&b.target.parentNode){a:{d=b.target;var k=m.Element.prototype,e=k.matches||k.msMatchesSelector||k.webkitMatchesSelector,p=null;if(k.closest)p=k.closest.call(d,".highcharts-popup");else{do{if(e.call(d,".highcharts-popup"))break a;d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType)}d=p}d=!d}d&&(f(this,"closePopup"),this.deselectAnnotation());a&&a.start&&(this.nextEvent?(this.nextEvent(b,this.currentUserDetails),this.steps&&(this.stepIndex++,
a.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=a.steps[this.stepIndex]:(f(this,"deselectButton",{button:this.selectedButtonElement}),c.removeClass("highcharts-draw-mode"),a.end&&a.end.call(this,b,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=a.start.call(this,b),a.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=a.steps[this.stepIndex]):(f(this,"deselectButton",{button:this.selectedButtonElement}),
c.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,a.end&&a.end.call(this,b,this.currentUserDetails))))},bindingsContainerMouseMove:function(a,b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)},fieldsToOptions:function(a,b){l(a,function(a,c){var d=parseFloat(a),k=c.split("."),f=b,e=k.length-1;!h(d)||a.match(/px/g)||c.match(/format/g)||(a=d);""!==a&&"undefined"!==a&&k.forEach(function(b,c){var d=q(k[c+1],"");e===c?f[b]=a:(f[b]||(f[b]=d.match(/\d/g)?[]:
{}),f=f[b])})});return b},deselectAnnotation:function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)},annotationToFields:function(a){function c(f,e,w,u){var g;w&&-1===m.indexOf(e)&&(0<=(w.indexOf&&w.indexOf(e))||w[e]||!0===w)&&(d(f)?(u[e]=[],f.forEach(function(a,b){k(a)?(u[e][b]={},l(a,function(a,d){c(a,d,p[e],u[e][b])})):c(a,0,p[e],u[e])})):k(f)?(g={},d(u)?(u.push(g),g[e]={},g=g[e]):u[e]=g,l(f,function(a,b){c(a,b,0===e?w:p[e],g)})):"format"===
e?u[e]=[b.format(f,a.labels[0].points[0]).toString(),"text"]:d(u)?u.push([f,h(f)]):u[e]=[f,h(f)])}var f=a.options,e=b.NavigationBindings.annotationsEditable,p=e.nestedOptions,h=this.utils.getFieldType,g=q(f.type,f.shapes&&f.shapes[0]&&f.shapes[0].type,f.labels&&f.labels[0]&&f.labels[0].itemType,"label"),m=b.NavigationBindings.annotationsNonEditable[f.langKey]||[],v={langKey:f.langKey,type:g};l(f,function(a,b){"typeOptions"===b?(v[b]={},l(f[b],function(a,d){c(a,d,p,v[b],!0)})):c(a,b,e[g],v)});return v},
getClickedClassNames:function(a,c){var d=c.target;c=[];for(var f;d&&((f=b.attr(d,"class"))&&(c=c.concat(f.split(" ").map(function(a){return[a,d]}))),d=d.parentNode,d!==a););return c},getButtonEvents:function(a,b){var c=this,d;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!d&&(d={events:c.boundClassNames[a[0]],button:a[1]})});return d},update:function(a){this.options=r(!0,this.options,a);this.removeEvents();this.initEvents()},removeEvents:function(){this.eventsToUnbind.forEach(function(a){a()})},
destroy:function(){this.removeEvents()},utils:{updateRectSize:function(a,b){var c=b.chart,d=b.options.typeOptions,f=c.pointer.getCoordinates(a);a=f.xAxis[0].value-d.point.x;d=d.point.y-f.yAxis[0].value;b.update({typeOptions:{background:{width:c.inverted?d:a,height:c.inverted?a:d}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}}});b.Chart.prototype.initNavigationBindings=function(){var a=this.options;a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=
new b.NavigationBindings(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};n(b.Chart,"load",function(){this.initNavigationBindings()});n(b.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});n(b.NavigationBindings,"deselectButton",function(){this.selectedButtonElement=null});n(b.Annotation,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});b.Annotation&&(g(b.Annotation),
b.objectEach(b.Annotation.types,function(a){g(a)}));b.setOptions({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",
borderWidth:"Border width",style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation,d=c&&c.bindings;return this.chart.addAnnotation(r({langKey:"circle",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},
r:5,controlPoints:[{positioner:function(a){var c=b.Annotation.MockPoint.pointToPixels(a.points[0]);a=a.options.r;return{x:c.x+a*Math.cos(Math.PI/4)-this.graphic.width/2,y:c.y+a*Math.sin(Math.PI/4)-this.graphic.height/2}},events:{drag:function(a,b){var c=b.annotation;a=this.mouseMoveToTranslation(a);b.setRadius(Math.max(b.options.r+a.y/Math.sin(Math.PI/4),5));c.options.shapes[0]=c.userOptions.shapes[0]=b.options;b.redraw(!1)}}}]}]},c.annotationsOptions,d.circle&&d.circle.annotationsOptions))},steps:[function(a,
b){var c=b.options.shapes[0].point,d=this.chart.xAxis[0].toPixels(c.x),c=this.chart.yAxis[0].toPixels(c.y),f=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(f?c-a.chartX:d-a.chartX,2)+Math.pow(f?d-a.chartY:c-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation,d=c&&c.bindings;return this.chart.addAnnotation(r({langKey:"rectangle",shapes:[{type:"rect",
point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},width:5,height:5,controlPoints:[{positioner:function(a){var c=b.Annotation.MockPoint.pointToPixels(a.points[0]);return{x:c.x+a.options.width-4,y:c.y+a.options.height-4}},events:{drag:function(a,b){var c=b.annotation,d=this.chart.inverted;a=this.mouseMoveToTranslation(a);b.options.width=Math.max(b.options.width+(d?a.y:a.x),5);b.options.height=Math.max(b.options.height+(d?a.x:a.y),5);c.options.shapes[0]=b.options;c.userOptions.shapes[0]=
b.options;b.redraw(!1)}}}]}]},c.annotationsOptions,d.rect&&d.rect.annotationsOptions))},steps:[function(a,b){var c=this.chart.yAxis[0],d=this.chart.inverted,f=b.options.shapes[0].point,k=this.chart.xAxis[0].toPixels(f.x),c=c.toPixels(f.y);b.update({shapes:[{width:Math.max(d?a.chartX-c:a.chartX-k,5),height:Math.max(d?a.chartY-k:a.chartY-c,5),point:{x:f.x,y:f.y}}]})}]},labelAnnotation:{className:"highcharts-label-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var c=this.chart.options.navigation,
d=c&&c.bindings;this.chart.addAnnotation(r({langKey:"label",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},controlPoints:[{symbol:"triangle-down",positioner:function(a){if(!a.graphic.placed)return{x:0,y:-9E7};a=b.Annotation.MockPoint.pointToPixels(a.points[0]);return{x:a.x-this.graphic.width/2,y:a.y-this.graphic.height/2}},events:{drag:function(a,b){a=this.mouseMoveToTranslation(a);b.translatePoint(a.x,a.y);b.annotation.labels[0].options=b.options;
b.redraw(!1)}}},{symbol:"square",positioner:function(a){return a.graphic.placed?{x:a.graphic.alignAttr.x-this.graphic.width/2,y:a.graphic.alignAttr.y-this.graphic.height/2}:{x:0,y:-9E7}},events:{drag:function(a,b){a=this.mouseMoveToTranslation(a);b.translate(a.x,a.y);b.annotation.labels[0].options=b.options;b.redraw(!1)}}}],overflow:"none",crop:!0}]},c.annotationsOptions,d.label&&d.label.annotationsOptions))}}},events:{},annotationsOptions:{}}})});t(c,"annotations/popup.js",[c["parts/Globals.js"],
c["parts/Utilities.js"]],function(b,c){var a=c.isArray,g=c.isString,d=b.addEvent,h=b.createElement,e=b.defined,m=b.objectEach,n=b.pick;c=b.wrap;var q=b.isObject,r=/\d/g;c(b.Pointer.prototype,"onContainerMouseDown",function(a,b){var c=b.target&&b.target.className;g(c)&&0<=c.indexOf("highcharts-popup-field")||a.apply(this,Array.prototype.slice.call(arguments,1))});b.Popup=function(a){this.init(a)};b.Popup.prototype={init:function(a){this.container=h("div",{className:"highcharts-popup"},null,a);this.lang=
this.getLangpack();this.addCloseBtn()},addCloseBtn:function(){var a=this,b;b=h("div",{className:"highcharts-popup-close"},null,this.container);["click","touchstart"].forEach(function(c){d(b,c,function(){a.closePopup()})})},addColsContainer:function(a){var b;b=h("div",{className:"highcharts-popup-lhs-col"},null,a);a=h("div",{className:"highcharts-popup-rhs-col"},null,a);h("div",{className:"highcharts-popup-rhs-col-wrapper"},null,a);return{lhsCol:b,rhsCol:a}},addInput:function(a,b,c,d){var f=a.split("."),
f=f[f.length-1],e=this.lang;b="highcharts-"+b+"-"+f;b.match(r)||h("label",{innerHTML:e[f]||f,htmlFor:b},null,c);h("input",{name:b,value:d[0],type:d[1],className:"highcharts-popup-field"},null,c).setAttribute("highcharts-data-name",a)},addButton:function(a,b,c,e,g){var f=this,k=this.closePopup,l=this.getFields,p;p=h("button",{innerHTML:b},null,a);["click","touchstart"].forEach(function(a){d(p,a,function(){k.call(f);return e(l(g,c))})});return p},getFields:function(a,b){var c=a.querySelectorAll("input"),
d=a.querySelectorAll("#highcharts-select-series \x3e option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume \x3e option:checked")[0];var f,e,k;k={actionType:b,linkedTo:d&&d.getAttribute("value"),fields:{}};[].forEach.call(c,function(a){e=a.getAttribute("highcharts-data-name");(f=a.getAttribute("highcharts-data-series-id"))?k.seriesId=a.value:e?k.fields[e]=a.value:k.type=a.value});a&&(k.fields["params.volumeSeriesID"]=a.getAttribute("value"));return k},showPopup:function(){var a=this.container,
b=a.querySelectorAll(".highcharts-popup-close")[0];a.innerHTML="";0<=a.className.indexOf("highcharts-annotation-toolbar")&&(a.classList.remove("highcharts-annotation-toolbar"),a.removeAttribute("style"));a.appendChild(b);a.style.display="block"},closePopup:function(){this.popup.container.style.display="none"},showForm:function(a,b,c,d){this.popup=b.navigationBindings.popup;this.showPopup();"indicators"===a&&this.indicators.addForm.call(this,b,c,d);"annotation-toolbar"===a&&this.annotations.addToolbar.call(this,
b,c,d);"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,d);"flag"===a&&this.annotations.addForm.call(this,b,c,d,!0)},getLangpack:function(){return b.getOptions().lang.navigation.popup},annotations:{addToolbar:function(a,b,c){var d=this,e=this.lang,f=this.popup.container,k=this.showForm,g;-1===f.className.indexOf("highcharts-annotation-toolbar")&&(f.className+=" highcharts-annotation-toolbar");f.style.top=a.plotTop+10+"px";h("span",{innerHTML:n(e[b.langKey]||b.langKey,b.shapes&&b.shapes[0].type)},
null,f);g=this.addButton(f,e.removeButton||"remove","remove",c,f);g.className+=" highcharts-annotation-remove-button";g=this.addButton(f,e.editButton||"edit","edit",function(){k.call(d,"annotation-edit",a,b,c)},f);g.className+=" highcharts-annotation-edit-button"},addForm:function(a,b,c,d){var e=this.popup.container,f=this.lang,k,g;h("h2",{innerHTML:f[b.langKey]||b.langKey,className:"highcharts-popup-main-title"},null,e);g=h("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},null,
e);k=h("div",{className:"highcharts-popup-bottom-row"},null,e);this.annotations.addFormFields.call(this,g,a,"",b,[],!0);this.addButton(k,d?f.addButton||"add":f.saveButton||"save",d?"add":"save",c,e)},addFormFields:function(b,c,d,e,g,u){var f=this,k=this.annotations.addFormFields,l=this.addInput,p=this.lang,n,v;m(e,function(e,h){n=""!==d?d+"."+h:h;q(e)&&(!a(e)||a(e)&&q(e[0])?(v=p[h]||h,v.match(r)||g.push([!0,v,b]),k.call(f,b,c,n,e,g,!1)):g.push([f,n,"annotation",b,e]))});u&&(g=g.sort(function(a){return a[1].match(/format/g)?
-1:1}),g.forEach(function(a){!0===a[0]?h("span",{className:"highcharts-annotation-title",innerHTML:a[1]},null,a[2]):l.apply(a[0],a.splice(1))}))}},indicators:{addForm:function(a,b,c){var d=this.indicators,e=this.lang,f;this.tabs.init.call(this,a);b=this.popup.container.querySelectorAll(".highcharts-tab-item-content");this.addColsContainer(b[0]);d.addIndicatorList.call(this,a,b[0],"add");f=b[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,e.addButton||"add","add",c,f);this.addColsContainer(b[1]);
d.addIndicatorList.call(this,a,b[1],"edit");f=b[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,e.saveButton||"save","edit",c,f);this.addButton(f,e.removeButton||"remove","remove",c,f)},addIndicatorList:function(a,b,c){var e=this,f=b.querySelectorAll(".highcharts-popup-lhs-col")[0];b=b.querySelectorAll(".highcharts-popup-rhs-col")[0];var k="edit"===c,g=k?a.series:a.options.plotOptions,l=this.indicators.addFormFields,n,q,r;q=h("ul",{className:"highcharts-indicator-list"},null,
f);n=b.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];m(g,function(b,c){var f=b.options;if(b.params||f&&f.params){var p=e.indicators.getNameType(b,c),m=p.type;r=h("li",{className:"highcharts-indicator-list",innerHTML:p.name},null,q);["click","touchstart"].forEach(function(c){d(r,c,function(){l.call(e,a,k?b:g[m],p.type,n);k&&b.options&&h("input",{type:"hidden",name:"highcharts-id-"+m,value:b.options.id},null,n).setAttribute("highcharts-data-series-id",b.options.id)})})}});0<q.childNodes.length&&
q.childNodes[0].click()},getNameType:function(a,c){var d=a.options,e=b.seriesTypes,e=e[c]&&e[c].prototype.nameBase||c.toUpperCase();d&&d.type&&(c=a.options.type,e=a.name);return{name:e,type:c}},listAllSeries:function(a,b,c,d,g){a="highcharts-"+b+"-type-"+a;var f,k;h("label",{innerHTML:this.lang[b]||b,htmlFor:a},null,d);f=h("select",{name:a,className:"highcharts-popup-field"},null,d);f.setAttribute("id","highcharts-select-"+b);c.series.forEach(function(a){k=a.options;!k.params&&k.id&&"highcharts-navigator-series"!==
k.id&&h("option",{innerHTML:k.name||k.id,value:k.id},null,f)});e(g)&&(f.value=g)},addFormFields:function(a,b,c,d){var e=b.params||b.options.params,f=this.indicators.getNameType;d.innerHTML="";h("h3",{className:"highcharts-indicator-title",innerHTML:f(b,c).name},null,d);h("input",{type:"hidden",name:"highcharts-type-"+c,value:c},null,d);this.indicators.listAllSeries.call(this,c,"series",a,d,b.linkedParent&&e.volumeSeriesID);e.volumeSeriesID&&this.indicators.listAllSeries.call(this,c,"volume",a,d,b.linkedParent&&
b.linkedParent.options.id);this.indicators.addParamInputs.call(this,a,"params",e,c,d)},addParamInputs:function(a,b,c,d,e){var f=this,h=this.indicators.addParamInputs,k=this.addInput,g;m(c,function(c,l){g=b+"."+l;q(c)?h.call(f,a,g,c,d,e):"params.volumeSeriesID"!==g&&k.call(f,g,d,e,[c,"text"])})},getAmount:function(){var a=0;m(this.series,function(b){var c=b.options;(b.params||c&&c.params)&&a++});return a}},tabs:{init:function(a){var b=this.tabs;a=this.indicators.getAmount.call(a);var c;c=b.addMenuItem.call(this,
"add");b.addMenuItem.call(this,"edit",a);b.addContentItem.call(this,"add");b.addContentItem.call(this,"edit");b.switchTabs.call(this,a);b.selectTab.call(this,c,0)},addMenuItem:function(a,b){var c=this.popup.container,d="highcharts-tab-item",e=this.lang;0===b&&(d+=" highcharts-tab-disabled");b=h("span",{innerHTML:e[a+"Button"]||a,className:d},null,c);b.setAttribute("highcharts-data-tab-type",a);return b},addContentItem:function(){return h("div",{className:"highcharts-tab-item-content"},null,this.popup.container)},
switchTabs:function(a){var b=this,c;this.popup.container.querySelectorAll(".highcharts-tab-item").forEach(function(e,f){c=e.getAttribute("highcharts-data-tab-type");"edit"===c&&0===a||["click","touchstart"].forEach(function(a){d(e,a,function(){b.tabs.deselectAll.call(b);b.tabs.selectTab.call(b,this,f)})})})},selectTab:function(a,b){var c=this.popup.container.querySelectorAll(".highcharts-tab-item-content");a.className+=" highcharts-tab-item-active";c[b].className+=" highcharts-tab-item-show"},deselectAll:function(){var a=
this.popup.container,b=a.querySelectorAll(".highcharts-tab-item"),a=a.querySelectorAll(".highcharts-tab-item-content"),c;for(c=0;c<b.length;c++)b[c].classList.remove("highcharts-tab-item-active"),a[c].classList.remove("highcharts-tab-item-show")}}};d(b.NavigationBindings,"showPopup",function(a){this.popup||(this.popup=new b.Popup(this.chart.container));this.popup.showForm(a.formType,this.chart,a.options,a.onSubmit)});d(b.NavigationBindings,"closePopup",function(){this.popup&&this.popup.closePopup()})});
t(c,"masters/modules/annotations.src.js",[],function(){})});
//# sourceMappingURL=annotations.js.map