/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Boost module

 (c) 2010-2019 Highsoft AS
 Author: Torstein Honsi

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/boost-canvas",["highcharts"],function(l){d(l);d.Highcharts=l;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function l(b,d,l,n){b.hasOwnProperty(d)||(b[d]=n.apply(null,l))}d=d?d._modules:{};l(d,"modules/boost-canvas.src.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(b,d){var l=d.isNumber,n=b.win.document,
ba=function(){},ca=b.Color,v=b.Series,k=b.seriesTypes,w=b.extend,x=b.addEvent,da=b.fireEvent,ea=b.merge,fa=b.pick,y=b.wrap,I;b.initCanvasBoost=function(){b.seriesTypes.heatmap&&b.wrap(b.seriesTypes.heatmap.prototype,"drawPoints",function(){var a=this.chart,c=this.getContext(),g=this.chart.inverted,b=this.xAxis,e=this.yAxis;c?(this.points.forEach(function(d){var f=d.plotY;void 0===f||isNaN(f)||null===d.y||(f=d.shapeArgs,d=a.styledMode?d.series.colorAttribs(d):d.series.pointAttribs(d),c.fillStyle=d.fill,
g?c.fillRect(e.len-f.y+b.left,b.len-f.x+e.top,-f.height,-f.width):c.fillRect(f.x+b.left,f.y+e.top,f.width,f.height))}),this.canvasToSVG()):this.chart.showLoading("Your browser doesn't support HTML5 canvas, \x3cbr\x3eplease use a modern browser")});b.extend(v.prototype,{getContext:function(){var a=this.chart,c=a.chartWidth,g=a.chartHeight,d=a.seriesGroup||this.group,e=this,b,f=function(a,e,g,c,d,b,f){a.call(this,g,e,c,d,b,f)};a.isChartSeriesBoosting()&&(e=a,d=a.seriesGroup);b=e.ctx;e.canvas||(e.canvas=
n.createElement("canvas"),e.renderTarget=a.renderer.image("",0,0,c,g).addClass("highcharts-boost-canvas").add(d),e.ctx=b=e.canvas.getContext("2d"),a.inverted&&["moveTo","lineTo","rect","arc"].forEach(function(a){y(b,a,f)}),e.boostCopy=function(){e.renderTarget.attr({href:e.canvas.toDataURL("image/png")})},e.boostClear=function(){b.clearRect(0,0,e.canvas.width,e.canvas.height);e===this&&e.renderTarget.attr({href:""})},e.boostClipRect=a.renderer.clipRect(),e.renderTarget.clip(e.boostClipRect));e.canvas.width!==
c&&(e.canvas.width=c);e.canvas.height!==g&&(e.canvas.height=g);e.renderTarget.attr({x:0,y:0,width:c,height:g,style:"pointer-events: none",href:""});e.boostClipRect.attr(a.getBoostClipRect(e));return b},canvasToSVG:function(){this.chart.isChartSeriesBoosting()?this.boostClear&&this.boostClear():(this.boostCopy||this.chart.boostCopy)&&(this.boostCopy||this.chart.boostCopy)()},cvsLineTo:function(a,c,g){a.lineTo(c,g)},renderCanvas:function(){var a=this,c=a.options,g=a.chart,d=this.xAxis,e=this.yAxis,
k=(g.options.boost||{}).timeRendering||!1,f,q=0,n=a.processedXData,v=a.processedYData,K=c.data,m=d.getExtremes(),z=m.min,A=m.max,m=e.getExtremes(),y=m.min,ga=m.max,L={},B,ha=!!a.sampling,M,C=c.marker&&c.marker.radius,N=this.cvsDrawPoint,D=c.lineWidth?this.cvsLineTo:!1,O=C&&1>=C?this.cvsMarkerSquare:this.cvsMarkerCircle,ia=this.cvsStrokeBatch||1E3,ja=!1!==c.enableMouseTracking,P,m=c.threshold,r=e.getThreshold(m),Q=l(m),R=r,ka=this.fill,S=a.pointArrayMap&&"low,high"===a.pointArrayMap.join(","),T=!!c.stacking,
U=a.cropStart||0,m=g.options.loading,la=a.requireSorting,V,ma=c.connectNulls,W=!n,E,F,t,u,G,p=T?a.data:n||K,na=a.fillOpacity?(new ca(a.color)).setOpacity(fa(c.fillOpacity,.75)).get():a.color,X=function(){ka?(f.fillStyle=na,f.fill()):(f.strokeStyle=a.color,f.lineWidth=c.lineWidth,f.stroke())},Z=function(e,c,d,b){0===q&&(f.beginPath(),D&&(f.lineJoin="round"));g.scroller&&"highcharts-navigator-series"===a.options.className?(c+=g.scroller.top,d&&(d+=g.scroller.top)):c+=g.plotTop;e+=g.plotLeft;V?f.moveTo(e,
c):N?N(f,e,c,d,P):D?D(f,e,c):O&&O.call(a,f,e,c,C,b);q+=1;q===ia&&(X(),q=0);P={clientX:e,plotY:c,yBottom:d}},oa="x"===c.findNearestPointBy,aa=this.xData||this.options.xData||this.processedXData||!1,H=function(a,c,b){G=oa?a:a+","+c;ja&&!L[G]&&(L[G]=!0,g.inverted&&(a=d.len-a,c=e.len-c),M.push({x:aa?aa[U+b]:!1,clientX:a,plotX:a,plotY:c,i:U+b}))};this.renderTarget&&this.renderTarget.attr({href:""});(this.points||this.graph)&&this.destroyGraphics();a.plotGroup("group","series",a.visible?"visible":"hidden",
c.zIndex,g.seriesGroup);a.markerGroup=a.group;x(a,"destroy",function(){a.markerGroup=null});M=this.points=[];f=this.getContext();a.buildKDTree=ba;this.boostClear&&this.boostClear();this.visible&&(99999<K.length&&(g.options.loading=ea(m,{labelStyle:{backgroundColor:b.color("#ffffff").setOpacity(.75).get(),padding:"1em",borderRadius:"0.5em"},style:{backgroundColor:"none",opacity:1}}),b.clearTimeout(I),g.showLoading("Drawing..."),g.options.loading=m),k&&console.time("canvas rendering"),b.eachAsync(p,
function(c,b){var f,h,k,J=!1,m=!1,l=!1,n=!1,q="undefined"===typeof g.index,Y=!0;if(!q){W?(f=c[0],h=c[1],p[b+1]&&(l=p[b+1][0]),p[b-1]&&(n=p[b-1][0])):(f=c,h=v[b],p[b+1]&&(l=p[b+1]),p[b-1]&&(n=p[b-1]));l&&l>=z&&l<=A&&(J=!0);n&&n>=z&&n<=A&&(m=!0);S?(W&&(h=c.slice(1,3)),k=h[0],h=h[1]):T&&(f=c.x,h=c.stackY,k=h-c.y);c=null===h;la||(Y=h>=y&&h<=ga);if(!c&&(f>=z&&f<=A&&Y||J||m))if(f=Math.round(d.toPixels(f,!0)),ha){if(void 0===t||f===B){S||(k=h);if(void 0===u||h>F)F=h,u=b;if(void 0===t||k<E)E=k,t=b}f!==B&&
(void 0!==t&&(h=e.toPixels(F,!0),r=e.toPixels(E,!0),Z(f,Q?Math.min(h,R):h,Q?Math.max(r,R):r,b),H(f,h,u),r!==h&&H(f,r,t)),t=u=void 0,B=f)}else h=Math.round(e.toPixels(h,!0)),Z(f,h,r,b),H(f,h,b);V=c&&!ma;0===b%5E4&&(a.boostCopy||a.chart.boostCopy)&&(a.boostCopy||a.chart.boostCopy)()}return!q},function(){var c=g.loadingDiv,b=g.loadingShown;X();a.canvasToSVG();k&&console.timeEnd("canvas rendering");da(a,"renderedCanvas");b&&(w(c.style,{transition:"opacity 250ms",opacity:0}),g.loadingShown=!1,I=setTimeout(function(){c.parentNode&&
c.parentNode.removeChild(c);g.loadingDiv=g.loadingSpan=null},250));delete a.buildKDTree;a.buildKDTree()},g.renderer.forExport?Number.MAX_VALUE:void 0))}});k.scatter.prototype.cvsMarkerCircle=function(a,c,b,d){a.moveTo(c,b);a.arc(c,b,d,0,2*Math.PI,!1)};k.scatter.prototype.cvsMarkerSquare=function(a,c,b,d){a.rect(c-d,b-d,2*d,2*d)};k.scatter.prototype.fill=!0;k.bubble&&(k.bubble.prototype.cvsMarkerCircle=function(a,c,b,d,e){a.moveTo(c,b);a.arc(c,b,this.radii&&this.radii[e],0,2*Math.PI,!1)},k.bubble.prototype.cvsStrokeBatch=
1);w(k.area.prototype,{cvsDrawPoint:function(a,c,b,d,e){e&&c!==e.clientX&&(a.moveTo(e.clientX,e.yBottom),a.lineTo(e.clientX,e.plotY),a.lineTo(c,b),a.lineTo(c,d))},fill:!0,fillOpacity:!0,sampling:!0});w(k.column.prototype,{cvsDrawPoint:function(a,c,b,d){a.rect(c-1,b,1,d-b)},fill:!0,sampling:!0});b.Chart.prototype.callbacks.push(function(a){x(a,"predraw",function(){a.renderTarget&&a.renderTarget.attr({href:""});a.canvas&&a.canvas.getContext("2d").clearRect(0,0,a.canvas.width,a.canvas.height)});x(a,
"render",function(){a.boostCopy&&a.boostCopy()})})}});l(d,"masters/modules/boost-canvas.src.js",[],function(){})});
//# sourceMappingURL=boost-canvas.js.map