/*
 Highstock JS v7.1.2-modified (2019-07-03)

 Drag-panes module

 (c) 2010-2019 Highsoft AS
 Author: Kacper Madej

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/drag-panes",["highcharts","highcharts/modules/stock"],function(b){a(b);a.Highcharts=b;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function b(a,r,b,u){a.hasOwnProperty(r)||(a[r]=u.apply(null,b))}a=a?a._modules:{};b(a,"modules/drag-panes.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,b){var r=b.isNumber,
u=a.hasTouch;b=a.merge;var w=a.wrap,f=a.addEvent,x=a.relativeLength,A=a.objectEach,l=a.Axis,y=a.Pointer;b(!0,l.prototype.defaultYAxisOptions,{minLength:"10%",maxLength:"100%",resize:{controlledAxis:{next:[],prev:[]},enabled:!1,cursor:"ns-resize",lineColor:"#cccccc",lineDashStyle:"Solid",lineWidth:4,x:0,y:0}});a.AxisResizer=function(c){this.init(c)};a.AxisResizer.prototype={init:function(c,a){this.axis=c;this.options=c.options.resize;this.render();a||this.addMouseEvents()},render:function(){var c=
this.axis,a=c.chart,d=this.options,z=d.x,b=d.y,h=Math.min(Math.max(c.top+c.height+b,a.plotTop),a.plotTop+a.plotHeight),k={};a.styledMode||(k={cursor:d.cursor,stroke:d.lineColor,"stroke-width":d.lineWidth,dashstyle:d.lineDashStyle});this.lastPos=h-b;this.controlLine||(this.controlLine=a.renderer.path().addClass("highcharts-axis-resizer"));this.controlLine.add(c.axisGroup);d=a.styledMode?this.controlLine.strokeWidth():d.lineWidth;k.d=a.renderer.crispLine(["M",c.left+z,h,"L",c.left+c.width+z,h],d);this.controlLine.attr(k)},
addMouseEvents:function(){var c=this,a=c.controlLine.element,d=c.axis.chart.container,b=[],v,h,k;c.mouseMoveHandler=v=function(a){c.onMouseMove(a)};c.mouseUpHandler=h=function(a){c.onMouseUp(a)};c.mouseDownHandler=k=function(a){c.onMouseDown(a)};b.push(f(d,"mousemove",v),f(d.ownerDocument,"mouseup",h),f(a,"mousedown",k));u&&b.push(f(d,"touchmove",v),f(d.ownerDocument,"touchend",h),f(a,"touchstart",k));c.eventsToUnbind=b},onMouseMove:function(c){c.touches&&0===c.touches[0].pageX||!this.grabbed||(this.hasDragged=
!0,this.updateAxes(this.axis.chart.pointer.normalize(c).chartY-this.options.y))},onMouseUp:function(c){this.hasDragged&&this.updateAxes(this.axis.chart.pointer.normalize(c).chartY-this.options.y);this.grabbed=this.hasDragged=this.axis.chart.activeResizer=null},onMouseDown:function(){this.axis.chart.pointer.reset(!1,0);this.grabbed=this.axis.chart.activeResizer=!0},updateAxes:function(c){var a=this,d=a.axis.chart,b=a.options.controlledAxis,f=0===b.next.length?[d.yAxis.indexOf(a.axis)+1]:b.next,b=[a.axis].concat(b.prev),
h=[],k=!1,q=d.plotTop,n=d.plotHeight,l=q+n,p;c=Math.max(Math.min(c,l),q);p=c-a.lastPos;1>p*p||([b,f].forEach(function(b,f){b.forEach(function(b,g){var e=(b=r(b)?d.yAxis[b]:f||g?d.get(b):b)&&b.options,m,t;e&&"navigator-y-axis"!==e.id&&(g=b.top,t=Math.round(x(e.minLength,n)),m=Math.round(x(e.maxLength,n)),f?(p=c-a.lastPos,e=Math.round(Math.min(Math.max(b.len-p,t),m)),g=b.top+p,g+e>l&&(m=l-e-g,c+=m,g+=m),g<q&&(g=q,g+e>l&&(e=n)),e===t&&(k=!0),h.push({axis:b,options:{top:100*(g-q)/n+"%",height:100*e/n+
"%"}})):(e=Math.round(Math.min(Math.max(c-g,t),m)),e===m&&(k=!0),c=g+e,h.push({axis:b,options:{height:100*e/n+"%"}})))})}),k||(h.forEach(function(a){a.axis.update(a.options,!1)}),d.redraw(!1)))},destroy:function(){var a=this;delete a.axis.resizer;this.eventsToUnbind&&this.eventsToUnbind.forEach(function(a){a()});a.controlLine.destroy();A(a,function(c,b){a[b]=null})}};l.prototype.keepProps.push("resizer");f(l,"afterRender",function(){var c=this.resizer,b=this.options.resize;b&&(b=!1!==b.enabled,c?
b?c.init(this,!0):c.destroy():b&&(this.resizer=new a.AxisResizer(this)))});f(l,"destroy",function(a){!a.keepEvents&&this.resizer&&this.resizer.destroy()});w(y.prototype,"runPointActions",function(a){this.chart.activeResizer||a.apply(this,Array.prototype.slice.call(arguments,1))});w(y.prototype,"drag",function(a){this.chart.activeResizer||a.apply(this,Array.prototype.slice.call(arguments,1))})});b(a,"masters/modules/drag-panes.src.js",[],function(){})});
//# sourceMappingURL=drag-panes.js.map