/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Highcharts Drilldown module

 Author: Torstein Honsi
 License: www.highcharts.com/license

*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/modules/drilldown",["highcharts"],function(n){e(n);e.Highcharts=n;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function n(c,e,n,u){c.hasOwnProperty(e)||(c[e]=u.apply(null,n))}e=e?e._modules:{};n(e,"modules/drilldown.src.js",[e["parts/Globals.js"]],function(c){var e=c.animObject,n=c.noop,u=c.color,x=c.defaultOptions,r=c.extend,
C=c.format,y=c.objectEach,t=c.pick,m=c.Chart,p=c.seriesTypes,z=p.pie,p=p.column,A=c.Tick,v=c.fireEvent,B=1;r(x.lang,{drillUpText:"\u25c1 Back to {series.name}"});x.drilldown={activeAxisLabelStyle:{cursor:"pointer",color:"#003399",fontWeight:"bold",textDecoration:"underline"},activeDataLabelStyle:{cursor:"pointer",color:"#003399",fontWeight:"bold",textDecoration:"underline"},animation:{duration:500},drillUpButton:{position:{align:"right",x:-10,y:10}}};c.SVGRenderer.prototype.Element.prototype.fadeIn=
function(a){this.attr({opacity:.1,visibility:"inherit"}).animate({opacity:t(this.newOpacity,1)},a||{duration:250})};m.prototype.addSeriesAsDrilldown=function(a,b){this.addSingleSeriesAsDrilldown(a,b);this.applyDrilldown()};m.prototype.addSingleSeriesAsDrilldown=function(a,b){var d=a.series,f=d.xAxis,g=d.yAxis,k,q=[],h=[],l,e,m;m=this.styledMode?{colorIndex:t(a.colorIndex,d.colorIndex)}:{color:a.color||d.color};this.drilldownLevels||(this.drilldownLevels=[]);l=d.options._levelNumber||0;(e=this.drilldownLevels[this.drilldownLevels.length-
1])&&e.levelNumber!==l&&(e=void 0);b=r(r({_ddSeriesId:B++},m),b);k=d.points.indexOf(a);d.chart.series.forEach(function(a){a.xAxis!==f||a.isDrilling||(a.options._ddSeriesId=a.options._ddSeriesId||B++,a.options._colorIndex=a.userOptions._colorIndex,a.options._levelNumber=a.options._levelNumber||l,e?(q=e.levelSeries,h=e.levelSeriesOptions):(q.push(a),a.purgedOptions=c.merge({_ddSeriesId:a.options._ddSeriesId,_levelNumber:a.options._levelNumber,selected:a.options.selected},a.userOptions),h.push(a.purgedOptions)))});
a=r({levelNumber:l,seriesOptions:d.options,seriesPurgedOptions:d.purgedOptions,levelSeriesOptions:h,levelSeries:q,shapeArgs:a.shapeArgs,bBox:a.graphic?a.graphic.getBBox():{},color:a.isNull?(new c.Color(u)).setOpacity(0).get():u,lowerSeriesOptions:b,pointOptions:d.options.data[k],pointIndex:k,oldExtremes:{xMin:f&&f.userMin,xMax:f&&f.userMax,yMin:g&&g.userMin,yMax:g&&g.userMax},resetZoomButton:this.resetZoomButton},m);this.drilldownLevels.push(a);f&&f.names&&(f.names.length=0);b=a.lowerSeries=this.addSeries(b,
!1);b.options._levelNumber=l+1;f&&(f.oldPos=f.pos,f.userMin=f.userMax=null,g.userMin=g.userMax=null);d.type===b.type&&(b.animate=b.animateDrilldown||n,b.options.animation=!0)};m.prototype.applyDrilldown=function(){var a=this.drilldownLevels,b;a&&0<a.length&&(b=a[a.length-1].levelNumber,this.drilldownLevels.forEach(function(a){a.levelNumber===b&&a.levelSeries.forEach(function(a){a.options&&a.options._levelNumber===b&&a.remove(!1)})}));this.resetZoomButton&&(this.resetZoomButton.hide(),delete this.resetZoomButton);
this.pointer.reset();this.redraw();this.showDrillUpButton();v(this,"afterDrilldown")};m.prototype.getDrilldownBackText=function(){var a=this.drilldownLevels;if(a&&0<a.length)return a=a[a.length-1],a.series=a.seriesOptions,C(this.options.lang.drillUpText,a)};m.prototype.showDrillUpButton=function(){var a=this,b=this.getDrilldownBackText(),d=a.options.drilldown.drillUpButton,f,g;this.drillUpButton?this.drillUpButton.attr({text:b}).align():(g=(f=d.theme)&&f.states,this.drillUpButton=this.renderer.button(b,
null,null,function(){a.drillUp()},f,g&&g.hover,g&&g.select).addClass("highcharts-drillup-button").attr({align:d.position.align,zIndex:7}).add().align(d.position,!1,d.relativeTo||"plotBox"))};m.prototype.drillUp=function(){if(this.drilldownLevels&&0!==this.drilldownLevels.length){for(var a=this,b=a.drilldownLevels,d=b[b.length-1].levelNumber,f=b.length,g=a.series,k,c,h,l,e=function(b){var d;g.forEach(function(a){a.options._ddSeriesId===b._ddSeriesId&&(d=a)});d=d||a.addSeries(b,!1);d.type===h.type&&
d.animateDrillupTo&&(d.animate=d.animateDrillupTo);b===c.seriesPurgedOptions&&(l=d)};f--;)if(c=b[f],c.levelNumber===d){b.pop();h=c.lowerSeries;if(!h.chart)for(k=g.length;k--;)if(g[k].options.id===c.lowerSeriesOptions.id&&g[k].options._levelNumber===d+1){h=g[k];break}h.xData=[];c.levelSeriesOptions.forEach(e);v(a,"drillup",{seriesOptions:c.seriesOptions});l.type===h.type&&(l.drilldownLevel=c,l.options.animation=a.options.drilldown.animation,h.animateDrillupFrom&&h.chart&&h.animateDrillupFrom(c));l.options._levelNumber=
d;h.remove(!1);l.xAxis&&(k=c.oldExtremes,l.xAxis.setExtremes(k.xMin,k.xMax,!1),l.yAxis.setExtremes(k.yMin,k.yMax,!1));c.resetZoomButton&&(a.resetZoomButton=c.resetZoomButton,a.resetZoomButton.show())}this.redraw();0===this.drilldownLevels.length?this.drillUpButton=this.drillUpButton.destroy():this.drillUpButton.attr({text:this.getDrilldownBackText()}).align();this.ddDupes.length=[];v(a,"drillupall")}};m.prototype.callbacks.push(function(){var a=this;a.drilldown={update:function(b,d){c.merge(!0,a.options.drilldown,
b);t(d,!0)&&a.redraw()}}});c.addEvent(m,"beforeShowResetZoom",function(){if(this.drillUpButton)return!1});c.addEvent(m,"render",function(){(this.xAxis||[]).forEach(function(a){a.ddPoints={};a.series.forEach(function(b){var d,f=b.xData||[],g=b.points,c;for(d=0;d<f.length;d++)c=b.options.data[d],"number"!==typeof c&&(c=b.pointClass.prototype.optionsToObject.call({series:b},c),c.drilldown&&(a.ddPoints[f[d]]||(a.ddPoints[f[d]]=[]),a.ddPoints[f[d]].push(g?g[d]:!0)))});y(a.ticks,A.prototype.drillable)})});
p.prototype.animateDrillupTo=function(a){if(!a){var b=this,d=b.drilldownLevel;this.points.forEach(function(a){var b=a.dataLabel;a.graphic&&a.graphic.hide();b&&(b.hidden="hidden"===b.attr("visibility"),b.hidden||(b.hide(),a.connector&&a.connector.hide()))});c.syncTimeout(function(){b.points&&b.points.forEach(function(a,b){b=b===(d&&d.pointIndex)?"show":"fadeIn";var c="show"===b?!0:void 0,f=a.dataLabel;if(a.graphic)a.graphic[b](c);f&&!f.hidden&&(f.fadeIn(),a.connector&&a.connector.fadeIn())})},Math.max(this.chart.options.drilldown.animation.duration-
50,0));this.animate=n}};p.prototype.animateDrilldown=function(a){var b=this,d=this.chart,f=d.drilldownLevels,c,k=e(d.options.drilldown.animation),q=this.xAxis,h=d.styledMode;a||(f.forEach(function(a){b.options._ddSeriesId===a.lowerSeriesOptions._ddSeriesId&&(c=a.shapeArgs,h||(c.fill=a.color))}),c.x+=t(q.oldPos,q.pos)-q.pos,this.points.forEach(function(a){var d=a.shapeArgs;h||(d.fill=a.color);a.graphic&&a.graphic.attr(c).animate(r(a.shapeArgs,{fill:a.color||b.color}),k);a.dataLabel&&a.dataLabel.fadeIn(k)}),
this.animate=null)};p.prototype.animateDrillupFrom=function(a){var b=e(this.chart.options.drilldown.animation),d=this.group,f=d!==this.chart.columnGroup,g=this;g.trackerGroups.forEach(function(a){if(g[a])g[a].on("mouseover")});f&&delete this.group;this.points.forEach(function(k){var e=k.graphic,h=a.shapeArgs,l=function(){e.destroy();d&&f&&(d=d.destroy())};e&&(delete k.graphic,g.chart.styledMode||(h.fill=a.color),b.duration?e.animate(h,c.merge(b,{complete:l})):(e.attr(h),l()))})};z&&r(z.prototype,
{animateDrillupTo:p.prototype.animateDrillupTo,animateDrillupFrom:p.prototype.animateDrillupFrom,animateDrilldown:function(a){var b=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],d=this.chart.options.drilldown.animation,f=b.shapeArgs,g=f.start,k=(f.end-g)/this.points.length,e=this.chart.styledMode;a||(this.points.forEach(function(a,l){var h=a.shapeArgs;e||(f.fill=b.color,h.fill=a.color);if(a.graphic)a.graphic.attr(c.merge(f,{start:g+l*k,end:g+(l+1)*k}))[d?"animate":"attr"](h,d)}),
this.animate=null)}});c.Point.prototype.doDrilldown=function(a,b,d){var c=this.series.chart,g=c.options.drilldown,e=(g.series||[]).length,m;c.ddDupes||(c.ddDupes=[]);for(;e--&&!m;)g.series[e].id===this.drilldown&&-1===c.ddDupes.indexOf(this.drilldown)&&(m=g.series[e],c.ddDupes.push(this.drilldown));v(c,"drilldown",{point:this,seriesOptions:m,category:b,originalEvent:d,points:void 0!==b&&this.series.xAxis.getDDPoints(b).slice(0)},function(b){var d=b.point.series&&b.point.series.chart,c=b.seriesOptions;
d&&c&&(a?d.addSingleSeriesAsDrilldown(b.point,c):d.addSeriesAsDrilldown(b.point,c))})};c.Axis.prototype.drilldownCategory=function(a,b){y(this.getDDPoints(a),function(d){d&&d.series&&d.series.visible&&d.doDrilldown&&d.doDrilldown(!0,a,b)});this.chart.applyDrilldown()};c.Axis.prototype.getDDPoints=function(a){return this.ddPoints&&this.ddPoints[a]};A.prototype.drillable=function(){var a=this.pos,b=this.label,d=this.axis,f="xAxis"===d.coll&&d.getDDPoints,g=f&&d.getDDPoints(a),e=d.chart.styledMode;f&&
(b&&g&&g.length?(b.drillable=!0,b.basicStyles||e||(b.basicStyles=c.merge(b.styles)),b.addClass("highcharts-drilldown-axis-label").on("click",function(b){d.drilldownCategory(a,b)}),e||b.css(d.chart.options.drilldown.activeAxisLabelStyle)):b&&b.drillable&&(e||(b.styles={},b.css(b.basicStyles)),b.on("click",null),b.removeClass("highcharts-drilldown-axis-label")))};c.addEvent(c.Point,"afterInit",function(){var a=this,b=a.series;a.drilldown&&c.addEvent(a,"click",function(d){b.xAxis&&!1===b.chart.options.drilldown.allowPointDrilldown?
b.xAxis.drilldownCategory(a.x,d):a.doDrilldown(void 0,void 0,d)});return a});c.addEvent(c.Series,"afterDrawDataLabels",function(){var a=this.chart.options.drilldown.activeDataLabelStyle,b=this.chart.renderer,d=this.chart.styledMode;this.points.forEach(function(c){var e=c.options.dataLabels,f=t(c.dlOptions,e&&e.style,{});c.drilldown&&c.dataLabel&&("contrast"!==a.color||d||(f.color=b.getContrast(c.color||this.color)),e&&e.color&&(f.color=e.color),c.dataLabel.addClass("highcharts-drilldown-data-label"),
d||c.dataLabel.css(a).css(f))},this)});var w=function(a,b,d,c){a[d?"addClass":"removeClass"]("highcharts-drilldown-point");c||a.css({cursor:b})};c.addEvent(c.Series,"afterDrawTracker",function(){var a=this.chart.styledMode;this.points.forEach(function(b){b.drilldown&&b.graphic&&w(b.graphic,"pointer",!0,a)})});c.addEvent(c.Point,"afterSetState",function(){var a=this.series.chart.styledMode;this.drilldown&&this.series.halo&&"hover"===this.state?w(this.series.halo,"pointer",!0,a):this.series.halo&&w(this.series.halo,
"auto",!1,a)})});n(e,"masters/modules/drilldown.src.js",[],function(){})});
//# sourceMappingURL=drilldown.js.map