/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Exporting module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/export-data",["highcharts","highcharts/modules/exporting"],function(f){b(f);b.Highcharts=f;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function f(a,g,c,d){a.hasOwnProperty(g)||(a[g]=d.apply(null,c))}b=b?b._modules:{};f(b,"mixins/ajax.js",[b["parts/Globals.js"]],function(a){a.ajax=function(g){var c=a.merge(!0,{url:!1,
type:"GET",dataType:"json",success:!1,error:!1,data:!1,headers:{}},g);g={json:"application/json",xml:"application/xml",text:"text/plain",octet:"application/octet-stream"};var d=new XMLHttpRequest;if(!c.url)return!1;d.open(c.type.toUpperCase(),c.url,!0);c.headers["Content-Type"]||d.setRequestHeader("Content-Type",g[c.dataType]||g.text);a.objectEach(c.headers,function(a,g){d.setRequestHeader(g,a)});d.onreadystatechange=function(){var a;if(4===d.readyState){if(200===d.status){a=d.responseText;if("json"===
c.dataType)try{a=JSON.parse(a)}catch(n){c.error&&c.error(d,n);return}return c.success&&c.success(a)}c.error&&c.error(d,d.responseText)}};try{c.data=JSON.stringify(c.data)}catch(D){}d.send(c.data||!0)};a.getJSON=function(g,c){a.ajax({url:g,success:c,dataType:"json",headers:{"Content-Type":"text/plain"}})}});f(b,"mixins/download-url.js",[b["parts/Globals.js"]],function(a){var g=a.win,c=g.navigator,d=g.document,b=g.URL||g.webkitURL||g,n=/Edge\/\d+/.test(c.userAgent);a.dataURLtoBlob=function(a){if((a=
a.match(/data:([^;]*)(;base64)?,([0-9A-Za-z+/]+)/))&&3<a.length&&g.atob&&g.ArrayBuffer&&g.Uint8Array&&g.Blob&&b.createObjectURL){for(var c=g.atob(a[3]),d=new g.ArrayBuffer(c.length),d=new g.Uint8Array(d),h=0;h<d.length;++h)d[h]=c.charCodeAt(h);a=new g.Blob([d],{type:a[1]});return b.createObjectURL(a)}};a.downloadURL=function(h,b){var q=d.createElement("a"),r;if("string"===typeof h||h instanceof String||!c.msSaveOrOpenBlob){if(n||2E6<h.length)if(h=a.dataURLtoBlob(h),!h)throw Error("Failed to convert to blob");
if(void 0!==q.download)q.href=h,q.download=b,d.body.appendChild(q),q.click(),d.body.removeChild(q);else try{if(r=g.open(h,"chart"),void 0===r||null===r)throw Error("Failed to open window");}catch(k){g.location.href=h}}else c.msSaveOrOpenBlob(h,b)}});f(b,"modules/export-data.src.js",[b["parts/Globals.js"]],function(a){function g(a,d){if(b.Blob&&b.navigator.msSaveOrOpenBlob)return new b.Blob(["\ufeff"+a],{type:d})}var c=a.defined,d=a.pick,b=a.win,n=b.document,h=a.seriesTypes,f=a.downloadURL,q=a.fireEvent;
a.setOptions({exporting:{csv:{columnHeaderFormatter:null,dateFormat:"%Y-%m-%d %H:%M:%S",decimalPoint:null,itemDelimiter:null,lineDelimiter:"\n"},showTable:!1,useMultiLevelHeaders:!0,useRowspanHeaders:!0},lang:{downloadCSV:"Download CSV",downloadXLS:"Download XLS",openInCloud:"Open in Highcharts Cloud",viewData:"View data table"}});a.addEvent(a.Chart,"render",function(){this.options&&this.options.exporting&&this.options.exporting.showTable&&!this.options.chart.forExport&&this.viewData()});a.Chart.prototype.setUpKeyToAxis=
function(){h.arearange&&(h.arearange.prototype.keyToAxis={low:"y",high:"y"});h.gantt&&(h.gantt.prototype.keyToAxis={start:"x",end:"x"})};a.Chart.prototype.getDataRows=function(b){var g=this.time,h=this.options.exporting&&this.options.exporting.csv||{},l,k=this.xAxis,t={},f=[],m,n=[],p=[],x,u,v,C=function(e,g,d){if(h.columnHeaderFormatter){var c=h.columnHeaderFormatter(e,g,d);if(!1!==c)return c}return e?e instanceof a.Axis?e.options.title&&e.options.title.text||(e.isDatetimeAxis?"DateTime":"Category"):
b?{columnTitle:1<d?g:e.name,topLevelColumnTitle:e.name}:e.name+(1<d?" ("+g+")":""):"Category"},y=[];u=0;this.setUpKeyToAxis();this.series.forEach(function(e){var c=e.options.keys||e.pointArrayMap||["y"],l=c.length,v=!e.requireSorting&&{},w={},A={},m=k.indexOf(e.xAxis),B,f;c.forEach(function(a){var c=(e.keyToAxis&&e.keyToAxis[a]||a)+"Axis";w[a]=e[c]&&e[c].categories||[];A[a]=e[c]&&e[c].isDatetimeAxis});if(!1!==e.options.includeInDataExport&&!e.options.isInternal&&!1!==e.visible){a.find(y,function(e){return e[0]===
m})||y.push([m,u]);for(f=0;f<l;)x=C(e,c[f],c.length),p.push(x.columnTitle||x),b&&n.push(x.topLevelColumnTitle||x),f++;B={chart:e.chart,autoIncrement:e.autoIncrement,options:e.options,pointArrayMap:e.pointArrayMap};e.options.data.forEach(function(a,b){var k,p;p={series:B};e.pointClass.prototype.applyOptions.apply(p,[a]);a=p.x;k=e.data[b]&&e.data[b].name;f=0;e.xAxis&&"name"!==e.exportKey||(a=k);v&&(v[a]&&(a+="|"+b),v[a]=!0);t[a]||(t[a]=[],t[a].xValues=[]);t[a].x=p.x;t[a].name=k;for(t[a].xValues[m]=
p.x;f<l;)b=c[f],k=p[b],t[a][u+f]=d(w[b][k],A[b]?g.dateFormat(h.dateFormat,k):null,k),f++});u+=f}});for(m in t)t.hasOwnProperty(m)&&f.push(t[m]);var w,z;m=b?[n,p]:[p];for(u=y.length;u--;)w=y[u][0],z=y[u][1],l=k[w],f.sort(function(a,b){return a.xValues[w]-b.xValues[w]}),v=C(l),m[0].splice(z,0,v),b&&m[1]&&m[1].splice(z,0,v),f.forEach(function(a){var e=a.name;l&&!c(e)&&(l.isDatetimeAxis?(a.x instanceof Date&&(a.x=a.x.getTime()),e=g.dateFormat(h.dateFormat,a.x)):e=l.categories?d(l.names[a.x],l.categories[a.x],
a.x):a.x);a.splice(z,0,e)});m=m.concat(f);q(this,"exportData",{dataRows:m});return m};a.Chart.prototype.getCSV=function(a){var b="",c=this.getDataRows(),g=this.options.exporting.csv,k=d(g.decimalPoint,","!==g.itemDelimiter&&a?(1.1).toLocaleString()[1]:"."),h=d(g.itemDelimiter,","===k?";":","),f=g.lineDelimiter;c.forEach(function(a,g){for(var d,l=a.length;l--;)d=a[l],"string"===typeof d&&(d='"'+d+'"'),"number"===typeof d&&"."!==k&&(d=d.toString().replace(".",k)),a[l]=d;b+=a.join(h);g<c.length-1&&(b+=
f)});return b};a.Chart.prototype.getTable=function(a){var b='\x3ctable id\x3d"highcharts-data-table-'+this.index+'"\x3e',c=this.options,g=a?(1.1).toLocaleString()[1]:".",h=d(c.exporting.useMultiLevelHeaders,!0);a=this.getDataRows(h);var f=0,k=h?a.shift():null,m=a.shift(),n=function(a,b,c,h){var f=d(h,"");b="text"+(b?" "+b:"");"number"===typeof f?(f=f.toString(),","===g&&(f=f.replace(".",g)),b="number"):h||(b="empty");return"\x3c"+a+(c?" "+c:"")+' class\x3d"'+b+'"\x3e'+f+"\x3c/"+a+"\x3e"};!1!==c.exporting.tableCaption&&
(b+='\x3ccaption class\x3d"highcharts-table-caption"\x3e'+d(c.exporting.tableCaption,c.title.text?c.title.text.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#x27;").replace(/\//g,"\x26#x2F;"):"Chart")+"\x3c/caption\x3e");for(var p=0,r=a.length;p<r;++p)a[p].length>f&&(f=a[p].length);b+=function(a,b,g){var d="\x3cthead\x3e",f=0;g=g||b&&b.length;var l,e,k=0;if(e=h&&a&&b){a:if(e=a.length,b.length===e){for(;e--;)if(a[e]!==b[e]){e=!1;
break a}e=!0}else e=!1;e=!e}if(e){for(d+="\x3ctr\x3e";f<g;++f)e=a[f],l=a[f+1],e===l?++k:k?(d+=n("th","highcharts-table-topheading",'scope\x3d"col" colspan\x3d"'+(k+1)+'"',e),k=0):(e===b[f]?c.exporting.useRowspanHeaders?(l=2,delete b[f]):(l=1,b[f]=""):l=1,d+=n("th","highcharts-table-topheading",'scope\x3d"col"'+(1<l?' valign\x3d"top" rowspan\x3d"'+l+'"':""),e));d+="\x3c/tr\x3e"}if(b){d+="\x3ctr\x3e";f=0;for(g=b.length;f<g;++f)void 0!==b[f]&&(d+=n("th",null,'scope\x3d"col"',b[f]));d+="\x3c/tr\x3e"}return d+
"\x3c/thead\x3e"}(k,m,Math.max(f,m.length));b+="\x3ctbody\x3e";a.forEach(function(a){b+="\x3ctr\x3e";for(var c=0;c<f;c++)b+=n(c?"td":"th",null,c?"":'scope\x3d"row"',a[c]);b+="\x3c/tr\x3e"});b+="\x3c/tbody\x3e\x3c/table\x3e";a={html:b};q(this,"afterGetTable",a);return a.html};a.Chart.prototype.downloadCSV=function(){var a=this.getCSV(!0);f(g(a,"text/csv")||"data:text/csv,\ufeff"+encodeURIComponent(a),this.getFilename()+".csv")};a.Chart.prototype.downloadXLS=function(){var a='\x3chtml xmlns:o\x3d"urn:schemas-microsoft-com:office:office" xmlns:x\x3d"urn:schemas-microsoft-com:office:excel" xmlns\x3d"http://www.w3.org/TR/REC-html40"\x3e\x3chead\x3e\x3c!--[if gte mso 9]\x3e\x3cxml\x3e\x3cx:ExcelWorkbook\x3e\x3cx:ExcelWorksheets\x3e\x3cx:ExcelWorksheet\x3e\x3cx:Name\x3eArk1\x3c/x:Name\x3e\x3cx:WorksheetOptions\x3e\x3cx:DisplayGridlines/\x3e\x3c/x:WorksheetOptions\x3e\x3c/x:ExcelWorksheet\x3e\x3c/x:ExcelWorksheets\x3e\x3c/x:ExcelWorkbook\x3e\x3c/xml\x3e\x3c![endif]--\x3e\x3cstyle\x3etd{border:none;font-family: Calibri, sans-serif;} .number{mso-number-format:"0.00";} .text{ mso-number-format:"@";}\x3c/style\x3e\x3cmeta name\x3dProgId content\x3dExcel.Sheet\x3e\x3cmeta charset\x3dUTF-8\x3e\x3c/head\x3e\x3cbody\x3e'+
this.getTable(!0)+"\x3c/body\x3e\x3c/html\x3e";f(g(a,"application/vnd.ms-excel")||"data:application/vnd.ms-excel;base64,"+b.btoa(unescape(encodeURIComponent(a))),this.getFilename()+".xls")};a.Chart.prototype.viewData=function(){this.dataTableDiv||(this.dataTableDiv=n.createElement("div"),this.dataTableDiv.className="highcharts-data-table",this.renderTo.parentNode.insertBefore(this.dataTableDiv,this.renderTo.nextSibling));this.dataTableDiv.innerHTML=this.getTable();q(this,"afterViewData",this.dataTableDiv)};
a.Chart.prototype.openInCloud=function(){function b(c){Object.keys(c).forEach(function(d){"function"===typeof c[d]&&delete c[d];a.isObject(c[d])&&b(c[d])})}var c,d;c=a.merge(this.userOptions);b(c);c={name:c.title&&c.title.text||"Chart title",options:c,settings:{constructor:"Chart",dataProvider:{csv:this.getCSV()}}};d=JSON.stringify(c);(function(){var a=n.createElement("form");n.body.appendChild(a);a.method="post";a.action="https://cloud-api.highcharts.com/openincloud";a.target="_blank";var b=n.createElement("input");
b.type="hidden";b.name="chart";b.value=d;a.appendChild(b);a.submit();n.body.removeChild(a)})()};var r=a.getOptions().exporting;r&&(a.extend(r.menuItemDefinitions,{downloadCSV:{textKey:"downloadCSV",onclick:function(){this.downloadCSV()}},downloadXLS:{textKey:"downloadXLS",onclick:function(){this.downloadXLS()}},viewData:{textKey:"viewData",onclick:function(){this.viewData()}},openInCloud:{textKey:"openInCloud",onclick:function(){this.openInCloud()}}}),r.buttons&&r.buttons.contextButton.menuItems.push("separator",
"downloadCSV","downloadXLS","viewData","openInCloud"));h.map&&(h.map.prototype.exportKey="name");h.mapbubble&&(h.mapbubble.prototype.exportKey="name");h.treemap&&(h.treemap.prototype.exportKey="name")});f(b,"masters/modules/export-data.src.js",[],function(){})});
//# sourceMappingURL=export-data.js.map