/*
 Highcharts Gantt JS v7.1.2-modified (2019-07-03)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(q){"object"===typeof module&&module.exports?(q["default"]=q,module.exports=q):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(D){q(D);q.Highcharts=D;return q}):q("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(q){function D(b,g,H,w){b.hasOwnProperty(g)||(b[g]=w.apply(null,H))}q=q?q._modules:{};D(q,"parts-gantt/CurrentDateIndicator.js",[q["parts/Globals.js"]],function(b){var g=b.addEvent,H=b.PlotLineOrBand,w=b.merge,v={currentDateIndicator:!0,
color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:void 0,rotation:0,style:{fontSize:"10px"}}};g(b.Axis,"afterSetOptions",function(){var b=this.options,g=b.currentDateIndicator;g&&("object"===typeof g?(g.label&&g.label.format&&(g.label.formatter=void 0),g=w(v,g)):g=w(v),g.value=new Date,b.plotLines||(b.plotLines=[]),b.plotLines.push(g))});g(H,"render",function(){var r=this.options,g,n;r.currentDateIndicator&&r.label&&(g=r.label.format,n=r.label.formatter,r.value=new Date,r.label.text=
"function"===typeof n?n(this):b.dateFormat(g,new Date),this.label&&this.label.attr({text:r.label.text}))})});D(q,"parts-gantt/GridAxis.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){var H=g.isArray,w=g.isNumber,v=b.addEvent,r=b.dateFormat,q=b.defined,n=function(d){return b.isObject(d,!0)},C=b.merge,x=b.pick,u=b.wrap;g=b.Chart;var k=b.Axis,F=b.Tick,A=function(d){var a=d.options,c=a&&n(a.grid)?a.grid:{},f=25/11,h=d.chart.renderer.fontMetrics(a.labels.style.fontSize);a.labels||(a.labels=
{});a.labels.align=x(a.labels.align,"center");d.categories||(a.showLastLabel=!1);d.horiz&&(a.tickLength=c.cellHeight||h.h*f);d.labelRotation=0;a.labels.rotation=0},m={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};k.prototype.isOuterAxis=function(){var d=this,a=d.columnIndex,c=d.linkedParent&&d.linkedParent.columns||d.columns,f=a?d.linkedParent:d,h=-1,m=0;d.chart[d.coll].forEach(function(e,c){e.side!==d.side||e.options.isInternal||(m=c,e===f&&(h=c))});return m===h&&(w(a)?c.length===
a:!0)};k.prototype.getMaxLabelDimensions=function(d,a){var c={width:0,height:0};a.forEach(function(a){a=d[a];var f;n(a)&&(f=n(a.label)?a.label:{},a=f.getBBox?f.getBBox().height:0,f.textStr&&!w(f.textPxLength)&&(f.textPxLength=f.getBBox().width),f=w(f.textPxLength)?f.textPxLength:0,c.height=Math.max(a,c.height),c.width=Math.max(f,c.width))});return c};b.dateFormats.W=function(d){d=new Date(d);var a;d.setHours(0,0,0,0);d.setDate(d.getDate()-(d.getDay()||7));a=new Date(d.getFullYear(),0,1);return Math.ceil(((d-
a)/864E5+1)/7)};b.dateFormats.E=function(d){return r("%a",d,!0).charAt(0)};v(F,"afterGetLabelPosition",function(d){var a=this.label,c=this.axis,f=c.reversed,h=c.chart,z=c.options,e=z&&n(z.grid)?z.grid:{},z=c.options.labels,p=z.align,t=m[c.side],b=d.tickmarkOffset,E=c.tickPositions,y=this.pos-b,E=w(E[d.index+1])?E[d.index+1]-b:c.max+b,J=c.tickSize("tick",!0),b=H(J)?J[0]:0,J=J&&J[1]/2,I;!0===e.enabled&&("top"===t?(e=c.top+c.offset,I=e-b):"bottom"===t?(I=h.chartHeight-c.bottom+c.offset,e=I+b):(e=c.top+
c.len-c.translate(f?E:y),I=c.top+c.len-c.translate(f?y:E)),"right"===t?(t=h.chartWidth-c.right+c.offset,f=t+b):"left"===t?(f=c.left+c.offset,t=f-b):(t=Math.round(c.left+c.translate(f?E:y))-J,f=Math.round(c.left+c.translate(f?y:E))-J),this.slotWidth=f-t,d.pos.x="left"===p?t:"right"===p?f:t+(f-t)/2,d.pos.y=I+(e-I)/2,h=h.renderer.fontMetrics(z.style.fontSize,a.element),a=a.getBBox().height,z.useHTML?d.pos.y+=h.b+-(a/2):(a=Math.round(a/h.h),d.pos.y+=(h.b-(h.h-h.f))/2+-((a-1)*h.h/2)),d.pos.x+=c.horiz&&
z.x||0)});v(k,"afterTickSize",function(d){var a=this.maxLabelDimensions,c=this.options;!0===(c&&n(c.grid)?c.grid:{}).enabled&&(c=2*Math.abs(this.defaultLeftAxisOptions.labels.x),a=c+(this.horiz?a.height:a.width),H(d.tickSize)?d.tickSize[0]=a:d.tickSize=[a])});v(k,"afterGetTitlePosition",function(d){var a=this.options;if(!0===(a&&n(a.grid)?a.grid:{}).enabled){var c=this.axisTitle,f=c&&c.getBBox().width,h=this.horiz,z=this.left,e=this.top,p=this.width,t=this.height,b=a.title,a=this.opposite,E=this.offset,
y=this.tickSize()||[0],J=b.x||0,I=b.y||0,u=x(b.margin,h?5:10),c=this.chart.renderer.fontMetrics(b.style&&b.style.fontSize,c).f,y=(h?e+t:z)+y[0]/2*(a?-1:1)*(h?1:-1)+(this.side===m.bottom?c:0);d.titlePosition.x=h?z-f/2-u+J:y+(a?p:0)+E+J;d.titlePosition.y=h?y-(a?t:0)+(a?c:-c)/2+E+I:e-u+I}});u(k.prototype,"unsquish",function(d){var a=this.options;return!0===(a&&n(a.grid)?a.grid:{}).enabled&&this.categories?this.tickInterval:d.apply(this,Array.prototype.slice.call(arguments,1))});v(k,"afterSetOptions",
function(a){var d=this.options;a=a.userOptions;var c,f=d&&n(d.grid)?d.grid:{};!0===f.enabled&&(c=C(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",
[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a),"xAxis"===this.coll&&(q(a.linkedTo)&&!q(a.tickPixelInterval)&&(c.tickPixelInterval=350),q(a.tickPixelInterval)||!q(a.linkedTo)||q(a.tickPositioner)||q(a.tickInterval)||(c.tickPositioner=function(a,d){var e=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(e){var f,h,l,m,y=c.units;for(m=0;m<y.length;m++)if(y[m][0]===e.unitName){f=m;break}if(y[f][1])return y[f+1]&&(l=y[f+1][0],h=(y[f+1][1]||[1])[0]),
e=b.timeUnits[l],this.tickInterval=e*h,this.getTimeTicks({unitRange:e,count:h,unitName:l},a,d,this.options.startOfWeek)}})),C(!0,this.options,c),this.horiz&&(d.minPadding=x(a.minPadding,0),d.maxPadding=x(a.maxPadding,0)),w(d.grid.borderWidth)&&(d.tickWidth=d.lineWidth=f.borderWidth))});v(k,"afterSetAxisTranslation",function(){var a=this.options,l=a&&n(a.grid)?a.grid:{},c=this.tickPositions&&this.tickPositions.info,f=this.userOptions.labels||{};this.horiz&&(!0===l.enabled&&this.series.forEach(function(a){a.options.pointRange=
0}),c&&(!1===a.dateTimeLabelFormats[c.unitName].range||1<c.count)&&!q(f.align)&&(a.labels.align="left",q(f.x)||(a.labels.x=3)))});v(k,"trimTicks",function(){var a=this.options,l=a&&n(a.grid)?a.grid:{},c=this.categories,f=this.tickPositions,h=f[0],m=f[f.length-1],e=this.linkedParent&&this.linkedParent.min||this.min,p=this.linkedParent&&this.linkedParent.max||this.max,t=this.tickInterval;!0!==l.enabled||c||!this.horiz&&!this.isLinked||(h<e&&h+t>e&&!a.startOnTick&&(f[0]=e),m>p&&m-t<p&&!a.endOnTick&&
(f[f.length-1]=p))});v(k,"afterRender",function(){var a=this.options,l=a&&n(a.grid)?a.grid:{},c,f,h,z,e,p,t=this.chart.renderer,b=this.horiz;if(!0===l.enabled){l=2*Math.abs(this.defaultLeftAxisOptions.labels.x);this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);l=this.maxLabelDimensions.width+l;c=a.lineWidth;this.rightWall&&this.rightWall.destroy();f=this.axisGroup.getBBox();if(this.isOuterAxis()&&this.axisLine&&(b&&(l=f.height-1),c)){f=this.getLinePath(c);e=f.indexOf("M")+
1;p=f.indexOf("L")+1;h=f.indexOf("M")+2;z=f.indexOf("L")+2;if(this.side===m.top||this.side===m.left)l=-l;b?(f[h]+=l,f[z]+=l):(f[e]+=l,f[p]+=l);this.axisLineExtra?this.axisLineExtra.animate({d:f}):this.axisLineExtra=t.path(f).attr({stroke:a.lineColor,"stroke-width":c,zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup);this.axisLine[this.showAxis?"show":"hide"](!0)}(this.columns||[]).forEach(function(a){a.render()})}});var a={afterGetOffset:function(){(this.columns||[]).forEach(function(a){a.getOffset()})},
afterInit:function(){var a=this.chart,l=this.userOptions,c=this.options,c=c&&n(c.grid)?c.grid:{};c.enabled&&(A(this),u(this,"labelFormatter",function(a){var e=this.axis,d=e.tickPositions,c=this.value,f=(e.isLinked?e.linkedParent:e).series[0],h=c===d[0],d=c===d[d.length-1],f=f&&b.find(f.options.data,function(a){return a[e.isXAxis?"x":"y"]===c});this.isFirst=h;this.isLast=d;this.point=f;return a.call(this)}));if(c.columns)for(var f=this.columns=[],h=this.columnIndex=0;++h<c.columns.length;){var m=C(l,
c.columns[c.columns.length-h-1],{linkedTo:0,type:"category"});delete m.grid.columns;m=new k(this.chart,m,!0);m.isColumn=!0;m.columnIndex=h;b.erase(a.axes,m);b.erase(a[this.coll],m);f.push(m)}},afterSetOptions:function(a){a=(a=a.userOptions)&&n(a.grid)?a.grid:{};var d=a.columns;a.enabled&&d&&C(!0,this.options,d[d.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(a){a.setScale()})},destroy:function(a){(this.columns||[]).forEach(function(d){d.destroy(a.keepEvents)})},init:function(a){var d=
(a=a.userOptions)&&n(a.grid)?a.grid:{};d.enabled&&q(d.borderColor)&&(a.tickColor=a.lineColor=d.borderColor)}};Object.keys(a).forEach(function(d){v(k,d,a[d])});v(g,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})})});D(q,"modules/static-scale.src.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){var q=g.isNumber;g=b.Chart;var w=b.pick;b.addEvent(b.Axis,"afterSetOptions",function(){var b=this.chart.options&&
this.chart.options.chart;!this.horiz&&q(this.options.staticScale)&&(!b.height||b.scrollablePlotArea&&b.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});g.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(g){var r=g.chart,v=!!r.initiatedScale&&r.options.animation,n=g.options.staticScale,C;g.staticScale&&b.defined(g.min)&&(C=w(g.unitLength,g.max+g.tickInterval-g.min)*n,C=Math.max(C,n),n=C-r.plotHeight,1<=Math.abs(n)&&
(r.plotHeight=C,r.redrawTrigger="adjustHeight",r.setSize(void 0,r.chartHeight+n,v)),g.series.forEach(function(b){(b=b.sharedClipKey&&r[b.sharedClipKey])&&b.attr({height:r.plotHeight})}))}),this.initiatedScale=!0);this.redrawTrigger=null};b.addEvent(g,"render",g.prototype.adjustHeight)});D(q,"parts-gantt/Tree.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){var q=g.isNumber,w=b.extend,v=b.pick,r=function(b,g){var n=b.reduce(function(b,k){var u=v(k.parent,"");void 0===b[u]&&(b[u]=[]);
b[u].push(k);return b},{});Object.keys(n).forEach(function(b,k){var u=n[b];""!==b&&-1===g.indexOf(b)&&(u.forEach(function(b){k[""].push(b)}),delete k[b])});return n},B=function(b,g,x,u,k,r){var n=0,m=0,a=r&&r.after,d=r&&r.before;g={data:u,depth:x-1,id:b,level:x,parent:g};var l,c;"function"===typeof d&&d(g,r);d=(k[b]||[]).map(function(a){var d=B(a.id,b,x+1,a,k,r),f=a.start;a=!0===a.milestone?f:a.end;l=!q(l)||f<l?f:l;c=!q(c)||a>c?a:c;n=n+1+d.descendants;m=Math.max(d.height+1,m);return d});u&&(u.start=
v(u.start,l),u.end=v(u.end,c));w(g,{children:d,descendants:n,height:m});"function"===typeof a&&a(g,r);return g};return{getListOfParents:r,getNode:B,getTree:function(b,g){var n=b.map(function(b){return b.id});b=r(b,n);return B("",null,1,null,b,g)}}});D(q,"mixins/tree-series.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){var q=g.isArray,w=g.isNumber,v=b.extend,r=b.isObject,B=b.merge,n=b.pick;return{getColor:function(g,x){var u=x.index,k=x.mapOptionsToLevel,r=x.parentColor,A=x.parentColorIndex,
m=x.series,a=x.colors,d=x.siblings,l=m.points,c=m.chart.options.chart,f,h,z,e;if(g){l=l[g.i];g=k[g.level]||{};if(k=l&&g.colorByPoint)h=l.index%(a?a.length:c.colorCount),f=a&&a[h];if(!m.chart.styledMode){a=l&&l.options.color;c=g&&g.color;if(z=r)z=(z=g&&g.colorVariation)&&"brightness"===z.key?b.color(r).brighten(u/d*z.to).get():r;z=n(a,c,f,z,m.color)}e=n(l&&l.options.colorIndex,g&&g.colorIndex,h,A,x.colorIndex)}return{color:z,colorIndex:e}},getLevelOptions:function(b){var n=null,u,k,g,A;if(r(b))for(n=
{},g=w(b.from)?b.from:1,A=b.levels,k={},u=r(b.defaults)?b.defaults:{},q(A)&&(k=A.reduce(function(b,a){var d,l;r(a)&&w(a.level)&&(l=B({},a),d="boolean"===typeof l.levelIsConstant?l.levelIsConstant:u.levelIsConstant,delete l.levelIsConstant,delete l.level,a=a.level+(d?0:g-1),r(b[a])?v(b[a],l):b[a]=l);return b},{})),A=w(b.to)?b.to:1,b=0;b<=A;b++)n[b]=B({},u,r(k[b])?k[b]:{});return n},setTreeValues:function x(b,k){var u=k.before,g=k.idRoot,m=k.mapIdToNode[g],a=k.points[b.i],d=a&&a.options||{},l=0,c=[];
v(b,{levelDynamic:b.level-(("boolean"===typeof k.levelIsConstant?k.levelIsConstant:1)?0:m.level),name:n(a&&a.name,""),visible:g===b.id||("boolean"===typeof k.visible?k.visible:!1)});"function"===typeof u&&(b=u(b,k));b.children.forEach(function(a,d){var f=v({},k);v(f,{index:d,siblings:b.children.length,visible:b.visible});a=x(a,f);c.push(a);a.visible&&(l+=a.val)});b.visible=0<l||b.visible;u=n(d.value,l);v(b,{children:c,childrenTotal:l,isLeaf:b.visible&&!l,val:u});return b},updateRootId:function(b){var u;
r(b)&&(u=r(b.options)?b.options:{},u=n(b.rootNode,u.rootId,""),r(b.userOptions)&&(b.userOptions.rootId=u),b.rootNode=u);return u}}});D(q,"modules/broken-axis.src.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){var q=g.isArray;g=b.addEvent;var w=b.pick,v=b.extend,r=b.find,B=b.fireEvent,n=b.Axis,C=b.Series,x=function(b,k){return r(k,function(k){return k.from<b&&b<k.to})};v(n.prototype,{isInBreak:function(b,k){var n=b.repeat||Infinity,u=b.from,m=b.to-b.from;k=k>=u?(k-u)%n:n-(u-k)%n;
return b.inclusive?k<=m:k<m&&0!==k},isInAnyBreak:function(b,k){var n=this.options.breaks,u=n&&n.length,m,a,d;if(u){for(;u--;)this.isInBreak(n[u],b)&&(m=!0,a||(a=w(n[u].showPoints,!this.isXAxis)));d=m&&k?m&&!a:m}return d}});g(n,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});g(n,"afterSetTickPositions",function(){if(this.isBroken){var b=this.tickPositions,k=this.tickPositions.info,n=[],g;for(g=0;g<b.length;g++)this.isInAnyBreak(b[g])||n.push(b[g]);
this.tickPositions=n;this.tickPositions.info=k}});g(n,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});n.prototype.setBreaks=function(b,k){function g(a){var d=a,c,f;for(f=0;f<m.breakArray.length;f++)if(c=m.breakArray[f],c.to<=a)d-=c.len;else if(c.from>=a)break;else if(m.isInBreak(c,a)){d-=a-c.from;break}return d}function u(a){var d,c;for(c=0;c<m.breakArray.length&&!(d=m.breakArray[c],d.from>=a);c++)d.to<a?a+=d.len:m.isInBreak(d,a)&&(a+=d.len);return a}var m=this,a=q(b)&&!!b.length;
m.isDirty=m.isBroken!==a;m.isBroken=a;m.options.breaks=m.userOptions.breaks=b;m.forceRedraw=!0;a||m.val2lin!==g||(delete m.val2lin,delete m.lin2val);a&&(m.userOptions.ordinal=!1,m.val2lin=g,m.lin2val=u,m.setExtremes=function(a,b,c,f,h){if(this.isBroken){for(var d,e=this.options.breaks;d=x(a,e);)a=d.to;for(;d=x(b,e);)b=d.from;b<a&&(b=a)}n.prototype.setExtremes.call(this,a,b,c,f,h)},m.setAxisTranslation=function(a){n.prototype.setAxisTranslation.call(this,a);this.unitLength=null;if(this.isBroken){a=
m.options.breaks;var d=[],c=[],f=0,b,z,e=m.userMin||m.min,p=m.userMax||m.max,t=w(m.pointRangePadding,0),G,E;a.forEach(function(a){z=a.repeat||Infinity;m.isInBreak(a,e)&&(e+=a.to%z-e%z);m.isInBreak(a,p)&&(p-=p%z-a.from%z)});a.forEach(function(a){G=a.from;for(z=a.repeat||Infinity;G-z>e;)G-=z;for(;G<e;)G+=z;for(E=G;E<p;E+=z)d.push({value:E,move:"in"}),d.push({value:E+(a.to-a.from),move:"out",size:a.breakSize})});d.sort(function(a,e){return a.value===e.value?("in"===a.move?0:1)-("in"===e.move?0:1):a.value-
e.value});b=0;G=e;d.forEach(function(a){b+="in"===a.move?1:-1;1===b&&"in"===a.move&&(G=a.value);0===b&&(c.push({from:G,to:a.value,len:a.value-G-(a.size||0)}),f+=a.value-G-(a.size||0))});m.breakArray=c;m.unitLength=p-e-f+t;B(m,"afterBreaks");m.staticScale?m.transA=m.staticScale:m.unitLength&&(m.transA*=(p-m.min+t)/m.unitLength);t&&(m.minPixelPadding=m.transA*m.minPointOffset);m.min=e;m.max=p}});w(k,!0)&&this.chart.redraw()};g(C,"afterGeneratePoints",function(){var b=this.xAxis,k=this.yAxis,n=this.points,
g,m=n.length,a=this.options.connectNulls,d;if(b&&k&&(b.options.breaks||k.options.breaks))for(;m--;)g=n[m],d=null===g.y&&!1===a,d||!b.isInAnyBreak(g.x,!0)&&!k.isInAnyBreak(g.y,!0)||(n.splice(m,1),this.data[m]&&this.data[m].destroyElements())});g(C,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,w(this.pointArrayMap,["y"]))});b.Series.prototype.drawBreaks=function(b,k){var n=this,g=n.points,m,a,d,l;b&&k.forEach(function(c){m=b.breakArray||[];a=b.isXAxis?b.min:w(n.options.threshold,
b.min);g.forEach(function(f){l=w(f["stack"+c.toUpperCase()],f[c]);m.forEach(function(c){d=!1;if(a<c.from&&l>c.to||a>c.from&&l<c.from)d="pointBreak";else if(a<c.from&&l>c.from&&l<c.to||a>c.from&&l>c.to&&l<c.from)d="pointInBreak";d&&B(b,d,{point:f,brk:c})})})})};b.Series.prototype.gappedPath=function(){var n=this.currentDataGrouping,k=n&&n.gapSize,n=this.options.gapSize,g=this.points.slice(),x=g.length-1,m=this.yAxis;if(n&&0<x)for("value"!==this.options.gapUnit&&(n*=this.closestPointRange),k&&k>n&&
(n=k);x--;)g[x+1].x-g[x].x>n&&(k=(g[x].x+g[x+1].x)/2,g.splice(x+1,0,{isNull:!0,x:k}),this.options.stacking&&(k=m.stacks[this.stackKey][k]=new b.StackItem(m,m.options.stackLabels,!1,k,this.stack),k.total=0));return this.getGraphPath(g)}});D(q,"parts-gantt/TreeGrid.js",[q["parts/Globals.js"],q["parts/Utilities.js"],q["parts-gantt/Tree.js"],q["mixins/tree-series.js"]],function(b,g,q,w){var v=g.isNumber,r=g.isString,H=b.addEvent,n=function(a){return Array.prototype.slice.call(a,1)},C=b.defined;g=b.extend;
var x=b.find,u=b.fireEvent,k=w.getLevelOptions,F=b.merge,A=function(a){return b.isObject(a,!0)},m=b.pick,a=b.wrap;w=b.Axis;var d=b.Tick,l=function(e,c){var d,f;for(d in c)c.hasOwnProperty(d)&&(f=c[d],a(e,d,f))},c=function(a,c){var e=a.collapseStart;a=a.collapseEnd;a>=c&&(e-=.5);return{from:e,to:a,showPoints:!1}},f=function(a){return Object.keys(a.mapOfPosToGridNode).reduce(function(e,c){c=+c;a.min<=c&&a.max>=c&&!a.isInAnyBreak(c)&&e.push(c);return e},[])},h=function(a,e){var d=a.options.breaks||[],
f=c(e,a.max);return d.some(function(a){return a.from===f.from&&a.to===f.to})},z=function(a,e){var d=a.options.breaks||[];a=c(e,a.max);d.push(a);return d},e=function(a,e){var d=a.options.breaks||[],f=c(e,a.max);return d.reduce(function(a,e){e.to===f.to&&e.from===f.from||a.push(e);return a},[])},p=function(a,e){var c=a.labelIcon,d=!c,f=e.renderer,b=e.xy,p=e.options,h=p.width,t=p.height,l=b.x-h/2-p.padding,b=b.y-t/2,y=e.collapsed?90:180,z=e.show&&v(b);d&&(a.labelIcon=c=f.path(f.symbols[p.type](p.x,p.y,
h,t)).addClass("highcharts-label-icon").add(e.group));z||c.attr({y:-9999});f.styledMode||c.attr({"stroke-width":1,fill:m(e.color,"#666666")}).css({cursor:"pointer",stroke:p.lineColor,strokeWidth:p.lineWidth});c[d?"attr":"animate"]({translateX:l,translateY:b,rotation:y})},t=function(a,e,c){var d=[],f=[],b={},p={},h=-1,t="boolean"===typeof e?e:!1;a=q.getTree(a,{after:function(a){a=p[a.pos];var e=0,c=0;a.children.forEach(function(a){c+=a.descendants+1;e=Math.max(a.height+1,e)});a.descendants=c;a.height=
e;a.collapsed&&f.push(a)},before:function(a){var e=A(a.data)?a.data:{},c=r(e.name)?e.name:"",f=b[a.parent],f=A(f)?p[f.pos]:null,l=function(a){return a.name===c},m;t&&A(f)&&(m=x(f.children,l))?(l=m.pos,m.nodes.push(a)):l=h++;p[l]||(p[l]=m={depth:f?f.depth+1:0,name:c,nodes:[a],children:[],pos:l},-1!==l&&d.push(c),A(f)&&f.children.push(m));r(a.id)&&(b[a.id]=a);!0===e.collapsed&&(m.collapsed=!0);a.pos=l}});p=function(a,e){var c=function(a,d,f){var b=d+(-1===d?0:e-1),p=(b-d)/2,h=d+p;a.nodes.forEach(function(a){var e=
a.data;A(e)&&(e.y=d+e.seriesIndex,delete e.seriesIndex);a.pos=h});f[h]=a;a.pos=h;a.tickmarkOffset=p+.5;a.collapseStart=b+.5;a.children.forEach(function(a){c(a,b+1,f);b=a.collapseEnd-.5});a.collapseEnd=b+.5;return f};return c(a["-1"],-1,{})}(p,c);return{categories:d,mapOfIdToNode:b,mapOfPosToGridNode:p,collapsedNodes:f,tree:a}},G=function(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(e){var c=e.options||{},d=c.labels,f,p=c.uniqueNames,h=0,l;if(!e.mapOfPosToGridNode||
e.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty}))c=e.series.reduce(function(a,e){e.visible&&(e.options.data.forEach(function(e){A(e)&&(e.seriesIndex=h,a.push(e))}),!0===p&&h++);return a},[]),l=t(c,p,!0===p?h:1),e.categories=l.categories,e.mapOfPosToGridNode=l.mapOfPosToGridNode,e.hasNames=!0,e.tree=l.tree,e.series.forEach(function(a){var e=a.options.data.map(function(a){return A(a)?F(a):a});a.visible&&a.setData(e,!1)}),e.mapOptionsToLevel=k({defaults:d,from:1,levels:d.levels,
to:e.tree.height}),"beforeRender"===a.type&&(f=b.addEvent(e,"foundExtremes",function(){l.collapsedNodes.forEach(function(a){a=z(e,a);e.setBreaks(a,!1)});f()}))})};l(w.prototype,{init:function(a,e,c){var d="treegrid"===c.type;d&&(H(e,"beforeRender",G),H(e,"beforeRedraw",G),c=F({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));a.apply(this,
[e,c]);d&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(a){var e=this.options,c=e&&e.labels,e=c&&v(c.indentation)?e.labels.indentation:0,c=a.apply(this,n(arguments)),d;"treegrid"===this.options.type&&this.mapOfPosToGridNode&&(d=this.mapOfPosToGridNode[-1].height,c.width+=e*(d-1));return c},generateTick:function(a,e){var c=A(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},f=this.ticks,b=f[e],p,h;"treegrid"===this.options.type?(h=this.mapOfPosToGridNode[e],(c=c[h.depth])&&
(p={labels:c}),b?(b.parameters.category=h.name,b.options=p,b.addLabel()):f[e]=new d(this,e,null,void 0,{category:h.name,tickmarkOffset:h.tickmarkOffset,options:p})):a.apply(this,n(arguments))},setTickInterval:function(a){var e=this.options;"treegrid"===e.type?(this.min=m(this.userMin,e.min,this.dataMin),this.max=m(this.userMax,e.max,this.dataMax),u(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?f(this):[]):a.apply(this,
n(arguments))}});l(d.prototype,{getLabelPosition:function(a,e,c,d,f,b,p,h,l){var t=m(this.options&&this.options.labels,b);b=this.pos;var y=this.axis,z="treegrid"===y.options.type;a=a.apply(this,[e,c,d,f,t,p,h,l]);z&&(e=t&&A(t.symbol)?t.symbol:{},t=t&&v(t.indentation)?t.indentation:0,b=(b=(y=y.mapOfPosToGridNode)&&y[b])&&b.depth||1,a.x+=e.width+2*e.padding+(b-1)*t);return a},renderLabel:function(a){var e=this,c=e.pos,d=e.axis,f=e.label,l=d.mapOfPosToGridNode,t=d.options,z=m(e.options&&e.options.labels,
t&&t.labels),G=z&&A(z.symbol)?z.symbol:{},E=(l=l&&l[c])&&l.depth,t="treegrid"===t.type,g=!(!f||!f.element),k=-1<d.tickPositions.indexOf(c),c=d.chart.styledMode;t&&l&&g&&f.addClass("highcharts-treegrid-node-level-"+E);a.apply(e,n(arguments));t&&l&&g&&0<l.descendants&&(d=h(d,l),p(e,{color:!c&&f.styles.color,collapsed:d,group:f.parentGroup,options:G,renderer:f.renderer,show:k,xy:f.xy}),G="highcharts-treegrid-node-"+(d?"expanded":"collapsed"),f.addClass("highcharts-treegrid-node-"+(d?"collapsed":"expanded")).removeClass(G),
c||f.css({cursor:"pointer"}),[f,e.labelIcon].forEach(function(a){a.attachedTreeGridEvents||(b.addEvent(a.element,"mouseover",function(){var a=f;a.addClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:"underline"})}),b.addEvent(a.element,"mouseout",function(){var a=f,e=z,e=C(e.style)?e.style:{};a.removeClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:e.textDecoration})}),b.addEvent(a.element,"click",function(){e.toggleCollapse()}),
a.attachedTreeGridEvents=!0)}))}});g(d.prototype,{collapse:function(a){var e=this.axis,c=z(e,e.mapOfPosToGridNode[this.pos]);e.setBreaks(c,m(a,!0))},expand:function(a){var c=this.axis,d=e(c,c.mapOfPosToGridNode[this.pos]);c.setBreaks(d,m(a,!0))},toggleCollapse:function(a){var c=this.axis,d;d=c.mapOfPosToGridNode[this.pos];d=h(c,d)?e(c,d):z(c,d);c.setBreaks(d,m(a,!0))}});w.prototype.utils={getNode:q.getNode}});D(q,"parts-gantt/PathfinderAlgorithms.js",[q["parts/Globals.js"]],function(b){function g(b,
n,g){g=g||0;var k=b.length-1;n-=1e-7;for(var x,m;g<=k;)if(x=k+g>>1,m=n-b[x].xMin,0<m)g=x+1;else if(0>m)k=x-1;else return x;return 0<g?g-1:0}function q(b,n){for(var k=g(b,n.x+1)+1;k--;){var x;if(x=b[k].xMax>=n.x)x=b[k],x=n.x<=x.xMax&&n.x>=x.xMin&&n.y<=x.yMax&&n.y>=x.yMin;if(x)return k}return-1}function w(b){var n=[];if(b.length){n.push("M",b[0].start.x,b[0].start.y);for(var g=0;g<b.length;++g)n.push("L",b[g].end.x,b[g].end.y)}return n}function v(b,n){b.yMin=B(b.yMin,n.yMin);b.yMax=r(b.yMax,n.yMax);
b.xMin=B(b.xMin,n.xMin);b.xMax=r(b.xMax,n.xMax)}var r=Math.min,B=Math.max,n=Math.abs,C=b.pick;return{straight:function(b,n){return{path:["M",b.x,b.y,"L",n.x,n.y],obstacles:[{start:b,end:n}]}},simpleConnect:b.extend(function(b,g,k){function r(a,c,e,d,b){a={x:a.x,y:a.y};a[c]=e[d||c]+(b||0);return a}function x(a,c,e){var d=n(c[e]-a[e+"Min"])>n(c[e]-a[e+"Max"]);return r(c,e,a,e+(d?"Max":"Min"),d?1:-1)}var m=[],a,d=C(k.startDirectionX,n(g.x-b.x)>n(g.y-b.y))?"x":"y",l=k.chartObstacles,c=q(l,b);k=q(l,g);
var f;-1<k?(a=l[k],k=x(a,g,d),a={start:k,end:g},f=k):f=g;-1<c&&(l=l[c],k=x(l,b,d),m.push({start:b,end:k}),k[d]>=b[d]===k[d]>=f[d]&&(d="y"===d?"x":"y",g=b[d]<g[d],m.push({start:k,end:r(k,d,l,d+(g?"Max":"Min"),g?1:-1)}),d="y"===d?"x":"y"));b=m.length?m[m.length-1].end:b;k=r(b,d,f);m.push({start:b,end:k});d=r(k,"y"===d?"x":"y",f);m.push({start:k,end:d});m.push(a);return{path:w(m),obstacles:m}},{requiresObstacles:!0}),fastAvoid:b.extend(function(b,u,k){function x(a,e,c){var d,b,f,p,h,l=a.x<e.x?1:-1;a.x<
e.x?(d=a,b=e):(d=e,b=a);a.y<e.y?(p=a,f=e):(p=e,f=a);for(h=0>l?r(g(y,b.x),y.length-1):0;y[h]&&(0<l&&y[h].xMin<=b.x||0>l&&y[h].xMax>=d.x);){if(y[h].xMin<=b.x&&y[h].xMax>=d.x&&y[h].yMin<=f.y&&y[h].yMax>=p.y)return c?{y:a.y,x:a.x<e.x?y[h].xMin-1:y[h].xMax+1,obstacle:y[h]}:{x:a.x,y:a.y<e.y?y[h].yMin-1:y[h].yMax+1,obstacle:y[h]};h+=l}return e}function H(a,e,c,d,b){var f=b.soft,p=b.hard,h=d?"x":"y",l={x:e.x,y:e.y},t={x:e.x,y:e.y};b=a[h+"Max"]>=f[h+"Max"];var f=a[h+"Min"]<=f[h+"Min"],m=a[h+"Max"]>=p[h+"Max"],
p=a[h+"Min"]<=p[h+"Min"],z=n(a[h+"Min"]-e[h]),g=n(a[h+"Max"]-e[h]);c=10>n(z-g)?e[h]<c[h]:g<z;t[h]=a[h+"Min"];l[h]=a[h+"Max"];a=x(e,t,d)[h]!==t[h];e=x(e,l,d)[h]!==l[h];c=a?e?c:!0:e?!1:c;c=f?b?c:!0:b?!1:c;return p?m?c:!0:m?!1:c}function m(a,e,c){if(a.x===e.x&&a.y===e.y)return[];var d=c?"x":"y",b,f,h,l,g=k.obstacleOptions.margin;b={soft:{xMin:p,xMax:t,yMin:G,yMax:E},hard:k.hardBounds};f=q(y,a);-1<f?(f=y[f],b=H(f,a,e,c,b),v(f,k.hardBounds),l=c?{y:a.y,x:f[b?"xMax":"xMin"]+(b?1:-1)}:{x:a.x,y:f[b?"yMax":
"yMin"]+(b?1:-1)},h=q(y,l),-1<h&&(h=y[h],v(h,k.hardBounds),l[d]=b?B(f[d+"Max"]-g+1,(h[d+"Min"]+f[d+"Max"])/2):r(f[d+"Min"]+g-1,(h[d+"Max"]+f[d+"Min"])/2),a.x===l.x&&a.y===l.y?(z&&(l[d]=b?B(f[d+"Max"],h[d+"Max"])+1:r(f[d+"Min"],h[d+"Min"])-1),z=!z):z=!1),a=[{start:a,end:l}]):(d=x(a,{x:c?e.x:a.x,y:c?a.y:e.y},c),a=[{start:a,end:{x:d.x,y:d.y}}],d[c?"x":"y"]!==e[c?"x":"y"]&&(b=H(d.obstacle,d,e,!c,b),v(d.obstacle,k.hardBounds),b={x:c?d.x:d.obstacle[b?"xMax":"xMin"]+(b?1:-1),y:c?d.obstacle[b?"yMax":"yMin"]+
(b?1:-1):d.y},c=!c,a=a.concat(m({x:d.x,y:d.y},b,c))));return a=a.concat(m(a[a.length-1].end,e,!c))}function a(a,e,c){var d=r(a.xMax-e.x,e.x-a.xMin)<r(a.yMax-e.y,e.y-a.yMin);c=H(a,e,c,d,{soft:k.hardBounds,hard:k.hardBounds});return d?{y:e.y,x:a[c?"xMax":"xMin"]+(c?1:-1)}:{x:e.x,y:a[c?"yMax":"yMin"]+(c?1:-1)}}var d=C(k.startDirectionX,n(u.x-b.x)>n(u.y-b.y)),l=d?"x":"y",c,f,h=[],z=!1,e=k.obstacleMetrics,p=r(b.x,u.x)-e.maxWidth-10,t=B(b.x,u.x)+e.maxWidth+10,G=r(b.y,u.y)-e.maxHeight-10,E=B(b.y,u.y)+e.maxHeight+
10,y=k.chartObstacles;c=g(y,p);e=g(y,t);y=y.slice(c,e+1);-1<(e=q(y,u))&&(f=a(y[e],u,b),h.push({end:u,start:f}),u=f);for(;-1<(e=q(y,u));)c=0>u[l]-b[l],f={x:u.x,y:u.y},f[l]=y[e][c?l+"Max":l+"Min"]+(c?1:-1),h.push({end:u,start:f}),u=f;b=m(b,u,d);b=b.concat(h.reverse());return{path:w(b),obstacles:b}},{requiresObstacles:!0})}});D(q,"parts-gantt/ArrowSymbols.js",[q["parts/Globals.js"]],function(b){b.SVGRenderer.prototype.symbols.arrow=function(b,q,w,v){return["M",b,q+v/2,"L",b+w,q,"L",b,q+v/2,"L",b+w,q+
v]};b.SVGRenderer.prototype.symbols["arrow-half"]=function(g,q,w,v){return b.SVGRenderer.prototype.symbols.arrow(g,q,w/2,v)};b.SVGRenderer.prototype.symbols["triangle-left"]=function(b,q,w,v){return["M",b+w,q,"L",b,q+v/2,"L",b+w,q+v,"Z"]};b.SVGRenderer.prototype.symbols["arrow-filled"]=b.SVGRenderer.prototype.symbols["triangle-left"];b.SVGRenderer.prototype.symbols["triangle-left-half"]=function(g,q,w,v){return b.SVGRenderer.prototype.symbols["triangle-left"](g,q,w/2,v)};b.SVGRenderer.prototype.symbols["arrow-filled-half"]=
b.SVGRenderer.prototype.symbols["triangle-left-half"]});D(q,"parts-gantt/Pathfinder.js",[q["parts/Globals.js"],q["parts-gantt/PathfinderAlgorithms.js"]],function(b,g){function q(a){var d=a.shapeArgs;return d?{xMin:d.x,xMax:d.x+d.width,yMin:d.y,yMax:d.y+d.height}:(d=a.graphic&&a.graphic.getBBox())?{xMin:a.plotX-d.width/2,xMax:a.plotX+d.width/2,yMin:a.plotY-d.height/2,yMax:a.plotY+d.height/2}:null}function w(a){for(var d=a.length,b=0,c,f,h=[],z=function(a,c,d){d=F(d,10);var e=a.yMax+d>c.yMin-d&&a.yMin-
d<c.yMax+d,b=a.xMax+d>c.xMin-d&&a.xMin-d<c.xMax+d,f=e?a.xMin>c.xMax?a.xMin-c.xMax:c.xMin-a.xMax:Infinity,h=b?a.yMin>c.yMax?a.yMin-c.yMax:c.yMin-a.yMax:Infinity;return b&&e?d?z(a,c,Math.floor(d/2)):Infinity:m(f,h)};b<d;++b)for(c=b+1;c<d;++c)f=z(a[b],a[c]),80>f&&h.push(f);h.push(80);return A(Math.floor(h.sort(function(a,c){return a-c})[Math.floor(h.length/10)]/2-1),1)}function v(a,d,b){this.init(a,d,b)}function r(a){this.init(a)}function B(a){if(a.options.pathfinder||a.series.reduce(function(a,b){b.options&&
k(!0,b.options.connectors=b.options.connectors||{},b.options.pathfinder);return a||b.options&&b.options.pathfinder},!1))k(!0,a.options.connectors=a.options.connectors||{},a.options.pathfinder),b.error('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}var n=b.defined,C=b.deg2rad,x=b.extend,u=b.addEvent,k=b.merge,F=b.pick,A=Math.max,m=Math.min;x(b.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",
inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});v.prototype={init:function(a,d,b){this.fromPoint=a;this.toPoint=d;this.options=b;this.chart=a.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(a,d,b){var c=this.chart,f=c.styledMode,h=c.pathfinder,l=!c.options.chart.forExport&&!1!==b,e=this.graphics&&this.graphics.path;h.group||(h.group=c.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(c.seriesGroup));h.group.translate(c.plotLeft,
c.plotTop);e&&e.renderer||(e=c.renderer.path().add(h.group),f||e.attr({opacity:0}));e.attr(d);a={d:a};f||(a.opacity=1);e[l?"animate":"attr"](a,b);this.graphics=this.graphics||{};this.graphics.path=e},addMarker:function(a,d,b){var c=this.fromPoint.series.chart,f=c.pathfinder,c=c.renderer,h="start"===a?this.fromPoint:this.toPoint,l=h.getPathfinderAnchorPoint(d),e,p;d.enabled&&(b="start"===a?{x:b[4],y:b[5]}:{x:b[b.length-5],y:b[b.length-4]},b=h.getRadiansToVector(b,l),l=h.getMarkerVector(b,d.radius,
l),b=-b/C,d.width&&d.height?(e=d.width,p=d.height):e=p=2*d.radius,this.graphics=this.graphics||{},l={x:l.x-e/2,y:l.y-p/2,width:e,height:p,rotation:b,rotationOriginX:l.x,rotationOriginY:l.y},this.graphics[a]?this.graphics[a].animate(l):(this.graphics[a]=c.symbol(d.symbol).addClass("highcharts-point-connecting-path-"+a+"-marker").attr(l).add(f.group),c.styledMode||this.graphics[a].attr({fill:d.color||this.fromPoint.color,stroke:d.lineColor,"stroke-width":d.lineWidth,opacity:0}).animate({opacity:1},
h.series.options.animation)))},getPath:function(a){var d=this.pathfinder,l=this.chart,c=d.algorithms[a.type],f=d.chartObstacles;if("function"!==typeof c)b.error('"'+a.type+'" is not a Pathfinder algorithm.');else return c.requiresObstacles&&!f&&(f=d.chartObstacles=d.getChartObstacles(a),l.options.connectors.algorithmMargin=a.algorithmMargin,d.chartObstacleMetrics=d.getObstacleMetrics(f)),c(this.fromPoint.getPathfinderAnchorPoint(a.startMarker),this.toPoint.getPathfinderAnchorPoint(a.endMarker),k({chartObstacles:f,
lineObstacles:d.lineObstacles||[],obstacleMetrics:d.chartObstacleMetrics,hardBounds:{xMin:0,xMax:l.plotWidth,yMin:0,yMax:l.plotHeight},obstacleOptions:{margin:a.algorithmMargin},startDirectionX:d.getAlgorithmStartDirection(a.startMarker)},a))},render:function(){var a=this.fromPoint,d=a.series,b=d.chart,c=b.pathfinder,f=k(b.options.connectors,d.options.connectors,a.options.connectors,this.options),h={};b.styledMode||(h.stroke=f.lineColor||a.color,h["stroke-width"]=f.lineWidth,f.dashStyle&&(h.dashstyle=
f.dashStyle));h["class"]="highcharts-point-connecting-path highcharts-color-"+a.colorIndex;f=k(h,f);n(f.marker.radius)||(f.marker.radius=m(A(Math.ceil((f.algorithmMargin||8)/2)-1,1),5));a=this.getPath(f);b=a.path;a.obstacles&&(c.lineObstacles=c.lineObstacles||[],c.lineObstacles=c.lineObstacles.concat(a.obstacles));this.renderPath(b,h,d.options.animation);this.addMarker("start",k(f.marker,f.startMarker),b);this.addMarker("end",k(f.marker,f.endMarker),b)},destroy:function(){this.graphics&&(b.objectEach(this.graphics,
function(a){a.destroy()}),delete this.graphics)}};r.prototype={algorithms:g,init:function(a){this.chart=a;this.connections=[];u(a,"redraw",function(){this.pathfinder.update()})},update:function(a){var d=this.chart,l=this,c=l.connections;l.connections=[];d.series.forEach(function(a){a.visible&&!a.options.isInternal&&a.points.forEach(function(a){var e,c=a.options&&a.options.connect&&b.splat(a.options.connect);a.visible&&!1!==a.isInside&&c&&c.forEach(function(c){e=d.get("string"===typeof c?c:c.to);e instanceof
b.Point&&e.series.visible&&e.visible&&!1!==e.isInside&&l.connections.push(new v(a,e,"string"===typeof c?{}:c))})})});for(var f=0,h,m,e=c.length,p=l.connections.length;f<e;++f){m=!1;for(h=0;h<p;++h)if(c[f].fromPoint===l.connections[h].fromPoint&&c[f].toPoint===l.connections[h].toPoint){l.connections[h].graphics=c[f].graphics;m=!0;break}m||c[f].destroy()}delete this.chartObstacles;delete this.lineObstacles;l.renderConnections(a)},renderConnections:function(a){a?this.chart.series.forEach(function(a){var d=
function(){var c=a.chart.pathfinder;(c&&c.connections||[]).forEach(function(c){c.fromPoint&&c.fromPoint.series===a&&c.render()});a.pathfinderRemoveRenderEvent&&(a.pathfinderRemoveRenderEvent(),delete a.pathfinderRemoveRenderEvent)};!1===a.options.animation?d():a.pathfinderRemoveRenderEvent=u(a,"afterAnimate",d)}):this.connections.forEach(function(a){a.render()})},getChartObstacles:function(a){for(var d=[],b=this.chart.series,c=F(a.algorithmMargin,0),f,h=0,m=b.length;h<m;++h)if(b[h].visible&&!b[h].options.isInternal)for(var e=
0,p=b[h].points.length,t;e<p;++e)t=b[h].points[e],t.visible&&(t=q(t))&&d.push({xMin:t.xMin-c,xMax:t.xMax+c,yMin:t.yMin-c,yMax:t.yMax+c});d=d.sort(function(a,e){return a.xMin-e.xMin});n(a.algorithmMargin)||(f=a.algorithmMargin=w(d),d.forEach(function(a){a.xMin-=f;a.xMax+=f;a.yMin-=f;a.yMax+=f}));return d},getObstacleMetrics:function(a){for(var d=0,b=0,c,f,h=a.length;h--;)c=a[h].xMax-a[h].xMin,f=a[h].yMax-a[h].yMin,d<c&&(d=c),b<f&&(b=f);return{maxHeight:b,maxWidth:d}},getAlgorithmStartDirection:function(a){var d=
"top"!==a.verticalAlign&&"bottom"!==a.verticalAlign;return"left"!==a.align&&"right"!==a.align?d?void 0:!1:d?!0:void 0}};b.Connection=v;b.Pathfinder=r;x(b.Point.prototype,{getPathfinderAnchorPoint:function(a){var d=q(this),b,c;switch(a.align){case "right":b="xMax";break;case "left":b="xMin"}switch(a.verticalAlign){case "top":c="yMin";break;case "bottom":c="yMax"}return{x:b?d[b]:(d.xMin+d.xMax)/2,y:c?d[c]:(d.yMin+d.yMax)/2}},getRadiansToVector:function(a,b){n(b)||(b=q(this),b={x:(b.xMin+b.xMax)/2,y:(b.yMin+
b.yMax)/2});return Math.atan2(b.y-a.y,a.x-b.x)},getMarkerVector:function(a,b,m){for(var c=2*Math.PI,d=q(this),h=d.xMax-d.xMin,l=d.yMax-d.yMin,e=Math.atan2(l,h),p=!1,h=h/2,t=l/2,n=d.xMin+h,d=d.yMin+t,g=n,y=d,k={},I=1,r=1;a<-Math.PI;)a+=c;for(;a>Math.PI;)a-=c;c=Math.tan(a);a>-e&&a<=e?(r=-1,p=!0):a>e&&a<=Math.PI-e?r=-1:a>Math.PI-e||a<=-(Math.PI-e)?(I=-1,p=!0):I=-1;p?(g+=I*h,y+=r*h*c):(g+=l/(2*c)*I,y+=r*t);m.x!==n&&(g=m.x);m.y!==d&&(y=m.y);k.x=g+b*Math.cos(a);k.y=y-b*Math.sin(a);return k}});b.Chart.prototype.callbacks.push(function(a){!1!==
a.options.connectors.enabled&&(B(a),this.pathfinder=new r(this),this.pathfinder.update(!0))})});D(q,"modules/xrange.src.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){var q=g.isNumber;g=b.addEvent;var w=b.defined,v=b.Color,r=b.seriesTypes.column,B=b.correctFloat,n=b.isObject,C=b.merge,x=b.pick,u=b.seriesType,k=b.Axis,F=b.Point,A=b.Series;u("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var b=this.point.partialFill;n(b)&&(b=b.amount);if(q(b)&&0<b)return B(100*
b)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'\x3cspan style\x3d"font-size: 10px"\x3e{point.x} - {point.x2}\x3c/span\x3e\x3cbr/\x3e',pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.yCategory}\x3c/b\x3e\x3cbr/\x3e'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:b.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:b.noop,buildKDTree:b.noop,
getColumnMetrics:function(){function b(){d.series.forEach(function(a){var c=a.xAxis;a.xAxis=a.yAxis;a.yAxis=c})}var a,d=this.chart;b();a=r.prototype.getColumnMetrics.call(this);b();return a},cropData:function(b,a,d,l){a=A.prototype.cropData.call(this,this.x2Data,a,d,l);a.xData=b.slice(a.start,a.end);return a},findPointIndex:function(m){var a=this.data,d=this.points,l=m.id,c,f;l&&(f=(c=b.find(a,function(a){return a.id===l}))?c.index:void 0);void 0===f&&(f=(c=b.find(a,function(a){return a.x===m.x&&
a.x2===m.x2&&!(d[f]&&d[f].touched)}))?c.index:void 0);this.cropped&&f>=this.cropStart&&(f-=this.cropStart);return f},translatePoint:function(b){var a=this.xAxis,d=this.yAxis,l=this.columnMetrics,c=this.options,f=c.minPointLength||0,h=b.plotX,m=x(b.x2,b.x+(b.len||0)),e=a.translate(m,0,0,0,1),m=Math.abs(e-h),p=this.chart.inverted,t=x(c.borderWidth,1)%2/2,g=l.offset,k=Math.round(l.width);f&&(f-=m,0>f&&(f=0),h-=f/2,e+=f/2);h=Math.max(h,-10);e=Math.min(Math.max(e,-10),a.len+10);w(b.options.pointWidth)&&
(g-=(Math.ceil(b.options.pointWidth)-k)/2,k=Math.ceil(b.options.pointWidth));c.pointPlacement&&q(b.plotY)&&d.categories&&(b.plotY=d.translate(b.y,0,1,0,1,c.pointPlacement));b.shapeArgs={x:Math.floor(Math.min(h,e))+t,y:Math.floor(b.plotY+g)+t,width:Math.round(Math.abs(e-h)),height:k,r:this.options.borderRadius};c=b.shapeArgs.x;f=c+b.shapeArgs.width;0>c||f>a.len?(c=Math.min(a.len,Math.max(0,c)),f=Math.max(0,Math.min(f,a.len)),e=f-c,b.dlBox=C(b.shapeArgs,{x:c,width:f-c,centerX:e?e/2:null})):b.dlBox=
null;p?(b.tooltipPos[1]+=m/2*(a.reversed?1:-1),b.tooltipPos[0]+=l.width/2,b.tooltipPos[1]=Math.max(Math.min(b.tooltipPos[1],a.len-1),0),b.tooltipPos[0]=Math.max(Math.min(b.tooltipPos[0],d.len-1),0)):(b.tooltipPos[0]+=m/2*(a.reversed?-1:1),b.tooltipPos[1]-=l.width/2,b.tooltipPos[0]=Math.max(Math.min(b.tooltipPos[0],a.len-1),0),b.tooltipPos[1]=Math.max(Math.min(b.tooltipPos[1],d.len-1),0));if(l=b.partialFill)n(l)&&(l=l.amount),q(l)||(l=0),d=b.shapeArgs,b.partShapeArgs={x:d.x,y:d.y,width:d.width,height:d.height,
r:this.options.borderRadius},h=Math.max(Math.round(m*l+b.plotX-h),0),b.clipRectArgs={x:a.reversed?d.x+m-h:d.x,y:d.y,width:h,height:d.height}},translate:function(){r.prototype.translate.apply(this,arguments);this.points.forEach(function(b){this.translatePoint(b)},this)},drawPoint:function(b,a){var d=this.options,l=this.chart.renderer,c=b.graphic,f=b.shapeType,h=b.shapeArgs,m=b.partShapeArgs,e=b.clipRectArgs,p=b.partialFill,t=d.stacking&&!d.borderRadius,g=b.state,k=d.states[g||"normal"]||{},y=void 0===
g?"attr":a,g=this.pointAttribs(b,g),k=x(this.chart.options.chart.animation,k.animation);if(b.isNull)c&&(b.graphic=c.destroy());else{if(c)c.rect[a](h);else b.graphic=c=l.g("point").addClass(b.getClassName()).add(b.group||this.group),c.rect=l[f](C(h)).addClass(b.getClassName()).addClass("highcharts-partfill-original").add(c);m&&(c.partRect?(c.partRect[a](C(m)),c.partialClipRect[a](C(e))):(c.partialClipRect=l.clipRect(e.x,e.y,e.width,e.height),c.partRect=l[f](m).addClass("highcharts-partfill-overlay").add(c).clip(c.partialClipRect)));
this.chart.styledMode||(c.rect[a](g,k).shadow(d.shadow,null,t),m&&(n(p)||(p={}),n(d.partialFill)&&(p=C(p,d.partialFill)),b=p.fill||v(g.fill).brighten(-.3).get()||v(b.color||this.color).brighten(-.3).get(),g.fill=b,c.partRect[y](g,k).shadow(d.shadow,null,t)))}},drawPoints:function(){var b=this,a=b.getAnimationVerb();b.points.forEach(function(d){b.drawPoint(d,a)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var b,
a=this.series;if(a.options.colorByPoint&&!this.options.color){b=a.options.colors||a.chart.options.colors;var d=this.y%(b?b.length:a.chart.options.chart.colorCount);b=b&&b[d];a.chart.styledMode||(this.color=b);this.options.colorIndex||(this.colorIndex=d)}else this.color||(this.color=a.color)},init:function(){F.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){F.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},
getLabelConfig:function(){var b=F.prototype.getLabelConfig.call(this),a=this.series.yAxis.categories;b.x2=this.x2;b.yCategory=this.yCategory=a&&a[this.y];return b},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});g(k,"afterGetSeriesExtremes",function(){var b=this.series,a,d;this.isXAxis&&(a=x(this.dataMax,-Number.MAX_VALUE),b.forEach(function(b){b.x2Data&&b.x2Data.forEach(function(b){b>a&&(a=b,d=!0)})}),d&&(this.dataMax=a))})});D(q,"parts-gantt/GanttSeries.js",
[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){var q=g.isNumber,w=b.dateFormat,v=b.merge,r=b.pick;g=b.seriesType;var B=b.seriesTypes.xrange;g("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'\x3cspan style\x3d"font-size: 10px"\x3e{series.name}\x3c/span\x3e\x3cbr/\x3e',pointFormat:null,pointFormatter:function(){var g=this.series,r=g.chart.tooltip,q=g.xAxis,u=g.tooltipOptions.dateTimeLabelFormats,k=q.options.startOfWeek,v=g.tooltipOptions,A=v.xDateFormat,g=
this.options.milestone,m="\x3cb\x3e"+(this.name||this.yCategory)+"\x3c/b\x3e";if(v.pointFormat)return this.tooltipFormatter(v.pointFormat);A||(A=b.splat(r.getDateFormat(q.closestPointRange,this.start,k,u))[0]);r=w(A,this.start);q=w(A,this.end);m+="\x3cbr/\x3e";return g?m+(r+"\x3cbr/\x3e"):m+("Start: "+r+"\x3cbr/\x3e")+("End: "+q+"\x3cbr/\x3e")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,
align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(b){var g,n;B.prototype.translatePoint.call(this,b);b.options.milestone&&(g=b.shapeArgs,n=g.height,b.shapeArgs={x:g.x-n/2,y:g.y,width:n,height:n})},drawPoint:function(b,g){var n=this.options,r=this.chart.renderer,k=b.shapeArgs,v=b.plotY,w=b.graphic,m=b.selected&&"select",a=n.stacking&&!n.borderRadius;if(b.options.milestone)if(q(v)&&null!==b.y){k=r.symbols.diamond(k.x,k.y,k.width,k.height);if(w)w[g]({d:k});
else b.graphic=r.path(k).addClass(b.getClassName(),!0).add(b.group||this.group);this.chart.styledMode||b.graphic.attr(this.pointAttribs(b,m)).shadow(n.shadow,null,a)}else w&&(b.graphic=w.destroy());else B.prototype.drawPoint.call(this,b,g)},setData:b.Series.prototype.setData,setGanttPointAliases:function(b){function g(g,n){void 0!==n&&(b[g]=n)}g("x",r(b.start,b.x));g("x2",r(b.end,b.x2));g("partialFill",r(b.completed,b.partialFill));g("connect",r(b.dependency,b.connect))}},v(B.prototype.pointClass.prototype,
{applyOptions:function(g,r){g=v(g);b.seriesTypes.gantt.prototype.setGanttPointAliases(g);return g=B.prototype.pointClass.prototype.applyOptions.call(this,g,r)},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}))});D(q,"parts-gantt/GanttChart.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){var q=g.isArray,w=b.merge,v=b.splat,r=b.Chart;b.ganttChart=function(g,n,C){var x="string"===
typeof g||g.nodeName,u=n.series,k=b.getOptions(),B,A=n;n=arguments[x?1:0];q(n.xAxis)||(n.xAxis=[n.xAxis||{},{}]);n.xAxis=n.xAxis.map(function(b,a){1===a&&(B=0);return w(k.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:B},b,{type:"datetime"})});n.yAxis=v(n.yAxis||{}).map(function(b){return w(k.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:b.categories?b.type:"treegrid"},b)});n.series=null;n=w(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1}},n,{isGantt:!0});n.series=A.series=
u;n.series.forEach(function(g){g.data.forEach(function(a){b.seriesTypes.gantt.prototype.setGanttPointAliases(a)})});return x?new r(g,n,C):new r(n,n)}});D(q,"parts/Scrollbar.js",[q["parts/Globals.js"]],function(b){function g(a,b,l){this.init(a,b,l)}var q=b.addEvent,w=b.Axis,v=b.correctFloat,r=b.defaultOptions,B=b.defined,n=b.destroyObjectProperties,C=b.fireEvent,x=b.hasTouch,u=b.merge,k=b.pick,D=b.removeEvent,A,m={height:b.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,
margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};r.scrollbar=u(!0,m,r.scrollbar);b.swapXY=A=function(a,b){var d=a.length,c;if(b)for(b=0;b<d;b+=3)c=a[b+1],a[b+1]=a[b+2],a[b+2]=c;return a};g.prototype={init:function(a,b,l){this.scrollbarButtons=
[];this.renderer=a;this.userOptions=b;this.options=u(m,b);this.chart=l;this.size=k(this.options.size,this.options.height);b.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,b=this.options,l=this.size,c=this.chart.styledMode,f;this.group=f=a.g("scrollbar").attr({zIndex:b.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:b.trackBorderRadius||0,height:l,width:l}).add(f);c||this.track.attr({fill:b.trackBackgroundColor,
stroke:b.trackBorderColor,"stroke-width":b.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(f);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:l,width:l,r:b.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(A(["M",-3,l/4,"L",-3,2*l/3,"M",0,l/4,"L",0,2*l/3,"M",3,l/4,"L",3,2*l/3],b.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);
c||(this.scrollbar.attr({fill:b.barBackgroundColor,stroke:b.barBorderColor,"stroke-width":b.barBorderWidth}),this.scrollbarRifles.attr({stroke:b.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,b,l,c){var d=this.options.vertical,h=0,g=this.rendered?"animate":"attr";this.x=a;this.y=b+this.trackBorderWidth;
this.width=l;this.xOffset=this.height=c;this.yOffset=h;d?(this.width=this.yOffset=l=h=this.size,this.xOffset=b=0,this.barWidth=c-2*l,this.x=a+=this.options.margin):(this.height=this.xOffset=c=b=this.size,this.barWidth=l-2*c,this.y+=this.options.margin);this.group[g]({translateX:a,translateY:this.y});this.track[g]({width:l,height:c});this.scrollbarButtons[1][g]({translateX:d?0:l-b,translateY:d?c-h:0})},drawScrollbarButton:function(a){var b=this.renderer,g=this.scrollbarButtons,c=this.options,f=this.size,
h;h=b.g().add(this.group);g.push(h);h=b.rect().addClass("highcharts-scrollbar-button").add(h);this.chart.styledMode||h.attr({stroke:c.buttonBorderColor,"stroke-width":c.buttonBorderWidth,fill:c.buttonBackgroundColor});h.attr(h.crisp({x:-.5,y:-.5,width:f+1,height:f+1,r:c.buttonBorderRadius},h.strokeWidth()));h=b.path(A(["M",f/2+(a?-1:1),f/2-3,"L",f/2+(a?-1:1),f/2+3,"L",f/2+(a?2:-2),f/2],c.vertical)).addClass("highcharts-scrollbar-arrow").add(g[a]);this.chart.styledMode||h.attr({fill:c.buttonArrowColor})},
setRange:function(a,b){var d=this.options,c=d.vertical,f=d.minWidth,h=this.barWidth,g,e,p=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";B(h)&&(a=Math.max(a,0),g=Math.ceil(h*a),this.calculatedWidth=e=v(h*Math.min(b,1)-g),e<f&&(g=(h-f+e)*a,e=f),f=Math.floor(g+this.xOffset+this.yOffset),h=e/2-.5,this.from=a,this.to=b,c?(this.scrollbarGroup[p]({translateY:f}),this.scrollbar[p]({height:e}),this.scrollbarRifles[p]({translateY:h}),this.scrollbarTop=
f,this.scrollbarLeft=0):(this.scrollbarGroup[p]({translateX:f}),this.scrollbar[p]({width:e}),this.scrollbarRifles[p]({translateX:h}),this.scrollbarLeft=f,this.scrollbarTop=0),12>=e?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0),!1===d.showFull&&(0>=a&&1<=b?this.group.hide():this.group.show()),this.rendered=!0)},initEvents:function(){var a=this;a.mouseMoveHandler=function(b){var d=a.chart.pointer.normalize(b),c=a.options.vertical?"chartY":"chartX",f=a.initPositions;!a.grabbedCenter||b.touches&&
0===b.touches[0][c]||(d=a.cursorToScrollbarPosition(d)[c],c=a[c],c=d-c,a.hasDragged=!0,a.updatePosition(f[0]+c,f[1]+c),a.hasDragged&&C(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};a.mouseUpHandler=function(b){a.hasDragged&&C(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(b){b=a.chart.pointer.normalize(b);b=a.cursorToScrollbarPosition(b);a.chartX=
b.chartX;a.chartY=b.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(b){var d=v(a.to-a.from)*a.options.step;a.updatePosition(v(a.from-d),v(a.to-d));C(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.buttonToMaxClick=function(b){var d=(a.to-a.from)*a.options.step;a.updatePosition(a.from+d,a.to+d);C(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})};a.trackClick=function(b){var d=a.chart.pointer.normalize(b),c=a.to-a.from,f=a.y+
a.scrollbarTop,h=a.x+a.scrollbarLeft;a.options.vertical&&d.chartY>f||!a.options.vertical&&d.chartX>h?a.updatePosition(a.from+c,a.to+c):a.updatePosition(a.from-c,a.to-c);C(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:b})}},cursorToScrollbarPosition:function(a){var b=this.options,b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-b)}},updatePosition:function(a,b){1<b&&(a=
v(1-v(b-a)),b=1);0>a&&(b=v(b-a),a=0);this.from=a;this.to=b},update:function(a){this.destroy();this.init(this.chart.renderer,u(!0,this.options,a),this.chart)},addEvents:function(){var a=this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,g=this.scrollbarGroup.element,c=this.mouseDownHandler,f=this.mouseMoveHandler,h=this.mouseUpHandler,a=[[b[a[0]].element,"click",this.buttonToMinClick],[b[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[g,"mousedown",
c],[g.ownerDocument,"mousemove",f],[g.ownerDocument,"mouseup",h]];x&&a.push([g,"touchstart",c],[g.ownerDocument,"touchmove",f],[g.ownerDocument,"touchend",h]);a.forEach(function(a){q.apply(null,a)});this._events=a},removeEvents:function(){this._events.forEach(function(a){D.apply(null,a)});this._events.length=0},destroy:function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},
this);a&&this===a.scrollbar&&(a.scrollbar=null,n(a.scrollbarButtons))}};b.Scrollbar||(q(w,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new g(a.chart.renderer,a.options.scrollbar,a.chart),q(a.scrollbar,"changed",function(d){var g=Math.min(k(a.options.min,a.min),a.min,a.dataMin),c=Math.max(k(a.options.max,a.max),a.max,a.dataMax)-g,f;a.horiz&&!a.reversed||
!a.horiz&&a.reversed?(f=g+c*this.to,g+=c*this.from):(f=g+c*(1-this.from),g+=c*(1-this.to));k(this.options.liveRedraw,b.svg&&!b.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===d.DOMType||!B(d.DOMType)?a.setExtremes(g,f,!0,"mousemove"!==d.DOMType,d):this.setRange(this.from,this.to)}))}),q(w,"afterRender",function(){var a=Math.min(k(this.options.min,this.min),this.min,k(this.dataMin,this.min)),b=Math.max(k(this.options.max,this.max),this.max,k(this.dataMax,this.max)),g=this.scrollbar,c=this.axisTitleMargin+
(this.titleOffset||0),f=this.chart.scrollbarsOffsets,h=this.options.margin||0;g&&(this.horiz?(this.opposite||(f[1]+=c),g.position(this.left,this.top+this.height+2+f[1]-(this.opposite?h:0),this.width,this.height),this.opposite||(f[1]+=h),c=1):(this.opposite&&(f[0]+=c),g.position(this.left+this.width+2+f[0]-(this.opposite?0:h),this.top,this.width,this.height),this.opposite&&(f[0]+=h),c=0),f[c]+=g.size+g.options.margin,isNaN(a)||isNaN(b)||!B(this.min)||!B(this.max)||this.min===this.max?g.setRange(0,
1):(f=(this.min-a)/(b-a),a=(this.max-a)/(b-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?g.setRange(f,a):g.setRange(1-a,1-f)))}),q(w,"afterGetOffset",function(){var a=this.horiz?2:1,b=this.scrollbar;b&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=b.size+b.options.margin)}),b.Scrollbar=g)});D(q,"parts/RangeSelector.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){function q(a){this.init(a)}var w=g.isNumber,v=g.pInt,r=b.addEvent,B=b.Axis;g=b.Chart;var n=
b.css,C=b.createElement,x=b.defaultOptions,u=b.defined,k=b.destroyObjectProperties,D=b.discardElement,A=b.extend,m=b.fireEvent,a=b.merge,d=b.pick,l=b.splat;A(x,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});x.lang=a(x.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});q.prototype={clickButton:function(a,
b){var c=this.chart,f=this.buttonOptions[a],e=c.xAxis[0],p=c.scroller&&c.scroller.getUnionExtremes()||e||{},g=p.dataMin,m=p.dataMax,k,y=e&&Math.round(Math.min(e.max,d(m,e.max))),n=f.type,q,p=f._range,u,v,x,U=f.dataGrouping;if(null!==g&&null!==m){c.fixedRange=p;U&&(this.forcedDataGrouping=!0,B.prototype.setDataGrouping.call(e||{chart:this.chart},U,!1),this.frozenStates=f.preserveDataGrouping);if("month"===n||"year"===n)e?(n={range:f,max:y,chart:c,dataMin:g,dataMax:m},k=e.minFromRange.call(n),w(n.newMax)&&
(y=n.newMax)):p=f;else if(p)k=Math.max(y-p,g),y=Math.min(k+p,m);else if("ytd"===n)if(e)void 0===m&&(g=Number.MAX_VALUE,m=Number.MIN_VALUE,c.series.forEach(function(a){a=a.xData;g=Math.min(a[0],g);m=Math.max(a[a.length-1],m)}),b=!1),y=this.getYTDExtremes(m,g,c.time.useUTC),k=u=y.min,y=y.max;else{this.deferredYTDClick=a;return}else"all"===n&&e&&(k=g,y=m);k+=f._offsetMin;y+=f._offsetMax;this.setSelected(a);e?e.setExtremes(k,y,d(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:f}):(q=l(c.options.xAxis)[0],
x=q.range,q.range=p,v=q.min,q.min=u,r(c,"load",function(){q.range=x;q.min=v}))}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,c=a.options.rangeSelector,d=c.buttons||[].concat(b.defaultButtons),e=c.selected,p=function(){var a=b.minInput,e=b.maxInput;a&&a.blur&&
m(a,"blur");e&&e.blur&&m(e,"blur")};b.chart=a;b.options=c;b.buttons=[];b.buttonOptions=d;this.unMouseDown=r(a.container,"mousedown",p);this.unResize=r(a,"resize",p);d.forEach(b.computeButtonRange);void 0!==e&&d[e]&&this.clickButton(e,!1);r(a,"load",function(){a.xAxis&&a.xAxis[0]&&r(a.xAxis[0],"setExtremes",function(e){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==e.trigger&&"updatedData"!==e.trigger&&b.forcedDataGrouping&&!b.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=
this,b=this.chart,d=b.xAxis[0],g=Math.round(d.max-d.min),e=!d.hasVisibleSeries,p=b.scroller&&b.scroller.getUnionExtremes()||d,t=p.dataMin,l=p.dataMax,b=a.getYTDExtremes(l,t,b.time.useUTC),m=b.min,n=b.max,k=a.selected,q=w(k),r=a.options.allButtonsEnabled,u=a.buttons;a.buttonOptions.forEach(function(b,c){var f=b._range,p=b.type,h=b.count||1,y=u[c],z=0,E=b._offsetMax-b._offsetMin;b=c===k;var G=f>l-t,I=f<d.minRange,J=!1,v=!1,f=f===g;("month"===p||"year"===p)&&g+36E5>=864E5*{month:28,year:365}[p]*h-E&&
g-36E5<=864E5*{month:31,year:366}[p]*h+E?f=!0:"ytd"===p?(f=n-m+E===g,J=!b):"all"===p&&(f=d.max-d.min>=l-t,v=!b&&q&&f);p=!r&&(G||I||v||e);h=b&&f||f&&!q&&!J||b&&a.frozenStates;p?z=3:h&&(q=!0,z=2);y.state!==z&&(y.setState(z),0===z&&k===c&&a.setSelected(null))})},computeButtonRange:function(a){var b=a.type,c=a.count||1,g={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(g[b])a._range=g[b]*c;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*c;a._offsetMin=d(a.offsetMin,
0);a._offsetMax=d(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,b){var c=this.chart.options.rangeSelector,d=this.chart.time,e=this[a+"Input"];u(b)&&(e.previousValue=e.HCTime,e.HCTime=b);e.value=d.dateFormat(c.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(c.inputDateFormat||"%b %e, %Y",e.HCTime)})},showInput:function(a){var b=this.inputGroup,c=this[a+"DateBox"];n(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-
2+"px",height:c.height-2+"px",border:"2px solid silver"})},hideInput:function(a){n(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(c){function d(){var a=k.value,b=(t.inputDateParser||Date.parse)(a),e=g.xAxis[0],c=g.scroller&&g.scroller.xAxis?g.scroller.xAxis:e,d=c.dataMin,c=c.dataMax;b!==k.previousValue&&(k.previousValue=b,w(b)||(b=a.split("-"),b=Date.UTC(v(b[0]),v(b[1])-1,v(b[2]))),w(b)&&(g.time.useUTC||(b+=6E4*(new Date).getTimezoneOffset()),m?b>h.maxInput.HCTime?
b=void 0:b<d&&(b=d):b<h.minInput.HCTime?b=void 0:b>c&&(b=c),void 0!==b&&e.setExtremes(m?b:e.min,m?e.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}var h=this,g=h.chart,e=g.renderer.style||{},p=g.renderer,t=g.options.rangeSelector,l=h.div,m="min"===c,k,q,r=this.inputGroup;this[c+"Label"]=q=p.label(x.lang[m?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(r);r.offset+=q.width+5;this[c+"DateBox"]=p=p.label("",r.offset).addClass("highcharts-range-input").attr({padding:2,
width:t.inputBoxWidth||90,height:t.inputBoxHeight||17,"text-align":"center"}).on("click",function(){h.showInput(c);h[c+"Input"].focus()});g.styledMode||p.attr({stroke:t.inputBoxBorderColor||"#cccccc","stroke-width":1});p.add(r);r.offset+=p.width+(m?10:0);this[c+"Input"]=k=C("input",{name:c,className:"highcharts-range-selector",type:"text"},{top:g.plotTop+"px"},l);g.styledMode||(q.css(a(e,t.labelStyle)),p.css(a({color:"#333333"},e,t.inputStyle)),n(k,A({position:"absolute",border:0,width:"1px",height:"1px",
padding:0,textAlign:"center",fontSize:e.fontSize,fontFamily:e.fontFamily,top:"-9999em"},t.inputStyle)));k.onfocus=function(){h.showInput(c)};k.onblur=function(){k===b.doc.activeElement&&d();h.hideInput(c);k.blur()};k.onchange=d;k.onkeypress=function(a){13===a.keyCode&&d()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector,a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}},getYTDExtremes:function(a,b,d){var c=
this.chart.time,e=new c.Date(a),f=c.get("FullYear",e);d=d?c.Date.UTC(f,0,1):+new c.Date(f,0,1);b=Math.max(b||0,d);e=e.getTime();return{max:Math.min(a||e,e),min:b}},render:function(a,b){var c=this,f=c.chart,e=f.renderer,p=f.container,g=f.options,m=g.exporting&&!1!==g.exporting.enabled&&g.navigation&&g.navigation.buttonOptions,l=x.lang,k=c.div,n=g.rangeSelector,q=d(g.chart.style&&g.chart.style.zIndex,0)+1,g=n.floating,r=c.buttons,k=c.inputGroup,v=n.buttonTheme,u=n.buttonPosition,w=n.inputPosition,B=
n.inputEnabled,A=v&&v.states,D=f.plotLeft,H,F=c.buttonGroup,N;N=c.rendered;var O=c.options.verticalAlign,Q=f.legend,R=Q&&Q.options,S=u.y,P=w.y,T=N||!1,V=T?"animate":"attr",M=0,K=0,L;if(!1!==n.enabled){N||(c.group=N=e.g("range-selector-group").attr({zIndex:7}).add(),c.buttonGroup=F=e.g("range-selector-buttons").add(N),c.zoomText=e.text(l.rangeSelectorZoom,0,15).add(F),f.styledMode||(c.zoomText.css(n.labelStyle),v["stroke-width"]=d(v["stroke-width"],0)),c.buttonOptions.forEach(function(a,b){r[b]=e.button(a.text,
0,0,function(e){var d=a.events&&a.events.click,f;d&&(f=d.call(a,e));!1!==f&&c.clickButton(b);c.isActive=!0},v,A&&A.hover,A&&A.select,A&&A.disabled).attr({"text-align":"center"}).add(F)}),!1!==B&&(c.div=k=C("div",null,{position:"relative",height:0,zIndex:q}),p.parentNode.insertBefore(k,p),c.inputGroup=k=e.g("input-group").add(N),k.offset=0,c.drawInput("min"),c.drawInput("max")));c.zoomText[V]({x:d(D+u.x,D)});H=d(D+u.x,D)+c.zoomText.getBBox().width+5;c.buttonOptions.forEach(function(a,b){r[b][V]({x:H});
H+=r[b].width+d(n.buttonSpacing,5)});D=f.plotLeft-f.spacing[3];c.updateButtonStates();m&&this.titleCollision(f)&&"top"===O&&"right"===u.align&&u.y+F.getBBox().height-12<(m.y||0)+m.height&&(M=-40);"left"===u.align?L=u.x-f.spacing[3]:"right"===u.align&&(L=u.x+M-f.spacing[1]);F.align({y:u.y,width:F.getBBox().width,align:u.align,x:L},!0,f.spacingBox);c.group.placed=T;c.buttonGroup.placed=T;!1!==B&&(M=m&&this.titleCollision(f)&&"top"===O&&"right"===w.align&&w.y-k.getBBox().height-12<(m.y||0)+m.height+
f.spacing[0]?-40:0,"left"===w.align?L=D:"right"===w.align&&(L=-Math.max(f.axisOffset[1],-M)),k.align({y:w.y,width:k.getBBox().width,align:w.align,x:w.x+L-2},!0,f.spacingBox),p=k.alignAttr.translateX+k.alignOptions.x-M+k.getBBox().x+2,m=k.alignOptions.width,l=F.alignAttr.translateX+F.getBBox().x,L=F.getBBox().width+20,(w.align===u.align||l+L>p&&p+m>l&&S<P+k.getBBox().height)&&k.attr({translateX:k.alignAttr.translateX+(f.axisOffset[1]>=-M?0:-M),translateY:k.alignAttr.translateY+F.getBBox().height+10}),
c.setInputValue("min",a),c.setInputValue("max",b),c.inputGroup.placed=T);c.group.align({verticalAlign:O},!0,f.spacingBox);a=c.group.getBBox().height+20;b=c.group.alignAttr.translateY;"bottom"===O&&(Q=R&&"bottom"===R.verticalAlign&&R.enabled&&!R.floating?Q.legendHeight+d(R.margin,10):0,a=a+Q-20,K=b-a-(g?0:n.y)-10);if("top"===O)g&&(K=0),f.titleOffset&&f.titleOffset[0]&&(K=f.titleOffset[0]+f.options.title.margin),K+=f.margin[0]-f.spacing[0]||0;else if("middle"===O)if(P===S)K=0>P?b+void 0:b;else if(P||
S)K=0>P||0>S?K-Math.min(P,S):b-a+NaN;c.group.translate(n.x,n.y+Math.floor(K));!1!==B&&(c.minInput.style.marginTop=c.group.translateY+"px",c.maxInput.style.marginTop=c.group.translateY+"px");c.rendered=!0}},getHeight:function(){var a=this.options,b=this.group,d=a.y,g=a.buttonPosition.y,e=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+d:0;b=Math.min(e,g);if(0>e&&0>g||0<e&&0<g)a+=Math.abs(b);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},
update:function(b){var c=this.chart;a(!0,c.options.rangeSelector,b);this.destroy();this.init(c);c.rangeSelector.render()},destroy:function(){var a=this,d=a.minInput,g=a.maxInput;a.unMouseDown();a.unResize();k(a.buttons);d&&(d.onfocus=d.onblur=d.onchange=null);g&&(g.onfocus=g.onblur=g.onchange=null);b.objectEach(a,function(b,e){b&&"chart"!==e&&(b.destroy?b.destroy():b.nodeType&&D(this[e]));b!==q.prototype[e]&&(a[e]=null)},this)}};B.prototype.minFromRange=function(){var a=this.range,b={month:"Month",
year:"FullYear"}[a.type],g,m=this.max,e,p,t=this.chart.time,k=function(a,e){var c=new t.Date(a),d=t.get(b,c);t.set(b,c,d+e);d===t.get(b,c)&&t.set("Date",c,0);return c.getTime()-a};w(a)?(g=m-a,p=a):(g=m+k(m,-a.count),this.chart&&(this.chart.fixedRange=m-g));e=d(this.dataMin,Number.MIN_VALUE);w(g)||(g=e);g<=e&&(g=e,void 0===p&&(p=k(g,a.count)),this.newMax=Math.min(g+p,this.dataMax));w(m)||(g=void 0);return g};b.RangeSelector||(r(g,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=
new q(this))}),r(g,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(w(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),r(g,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;
b&&b.enabled&&!u(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new q(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=!0)}),r(g,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===
a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),r(g,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),g.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();w(c.min)&&d.render(c.min,c.max)}var c,d=a.rangeSelector,e,g;d&&(g=r(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)}),e=r(a,"redraw",b),b());r(a,"destroy",function(){d&&(e(),
g())})}),b.RangeSelector=q)});D(q,"parts/Navigator.js",[q["parts/Globals.js"],q["parts/Utilities.js"]],function(b,g){function q(a){this.init(a)}var w=g.isArray,v=g.isNumber,r=b.addEvent,B=b.Axis;g=b.Chart;var n=b.color,C=b.defaultOptions,x=b.defined,u=b.destroyObjectProperties,k=b.erase,D=b.extend,A=b.hasTouch,m=b.isTouchDevice,a=b.merge,d=b.pick,l=b.removeEvent,c=b.Scrollbar,f=b.Series,h,z=function(a){for(var b=[],e=1;e<arguments.length;e++)b[e-1]=arguments[e];b=[].filter.call(b,v);if(b.length)return Math[a].apply(0,
b)};h=void 0===b.seriesTypes.areaspline?"line":"areaspline";D(C,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:n("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:h,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,
10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},pointRange:0,threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",
style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});b.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,f){a=f.width/2;b=Math.round(a/3)+.5;f=f.height;return["M",-a-1,.5,"L",a,.5,"L",a,f+.5,"L",-a-1,f+.5,"L",-a-1,.5,"M",-b,4,"L",-b,f-3,"M",b-1,4,"L",b-1,f-3]};B.prototype.toFixedRange=function(a,
b,c,f){var e=this.chart&&this.chart.fixedRange;a=d(c,this.translate(a,!0,!this.horiz));b=d(f,this.translate(b,!0,!this.horiz));c=e&&(b-a)/e;.7<c&&1.3>c&&(f?a=b-e:b=a+e);v(a)&&v(b)||(a=b=void 0);return{min:a,max:b}};q.prototype={drawHandle:function(a,b,c,d){var e=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+
this.height/2-e/2-1)})},drawOutline:function(a,b,c,d){var e=this.navigatorOptions.maskInside,f=this.outline.strokeWidth(),g=f/2,f=f%2/2,p=this.outlineHeight,h=this.scrollbarHeight,m=this.size,t=this.left-h,k=this.top;c?(t-=g,c=k+b+f,b=k+a+f,a=["M",t+p,k-h-f,"L",t+p,c,"L",t,c,"L",t,b,"L",t+p,b,"L",t+p,k+m+h].concat(e?["M",t+p,c-g,"L",t+p,b+g]:[])):(a+=t+h-f,b+=t+h-f,k+=g,a=["M",t,k,"L",a,k,"L",a,k+p,"L",b,k+p,"L",b,k,"L",t+m+2*h,k].concat(e?["M",a-g,k,"L",b+g,k]:[]));this.outline[d]({d:a})},drawMasks:function(a,
b,c,d){var e=this.left,f=this.top,g=this.height,p,h,k,t;c?(k=[e,e,e],t=[f,f+a,f+b],h=[g,g,g],p=[a,b-a,this.size-b]):(k=[e,e+a,e+b],t=[f,f,f],h=[a,b-a,this.size-b],p=[g,g,g]);this.shades.forEach(function(a,b){a[d]({x:k[b],y:t[b],width:h[b],height:p[b]})})},renderElements:function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,f=d.renderer,g,h={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=g=f.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(e,
c){a.shades[c]=f.rect().addClass("highcharts-navigator-mask"+(1===c?"-inside":"-outside")).add(g);d.styledMode||a.shades[c].attr({fill:e?b.maskFill:"rgba(0,0,0,0)"}).css(1===c&&h)});a.outline=f.path().addClass("highcharts-navigator-outline").add(g);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(e){b.handles.inverted=d.inverted;a.handles[e]=f.symbol(b.handles.symbols[e],-b.handles.width/2-1,0,b.handles.width,b.handles.height,
b.handles);a.handles[e].attr({zIndex:7-e}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][e]).add(g);if(!d.styledMode){var c=b.handles;a.handles[e].attr({fill:c.backgroundColor,stroke:c.borderColor,"stroke-width":c.lineWidth}).css(h)}})},update:function(b){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();a(!0,this.chart.options.navigator,this.options,b);this.init(this.chart)},render:function(a,c,f,g){var e=
this.chart,p,h,k=this.scrollbarHeight,m,l=this.xAxis;p=l.fake?e.xAxis[0]:l;var t=this.navigatorEnabled,n,q=this.rendered;h=e.inverted;var r,u=e.xAxis[0].minRange,w=e.xAxis[0].options.maxRange;if(!this.hasDragged||x(f)){if(!v(a)||!v(c))if(q)f=0,g=d(l.width,p.width);else return;this.left=d(l.left,e.plotLeft+k+(h?e.plotWidth:0));this.size=n=m=d(l.len,(h?e.plotHeight:e.plotWidth)-2*k);e=h?k:m+2*k;f=d(f,l.toPixels(a,!0));g=d(g,l.toPixels(c,!0));v(f)&&Infinity!==Math.abs(f)||(f=0,g=e);a=l.toValue(f,!0);
c=l.toValue(g,!0);r=Math.abs(b.correctFloat(c-a));r<u?this.grabbedLeft?f=l.toPixels(c-u,!0):this.grabbedRight&&(g=l.toPixels(a+u,!0)):x(w)&&r>w&&(this.grabbedLeft?f=l.toPixels(c-w,!0):this.grabbedRight&&(g=l.toPixels(a+w,!0)));this.zoomedMax=Math.min(Math.max(f,g,0),n);this.zoomedMin=Math.min(Math.max(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(f,g),0),n);this.range=this.zoomedMax-this.zoomedMin;n=Math.round(this.zoomedMax);f=Math.round(this.zoomedMin);t&&(this.navigatorGroup.attr({visibility:"visible"}),
q=q&&!this.hasDragged?"animate":"attr",this.drawMasks(f,n,h,q),this.drawOutline(f,n,h,q),this.navigatorOptions.handles.enabled&&(this.drawHandle(f,0,h,q),this.drawHandle(n,1,h,q)));this.scrollbar&&(h?(h=this.top-k,p=this.left-k+(t||!p.opposite?0:(p.titleOffset||0)+p.axisTitleMargin),k=m+2*k):(h=this.top+(t?this.height:-k),p=this.left-k),this.scrollbar.position(p,h,e,k),this.scrollbar.setRange(this.zoomedMin/(m||1),this.zoomedMax/(m||1)));this.rendered=!0}},addMouseEvents:function(){var a=this,b=a.chart,
c=b.container,d=[],f,g;a.mouseMoveHandler=f=function(b){a.onMouseMove(b)};a.mouseUpHandler=g=function(b){a.onMouseUp(b)};d=a.getPartsEvents("mousedown");d.push(r(c,"mousemove",f),r(c.ownerDocument,"mouseup",g));A&&(d.push(r(c,"touchmove",f),r(c.ownerDocument,"touchend",g)),d.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=d;a.series&&a.series[0]&&d.push(r(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var b=this,c=[];
["shades","handles"].forEach(function(e){b[e].forEach(function(d,f){c.push(r(d.element,a,function(a){b[e+"Mousedown"](a,f)}))})});return c},shadesMousedown:function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,e=this.xAxis,d=this.zoomedMin,f=this.left,g=this.size,p=this.range,h=a.chartX,k,m;c.inverted&&(h=a.chartY,f=this.top);1===b?(this.grabbedCenter=h,this.fixedWidth=p,this.dragOffset=h-d):(a=h-f-p/2,0===b?a=Math.max(0,a):2===b&&a+p>=g&&(a=g-p,this.reversedExtremes?(a-=p,m=this.getUnionExtremes().dataMin):
k=this.getUnionExtremes().dataMax),a!==d&&(this.fixedWidth=p,b=e.toFixedRange(a,a+p,m,k),x(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"})))},handlesMousedown:function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],e=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=e?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=e?c.max:c.min);
a.fixedRange=null},onMouseMove:function(a){var c=this,e=c.chart,f=c.left,g=c.navigatorSize,h=c.range,k=c.dragOffset,l=e.inverted;a.touches&&0===a.touches[0].pageX||(a=e.pointer.normalize(a),e=a.chartX,l&&(f=c.top,e=a.chartY),c.grabbedLeft?(c.hasDragged=!0,c.render(0,0,e-f,c.otherHandlePos)):c.grabbedRight?(c.hasDragged=!0,c.render(0,0,c.otherHandlePos,e-f)):c.grabbedCenter&&(c.hasDragged=!0,e<k?e=k:e>g+k-h&&(e=g+k-h),c.render(0,0,e-k,e-k+h)),c.hasDragged&&c.scrollbar&&d(c.scrollbar.options.liveRedraw,
b.svg&&!m&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){c.onMouseUp(a)},0)))},onMouseUp:function(a){var b=this.chart,c=this.xAxis,e=this.scrollbar,d,f,g=a.DOMEvent||a;(!this.hasDragged||e&&e.hasDragged)&&"scrollbar"!==a.trigger||(e=this.getUnionExtremes(),this.zoomedMin===this.otherHandlePos?d=this.fixedExtreme:this.zoomedMax===this.otherHandlePos&&(f=this.fixedExtreme),this.zoomedMax===this.size&&(f=this.reversedExtremes?e.dataMin:e.dataMax),0===this.zoomedMin&&(d=this.reversedExtremes?
e.dataMax:e.dataMin),c=c.toFixedRange(this.zoomedMin,this.zoomedMax,d,f),x(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:g}));"mousemove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),
this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){l(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&l(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(b){var e=b.options,f=e.navigator,g=f.enabled,h=e.scrollbar,k=h.enabled,e=g?f.height:0,m=k?h.height:0;this.handles=[];this.shades=[];this.chart=b;this.setBaseSeries();
this.height=e;this.scrollbarHeight=m;this.scrollbarEnabled=k;this.navigatorEnabled=g;this.navigatorOptions=f;this.scrollbarOptions=h;this.outlineHeight=e+m;this.opposite=d(f.opposite,!g&&b.inverted);var l=this,g=l.baseSeries,h=b.xAxis.length,k=b.yAxis.length,n=g&&g[0]&&g[0].xAxis||b.xAxis[0]||{options:{}};b.isDirtyBox=!0;l.navigatorEnabled?(l.xAxis=new B(b,a({breaks:n.options.breaks,ordinal:n.options.ordinal},f.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:h,isInternal:!0,
offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},b.inverted?{offsets:[m,0,-m,0],width:e}:{offsets:[0,-m,0,m],height:e})),l.yAxis=new B(b,a(f.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:k,isInternal:!0,zoomEnabled:!1},b.inverted?{width:e}:{height:e})),g||f.series.data?l.updateNavigatorSeries(!1):0===b.series.length&&(l.unbindRedraw=r(b,"beforeRedraw",function(){0<b.series.length&&!l.series&&(l.setBaseSeries(),l.unbindRedraw())})),l.reversedExtremes=
b.inverted&&!l.xAxis.reversed||!b.inverted&&l.xAxis.reversed,l.renderElements(),l.addMouseEvents()):l.xAxis={translate:function(a,c){var e=b.xAxis[0],d=e.getExtremes(),f=e.len-2*m,g=z("min",e.options.min,d.dataMin),e=z("max",e.options.max,d.dataMax)-g;return c?a*e/f+g:f*(a-g)/e},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:B.prototype.toFixedRange,fake:!0};b.options.scrollbar.enabled&&(b.scrollbar=l.scrollbar=new c(b.renderer,a(b.options.scrollbar,
{margin:l.navigatorEnabled?0:10,vertical:b.inverted}),b),r(l.scrollbar,"changed",function(a){var c=l.size,e=c*this.to,c=c*this.from;l.hasDragged=l.scrollbar.hasDragged;l.render(0,0,c,e);(b.options.scrollbar.liveRedraw||"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType)&&setTimeout(function(){l.onMouseUp(a)})}));l.addBaseSeriesEvents();l.addChartEvents()},getUnionExtremes:function(a){var b=this.chart.xAxis[0],c=this.xAxis,e=c.options,f=b.options,g;a&&null===b.dataMin||(g={dataMin:d(e&&e.min,z("min",
f.min,b.dataMin,c.dataMin,c.min)),dataMax:d(e&&e.max,z("max",f.max,b.dataMax,c.dataMax,c.max))});return g},setBaseSeries:function(a,c){var e=this.chart,d=this.baseSeries=[];a=a||e.options&&e.options.navigator.baseSeries||(e.series.length?b.find(e.series,function(a){return!a.options.isInternal}).index:0);(e.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,
c)},updateNavigatorSeries:function(c,d){var e=this,f=e.chart,g=e.baseSeries,h,k,m=e.navigatorOptions.series,p,n={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},q=e.series=(e.series||[]).filter(function(a){var b=a.baseSeries;return 0>g.indexOf(b)?(b&&(l(b,"updatedData",e.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});g&&g.length&&
g.forEach(function(b){var c=b.navigatorSeries,l=D({color:b.color,visible:b.visible},w(m)?C.navigator.series:m);c&&!1===e.navigatorOptions.adaptToUpdatedData||(n.name="Navigator "+g.length,h=b.options||{},p=h.navigatorOptions||{},k=a(h,n,l,p),l=p.data||l.data,e.hasNavigatorData=e.hasNavigatorData||!!l,k.data=l||h.data&&h.data.slice(0),c&&c.options?c.update(k,d):(b.navigatorSeries=f.initSeries(k),b.navigatorSeries.baseSeries=b,q.push(b.navigatorSeries)))});if(m.data&&(!g||!g.length)||w(m))e.hasNavigatorData=
!1,m=b.splat(m),m.forEach(function(b,c){n.name="Navigator "+(q.length+1);k=a(C.navigator.series,{color:f.series[c]&&!f.series[c].options.isInternal&&f.series[c].color||f.options.colors[c]||f.options.colors[0]},n,b);k.data=b.data;k.data&&(e.hasNavigatorData=!0,q.push(f.initSeries(k)))});c&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&r(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);b.forEach(function(b){r(b,"show",function(){this.navigatorSeries&&
this.navigatorSeries.setVisible(!0,!1)});r(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&r(b,"updatedData",this.updatedDataHandler);r(b,"remove",function(){this.navigatorSeries&&(k(a.series,this.navigatorSeries),x(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},getBaseSeriesMin:function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?
b.xData[0]:a)},a)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,b;a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,f=b.dataMax,b=b.max-b.min,g=a.stickToMin,h=a.stickToMax,k=d(this.options.overscroll,0),l,m,n=a.series&&a.series[0],q=!!this.setExtremes;this.eventArgs&&"rangeSelectorButton"===this.eventArgs.trigger||(g&&(m=c,
l=m+b),h&&(l=f+k,g||(m=Math.max(l-b,a.getBaseSeriesMin(n&&n.xData?n.xData[0]:-Number.MAX_VALUE)))),q&&(g||h)&&v(m)&&(this.min=this.userMin=m,this.max=this.userMax=l));a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=v(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);
b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(r(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,b.max)}),r(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":
"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))},destroy:function(){this.removeEvents();this.xAxis&&(k(this.chart.xAxis,this.xAxis),k(this.chart.axes,this.xAxis));this.yAxis&&(k(this.chart.yAxis,this.yAxis),k(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&
this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){u(a)},this)}};b.Navigator||(b.Navigator=q,r(B,"zoom",function(a){var b=this.chart.options,c=b.chart.zoomType,d=b.chart.pinchType,e=b.navigator,b=b.rangeSelector;this.isXAxis&&(e&&e.enabled||b&&b.enabled)&&("y"===c?a.zoomed=!1:(!m&&"xy"===c||m&&"xy"===d)&&this.options.range&&(c=this.previousZoom,x(a.newMin)?this.previousZoom=[this.min,this.max]:c&&(a.newMin=c[0],a.newMax=c[1],delete this.previousZoom)));void 0!==
a.zoomed&&a.preventDefault()}),r(g,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!m&&"x"===a.chart.zoomType||m&&"x"===a.chart.pinchType))return!1}),r(g,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new q(this)}),r(g,"afterSetChartSize",function(){var a=this.legend,b=this.navigator,c,f,g,h;b&&(f=a&&a.options,g=b.xAxis,h=b.yAxis,c=b.scrollbarHeight,this.inverted?
(b.left=b.opposite?this.chartWidth-c-b.height:this.spacing[3]+c,b.top=this.plotTop+c):(b.left=this.plotLeft+c,b.top=b.navigatorOptions.top||this.chartHeight-b.height-c-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(f&&"bottom"===f.verticalAlign&&f.enabled&&!f.floating?a.legendHeight+d(f.margin,10):0)),g&&h&&(this.inverted?g.options.left=h.options.left=b.left:g.options.top=h.options.top=b.top,g.setAxisSize(),h.setAxisSize()))}),r(g,"update",function(b){var c=
b.options.navigator||{},d=b.options.scrollbar||{};this.navigator||this.scroller||!c.enabled&&!d.enabled||(a(!0,this.options.navigator,c),a(!0,this.options.scrollbar,d),delete b.options.navigator,delete b.options.scrollbar)}),r(g,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new q(this),d(a.redraw,!0)&&this.redraw(a.animation))}),r(g,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,
!1)}),r(f,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),g.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}))});D(q,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map