/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Item series type for Highcharts

 (c) 2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/item-series",["highcharts"],function(b){a(b);a.Highcharts=b;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function b(a,h,b,D){a.hasOwnProperty(h)||(a[h]=D.apply(null,b))}a=a?a._modules:{};b(a,"modules/item-series.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,b){var h=b.isNumber,D=a.extend;b=a.merge;
var p=a.seriesTypes.pie.prototype.pointClass.prototype;a.seriesType("item","pie",{endAngle:void 0,innerSize:"40%",itemPadding:.1,layout:"vertical",marker:b(a.defaultOptions.plotOptions.line.marker,{radius:null}),rows:void 0,showInLegend:!0,startAngle:void 0},{translate:function(){this.slots||(this.slots=[]);h(this.options.startAngle)&&h(this.options.endAngle)?(a.seriesTypes.pie.prototype.translate.call(this),this.slots=this.getSlots()):this.generatePoints()},getSlots:function(){function c(a){0<B&&
(a.row.colCount--,B--)}for(var a=this.center,g=a[2],b=a[3],q,l=this.slots,r,x,t,u,v,C,d,k,n=0,e,h=this.endAngleRad-this.startAngleRad,w=Number.MAX_VALUE,y,f,z,A=this.options.rows,m=(g-b)/g;w>this.total;)for(y=w,w=l.length=0,f=z,z=[],n++,e=g/n/2,A?(b=(e-A)/e*g,0<=b?e=A:(b=0,m=1)):e=Math.floor(e*m),q=e;0<q;q--)t=(b+q/e*(g-b-n))/2,u=h*t,v=Math.ceil(u/n),z.push({rowRadius:t,rowLength:u,colCount:v}),w+=v+1;if(f){for(var B=y-this.total;0<B;)f.map(function(a){return{angle:a.colCount/a.rowLength,row:a}}).sort(function(a,
c){return c.angle-a.angle}).slice(0,Math.min(B,Math.ceil(f.length/2))).forEach(c);f.forEach(function(c){var b=c.rowRadius;C=(c=c.colCount)?h/c:0;for(k=0;k<=c;k+=1)d=this.startAngleRad+k*C,r=a[0]+Math.cos(d)*b,x=a[1]+Math.sin(d)*b,l.push({x:r,y:x,angle:d})},this);l.sort(function(a,c){return a.angle-c.angle});this.itemSize=n;return l}},getRows:function(){var a=this.options.rows,b,g;if(!a)if(g=this.chart.plotWidth/this.chart.plotHeight,a=Math.sqrt(this.total),1<g)for(a=Math.ceil(a);0<a;){b=this.total/
a;if(b/a>g)break;a--}else for(a=Math.floor(a);a<this.total;){b=this.total/a;if(b/a<g)break;a++}return a},drawPoints:function(){var b=this,h=this.options,g=b.chart.renderer,p=h.marker,q=this.borderWidth%2?.5:1,l=0,r=this.getRows(),x=Math.ceil(this.total/r),t=this.chart.plotWidth/x,u=this.chart.plotHeight/r,v=this.itemSize||Math.min(t,u);this.points.forEach(function(c){var d,k,n,e=c.marker||{},C=e.symbol||p.symbol,e=a.pick(e.radius,p.radius),w=a.defined(e)?2*e:v,y=w*h.itemPadding,f,z,A;c.graphics=k=
c.graphics||{};b.chart.styledMode||(n=b.pointAttribs(c,c.selected&&"select"));if(!c.isNull&&c.visible){c.graphic||(c.graphic=g.g("point").add(b.group));for(var m=0;m<c.y;m++)b.center&&b.slots?(f=b.slots.shift(),d=f.x-v/2,f=f.y-v/2):"horizontal"===h.layout?(d=l%x*t,f=u*Math.floor(l/x)):(d=t*Math.floor(l/r),f=l%r*u),d+=y,f+=y,A=z=Math.round(w-2*y),b.options.crisp&&(d=Math.round(d)-q,f=Math.round(f)+q),d={x:d,y:f,width:z,height:A},void 0!==e&&(d.r=e),k[m]?k[m].animate(d):k[m]=g.symbol(C,null,null,null,
null,{backgroundSize:"within"}).attr(D(d,n)).add(c.graphic),k[m].isActive=!0,l++}a.objectEach(k,function(a,b){a.isActive?a.isActive=!1:(a.destroy(),delete k[b])})})},drawDataLabels:function(){this.center&&this.slots?a.seriesTypes.pie.prototype.drawDataLabels.call(this):this.points.forEach(function(a){a.destroyElements({dataLabel:1})})},animate:function(a){a?this.group.attr({opacity:0}):(this.group.animate({opacity:1},this.options.animation),this.animate=null)}},{connectorShapes:p.connectorShapes,
getConnectorPath:p.getConnectorPath,setVisible:p.setVisible,getTranslate:p.getTranslate})});b(a,"masters/modules/item-series.src.js",[],function(){})});
//# sourceMappingURL=item-series.js.map