/*
 Highmaps JS v7.1.2-modified (2019-07-03)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(h){"object"===typeof module&&module.exports?(h["default"]=h,module.exports=h):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(B){h(B);h.Highcharts=B;return h}):h("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(h){function B(a,q,x,k){a.hasOwnProperty(q)||(a[q]=k.apply(null,x))}h=h?h._modules:{};B(h,"parts-map/MapAxis.js",[h["parts/Globals.js"]],function(a){var q=a.addEvent,x=a.Axis,k=a.pick;q(x,"getSeriesExtremes",function(){var a=
[];this.isXAxis&&(this.series.forEach(function(f,u){f.useMapGeometry&&(a[u]=f.xData,f.xData=[])}),this.seriesXData=a)});q(x,"afterGetSeriesExtremes",function(){var a=this.seriesXData,f,q,w;this.isXAxis&&(f=k(this.dataMin,Number.MAX_VALUE),q=k(this.dataMax,-Number.MAX_VALUE),this.series.forEach(function(d,c){d.useMapGeometry&&(f=Math.min(f,k(d.minX,f)),q=Math.max(q,k(d.maxX,q)),d.xData=a[c],w=!0)}),w&&(this.dataMin=f,this.dataMax=q),delete this.seriesXData)});q(x,"afterSetAxisTranslation",function(){var a=
this.chart,f;f=a.plotWidth/a.plotHeight;var a=a.xAxis[0],k;"yAxis"===this.coll&&void 0!==a.transA&&this.series.forEach(function(a){a.preserveAspectRatio&&(k=!0)});if(k&&(this.transA=a.transA=Math.min(this.transA,a.transA),f/=(a.max-a.min)/(this.max-this.min),f=1>f?this:a,a=(f.max-f.min)*f.transA,f.pixelPadding=f.len-a,f.minPixelPadding=f.pixelPadding/2,a=f.fixTo)){a=a[1]-f.toValue(a[0],!0);a*=f.transA;if(Math.abs(a)>f.minPixelPadding||f.min===f.dataMin&&f.max===f.dataMax)a=0;f.minPixelPadding-=a}});
q(x,"render",function(){this.fixTo=null})});B(h,"parts-map/ColorAxis.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(a,q){var x=q.isNumber;q=a.addEvent;var k=a.Axis,u=a.Chart,f=a.color,h,w=a.extend,d=a.Legend,c=a.LegendSymbolMixin,g=a.noop,y=a.merge,l=a.pick;h=a.ColorAxis=function(){this.init.apply(this,arguments)};w(h.prototype,k.prototype);w(h.prototype,{defaultColorAxisOptions:{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,
marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0},keepProps:["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"].concat(k.prototype.keepProps),init:function(b,e){var n="vertical"!==b.options.legend.layout,a;this.coll="colorAxis";a=this.buildOptions.call(b,this.defaultColorAxisOptions,e);k.prototype.init.call(this,b,a);e.dataClasses&&this.initDataClasses(e);
this.initStops();this.horiz=n;this.zoomEnabled=!1;this.defaultLegendLength=200},initDataClasses:function(b){var e=this.chart,n,a=0,m=e.options.chart.colorCount,p=this.options,c=b.dataClasses.length;this.dataClasses=n=[];this.legendItems=[];b.dataClasses.forEach(function(b,z){b=y(b);n.push(b);if(e.styledMode||!b.color)"category"===p.dataClassColor?(e.styledMode||(z=e.options.colors,m=z.length,b.color=z[a]),b.colorIndex=a,a++,a===m&&(a=0)):b.color=f(p.minColor).tweenTo(f(p.maxColor),2>c?.5:z/(c-1))})},
hasData:function(){return!(!this.tickPositions||!this.tickPositions.length)},setTickPositions:function(){if(!this.dataClasses)return k.prototype.setTickPositions.call(this)},initStops:function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(b){b.color=f(b[1])})},buildOptions:function(b,e){var n=this.options.legend,a="vertical"!==n.layout;return y(b,{side:a?2:1,reversed:!a},e,{opposite:!a,showEmpty:!1,title:null,visible:n.enabled})},
setOptions:function(b){k.prototype.setOptions.call(this,b);this.options.crosshair=this.options.marker},setAxisSize:function(){var b=this.legendSymbol,e=this.chart,n=e.options.legend||{},a,m;b?(this.left=n=b.attr("x"),this.top=a=b.attr("y"),this.width=m=b.attr("width"),this.height=b=b.attr("height"),this.right=e.chartWidth-n-m,this.bottom=e.chartHeight-a-b,this.len=this.horiz?m:b,this.pos=this.horiz?n:a):this.len=(this.horiz?n.symbolWidth:n.symbolHeight)||this.defaultLegendLength},normalizedValue:function(b){this.isLog&&
(b=this.val2lin(b));return 1-(this.max-b)/(this.max-this.min||1)},toColor:function(b,e){var a=this.stops,c,m,p=this.dataClasses,z,g;if(p)for(g=p.length;g--;){if(z=p[g],c=z.from,a=z.to,(void 0===c||b>=c)&&(void 0===a||b<=a)){m=z.color;e&&(e.dataClass=g,e.colorIndex=z.colorIndex);break}}else{b=this.normalizedValue(b);for(g=a.length;g--&&!(b>a[g][0]););c=a[g]||a[g+1];a=a[g+1]||c;b=1-(a[0]-b)/(a[0]-c[0]||1);m=c.color.tweenTo(a.color,b)}return m},getOffset:function(){var b=this.legendGroup,e=this.chart.axisOffset[this.side];
b&&(this.axisParent=b,k.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=e)},setLegendColor:function(){var b,e=this.reversed;b=e?1:0;e=e?0:1;b=this.horiz?[b,0,e,0]:[0,e,0,b];this.legendColor={linearGradient:{x1:b[0],y1:b[1],x2:b[2],y2:b[3]},stops:this.stops}},drawLegendSymbol:function(b,e){var a=b.padding,c=b.options,m=this.horiz,p=l(c.symbolWidth,m?this.defaultLegendLength:12),z=l(c.symbolHeight,m?12:this.defaultLegendLength),
g=l(c.labelPadding,m?16:30),c=l(c.itemDistance,10);this.setLegendColor();e.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,p,z).attr({zIndex:1}).add(e.legendGroup);this.legendItemWidth=p+a+(m?c:g);this.legendItemHeight=z+a+(m?g:0)},setState:function(b){this.series.forEach(function(e){e.setState(b)})},visible:!0,setVisible:g,getSeriesExtremes:function(){var b=this.series,e=b.length;this.dataMin=Infinity;for(this.dataMax=-Infinity;e--;)b[e].getExtremes(),void 0!==b[e].valueMin&&(this.dataMin=
Math.min(this.dataMin,b[e].valueMin),this.dataMax=Math.max(this.dataMax,b[e].valueMax))},drawCrosshair:function(b,e){var a=e&&e.plotX,c=e&&e.plotY,m,p=this.pos,z=this.len;e&&(m=this.toPixels(e[e.series.colorKey]),m<p?m=p-2:m>p+z&&(m=p+z+2),e.plotX=m,e.plotY=this.len-m,k.prototype.drawCrosshair.call(this,b,e),e.plotX=a,e.plotY=c,this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||
this.cross.attr({fill:this.crosshair.color})))},getPlotLinePath:function(b){var e=b.translatedValue;return x(e)?this.horiz?["M",e-4,this.top-6,"L",e+4,this.top-6,e,this.top,"Z"]:["M",this.left,e,"L",this.left-6,e+6,this.left-6,e-6,"Z"]:k.prototype.getPlotLinePath.apply(this,arguments)},update:function(b,e){var a=this.chart,c=a.legend,m=this.buildOptions.call(a,{},b);this.series.forEach(function(b){b.isDirtyData=!0});b.dataClasses&&c.allItems&&(c.allItems.forEach(function(b){b.isDataClass&&b.legendGroup&&
b.legendGroup.destroy()}),a.isDirtyLegend=!0);a.options[this.coll]=y(this.userOptions,m);k.prototype.update.call(this,m,e);this.legendItem&&(this.setLegendColor(),c.colorizeItem(this,!0))},remove:function(){this.legendItem&&this.chart.legend.destroyItem(this);k.prototype.remove.call(this)},getDataClassLegendSymbols:function(){var b=this,e=this.chart,n=this.legendItems,d=e.options.legend,m=d.valueDecimals,p=d.valueSuffix||"",z;n.length||this.dataClasses.forEach(function(d,t){var v=!0,f=d.from,r=d.to;
z="";void 0===f?z="\x3c ":void 0===r&&(z="\x3e ");void 0!==f&&(z+=a.numberFormat(f,m)+p);void 0!==f&&void 0!==r&&(z+=" - ");void 0!==r&&(z+=a.numberFormat(r,m)+p);n.push(w({chart:e,name:z,options:{},drawLegendSymbol:c.drawRectangle,visible:!0,setState:g,isDataClass:!0,setVisible:function(){v=this.visible=!v;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===t&&b.setVisible(v)})});e.legend.colorizeItem(this,v)}},d))});return n},name:""});["fill","stroke"].forEach(function(b){a.Fx.prototype[b+
"Setter"]=function(){this.elem.attr(b,f(this.start).tweenTo(f(this.end),this.pos),null,!0)}});q(u,"afterGetAxes",function(){var b=this.options.colorAxis;this.colorAxis=[];b&&new h(this,b)});q(d,"afterGetAllItems",function(b){var e=[],c=this.chart.colorAxis[0];c&&c.options&&c.options.showInLegend&&(c.options.dataClasses?e=c.getDataClassLegendSymbols():e.push(c),c.series.forEach(function(e){a.erase(b.allItems,e)}));for(c=e.length;c--;)b.allItems.unshift(e[c])});q(d,"afterColorizeItem",function(b){b.visible&&
b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})});q(d,"afterUpdate",function(b,e,a){this.chart.colorAxis[0]&&this.chart.colorAxis[0].update({},a)})});B(h,"parts-map/ColorSeriesMixin.js",[h["parts/Globals.js"]],function(a){var q=a.defined,h=a.noop,k=a.seriesTypes;a.colorPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setVisible:function(a){var f=this,u=a?"show":"hide";f.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(f[a])f[a][u]()})},
setState:function(u){a.Point.prototype.setState.call(this,u);this.graphic&&this.graphic.attr({zIndex:"hover"===u?1:0})}};a.colorSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],optionalAxis:"colorAxis",trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:h,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:k.column.prototype.pointAttribs,translateColors:function(){var a=this,f=this.options.nullColor,k=this.colorAxis,q=this.colorKey;this.data.forEach(function(d){var c=
d[q];if(c=d.options.color||(d.isNull?f:k&&void 0!==c?k.toColor(c,d):d.color||a.color))d.color=c})},colorAttribs:function(a){var f={};q(a.color)&&(f[this.colorProp||"fill"]=a.color);return f}}});B(h,"parts-map/MapNavigation.js",[h["parts/Globals.js"]],function(a){function q(a){a&&(a.preventDefault&&a.preventDefault(),a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)}function h(a){this.init(a)}var k=a.addEvent,u=a.Chart,f=a.doc,A=a.extend,w=a.merge,d=a.pick;h.prototype.init=function(a){this.chart=
a;a.mapNavButtons=[]};h.prototype.update=function(c){var g=this.chart,f=g.options.mapNavigation,l,b,e,n,r,m=function(b){this.handler.call(g,b);q(b)},p=g.mapNavButtons;c&&(f=g.options.mapNavigation=w(g.options.mapNavigation,c));for(;p.length;)p.pop().destroy();d(f.enableButtons,f.enabled)&&!g.renderer.forExport&&a.objectEach(f.buttons,function(a,c){l=w(f.buttonOptions,a);g.styledMode||(b=l.theme,b.style=w(l.theme.style,l.style),n=(e=b.states)&&e.hover,r=e&&e.select);a=g.renderer.button(l.text,0,0,
m,b,n,r,0,"zoomIn"===c?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[c]).attr({width:l.width,height:l.height,title:g.options.lang[c],padding:l.padding,zIndex:5}).add();a.handler=l.onclick;a.align(A(l,{width:a.width,height:2*a.height}),null,l.alignTo);k(a.element,"dblclick",q);p.push(a)});this.updateEvents(f)};h.prototype.updateEvents=function(a){var c=this.chart;d(a.enableDoubleClickZoom,a.enabled)||a.enableDoubleClickZoomTo?this.unbindDblClick=
this.unbindDblClick||k(c.container,"dblclick",function(a){c.pointer.onContainerDblClick(a)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());d(a.enableMouseWheelZoom,a.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||k(c.container,void 0===f.onmousewheel?"DOMMouseScroll":"mousewheel",function(a){c.pointer.onContainerMouseWheel(a);q(a);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};A(u.prototype,{fitToBox:function(a,g){[["x","width"],["y","height"]].forEach(function(c){var d=
c[0];c=c[1];a[d]+a[c]>g[d]+g[c]&&(a[c]>g[c]?(a[c]=g[c],a[d]=g[d]):a[d]=g[d]+g[c]-a[c]);a[c]>g[c]&&(a[c]=g[c]);a[d]<g[d]&&(a[d]=g[d])});return a},mapZoom:function(a,g,f,l,b){var e=this.xAxis[0],c=e.max-e.min,r=d(g,e.min+c/2),m=c*a,c=this.yAxis[0],p=c.max-c.min,z=d(f,c.min+p/2),p=p*a,r=this.fitToBox({x:r-m*(l?(l-e.pos)/e.len:.5),y:z-p*(b?(b-c.pos)/c.len:.5),width:m,height:p},{x:e.dataMin,y:c.dataMin,width:e.dataMax-e.dataMin,height:c.dataMax-c.dataMin}),m=r.x<=e.dataMin&&r.width>=e.dataMax-e.dataMin&&
r.y<=c.dataMin&&r.height>=c.dataMax-c.dataMin;l&&(e.fixTo=[l-e.pos,g]);b&&(c.fixTo=[b-c.pos,f]);void 0===a||m?(e.setExtremes(void 0,void 0,!1),c.setExtremes(void 0,void 0,!1)):(e.setExtremes(r.x,r.x+r.width,!1),c.setExtremes(r.y,r.y+r.height,!1));this.redraw()}});k(u,"beforeRender",function(){this.mapNavigation=new h(this);this.mapNavigation.update()});a.MapNavigation=h});B(h,"parts-map/MapPointer.js",[h["parts/Globals.js"]],function(a){var q=a.extend,h=a.pick,k=a.Pointer;a=a.wrap;q(k.prototype,{onContainerDblClick:function(a){var f=
this.chart;a=this.normalize(a);f.options.mapNavigation.enableDoubleClickZoomTo?f.pointer.inClass(a.target,"highcharts-tracker")&&f.hoverPoint&&f.hoverPoint.zoomTo():f.isInsidePlot(a.chartX-f.plotLeft,a.chartY-f.plotTop)&&f.mapZoom(.5,f.xAxis[0].toValue(a.chartX),f.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var f=this.chart,k;a=this.normalize(a);k=a.detail||-(a.wheelDelta/120);f.isInsidePlot(a.chartX-f.plotLeft,a.chartY-f.plotTop)&&f.mapZoom(Math.pow(f.options.mapNavigation.mouseWheelSensitivity,
k),f.xAxis[0].toValue(a.chartX),f.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)}});a(k.prototype,"zoomOption",function(a){var f=this.chart.options.mapNavigation;h(f.enableTouchZoom,f.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});a(k.prototype,"pinchTranslate",function(a,f,k,h,d,c,g){a.call(this,f,k,h,d,c,g);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=h.scaleX>h.scaleY,this.pinchTranslateDirection(!a,f,k,h,d,c,g,a?h.scaleX:h.scaleY))})});
B(h,"parts-map/MapSeries.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(a,h){var q=h.isArray,k=h.isNumber;h=a.colorPointMixin;var u=a.extend,f=a.merge,A=a.noop,w=a.pick,d=a.Point,c=a.Series,g=a.seriesType,y=a.seriesTypes,l=a.splat;g("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}\x3cbr/\x3e"},
turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},f(a.colorSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:A,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(a){a=c.prototype.setOptions.call(this,a);var b=a.joinBy;null===b&&(b="_i");b=this.joinBy=l(b);b[1]||(b[1]=b[0]);return a},getBox:function(b){var e=
Number.MAX_VALUE,c=-e,g=e,m=-e,p=e,z=e,d=this.xAxis,f=this.yAxis,h;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path&&(b.path=a.splitPath(b.path));var n=b.path||[],d=n.length,f=!1,v=-e,r=e,t=-e,l=e,C=b.properties;if(!b._foundBox){for(;d--;)k(n[d])&&(f?(v=Math.max(v,n[d]),r=Math.min(r,n[d])):(t=Math.max(t,n[d]),l=Math.min(l,n[d])),f=!f);b._midX=r+(v-r)*w(b.middleX,C&&C["hc-middle-x"],.5);b._midY=l+(t-l)*w(b.middleY,C&&C["hc-middle-y"],.5);b._maxX=v;b._minX=r;b._maxY=t;b._minY=l;b.labelrank=
w(b.labelrank,(v-r)*(t-l));b._foundBox=!0}c=Math.max(c,b._maxX);g=Math.min(g,b._minX);m=Math.max(m,b._maxY);p=Math.min(p,b._minY);z=Math.min(b._maxX-b._minX,b._maxY-b._minY,z);h=!0}});h&&(this.minY=Math.min(p,w(this.minY,e)),this.maxY=Math.max(m,w(this.maxY,-e)),this.minX=Math.min(g,w(this.minX,e)),this.maxX=Math.max(c,w(this.maxX,-e)),d&&void 0===d.options.minRange&&(d.minRange=Math.min(5*z,(this.maxX-this.minX)/5,d.minRange||e)),f&&void 0===f.options.minRange&&(f.minRange=Math.min(5*z,(this.maxY-
this.minY)/5,f.minRange||e)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){c.prototype.getExtremes.call(this,this.valueData);this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);this.valueMin=this.dataMin;this.valueMax=this.dataMax;this.dataMin=this.minY;this.dataMax=this.maxY},translatePath:function(a){var b=!1,c=this.xAxis,d=this.yAxis,m=c.min,p=c.transA,c=c.minPixelPadding,g=d.min,f=d.transA,d=d.minPixelPadding,t,l=[];if(a)for(t=a.length;t--;)k(a[t])?
(l[t]=b?(a[t]-m)*p+c:(a[t]-g)*f+d,b=!b):l[t]=a[t];return l},setData:function(b,e,d,g){var m=this.options,p=this.chart.options.chart,n=p&&p.map,v=m.mapData,t=this.joinBy,r=m.keys||this.pointArrayMap,l=[],h={},y=this.chart.mapTransforms;!v&&n&&(v="string"===typeof n?a.maps[n]:n);b&&b.forEach(function(c,e){var p=0;if(k(c))b[e]={value:c};else if(q(c)){b[e]={};!m.keys&&c.length>r.length&&"string"===typeof c[0]&&(b[e]["hc-key"]=c[0],++p);for(var d=0;d<r.length;++d,++p)r[d]&&void 0!==c[p]&&(0<r[d].indexOf(".")?
a.Point.prototype.setNestedProperty(b[e],c[p],r[d]):b[e][r[d]]=c[p])}t&&"_i"===t[0]&&(b[e]._i=e)});this.getBox(b);(this.chart.mapTransforms=y=p&&p.mapTransforms||v&&v["hc-transform"]||y)&&a.objectEach(y,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});if(v){"FeatureCollection"===v.type&&(this.mapTitle=v.title,v=a.geojson(v,this.type,this));this.mapData=v;this.mapMap={};for(y=0;y<v.length;y++)p=v[y],n=p.properties,p._i=y,t[0]&&n&&n[t[0]]&&(p[t[0]]=n[t[0]]),
h[p[t[0]]]=p;this.mapMap=h;b&&t[1]&&b.forEach(function(a){h[a[t[1]]]&&l.push(h[a[t[1]]])});m.allAreas?(this.getBox(v),b=b||[],t[1]&&b.forEach(function(a){l.push(a[t[1]])}),l="|"+l.map(function(a){return a&&a[t[0]]}).join("|")+"|",v.forEach(function(a){t[0]&&-1!==l.indexOf("|"+a[t[0]]+"|")||(b.push(f(a,{value:null})),g=!1)})):this.getBox(l)}c.prototype.setData.call(this,b,e,d,g)},drawGraph:A,drawDataLabels:A,doFullTranslate:function(){return this.isDirtyData||this.chart.isResizing||this.chart.renderer.isVML||
!this.baseTrans},translate:function(){var a=this,c=a.xAxis,d=a.yAxis,g=a.doFullTranslate();a.generatePoints();a.data.forEach(function(b){b.plotX=c.toPixels(b._midX,!0);b.plotY=d.toPixels(b._midY,!0);g&&(b.shapeType="path",b.shapeArgs={d:a.translatePath(b.path)})});a.translateColors()},pointAttribs:function(a,c){c=a.series.chart.styledMode?this.colorAttribs(a):y.column.prototype.pointAttribs.call(this,a,c);c["stroke-width"]=w(a.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||
"borderWidth"],"inherit");return c},drawPoints:function(){var a=this,c=a.xAxis,d=a.yAxis,g=a.group,m=a.chart,p=m.renderer,f,v,t,l,h=this.baseTrans,k,q,u,x,F;a.transformGroup||(a.transformGroup=p.g().attr({scaleX:1,scaleY:1}).add(g),a.transformGroup.survive=!0);a.doFullTranslate()?(m.hasRendered&&!m.styledMode&&a.points.forEach(function(b){b.shapeArgs&&(b.shapeArgs.fill=a.pointAttribs(b,b.state).fill)}),a.group=a.transformGroup,y.column.prototype.drawPoints.apply(a),a.group=g,a.points.forEach(function(b){if(b.graphic){var c=
"";b.name&&(c+="highcharts-name-"+b.name.replace(/ /g,"-").toLowerCase());b.properties&&b.properties["hc-key"]&&(c+=" highcharts-key-"+b.properties["hc-key"].toLowerCase());c&&b.graphic.addClass(c);m.styledMode&&b.graphic.css(a.pointAttribs(b,b.selected&&"select"))}}),this.baseTrans={originX:c.min-c.minPixelPadding/c.transA,originY:d.min-d.minPixelPadding/d.transA+(d.reversed?0:d.len/d.transA),transAX:c.transA,transAY:d.transA},this.transformGroup.animate({translateX:0,translateY:0,scaleX:1,scaleY:1})):
(f=c.transA/h.transAX,v=d.transA/h.transAY,t=c.toPixels(h.originX,!0),l=d.toPixels(h.originY,!0),.99<f&&1.01>f&&.99<v&&1.01>v&&(v=f=1,t=Math.round(t),l=Math.round(l)),k=this.transformGroup,m.renderer.globalAnimation?(q=k.attr("translateX"),u=k.attr("translateY"),x=k.attr("scaleX"),F=k.attr("scaleY"),k.attr({animator:0}).animate({animator:1},{step:function(a,b){k.attr({translateX:q+(t-q)*b.pos,translateY:u+(l-u)*b.pos,scaleX:x+(f-x)*b.pos,scaleY:F+(v-F)*b.pos})}})):k.attr({translateX:t,translateY:l,
scaleX:f,scaleY:v}));m.styledMode||g.element.setAttribute("stroke-width",w(a.options[a.pointAttrToOptions&&a.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(f||1));this.drawMapDataLabels()},drawMapDataLabels:function(){c.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var a=this,e=c.prototype.render;a.chart.renderer.isVML&&3E3<a.data.length?setTimeout(function(){e.call(a)}):e.call(a)},animate:function(a){var b=this.options.animation,
c=this.group,d=this.xAxis,m=this.yAxis,p=d.pos,g=m.pos;this.chart.renderer.isSVG&&(!0===b&&(b={duration:1E3}),a?c.attr({translateX:p+d.len/2,translateY:g+m.len/2,scaleX:.001,scaleY:.001}):(c.animate({translateX:p,translateY:g,scaleX:1,scaleY:1},b),this.animate=null))},animateDrilldown:function(a){var b=this.chart.plotBox,c=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],d=c.bBox,m=this.chart.options.drilldown.animation;a||(a=Math.min(d.width/b.width,d.height/b.height),c.shapeArgs=
{scaleX:a,scaleY:a,translateX:d.x,translateY:d.y},this.points.forEach(function(a){a.graphic&&a.graphic.attr(c.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},m)}),this.animate=null)},drawLegendSymbol:a.LegendSymbolMixin.drawRectangle,animateDrillupFrom:function(a){y.column.prototype.animateDrillupFrom.call(this,a)},animateDrillupTo:function(a){y.column.prototype.animateDrillupTo.call(this,a)}}),u({applyOptions:function(a,c){a=d.prototype.applyOptions.call(this,a,c);c=this.series;
var b=c.joinBy;c.mapData&&((b=void 0!==a[b[1]]&&c.mapMap[a[b[1]]])?(c.xyFromShape&&(a.x=b._midX,a.y=b._midY),u(a,b)):a.value=a.value||null);return a},onMouseOver:function(b){a.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)d.prototype.onMouseOver.call(this,b);else this.series.onMouseOut(b)},zoomTo:function(){var a=this.series;a.xAxis.setExtremes(this._minX,this._maxX,!1);a.yAxis.setExtremes(this._minY,this._maxY,!1);a.chart.redraw()}},h))});B(h,"parts-map/MapLineSeries.js",
[h["parts/Globals.js"]],function(a){var h=a.seriesType,x=a.seriesTypes;h("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,h){a=x.map.prototype.pointAttribs.call(this,a,h);a.fill=this.options.fillColor;return a},drawLegendSymbol:x.line.prototype.drawLegendSymbol})});B(h,"parts-map/MapPointSeries.js",[h["parts/Globals.js"]],function(a){var h=a.merge,x=a.Point;a=a.seriesType;a("mappoint",
"scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0},{applyOptions:function(a,q){a=void 0!==a.lat&&void 0!==a.lon?h(a,this.series.chart.fromLatLonToPoint(a)):a;return x.prototype.applyOptions.call(this,a,q)}})});B(h,"parts-more/BubbleLegend.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(a,h){var q=h.isNumber;h=a.Series;var k=a.Legend,u=a.Chart,f=a.addEvent,A=a.wrap,w=a.color,
d=a.numberFormat,c=a.objectEach,g=a.merge,y=a.noop,l=a.pick,b=a.stableSort,e=a.setOptions,n=a.arrayMin,r=a.arrayMax;e({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,
color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});a.BubbleLegend=function(a,b){this.init(a,b)};a.BubbleLegend.prototype={init:function(a,b){this.options=a;this.visible=!0;this.chart=b.chart;this.legend=b},setState:y,addToLegend:function(a){a.splice(this.options.legendIndex,0,this)},drawLegendSymbol:function(a){var c=this.chart,e=this.options,m=l(a.options.itemDistance,20),d,g=e.ranges;d=e.connectorDistance;this.fontMetrics=c.renderer.fontMetrics(e.labels.style.fontSize.toString()+
"px");g&&g.length&&q(g[0].value)?(b(g,function(a,b){return b.value-a.value}),this.ranges=g,this.setOptions(),this.render(),c=this.getMaxLabelSize(),g=this.ranges[0].radius,a=2*g,d=d-g+c.width,d=0<d?d:0,this.maxLabel=c,this.movementX="left"===e.labels.align?d:0,this.legendItemWidth=a+d+m,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0},setOptions:function(){var a=this.ranges,b=this.options,c=this.chart.series[b.seriesIndex],e=this.legend.baseline,d={"z-index":b.zIndex,
"stroke-width":b.borderWidth},f={"z-index":b.zIndex,"stroke-width":b.connectorWidth},n=this.getLabelStyles(),h=c.options.marker.fillOpacity,r=this.chart.styledMode;a.forEach(function(m,p){r||(d.stroke=l(m.borderColor,b.borderColor,c.color),d.fill=l(m.color,b.color,1!==h?w(c.color).setOpacity(h).get("rgba"):c.color),f.stroke=l(m.connectorColor,b.connectorColor,c.color));a[p].radius=this.getRangeRadius(m.value);a[p]=g(a[p],{center:a[0].radius-a[p].radius+e});r||g(!0,a[p],{bubbleStyle:g(!1,d),connectorStyle:g(!1,
f),labelStyle:n})},this)},getLabelStyles:function(){var a=this.options,b={},e="left"===a.labels.align,d=this.legend.options.rtl;c(a.labels.style,function(a,c){"color"!==c&&"fontSize"!==c&&"z-index"!==c&&(b[c]=a)});return g(!1,b,{"font-size":a.labels.style.fontSize,fill:l(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:d||e?"right":"left"})},getRangeRadius:function(a){var b=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,b.ranges[b.ranges.length-1].value,
b.ranges[0].value,b.minSize,b.maxSize,a)},render:function(){var a=this.chart.renderer,b=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=b&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()},
renderRange:function(a){var b=this.options,c=b.labels,e=this.chart.renderer,d=this.symbols,m=d.labels,g=a.center,f=Math.abs(a.radius),n=b.connectorDistance,h=c.align,l=c.style.fontSize,n=this.legend.options.rtl||"left"===h?-n:n,c=b.connectorWidth,r=this.ranges[0].radius,y=g-f-b.borderWidth/2+c/2,k,l=l/2-(this.fontMetrics.h-l)/2,q=e.styledMode;"center"===h&&(n=0,b.connectorDistance=0,a.labelStyle.align="center");h=y+b.labels.y;k=r+n+b.labels.x;d.bubbleItems.push(e.circle(r,g+((y%1?1:.5)-(c%2?0:.5)),
f).attr(q?{}:a.bubbleStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(b.className||"")).add(this.legendSymbol));d.connectors.push(e.path(e.crispLine(["M",r,y,"L",r+n,y],b.connectorWidth)).attr(q?{}:a.connectorStyle).addClass((q?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(b.connectorClassName||"")).add(this.legendSymbol));a=e.text(this.formatLabel(a),k,h+l).attr(q?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+
(b.labels.className||"")).add(this.legendSymbol);m.push(a);a.placed=!0;a.alignAttr={x:k,y:h+l}},getMaxLabelSize:function(){var a,b;this.symbols.labels.forEach(function(c){b=c.getBBox(!0);a=a?b.width>a.width?b:a:b});return a||{}},formatLabel:function(b){var c=this.options,e=c.labels.formatter;return(c=c.labels.format)?a.format(c,b):e?e.call(b):d(b.value,1)},hideOverlappingLabels:function(){var a=this.chart,b=this.symbols;!this.options.labels.allowOverlap&&b&&(a.hideOverlappingLabels(b.labels),b.labels.forEach(function(a,
c){a.newOpacity?a.newOpacity!==a.oldOpacity&&b.connectors[c].show():b.connectors[c].hide()}))},getRanges:function(){var a=this.legend.bubbleLegend,b,c=a.options.ranges,e,d=Number.MAX_VALUE,f=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(e=a.zData.filter(q),e.length&&(d=l(a.options.zMin,Math.min(d,Math.max(n(e),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),f=l(a.options.zMax,Math.max(f,r(e)))))});b=d===f?[{value:f}]:[{value:d},{value:(d+
f)/2},{value:f,autoRanges:!0}];c.length&&c[0].radius&&b.reverse();b.forEach(function(a,e){c&&c[e]&&(b[e]=g(!1,c[e],a))});return b},predictBubbleSizes:function(){var a=this.chart,b=this.fontMetrics,c=a.legend.options,e="horizontal"===c.layout,d=e?a.legend.lastLineHeight:0,g=a.plotSizeX,f=a.plotSizeY,n=a.series[this.options.seriesIndex],a=Math.ceil(n.minPxSize),h=Math.ceil(n.maxPxSize),n=n.options.maxSize,l=Math.min(f,g);if(c.floating||!/%$/.test(n))b=h;else if(n=parseFloat(n),b=(l+d-b.h/2)*n/100/(n/
100+1),e&&f-b>=g||!e&&g-b>=f)b=h;return[a,Math.ceil(b)]},updateRanges:function(a,b){var c=this.legend.options.bubbleLegend;c.minSize=a;c.maxSize=b;c.ranges=this.getRanges()},correctSizes:function(){var a=this.legend,b=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(b.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,b.maxPxSize),a.render())}};f(a.Legend,"afterGetAllItems",function(b){var c=this.bubbleLegend,e=this.options,d=e.bubbleLegend,g=this.chart.getVisibleBubbleSeriesIndex();
c&&c.ranges&&c.ranges.length&&(d.ranges.length&&(d.autoRanges=!!d.ranges[0].autoRanges),this.destroyItem(c));0<=g&&e.enabled&&d.enabled&&(d.seriesIndex=g,this.bubbleLegend=new a.BubbleLegend(d,this),this.bubbleLegend.addToLegend(b.allItems))});u.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1};k.prototype.getLinesHeights=function(){var a=this.allItems,b=[],c,e=a.length,d,g=0;for(d=
0;d<e;d++)if(a[d].legendItemHeight&&(a[d].itemHeight=a[d].legendItemHeight),a[d]===a[e-1]||a[d+1]&&a[d]._legendItemPos[1]!==a[d+1]._legendItemPos[1]){b.push({height:0});c=b[b.length-1];for(g;g<=d;g++)a[g].itemHeight>c.height&&(c.height=a[g].itemHeight);c.step=d}return b};k.prototype.retranslateItems=function(a){var b,c,e,d=this.options.rtl,g=0;this.allItems.forEach(function(f,n){b=f.legendGroup.translateX;c=f._legendItemPos[1];if((e=f.movementX)||d&&f.ranges)e=d?b-f.options.maxSize/2:b+e,f.legendGroup.attr({translateX:e});
n>a[g].step&&g++;f.legendGroup.attr({translateY:Math.round(c+a[g].height/2)});f._legendItemPos[1]=c+a[g].height/2})};f(h,"legendItemClick",function(){var a=this.chart,b=this.visible,c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),c.bubbleLegend.visible!==a&&(c.update({bubbleLegend:{enabled:a}}),c.bubbleLegend.visible=a),this.visible=b)});A(u.prototype,"drawChartBox",function(a,b,e){var d=this.legend,g=0<=this.getVisibleBubbleSeriesIndex(),
f;d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&g?(f=d.bubbleLegend.options,g=d.bubbleLegend.predictBubbleSizes(),d.bubbleLegend.updateRanges(g[0],g[1]),f.placed||(d.group.placed=!1,d.allItems.forEach(function(a){a.legendGroup.translateY=null})),d.render(),this.getMargins(),this.axes.forEach(function(a){a.render();f.placed||(a.setScale(),a.updateNames(),c(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))}),f.placed=!0,this.getMargins(),a.call(this,b,e),d.bubbleLegend.correctSizes(),
d.retranslateItems(d.getLinesHeights())):(a.call(this,b,e),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),d.retranslateItems(d.getLinesHeights())))})});B(h,"parts-more/BubbleSeries.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(a,h){var q=h.isNumber,k=h.pInt,u=a.arrayMax,f=a.arrayMin;h=a.Axis;var A=a.color,w=a.noop,d=a.pick,c=a.Point,g=a.Series,y=a.seriesType,l=a.seriesTypes;y("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},
animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,
c){var b=this.options.marker.fillOpacity;a=g.prototype.pointAttribs.call(this,a,c);1!==b&&(a.fill=A(a.fill).setOpacity(b).get("rgba"));return a},getRadii:function(a,c,d){var b,e=this.zData,g=d.minPxSize,f=d.maxPxSize,n=[],h;b=0;for(d=e.length;b<d;b++)h=e[b],n.push(this.getRadius(a,c,g,f,h));this.radii=n},getRadius:function(a,c,d,g,f){var b=this.options,e="width"!==b.sizeBy,n=b.zThreshold,h=c-a;b.sizeByAbsoluteValue&&null!==f&&(f=Math.abs(f-n),h=Math.max(c-n,Math.abs(a-n)),a=0);q(f)?f<a?d=d/2-1:(a=
0<h?(f-a)/h:.5,e&&0<=a&&(a=Math.sqrt(a)),d=Math.ceil(d+a*(g-d))/2):d=null;return d},animate:function(a){!a&&this.points.length<this.options.animationLimit&&(this.points.forEach(function(a){var b=a.graphic,c;b&&b.width&&(c={x:b.x,y:b.y,width:b.width,height:b.height},b.attr({x:a.plotX,y:a.plotY,width:1,height:1}),b.animate(c,this.options.animation))},this),this.animate=null)},hasData:function(){return!!this.processedXData.length},translate:function(){var b,c=this.data,d,g,f=this.radii;l.scatter.prototype.translate.call(this);
for(b=c.length;b--;)d=c[b],g=f?f[b]:0,q(g)&&g>=this.minPxSize/2?(d.marker=a.extend(d.marker,{radius:g,width:2*g,height:2*g}),d.dlBox={x:d.plotX-g,y:d.plotY-g,width:2*g,height:2*g}):d.shapeArgs=d.plotY=d.dlBox=void 0},alignDataLabel:l.column.prototype.alignDataLabel,buildKDTree:w,applyZones:w},{haloPath:function(a){return c.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});h.prototype.beforePadding=function(){var a=this,c=this.len,g=this.chart,h=0,l=c,y=this.isXAxis,
z=y?"xData":"yData",v=this.min,t={},w=Math.min(g.plotWidth,g.plotHeight),x=Number.MAX_VALUE,A=-Number.MAX_VALUE,B=this.max-v,D=c/B,E=[];this.series.forEach(function(b){var c=b.options;!b.bubblePadding||!b.visible&&g.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,E.push(b),y&&(["minSize","maxSize"].forEach(function(a){var b=c[a],d=/%$/.test(b),b=k(b);t[a]=d?w*b/100:b}),b.minPxSize=t.minSize,b.maxPxSize=Math.max(t.maxSize,t.minSize),b=b.zData.filter(q),b.length&&(x=d(c.zMin,Math.min(x,Math.max(f(b),
!1===c.displayNegative?c.zThreshold:-Number.MAX_VALUE))),A=d(c.zMax,Math.max(A,u(b))))))});E.forEach(function(b){var c=b[z],d=c.length,e;y&&b.getRadii(x,A,b);if(0<B)for(;d--;)q(c[d])&&a.dataMin<=c[d]&&c[d]<=a.dataMax&&(e=b.radii[d],h=Math.min((c[d]-v)*D-e,h),l=Math.max((c[d]-v)*D+e,l))});E.length&&0<B&&!this.isLog&&(l-=c,D*=(c+Math.max(0,h)-Math.min(l,c))/c,[["min","userMin",h],["max","userMax",l]].forEach(function(b){void 0===d(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/D)}))}});B(h,"parts-map/MapBubbleSeries.js",
[h["parts/Globals.js"]],function(a){var h=a.merge,x=a.Point,k=a.seriesType,u=a.seriesTypes;u.bubble&&k("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:u.map.prototype.getMapData,getBox:u.map.prototype.getBox,setData:u.map.prototype.setData,setOptions:u.map.prototype.setOptions},{applyOptions:function(a,k){return a&&void 0!==a.lat&&void 0!==a.lon?x.prototype.applyOptions.call(this,h(a,this.series.chart.fromLatLonToPoint(a)),
k):u.map.prototype.pointClass.prototype.applyOptions.call(this,a,k)},isValid:function(){return"number"===typeof this.z},ttBelow:!1})});B(h,"parts-map/HeatmapSeries.js",[h["parts/Globals.js"]],function(a){var h=a.colorPointMixin,x=a.merge,k=a.noop,u=a.pick,f=a.Series,A=a.seriesType,w=a.seriesTypes;A("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:null,
pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}\x3cbr/\x3e"},states:{hover:{halo:!1,brightness:.2}}},x(a.colorSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){var a;w.scatter.prototype.init.apply(this,arguments);a=this.options;a.pointRange=u(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1},translate:function(){var a=this.options,c=this.xAxis,g=this.yAxis,f=a.pointPadding||0,h=function(a,
b,c){return Math.min(Math.max(b,a),c)},b=this.pointPlacementToXValue();this.generatePoints();this.points.forEach(function(d){var e=(a.colsize||1)/2,l=(a.rowsize||1)/2,m=h(Math.round(c.len-c.translate(d.x-e,0,1,0,1,-b)),-c.len,2*c.len),e=h(Math.round(c.len-c.translate(d.x+e,0,1,0,1,-b)),-c.len,2*c.len),y=h(Math.round(g.translate(d.y-l,0,1,0,1)),-g.len,2*g.len),l=h(Math.round(g.translate(d.y+l,0,1,0,1)),-g.len,2*g.len),k=u(d.pointPadding,f);d.plotX=d.clientX=(m+e)/2;d.plotY=(y+l)/2;d.shapeType="rect";
d.shapeArgs={x:Math.min(m,e)+k,y:Math.min(y,l)+k,width:Math.max(Math.abs(e-m)-2*k,0),height:Math.max(Math.abs(l-y)-2*k,0)}});this.translateColors()},drawPoints:function(){var a=this.chart.styledMode?"css":"animate";w.column.prototype.drawPoints.call(this);this.points.forEach(function(c){c.graphic[a](this.colorAttribs(c))},this)},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,c){return f.prototype.getValidPoints.call(this,a,c,!0)},animate:k,getBox:k,drawLegendSymbol:a.LegendSymbolMixin.drawRectangle,
alignDataLabel:w.column.prototype.alignDataLabel,getExtremes:function(){f.prototype.getExtremes.call(this,this.valueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;f.prototype.getExtremes.call(this)}}),a.extend({haloPath:function(a){if(!a)return[];var c=this.shapeArgs;return["M",c.x-a,c.y-a,"L",c.x-a,c.y+c.height+a,c.x+c.width+a,c.y+c.height+a,c.x+c.width+a,c.y-a,"Z"]}},h))});B(h,"parts-map/GeoJSON.js",[h["parts/Globals.js"]],function(a){function h(a,c){var d,f,h,b=!1,e=a.x,n=a.y;a=0;
for(d=c.length-1;a<c.length;d=a++)f=c[a][1]>n,h=c[d][1]>n,f!==h&&e<(c[d][0]-c[a][0])*(n-c[a][1])/(c[d][1]-c[a][1])+c[a][0]&&(b=!b);return b}var x=a.Chart,k=a.extend,u=a.format,f=a.merge,A=a.win,w=a.wrap;x.prototype.transformFromLatLon=function(d,c){if(void 0===A.proj4)return a.error(21,!1,this),{x:0,y:null};d=A.proj4(c.crs,[d.lon,d.lat]);var g=c.cosAngle||c.rotation&&Math.cos(c.rotation),f=c.sinAngle||c.rotation&&Math.sin(c.rotation);d=c.rotation?[d[0]*g+d[1]*f,-d[0]*f+d[1]*g]:d;return{x:((d[0]-(c.xoffset||
0))*(c.scale||1)+(c.xpan||0))*(c.jsonres||1)+(c.jsonmarginX||0),y:(((c.yoffset||0)-d[1])*(c.scale||1)+(c.ypan||0))*(c.jsonres||1)-(c.jsonmarginY||0)}};x.prototype.transformToLatLon=function(d,c){if(void 0===A.proj4)a.error(21,!1,this);else{d={x:((d.x-(c.jsonmarginX||0))/(c.jsonres||1)-(c.xpan||0))/(c.scale||1)+(c.xoffset||0),y:((-d.y-(c.jsonmarginY||0))/(c.jsonres||1)+(c.ypan||0))/(c.scale||1)+(c.yoffset||0)};var g=c.cosAngle||c.rotation&&Math.cos(c.rotation),f=c.sinAngle||c.rotation&&Math.sin(c.rotation);
c=A.proj4(c.crs,"WGS84",c.rotation?{x:d.x*g+d.y*-f,y:d.x*f+d.y*g}:d);return{lat:c.y,lon:c.x}}};x.prototype.fromPointToLatLon=function(d){var c=this.mapTransforms,g;if(c){for(g in c)if(c.hasOwnProperty(g)&&c[g].hitZone&&h({x:d.x,y:-d.y},c[g].hitZone.coordinates[0]))return this.transformToLatLon(d,c[g]);return this.transformToLatLon(d,c["default"])}a.error(22,!1,this)};x.prototype.fromLatLonToPoint=function(d){var c=this.mapTransforms,g,f;if(!c)return a.error(22,!1,this),{x:0,y:null};for(g in c)if(c.hasOwnProperty(g)&&
c[g].hitZone&&(f=this.transformFromLatLon(d,c[g]),h({x:f.x,y:-f.y},c[g].hitZone.coordinates[0])))return f;return this.transformFromLatLon(d,c["default"])};a.geojson=function(a,c,g){var d=[],f=[],b=function(a){var b,c=a.length;f.push("M");for(b=0;b<c;b++)1===b&&f.push("L"),f.push(a[b][0],-a[b][1])};c=c||"map";a.features.forEach(function(a){var e=a.geometry,g=e.type,e=e.coordinates;a=a.properties;var h;f=[];"map"===c||"mapbubble"===c?("Polygon"===g?(e.forEach(b),f.push("Z")):"MultiPolygon"===g&&(e.forEach(function(a){a.forEach(b)}),
f.push("Z")),f.length&&(h={path:f})):"mapline"===c?("LineString"===g?b(e):"MultiLineString"===g&&e.forEach(b),f.length&&(h={path:f})):"mappoint"===c&&"Point"===g&&(h={x:e[0],y:-e[1]});h&&d.push(k(h,{name:a.name||a.NAME,properties:a}))});g&&a.copyrightShort&&(g.chart.mapCredits=u(g.chart.options.credits.mapText,{geojson:a}),g.chart.mapCreditsFull=u(g.chart.options.credits.mapTextFull,{geojson:a}));return d};w(x.prototype,"addCredits",function(a,c){c=f(!0,this.options.credits,c);this.mapCredits&&(c.href=
null);a.call(this,c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});B(h,"parts-map/Map.js",[h["parts/Globals.js"]],function(a){function h(a,c,d,b,e,f,h,m){return["M",a+e,c,"L",a+d-f,c,"C",a+d-f/2,c,a+d,c+f/2,a+d,c+f,"L",a+d,c+b-h,"C",a+d,c+b-h/2,a+d-h/2,c+b,a+d-h,c+b,"L",a+m,c+b,"C",a+m/2,c+b,a,c+b-m/2,a,c+b-m,"L",a,c+e,"C",a,c+e/2,a+e/2,c,a+e,c,"Z"]}var x=a.Chart,k=a.defaultOptions,u=a.extend,f=a.merge,A=a.pick,w=a.Renderer,d=a.SVGRenderer,c=a.VMLRenderer;u(k.lang,
{zoomIn:"Zoom in",zoomOut:"Zoom out"});k.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};a.splitPath=function(a){var c;a=a.replace(/([A-Za-z])/g," $1 ");a=a.replace(/^\s*/,"").replace(/\s*$/,
"");a=a.split(/[ ,]+/);for(c=0;c<a.length;c++)/[a-zA-Z]/.test(a[c])||(a[c]=parseFloat(a[c]));return a};a.maps={};d.prototype.symbols.topbutton=function(a,c,d,b,e){return h(a-1,c-1,d,b,e.r,e.r,0,0)};d.prototype.symbols.bottombutton=function(a,c,d,b,e){return h(a-1,c-1,d,b,0,0,e.r,e.r)};w===c&&["topbutton","bottombutton"].forEach(function(a){c.prototype.symbols[a]=d.prototype.symbols[a]});a.Map=a.mapChart=function(c,d,h){var b="string"===typeof c||c.nodeName,e=arguments[b?1:0],g=e,k={endOnTick:!1,visible:!1,
minPadding:0,maxPadding:0,startOnTick:!1},m,l=a.getOptions().credits;m=e.series;e.series=null;e=f({chart:{panning:"xy",type:"map"},credits:{mapText:A(l.mapText,' \u00a9 \x3ca href\x3d"{geojson.copyrightUrl}"\x3e{geojson.copyrightShort}\x3c/a\x3e'),mapTextFull:A(l.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:k,yAxis:f(k,{reversed:!0})},e,{chart:{inverted:!1,alignTicks:!1}});e.series=g.series=m;return b?new x(c,e,h):new x(e,d)}});B(h,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map