/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Sankey diagram module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/sankey",["highcharts"],function(w){c(w);c.Highcharts=w;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function w(d,c,v,n){d.hasOwnProperty(c)||(d[c]=n.apply(null,v))}c=c?c._modules:{};w(c,"mixins/nodes.js",[c["parts/Globals.js"]],function(d){var c=d.pick,v=d.defined,n=d.Point;d.NodesMixin={createNode:function(g){function h(b,
f){return d.find(b,function(b){return b.id===f})}var a=h(this.nodes,g),p=this.pointClass,r;a||(r=this.options.nodes&&h(this.options.nodes,g),a=(new p).init(this,d.extend({className:"highcharts-node",isNode:!0,id:g,y:1},r)),a.linksTo=[],a.linksFrom=[],a.formatPrefix="node",a.name=a.name||a.options.id,a.mass=c(a.options.mass,a.options.marker&&a.options.marker.radius,this.options.marker&&this.options.marker.radius,4),a.getSum=function(){var b=0,f=0;a.linksTo.forEach(function(e){b+=e.weight});a.linksFrom.forEach(function(b){f+=
b.weight});return Math.max(b,f)},a.offset=function(b,f){for(var e=0,t=0;t<a[f].length;t++){if(a[f][t]===b)return e;e+=a[f][t].weight}},a.hasShape=function(){var b=0;a.linksTo.forEach(function(f){f.outgoing&&b++});return!a.linksTo.length||b!==a.linksTo.length},this.nodes.push(a));return a},generatePoints:function(){var g={},h=this.chart;d.Series.prototype.generatePoints.call(this);this.nodes||(this.nodes=[]);this.colorCounter=0;this.nodes.forEach(function(a){a.linksFrom.length=0;a.linksTo.length=0;
a.level=void 0});this.points.forEach(function(a){v(a.from)&&(g[a.from]||(g[a.from]=this.createNode(a.from)),g[a.from].linksFrom.push(a),a.fromNode=g[a.from],h.styledMode?a.colorIndex=c(a.options.colorIndex,g[a.from].colorIndex):a.color=a.options.color||g[a.from].color);v(a.to)&&(g[a.to]||(g[a.to]=this.createNode(a.to)),g[a.to].linksTo.push(a),a.toNode=g[a.to]);a.name=a.name||a.id},this);this.nodeLookup=g},setData:function(){this.nodes&&(this.nodes.forEach(function(d){d.destroy()}),this.nodes.length=
0);d.Series.prototype.setData.apply(this,arguments)},destroy:function(){this.data=[].concat(this.points||[],this.nodes);return d.Series.prototype.destroy.apply(this,arguments)},setNodeState:function(d){var c=arguments,a=this.isNode?this.linksTo.concat(this.linksFrom):[this.fromNode,this.toNode];"select"!==d&&a.forEach(function(a){a.series&&(n.prototype.setState.apply(a,c),a.isNode||(a.fromNode.graphic&&n.prototype.setState.apply(a.fromNode,c),a.toNode.graphic&&n.prototype.setState.apply(a.toNode,
c)))});n.prototype.setState.apply(this,c)}}});w(c,"mixins/tree-series.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(d,c){var v=c.isArray,n=c.isNumber,g=d.extend,h=d.isObject,a=d.merge,p=d.pick;return{getColor:function(a,b){var f=b.index,e=b.mapOptionsToLevel,t=b.parentColor,q=b.parentColorIndex,k=b.series,m=b.colors,l=b.siblings,x=k.points,c=k.chart.options.chart,g,r,u,h;if(a){x=x[a.i];a=e[a.level]||{};if(e=x&&a.colorByPoint)r=x.index%(m?m.length:c.colorCount),g=m&&m[r];if(!k.chart.styledMode){m=
x&&x.options.color;c=a&&a.color;if(u=t)u=(u=a&&a.colorVariation)&&"brightness"===u.key?d.color(t).brighten(f/l*u.to).get():t;u=p(m,c,g,u,k.color)}h=p(x&&x.options.colorIndex,a&&a.colorIndex,r,q,b.colorIndex)}return{color:u,colorIndex:h}},getLevelOptions:function(d){var b=null,f,e,t,q;if(h(d))for(b={},t=n(d.from)?d.from:1,q=d.levels,e={},f=h(d.defaults)?d.defaults:{},v(q)&&(e=q.reduce(function(b,e){var q,d;h(e)&&n(e.level)&&(d=a({},e),q="boolean"===typeof d.levelIsConstant?d.levelIsConstant:f.levelIsConstant,
delete d.levelIsConstant,delete d.level,e=e.level+(q?0:t-1),h(b[e])?g(b[e],d):b[e]=d);return b},{})),q=n(d.to)?d.to:1,d=0;d<=q;d++)b[d]=a({},f,h(e[d])?e[d]:{});return b},setTreeValues:function b(f,e){var a=e.before,d=e.idRoot,k=e.mapIdToNode[d],m=e.points[f.i],l=m&&m.options||{},c=0,h=[];g(f,{levelDynamic:f.level-(("boolean"===typeof e.levelIsConstant?e.levelIsConstant:1)?0:k.level),name:p(m&&m.name,""),visible:d===f.id||("boolean"===typeof e.visible?e.visible:!1)});"function"===typeof a&&(f=a(f,
e));f.children.forEach(function(a,d){var q=g({},e);g(q,{index:d,siblings:f.children.length,visible:f.visible});a=b(a,q);h.push(a);a.visible&&(c+=a.val)});f.visible=0<c||f.visible;a=p(l.value,c);g(f,{children:h,childrenTotal:c,isLeaf:f.visible&&!c,val:a});return f},updateRootId:function(b){var a;h(b)&&(a=h(b.options)?b.options:{},a=p(b.rootNode,a.rootId,""),h(b.userOptions)&&(b.userOptions.rootId=a),b.rootNode=a);return a}}});w(c,"modules/sankey.src.js",[c["parts/Globals.js"],c["mixins/tree-series.js"]],
function(d,c){var v=c.getLevelOptions,n=d.defined,g=d.find,h=d.isObject,a=d.merge;c=d.seriesType;var p=d.pick,r=d.Point;c("sankey","column",{borderWidth:0,colorByPoint:!0,curveFactor:.33,dataLabels:{enabled:!0,backgroundColor:"none",crop:!1,nodeFormat:void 0,nodeFormatter:function(){return this.point.name},format:void 0,formatter:function(){},inside:!0},inactiveOtherPoints:!0,linkOpacity:.5,nodeWidth:20,nodePadding:10,showInLegend:!1,states:{hover:{linkOpacity:1},inactive:{linkOpacity:.1,opacity:.1,
animation:{duration:50}}},tooltip:{followPointer:!0,headerFormat:'\x3cspan style\x3d"font-size: 10px"\x3e{series.name}\x3c/span\x3e\x3cbr/\x3e',pointFormat:"{point.fromNode.name} \u2192 {point.toNode.name}: \x3cb\x3e{point.weight}\x3c/b\x3e\x3cbr/\x3e",nodeFormat:"{point.name}: \x3cb\x3e{point.sum}\x3c/b\x3e\x3cbr/\x3e"}},{isCartesian:!1,invertable:!0,forceDL:!0,orderNodes:!0,pointArrayMap:["from","to"],createNode:d.NodesMixin.createNode,setData:d.NodesMixin.setData,destroy:d.NodesMixin.destroy,getNodePadding:function(){return this.options.nodePadding},
createNodeColumn:function(){var b=this.chart,a=[],e=this.getNodePadding();a.sum=function(){return this.reduce(function(a,b){return a+b.getSum()},0)};a.offset=function(b,f){for(var q=0,t,l=0;l<a.length;l++){t=a[l].getSum()*f+e;if(a[l]===b)return{relativeTop:q+d.relativeLength(b.options.offset||0,t)};q+=t}};a.top=function(a){var f=this.reduce(function(b,f){0<b&&(b+=e);return b+=f.getSum()*a},0);return(b.plotSizeY-f)/2};return a},createNodeColumns:function(){var b=[];this.nodes.forEach(function(a){var e=
-1,f,c,m;if(!d.defined(a.options.column))if(0===a.linksTo.length)a.column=0;else{for(c=0;c<a.linksTo.length;c++)m=a.linksTo[0],m.fromNode.column>e&&(f=m.fromNode,e=f.column);a.column=e+1;"hanging"===f.options.layout&&(a.hangsFrom=f,c=-1,g(f.linksFrom,function(b,e){(b=b.toNode===a)&&(c=e);return b}),a.column+=c)}b[a.column]||(b[a.column]=this.createNodeColumn());b[a.column].push(a)},this);for(var a=0;a<b.length;a++)void 0===b[a]&&(b[a]=this.createNodeColumn());return b},hasData:function(){return!!this.processedXData.length},
pointAttribs:function(a,f){var b=this.mapOptionsToLevel[(a.isNode?a.level:a.fromNode.level)||0]||{},c=a.options,q=b.states&&b.states[f]||{};f=["colorByPoint","borderColor","borderWidth","linkOpacity"].reduce(function(a,e){a[e]=p(q[e],c[e],b[e]);return a},{});var k=p(q.color,c.color,f.colorByPoint?a.color:b.color);return a.isNode?{fill:k,stroke:f.borderColor,"stroke-width":f.borderWidth}:{fill:d.color(k).setOpacity(f.linkOpacity).get()}},generatePoints:function(){function a(b,e){void 0===b.level&&
(b.level=e,b.linksFrom.forEach(function(b){a(b.toNode,e+1)}))}d.NodesMixin.generatePoints.apply(this,arguments);this.orderNodes&&(this.nodes.filter(function(a){return 0===a.linksTo.length}).forEach(function(b){a(b,0)}),d.stableSort(this.nodes,function(a,b){return a.level-b.level}))},translateNode:function(b,d){var e=this.translationFactor,f=this.chart,c=this.options,k=b.getSum(),m=Math.round(k*e),l=Math.round(c.borderWidth)%2/2,g=d.offset(b,e);d=Math.floor(p(g.absoluteTop,d.top(e)+g.relativeTop))+
l;l=Math.floor(this.colDistance*b.column+c.borderWidth/2)+l;l=f.inverted?f.plotSizeX-l:l;e=Math.round(this.nodeWidth);b.sum=k;b.shapeType="rect";b.nodeX=l;b.nodeY=d;b.shapeArgs=f.inverted?{x:l-e,y:f.plotSizeY-d-m,width:b.options.height||c.height||e,height:b.options.width||c.width||m}:{x:l,y:d,width:b.options.width||c.width||e,height:b.options.height||c.height||m};b.shapeArgs.display=b.hasShape()?"":"none";f=this.mapOptionsToLevel[b.level];c=b.options;c=h(c)?c.dataLabels:{};f=h(f)?f.dataLabels:{};
f=a({style:{}},f,c);b.dlOptions=f;b.plotY=1},translateLink:function(a){var b=a.fromNode,e=a.toNode,d=this.chart,c=this.translationFactor,k=a.weight*c,m=this.options,l=b.offset(a,"linksFrom")*c,g=(d.inverted?-this.colDistance:this.colDistance)*m.curveFactor,l=b.nodeY+l,m=b.nodeX,c=this.nodeColumns[e.column].top(c)+e.offset(a,"linksTo")*c+this.nodeColumns[e.column].offset(e,c).relativeTop,h=this.nodeWidth,e=e.column*this.colDistance,n=a.outgoing,p=e>m;d.inverted&&(l=d.plotSizeY-l,c=d.plotSizeY-c,e=
d.plotSizeX-e,h=-h,k=-k,p=m>e);a.shapeType="path";a.linkBase=[l,l+k,c,c+k];if(p)a.shapeArgs={d:["M",m+h,l,"C",m+h+g,l,e-g,c,e,c,"L",e+(n?h:0),c+k/2,"L",e,c+k,"C",e-g,c+k,m+h+g,l+k,m+h,l+k,"z"]};else{var g=e-20-k,n=e-20,p=e,u=m+h,r=u+20,v=r+k,w=l,z=l+k,C=z+20,d=C+(d.plotHeight-l-k),y=d+20,B=y+k,D=c,A=D+k,E=A+20,F=y+.7*k,G=p-.7*k,H=u+.7*k;a.shapeArgs={d:["M",u,w,"C",H,w,v,z-.7*k,v,C,"L",v,d,"C",v,F,H,B,u,B,"L",p,B,"C",G,B,g,F,g,d,"L",g,E,"C",g,A-.7*k,G,D,p,D,"L",p,A,"C",n,A,n,A,n,E,"L",n,d,"C",n,y,
n,y,p,y,"L",u,y,"C",r,y,r,y,r,d,"L",r,C,"C",r,z,r,z,u,z,"z"]}}a.dlBox={x:m+(e-m+h)/2,y:l+(c-l)/2,height:k,width:0};a.y=a.plotY=1;a.color||(a.color=b.color)},translate:function(){this.processedXData||this.processData();this.generatePoints();this.nodeColumns=this.createNodeColumns();this.nodeWidth=d.relativeLength(this.options.nodeWidth,this.chart.plotSizeX);var a=this,c=this.chart,e=this.options,g=this.nodeWidth,h=this.nodeColumns,k=this.getNodePadding();this.translationFactor=h.reduce(function(a,
b){return Math.min(a,(c.plotSizeY-e.borderWidth-(b.length-1)*k)/b.sum())},Infinity);this.colDistance=(c.plotSizeX-g-e.borderWidth)/(h.length-1);a.mapOptionsToLevel=v({from:1,levels:e.levels,to:h.length-1,defaults:{borderColor:e.borderColor,borderRadius:e.borderRadius,borderWidth:e.borderWidth,color:a.color,colorByPoint:e.colorByPoint,levelIsConstant:!0,linkColor:e.linkColor,linkLineWidth:e.linkLineWidth,linkOpacity:e.linkOpacity,states:e.states}});h.forEach(function(b){b.forEach(function(c){a.translateNode(c,
b)})},this);this.nodes.forEach(function(b){b.linksFrom.forEach(function(b){a.translateLink(b);b.allowShadow=!1})})},render:function(){var a=this.points;this.points=this.points.concat(this.nodes||[]);d.seriesTypes.column.prototype.render.call(this);this.points=a},animate:d.Series.prototype.animate},{applyOptions:function(a,c){r.prototype.applyOptions.call(this,a,c);n(this.options.level)&&(this.options.column=this.column=this.options.level);return this},setState:d.NodesMixin.setNodeState,getClassName:function(){return(this.isNode?
"highcharts-node ":"highcharts-link ")+r.prototype.getClassName.call(this)},isValid:function(){return this.isNode||"number"===typeof this.weight}})});w(c,"masters/modules/sankey.src.js",[],function(){})});
//# sourceMappingURL=sankey.js.map