/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Solid angular gauge module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/solid-gauge",["highcharts","highcharts/highcharts-more"],function(c){b(c);b.Highcharts=c;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function c(l,b,c,r){l.hasOwnProperty(b)||(l[b]=r.apply(null,c))}b=b?b._modules:{};c(b,"modules/solid-gauge.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,c){var l=
c.isNumber,r=c.pInt,u=b.pick;c=b.wrap;var t;c(b.Renderer.prototype.symbols,"arc",function(a,b,f,e,c,d){a=a(b,f,e,c,d);d.rounded&&(e=((d.r||e)-d.innerR)/2,d=["A",e,e,0,1,1,a[12],a[13]],a.splice.apply(a,[a.length-1,0].concat(["A",e,e,0,1,1,a[1],a[2]])),a.splice.apply(a,[11,3].concat(d)));return a});t={initDataClasses:function(a){var h=this.chart,f,e=0,c=this.options;this.dataClasses=f=[];a.dataClasses.forEach(function(d,m){d=b.merge(d);f.push(d);d.color||("category"===c.dataClassColor?(m=h.options.colors,
d.color=m[e++],e===m.length&&(e=0)):d.color=b.color(c.minColor).tweenTo(b.color(c.maxColor),m/(a.dataClasses.length-1)))})},initStops:function(a){this.stops=a.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(a){a.color=b.color(a[1])})},toColor:function(a,b){var f=this.stops,e,c,d=this.dataClasses,h,g;if(d)for(g=d.length;g--;){if(h=d[g],e=h.from,f=h.to,(void 0===e||a>=e)&&(void 0===f||a<=f)){c=h.color;b&&(b.dataClass=g);break}}else{this.isLog&&(a=this.val2lin(a));
a=1-(this.max-a)/(this.max-this.min);for(g=f.length;g--&&!(a>f[g][0]););e=f[g]||f[g+1];f=f[g+1]||e;a=1-(f[0]-a)/(f[0]-e[0]||1);c=e.color.tweenTo(f.color,a)}return c}};b.seriesType("solidgauge","gauge",{colorByPoint:!0,dataLabels:{y:0}},{drawLegendSymbol:b.LegendSymbolMixin.drawRectangle,translate:function(){var a=this.yAxis;b.extend(a,t);!a.dataClasses&&a.options.dataClasses&&a.initDataClasses(a.options);a.initStops(a.options);b.seriesTypes.gauge.prototype.translate.call(this)},drawPoints:function(){var a=
this,c=a.yAxis,f=c.center,e=a.options,t=a.chart.renderer,d=e.overshoot,m=l(d)?d/180*Math.PI:0,g;l(e.threshold)&&(g=c.startAngleRad+c.translate(e.threshold,null,null,null,!0));this.thresholdAngleRad=u(g,c.startAngleRad);a.points.forEach(function(d){if(!d.isNull){var g=d.graphic,k=c.startAngleRad+c.translate(d.y,null,null,null,!0),h=r(u(d.options.radius,e.radius,100))*f[2]/200,n=r(u(d.options.innerRadius,e.innerRadius,60))*f[2]/200,p=c.toColor(d.y,d),q=Math.min(c.startAngleRad,c.endAngleRad),l=Math.max(c.startAngleRad,
c.endAngleRad);"none"===p&&(p=d.color||a.color||"none");"none"!==p&&(d.color=p);k=Math.max(q-m,Math.min(l+m,k));!1===e.wrap&&(k=Math.max(q,Math.min(l,k)));q=Math.min(k,a.thresholdAngleRad);k=Math.max(k,a.thresholdAngleRad);k-q>2*Math.PI&&(k=q+2*Math.PI);d.shapeArgs=n={x:f[0],y:f[1],r:h,innerR:n,start:q,end:k,rounded:e.rounded};d.startR=h;g?(h=n.d,g.animate(b.extend({fill:p},n)),h&&(n.d=h)):(d.graphic=g=t.arc(n).attr({fill:p,"sweep-flag":0}).add(a.group),a.chart.styledMode||("square"!==e.linecap&&
g.attr({"stroke-linecap":"round","stroke-linejoin":"round"}),g.attr({stroke:e.borderColor||"none","stroke-width":e.borderWidth||0})));g&&g.addClass(d.getClassName(),!0)}})},animate:function(a){a||(this.startAngleRad=this.thresholdAngleRad,b.seriesTypes.pie.prototype.animate.call(this,a))}})});c(b,"masters/modules/solid-gauge.src.js",[],function(){})});
//# sourceMappingURL=solid-gauge.js.map