/*
 Highstock JS v7.1.2-modified (2019-07-03)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(z){"object"===typeof module&&module.exports?(z["default"]=z,module.exports=z):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(G){z(G);z.Highcharts=G;return z}):z("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(z){function G(c,r,B,E){c.hasOwnProperty(r)||(c[r]=E.apply(null,B))}z=z?z._modules:{};G(z,"parts/Scrollbar.js",[z["parts/Globals.js"]],function(c){function r(b,h,n){this.init(b,h,n)}var B=c.addEvent,E=c.Axis,x=c.correctFloat,
l=c.defaultOptions,y=c.defined,D=c.destroyObjectProperties,A=c.fireEvent,C=c.hasTouch,q=c.merge,e=c.pick,u=c.removeEvent,t,d={height:c.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",
trackBorderWidth:1};l.scrollbar=q(!0,d,l.scrollbar);c.swapXY=t=function(b,h){var n=b.length,a;if(h)for(h=0;h<n;h+=3)a=b[h+1],b[h+1]=b[h+2],b[h+2]=a;return b};r.prototype={init:function(b,h,n){this.scrollbarButtons=[];this.renderer=b;this.userOptions=h;this.options=q(d,h);this.chart=n;this.size=e(this.options.size,this.options.height);h.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var b=this.renderer,h=this.options,n=this.size,a=this.chart.styledMode,k;this.group=
k=b.g("scrollbar").attr({zIndex:h.zIndex,translateY:-99999}).add();this.track=b.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:h.trackBorderRadius||0,height:n,width:n}).add(k);a||this.track.attr({fill:h.trackBackgroundColor,stroke:h.trackBorderColor,"stroke-width":h.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=b.g().add(k);this.scrollbar=b.rect().addClass("highcharts-scrollbar-thumb").attr({height:n,
width:n,r:h.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=b.path(t(["M",-3,n/4,"L",-3,2*n/3,"M",0,n/4,"L",0,2*n/3,"M",3,n/4,"L",3,2*n/3],h.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);a||(this.scrollbar.attr({fill:h.barBackgroundColor,stroke:h.barBorderColor,"stroke-width":h.barBorderWidth}),this.scrollbarRifles.attr({stroke:h.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%
2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(b,h,n,a){var k=this.options.vertical,m=0,d=this.rendered?"animate":"attr";this.x=b;this.y=h+this.trackBorderWidth;this.width=n;this.xOffset=this.height=a;this.yOffset=m;k?(this.width=this.yOffset=n=m=this.size,this.xOffset=h=0,this.barWidth=a-2*n,this.x=b+=this.options.margin):(this.height=this.xOffset=a=h=this.size,this.barWidth=n-2*a,this.y+=this.options.margin);this.group[d]({translateX:b,
translateY:this.y});this.track[d]({width:n,height:a});this.scrollbarButtons[1][d]({translateX:k?0:n-h,translateY:k?a-m:0})},drawScrollbarButton:function(b){var h=this.renderer,n=this.scrollbarButtons,a=this.options,k=this.size,m;m=h.g().add(this.group);n.push(m);m=h.rect().addClass("highcharts-scrollbar-button").add(m);this.chart.styledMode||m.attr({stroke:a.buttonBorderColor,"stroke-width":a.buttonBorderWidth,fill:a.buttonBackgroundColor});m.attr(m.crisp({x:-.5,y:-.5,width:k+1,height:k+1,r:a.buttonBorderRadius},
m.strokeWidth()));m=h.path(t(["M",k/2+(b?-1:1),k/2-3,"L",k/2+(b?-1:1),k/2+3,"L",k/2+(b?2:-2),k/2],a.vertical)).addClass("highcharts-scrollbar-arrow").add(n[b]);this.chart.styledMode||m.attr({fill:a.buttonArrowColor})},setRange:function(b,h){var n=this.options,a=n.vertical,k=n.minWidth,m=this.barWidth,d,g,p=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";y(m)&&(b=Math.max(b,0),d=Math.ceil(m*b),this.calculatedWidth=g=x(m*Math.min(h,1)-d),g<k&&
(d=(m-k+g)*b,g=k),k=Math.floor(d+this.xOffset+this.yOffset),m=g/2-.5,this.from=b,this.to=h,a?(this.scrollbarGroup[p]({translateY:k}),this.scrollbar[p]({height:g}),this.scrollbarRifles[p]({translateY:m}),this.scrollbarTop=k,this.scrollbarLeft=0):(this.scrollbarGroup[p]({translateX:k}),this.scrollbar[p]({width:g}),this.scrollbarRifles[p]({translateX:m}),this.scrollbarLeft=k,this.scrollbarTop=0),12>=g?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0),!1===n.showFull&&(0>=b&&1<=h?this.group.hide():
this.group.show()),this.rendered=!0)},initEvents:function(){var b=this;b.mouseMoveHandler=function(h){var d=b.chart.pointer.normalize(h),a=b.options.vertical?"chartY":"chartX",k=b.initPositions;!b.grabbedCenter||h.touches&&0===h.touches[0][a]||(d=b.cursorToScrollbarPosition(d)[a],a=b[a],a=d-a,b.hasDragged=!0,b.updatePosition(k[0]+a,k[1]+a),b.hasDragged&&A(b,"changed",{from:b.from,to:b.to,trigger:"scrollbar",DOMType:h.type,DOMEvent:h}))};b.mouseUpHandler=function(h){b.hasDragged&&A(b,"changed",{from:b.from,
to:b.to,trigger:"scrollbar",DOMType:h.type,DOMEvent:h});b.grabbedCenter=b.hasDragged=b.chartX=b.chartY=null};b.mouseDownHandler=function(h){h=b.chart.pointer.normalize(h);h=b.cursorToScrollbarPosition(h);b.chartX=h.chartX;b.chartY=h.chartY;b.initPositions=[b.from,b.to];b.grabbedCenter=!0};b.buttonToMinClick=function(h){var d=x(b.to-b.from)*b.options.step;b.updatePosition(x(b.from-d),x(b.to-d));A(b,"changed",{from:b.from,to:b.to,trigger:"scrollbar",DOMEvent:h})};b.buttonToMaxClick=function(h){var d=
(b.to-b.from)*b.options.step;b.updatePosition(b.from+d,b.to+d);A(b,"changed",{from:b.from,to:b.to,trigger:"scrollbar",DOMEvent:h})};b.trackClick=function(h){var d=b.chart.pointer.normalize(h),a=b.to-b.from,k=b.y+b.scrollbarTop,m=b.x+b.scrollbarLeft;b.options.vertical&&d.chartY>k||!b.options.vertical&&d.chartX>m?b.updatePosition(b.from+a,b.to+a):b.updatePosition(b.from-a,b.to-a);A(b,"changed",{from:b.from,to:b.to,trigger:"scrollbar",DOMEvent:h})}},cursorToScrollbarPosition:function(b){var h=this.options,
h=h.minWidth>this.calculatedWidth?h.minWidth:0;return{chartX:(b.chartX-this.x-this.xOffset)/(this.barWidth-h),chartY:(b.chartY-this.y-this.yOffset)/(this.barWidth-h)}},updatePosition:function(b,h){1<h&&(b=x(1-x(h-b)),h=1);0>b&&(h=x(h-b),b=0);this.from=b;this.to=h},update:function(b){this.destroy();this.init(this.chart.renderer,q(!0,this.options,b),this.chart)},addEvents:function(){var b=this.options.inverted?[1,0]:[0,1],h=this.scrollbarButtons,d=this.scrollbarGroup.element,a=this.mouseDownHandler,
k=this.mouseMoveHandler,m=this.mouseUpHandler,b=[[h[b[0]].element,"click",this.buttonToMinClick],[h[b[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[d,"mousedown",a],[d.ownerDocument,"mousemove",k],[d.ownerDocument,"mouseup",m]];C&&b.push([d,"touchstart",a],[d.ownerDocument,"touchmove",k],[d.ownerDocument,"touchend",m]);b.forEach(function(b){B.apply(null,b)});this._events=b},removeEvents:function(){this._events.forEach(function(b){u.apply(null,b)});this._events.length=
0},destroy:function(){var b=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(b){this[b]&&this[b].destroy&&(this[b]=this[b].destroy())},this);b&&this===b.scrollbar&&(b.scrollbar=null,D(b.scrollbarButtons))}};c.Scrollbar||(B(E,"afterInit",function(){var b=this;b.options&&b.options.scrollbar&&b.options.scrollbar.enabled&&(b.options.scrollbar.vertical=!b.horiz,b.options.startOnTick=b.options.endOnTick=!1,b.scrollbar=new r(b.chart.renderer,
b.options.scrollbar,b.chart),B(b.scrollbar,"changed",function(h){var d=Math.min(e(b.options.min,b.min),b.min,b.dataMin),a=Math.max(e(b.options.max,b.max),b.max,b.dataMax)-d,k;b.horiz&&!b.reversed||!b.horiz&&b.reversed?(k=d+a*this.to,d+=a*this.from):(k=d+a*(1-this.from),d+=a*(1-this.to));e(this.options.liveRedraw,c.svg&&!c.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===h.DOMType||!y(h.DOMType)?b.setExtremes(d,k,!0,"mousemove"!==h.DOMType,h):this.setRange(this.from,this.to)}))}),B(E,"afterRender",
function(){var b=Math.min(e(this.options.min,this.min),this.min,e(this.dataMin,this.min)),h=Math.max(e(this.options.max,this.max),this.max,e(this.dataMax,this.max)),d=this.scrollbar,a=this.axisTitleMargin+(this.titleOffset||0),k=this.chart.scrollbarsOffsets,m=this.options.margin||0;d&&(this.horiz?(this.opposite||(k[1]+=a),d.position(this.left,this.top+this.height+2+k[1]-(this.opposite?m:0),this.width,this.height),this.opposite||(k[1]+=m),a=1):(this.opposite&&(k[0]+=a),d.position(this.left+this.width+
2+k[0]-(this.opposite?0:m),this.top,this.width,this.height),this.opposite&&(k[0]+=m),a=0),k[a]+=d.size+d.options.margin,isNaN(b)||isNaN(h)||!y(this.min)||!y(this.max)||this.min===this.max?d.setRange(0,1):(k=(this.min-b)/(h-b),b=(this.max-b)/(h-b),this.horiz&&!this.reversed||!this.horiz&&this.reversed?d.setRange(k,b):d.setRange(1-b,1-k)))}),B(E,"afterGetOffset",function(){var b=this.horiz?2:1,d=this.scrollbar;d&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[b]+=d.size+d.options.margin)}),
c.Scrollbar=r)});G(z,"parts/Navigator.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(c,r){function B(g){this.init(g)}var E=r.isArray,x=r.isNumber,l=c.addEvent,y=c.Axis;r=c.Chart;var D=c.color,A=c.defaultOptions,C=c.defined,q=c.destroyObjectProperties,e=c.erase,u=c.extend,t=c.hasTouch,d=c.isTouchDevice,b=c.merge,h=c.pick,n=c.removeEvent,a=c.Scrollbar,k=c.Series,m,w=function(g){for(var p=[],f=1;f<arguments.length;f++)p[f-1]=arguments[f];p=[].filter.call(p,x);if(p.length)return Math[g].apply(0,
p)};m=void 0===c.seriesTypes.areaspline?"line":"areaspline";u(A,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:D("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:m,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,
10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},pointRange:0,threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",
style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});c.Renderer.prototype.symbols["navigator-handle"]=function(g,p,f,b,a){g=a.width/2;p=Math.round(g/3)+.5;a=a.height;return["M",-g-1,.5,"L",g,.5,"L",g,a+.5,"L",-g-1,a+.5,"L",-g-1,.5,"M",-p,4,"L",-p,a-3,"M",p-1,4,"L",p-1,a-3]};y.prototype.toFixedRange=function(g,
p,f,b){var a=this.chart&&this.chart.fixedRange;g=h(f,this.translate(g,!0,!this.horiz));p=h(b,this.translate(p,!0,!this.horiz));f=a&&(p-g)/a;.7<f&&1.3>f&&(b?g=p-a:p=g+a);x(g)&&x(p)||(g=p=void 0);return{min:g,max:p}};B.prototype={drawHandle:function(g,p,f,b){var a=this.navigatorOptions.handles.height;this.handles[p][b](f?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(g,10)+.5-a)}:{translateX:Math.round(this.left+parseInt(g,10)),translateY:Math.round(this.top+
this.height/2-a/2-1)})},drawOutline:function(g,p,f,b){var a=this.navigatorOptions.maskInside,v=this.outline.strokeWidth(),d=v/2,v=v%2/2,m=this.outlineHeight,k=this.scrollbarHeight,h=this.size,c=this.left-k,e=this.top;f?(c-=d,f=e+p+v,p=e+g+v,g=["M",c+m,e-k-v,"L",c+m,f,"L",c,f,"L",c,p,"L",c+m,p,"L",c+m,e+h+k].concat(a?["M",c+m,f-d,"L",c+m,p+d]:[])):(g+=c+k-v,p+=c+k-v,e+=d,g=["M",c,e,"L",g,e,"L",g,e+m,"L",p,e+m,"L",p,e,"L",c+h+2*k,e].concat(a?["M",g-d,e,"L",p+d,e]:[]));this.outline[b]({d:g})},drawMasks:function(g,
p,f,b){var a=this.left,v=this.top,d=this.height,m,k,h,c;f?(h=[a,a,a],c=[v,v+g,v+p],k=[d,d,d],m=[g,p-g,this.size-p]):(h=[a,a+g,a+p],c=[v,v,v],k=[g,p-g,this.size-p],m=[d,d,d]);this.shades.forEach(function(f,g){f[b]({x:h[g],y:c[g],width:k[g],height:m[g]})})},renderElements:function(){var g=this,p=g.navigatorOptions,f=p.maskInside,a=g.chart,b=a.renderer,d,m={cursor:a.inverted?"ns-resize":"ew-resize"};g.navigatorGroup=d=b.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!f,f,!f].forEach(function(f,
v){g.shades[v]=b.rect().addClass("highcharts-navigator-mask"+(1===v?"-inside":"-outside")).add(d);a.styledMode||g.shades[v].attr({fill:f?p.maskFill:"rgba(0,0,0,0)"}).css(1===v&&m)});g.outline=b.path().addClass("highcharts-navigator-outline").add(d);a.styledMode||g.outline.attr({"stroke-width":p.outlineWidth,stroke:p.outlineColor});p.handles.enabled&&[0,1].forEach(function(f){p.handles.inverted=a.inverted;g.handles[f]=b.symbol(p.handles.symbols[f],-p.handles.width/2-1,0,p.handles.width,p.handles.height,
p.handles);g.handles[f].attr({zIndex:7-f}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][f]).add(d);if(!a.styledMode){var v=p.handles;g.handles[f].attr({fill:v.backgroundColor,stroke:v.borderColor,"stroke-width":v.lineWidth}).css(m)}})},update:function(g){(this.series||[]).forEach(function(g){g.baseSeries&&delete g.baseSeries.navigatorSeries});this.destroy();b(!0,this.chart.options.navigator,this.options,g);this.init(this.chart)},render:function(g,p,f,a){var b=
this.chart,v,d,m=this.scrollbarHeight,k,e=this.xAxis;v=e.fake?b.xAxis[0]:e;var q=this.navigatorEnabled,n,w=this.rendered;d=b.inverted;var u,t=b.xAxis[0].minRange,l=b.xAxis[0].options.maxRange;if(!this.hasDragged||C(f)){if(!x(g)||!x(p))if(w)f=0,a=h(e.width,v.width);else return;this.left=h(e.left,b.plotLeft+m+(d?b.plotWidth:0));this.size=n=k=h(e.len,(d?b.plotHeight:b.plotWidth)-2*m);b=d?m:k+2*m;f=h(f,e.toPixels(g,!0));a=h(a,e.toPixels(p,!0));x(f)&&Infinity!==Math.abs(f)||(f=0,a=b);g=e.toValue(f,!0);
p=e.toValue(a,!0);u=Math.abs(c.correctFloat(p-g));u<t?this.grabbedLeft?f=e.toPixels(p-t,!0):this.grabbedRight&&(a=e.toPixels(g+t,!0)):C(l)&&u>l&&(this.grabbedLeft?f=e.toPixels(p-l,!0):this.grabbedRight&&(a=e.toPixels(g+l,!0)));this.zoomedMax=Math.min(Math.max(f,a,0),n);this.zoomedMin=Math.min(Math.max(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(f,a),0),n);this.range=this.zoomedMax-this.zoomedMin;n=Math.round(this.zoomedMax);f=Math.round(this.zoomedMin);q&&(this.navigatorGroup.attr({visibility:"visible"}),
w=w&&!this.hasDragged?"animate":"attr",this.drawMasks(f,n,d,w),this.drawOutline(f,n,d,w),this.navigatorOptions.handles.enabled&&(this.drawHandle(f,0,d,w),this.drawHandle(n,1,d,w)));this.scrollbar&&(d?(d=this.top-m,v=this.left-m+(q||!v.opposite?0:(v.titleOffset||0)+v.axisTitleMargin),m=k+2*m):(d=this.top+(q?this.height:-m),v=this.left-m),this.scrollbar.position(v,d,b,m),this.scrollbar.setRange(this.zoomedMin/(k||1),this.zoomedMax/(k||1)));this.rendered=!0}},addMouseEvents:function(){var g=this,p=g.chart,
f=p.container,a=[],b,d;g.mouseMoveHandler=b=function(f){g.onMouseMove(f)};g.mouseUpHandler=d=function(f){g.onMouseUp(f)};a=g.getPartsEvents("mousedown");a.push(l(f,"mousemove",b),l(f.ownerDocument,"mouseup",d));t&&(a.push(l(f,"touchmove",b),l(f.ownerDocument,"touchend",d)),a.concat(g.getPartsEvents("touchstart")));g.eventsToUnbind=a;g.series&&g.series[0]&&a.push(l(g.series[0].xAxis,"foundExtremes",function(){p.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(g){var p=this,f=[];
["shades","handles"].forEach(function(a){p[a].forEach(function(b,v){f.push(l(b.element,g,function(f){p[a+"Mousedown"](f,v)}))})});return f},shadesMousedown:function(g,p){g=this.chart.pointer.normalize(g);var f=this.chart,a=this.xAxis,b=this.zoomedMin,d=this.left,m=this.size,k=this.range,h=g.chartX,c,e;f.inverted&&(h=g.chartY,d=this.top);1===p?(this.grabbedCenter=h,this.fixedWidth=k,this.dragOffset=h-b):(g=h-d-k/2,0===p?g=Math.max(0,g):2===p&&g+k>=m&&(g=m-k,this.reversedExtremes?(g-=k,e=this.getUnionExtremes().dataMin):
c=this.getUnionExtremes().dataMax),g!==b&&(this.fixedWidth=k,p=a.toFixedRange(g,g+k,e,c),C(p.min)&&f.xAxis[0].setExtremes(Math.min(p.min,p.max),Math.max(p.min,p.max),!0,null,{trigger:"navigator"})))},handlesMousedown:function(g,p){this.chart.pointer.normalize(g);g=this.chart;var f=g.xAxis[0],a=this.reversedExtremes;0===p?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=a?f.min:f.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=a?f.max:f.min);
g.fixedRange=null},onMouseMove:function(g){var a=this,f=a.chart,b=a.left,m=a.navigatorSize,k=a.range,e=a.dragOffset,n=f.inverted;g.touches&&0===g.touches[0].pageX||(g=f.pointer.normalize(g),f=g.chartX,n&&(b=a.top,f=g.chartY),a.grabbedLeft?(a.hasDragged=!0,a.render(0,0,f-b,a.otherHandlePos)):a.grabbedRight?(a.hasDragged=!0,a.render(0,0,a.otherHandlePos,f-b)):a.grabbedCenter&&(a.hasDragged=!0,f<e?f=e:f>m+e-k&&(f=m+e-k),a.render(0,0,f-e,f-e+k)),a.hasDragged&&a.scrollbar&&h(a.scrollbar.options.liveRedraw,
c.svg&&!d&&!this.chart.isBoosting)&&(g.DOMType=g.type,setTimeout(function(){a.onMouseUp(g)},0)))},onMouseUp:function(a){var g=this.chart,f=this.xAxis,b=this.scrollbar,d,m,k=a.DOMEvent||a;(!this.hasDragged||b&&b.hasDragged)&&"scrollbar"!==a.trigger||(b=this.getUnionExtremes(),this.zoomedMin===this.otherHandlePos?d=this.fixedExtreme:this.zoomedMax===this.otherHandlePos&&(m=this.fixedExtreme),this.zoomedMax===this.size&&(m=this.reversedExtremes?b.dataMin:b.dataMax),0===this.zoomedMin&&(d=this.reversedExtremes?
b.dataMax:b.dataMin),f=f.toFixedRange(this.zoomedMin,this.zoomedMax,d,m),C(f.min)&&g.xAxis[0].setExtremes(Math.min(f.min,f.max),Math.max(f.min,f.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:k}));"mousemove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),
this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){n(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&n(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(g){var p=g.options,f=p.navigator,v=f.enabled,d=p.scrollbar,m=d.enabled,p=v?f.height:0,k=m?d.height:0;this.handles=[];this.shades=[];this.chart=g;this.setBaseSeries();
this.height=p;this.scrollbarHeight=k;this.scrollbarEnabled=m;this.navigatorEnabled=v;this.navigatorOptions=f;this.scrollbarOptions=d;this.outlineHeight=p+k;this.opposite=h(f.opposite,!v&&g.inverted);var e=this,v=e.baseSeries,d=g.xAxis.length,m=g.yAxis.length,c=v&&v[0]&&v[0].xAxis||g.xAxis[0]||{options:{}};g.isDirtyBox=!0;e.navigatorEnabled?(e.xAxis=new y(g,b({breaks:c.options.breaks,ordinal:c.options.ordinal},f.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:d,isInternal:!0,
offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},g.inverted?{offsets:[k,0,-k,0],width:p}:{offsets:[0,-k,0,k],height:p})),e.yAxis=new y(g,b(f.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:m,isInternal:!0,zoomEnabled:!1},g.inverted?{width:p}:{height:p})),v||f.series.data?e.updateNavigatorSeries(!1):0===g.series.length&&(e.unbindRedraw=l(g,"beforeRedraw",function(){0<g.series.length&&!e.series&&(e.setBaseSeries(),e.unbindRedraw())})),e.reversedExtremes=
g.inverted&&!e.xAxis.reversed||!g.inverted&&e.xAxis.reversed,e.renderElements(),e.addMouseEvents()):e.xAxis={translate:function(f,a){var b=g.xAxis[0],p=b.getExtremes(),d=b.len-2*k,v=w("min",b.options.min,p.dataMin),b=w("max",b.options.max,p.dataMax)-v;return a?f*b/d+v:d*(f-v)/b},toPixels:function(f){return this.translate(f)},toValue:function(f){return this.translate(f,!0)},toFixedRange:y.prototype.toFixedRange,fake:!0};g.options.scrollbar.enabled&&(g.scrollbar=e.scrollbar=new a(g.renderer,b(g.options.scrollbar,
{margin:e.navigatorEnabled?0:10,vertical:g.inverted}),g),l(e.scrollbar,"changed",function(f){var a=e.size,b=a*this.to,a=a*this.from;e.hasDragged=e.scrollbar.hasDragged;e.render(0,0,a,b);(g.options.scrollbar.liveRedraw||"mousemove"!==f.DOMType&&"touchmove"!==f.DOMType)&&setTimeout(function(){e.onMouseUp(f)})}));e.addBaseSeriesEvents();e.addChartEvents()},getUnionExtremes:function(a){var b=this.chart.xAxis[0],f=this.xAxis,g=f.options,d=b.options,m;a&&null===b.dataMin||(m={dataMin:h(g&&g.min,w("min",
d.min,b.dataMin,f.dataMin,f.min)),dataMax:h(g&&g.max,w("max",d.max,b.dataMax,f.dataMax,f.max))});return m},setBaseSeries:function(a,b){var f=this.chart,g=this.baseSeries=[];a=a||f.options&&f.options.navigator.baseSeries||(f.series.length?c.find(f.series,function(f){return!f.options.isInternal}).index:0);(f.series||[]).forEach(function(f,b){f.options.isInternal||!f.options.showInNavigator&&(b!==a&&f.options.id!==a||!1===f.options.showInNavigator)||g.push(f)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,
b)},updateNavigatorSeries:function(a,p){var f=this,g=f.chart,d=f.baseSeries,m,k,h=f.navigatorOptions.series,e,q={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},w=f.series=(f.series||[]).filter(function(a){var b=a.baseSeries;return 0>d.indexOf(b)?(b&&(n(b,"updatedData",f.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});d&&d.length&&
d.forEach(function(a){var v=a.navigatorSeries,c=u({color:a.color,visible:a.visible},E(h)?A.navigator.series:h);v&&!1===f.navigatorOptions.adaptToUpdatedData||(q.name="Navigator "+d.length,m=a.options||{},e=m.navigatorOptions||{},k=b(m,q,c,e),c=e.data||c.data,f.hasNavigatorData=f.hasNavigatorData||!!c,k.data=c||m.data&&m.data.slice(0),v&&v.options?v.update(k,p):(a.navigatorSeries=g.initSeries(k),a.navigatorSeries.baseSeries=a,w.push(a.navigatorSeries)))});if(h.data&&(!d||!d.length)||E(h))f.hasNavigatorData=
!1,h=c.splat(h),h.forEach(function(a,p){q.name="Navigator "+(w.length+1);k=b(A.navigator.series,{color:g.series[p]&&!g.series[p].options.isInternal&&g.series[p].color||g.options.colors[p]||g.options.colors[0]},q,a);k.data=a.data;k.data&&(f.hasNavigatorData=!0,w.push(g.initSeries(k)))});a&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&l(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);b.forEach(function(f){l(f,"show",function(){this.navigatorSeries&&
this.navigatorSeries.setVisible(!0,!1)});l(f,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&f.xAxis&&l(f,"updatedData",this.updatedDataHandler);l(f,"remove",function(){this.navigatorSeries&&(e(a.series,this.navigatorSeries),C(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},getBaseSeriesMin:function(a){return this.baseSeries.reduce(function(a,f){return Math.min(a,f.xData?
f.xData[0]:a)},a)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,b;a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,b=this.getExtremes(),f=b.dataMin,d=b.dataMax,b=b.max-b.min,m=a.stickToMin,k=a.stickToMax,e=h(this.options.overscroll,0),c,q,n=a.series&&a.series[0],w=!!this.setExtremes;this.eventArgs&&"rangeSelectorButton"===this.eventArgs.trigger||(m&&(q=f,
c=q+b),k&&(c=d+e,m||(q=Math.max(c-b,a.getBaseSeriesMin(n&&n.xData?n.xData[0]:-Number.MAX_VALUE)))),w&&(m||k)&&x(q)&&(this.min=this.userMin=q,this.max=this.userMax=c));a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries,f=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=x(this.xAxis.min)&&this.xAxis.min<=f&&(!this.chart.fixedRange||!a.stickToMax);
b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(l(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,b.max)}),l(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":
"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))},destroy:function(){this.removeEvents();this.xAxis&&(e(this.chart.xAxis,this.xAxis),e(this.chart.axes,this.xAxis));this.yAxis&&(e(this.chart.yAxis,this.yAxis),e(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&
this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){q(a)},this)}};c.Navigator||(c.Navigator=B,l(y,"zoom",function(a){var b=this.chart.options,f=b.chart.zoomType,g=b.chart.pinchType,m=b.navigator,b=b.rangeSelector;this.isXAxis&&(m&&m.enabled||b&&b.enabled)&&("y"===f?a.zoomed=!1:(!d&&"xy"===f||d&&"xy"===g)&&this.options.range&&(f=this.previousZoom,C(a.newMin)?this.previousZoom=[this.min,this.max]:f&&(a.newMin=f[0],a.newMax=f[1],delete this.previousZoom)));void 0!==
a.zoomed&&a.preventDefault()}),l(r,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,f=a.rangeSelector;if((b&&b.enabled||f&&f.enabled)&&(!d&&"x"===a.chart.zoomType||d&&"x"===a.chart.pinchType))return!1}),l(r,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new B(this)}),l(r,"afterSetChartSize",function(){var a=this.legend,b=this.navigator,f,d,m,k;b&&(d=a&&a.options,m=b.xAxis,k=b.yAxis,f=b.scrollbarHeight,this.inverted?
(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(d&&"bottom"===d.verticalAlign&&d.enabled&&!d.floating?a.legendHeight+h(d.margin,10):0)),m&&k&&(this.inverted?m.options.left=k.options.left=b.left:m.options.top=k.options.top=b.top,m.setAxisSize(),k.setAxisSize()))}),l(r,"update",function(a){var d=
a.options.navigator||{},f=a.options.scrollbar||{};this.navigator||this.scroller||!d.enabled&&!f.enabled||(b(!0,this.options.navigator,d),b(!0,this.options.scrollbar,f),delete a.options.navigator,delete a.options.scrollbar)}),l(r,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new B(this),h(a.redraw,!0)&&this.redraw(a.animation))}),l(r,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,
!1)}),l(k,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),r.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}))});G(z,"parts/OrdinalAxis.js",[z["parts/Globals.js"]],function(c){var r=c.addEvent,B=c.Axis,E=c.Chart,x=c.css,l=c.defined,y=c.extend,D=c.noop,A=c.pick,C=c.timeUnits;r(c.Series,"updatedData",function(){var c=this.xAxis;c&&c.options.ordinal&&delete c.ordinalIndex});
B.prototype.getTimeTicks=function(c,e,u,t,d,b,h){var n=0,a,k,m={},w,g,p,f=[],v=-Number.MAX_VALUE,q=this.options.tickPixelInterval,F=this.chart.time,H=[];if(!this.options.ordinal&&!this.options.breaks||!d||3>d.length||void 0===e)return F.getTimeTicks.apply(F,arguments);g=d.length;for(a=0;a<g;a++){p=a&&d[a-1]>u;d[a]<e&&(n=a);if(a===g-1||d[a+1]-d[a]>5*b||p){if(d[a]>v){for(k=F.getTimeTicks(c,d[n],d[a],t);k.length&&k[0]<=v;)k.shift();k.length&&(v=k[k.length-1]);H.push(f.length);f=f.concat(k)}n=a+1}if(p)break}k=
k.info;if(h&&k.unitRange<=C.hour){a=f.length-1;for(n=1;n<a;n++)F.dateFormat("%d",f[n])!==F.dateFormat("%d",f[n-1])&&(m[f[n]]="day",w=!0);w&&(m[f[0]]="day");k.higherRanks=m}k.segmentStarts=H;f.info=k;if(h&&l(q)){n=H=f.length;w=[];for(var J,F=[];n--;)a=this.translate(f[n]),J&&(F[n]=J-a),w[n]=J=a;F.sort();F=F[Math.floor(F.length/2)];F<.6*q&&(F=null);n=f[H-1]>u?H-1:H;for(J=void 0;n--;)a=w[n],H=Math.abs(J-a),J&&H<.8*q&&(null===F||H<.8*F)?(m[f[n]]&&!m[f[n+1]]?(H=n+1,J=a):H=n,f.splice(H,1)):J=a}return f};
y(B.prototype,{beforeSetTickPositions:function(){var c,e=[],u,t=!1,d,b=this.getExtremes(),h=b.min,n=b.max,a,k=this.isXAxis&&!!this.options.breaks,b=this.options.ordinal,m=Number.MAX_VALUE,w=this.chart.options.chart.ignoreHiddenSeries,g;if(b||k){this.series.forEach(function(a,b){u=[];if(!(w&&!1===a.visible||!1===a.takeOrdinalPosition&&!k)&&(e=e.concat(a.processedXData),c=e.length,e.sort(function(a,b){return a-b}),m=Math.min(m,A(a.closestPointRange,m)),c)){for(b=0;b<c-1;)e[b]!==e[b+1]&&u.push(e[b+1]),
b++;u[0]!==e[0]&&u.unshift(e[0]);e=u}a.isSeriesBoosting&&(g=!0)});g&&(e.length=0);c=e.length;if(2<c){d=e[1]-e[0];for(a=c-1;a--&&!t;)e[a+1]-e[a]!==d&&(t=!0);!this.options.keepOrdinalPadding&&(e[0]-h>d||n-e[e.length-1]>d)&&(t=!0)}else this.options.overscroll&&(2===c?m=e[1]-e[0]:1===c?(m=this.options.overscroll,e=[e[0],e[0]+m]):m=this.overscrollPointsRange);t?(this.options.overscroll&&(this.overscrollPointsRange=m,e=e.concat(this.getOverscrollPositions())),this.ordinalPositions=e,d=this.ordinal2lin(Math.max(h,
e[0]),!0),a=Math.max(this.ordinal2lin(Math.min(n,e[e.length-1]),!0),1),this.ordinalSlope=n=(n-h)/(a-d),this.ordinalOffset=h-d*n):(this.overscrollPointsRange=A(this.closestPointRange,this.overscrollPointsRange),this.ordinalPositions=this.ordinalSlope=this.ordinalOffset=void 0)}this.isOrdinal=b&&t;this.groupIntervalFactor=null},val2lin:function(c,e){var q=this.ordinalPositions;if(q){var t=q.length,d,b;for(d=t;d--;)if(q[d]===c){b=d;break}for(d=t-1;d--;)if(c>q[d]||0===d){c=(c-q[d])/(q[d+1]-q[d]);b=d+
c;break}e=e?b:this.ordinalSlope*(b||0)+this.ordinalOffset}else e=c;return e},lin2val:function(c,e){var q=this.ordinalPositions;if(q){var t=this.ordinalSlope,d=this.ordinalOffset,b=q.length-1,h;if(e)0>c?c=q[0]:c>b?c=q[b]:(b=Math.floor(c),h=c-b);else for(;b--;)if(e=t*b+d,c>=e){t=t*(b+1)+d;h=(c-e)/(t-e);break}return void 0!==h&&void 0!==q[b]?q[b]+(h?h*(q[b+1]-q[b]):0):c}return c},getExtendedPositions:function(){var c=this,e=c.chart,u=c.series[0].currentDataGrouping,t=c.ordinalIndex,d=u?u.count+u.unitName:
"raw",b=c.options.overscroll,h=c.getExtremes(),n,a;t||(t=c.ordinalIndex={});t[d]||(n={series:[],chart:e,getExtremes:function(){return{min:h.dataMin,max:h.dataMax+b}},options:{ordinal:!0},val2lin:B.prototype.val2lin,ordinal2lin:B.prototype.ordinal2lin},c.series.forEach(function(b){a={xAxis:n,xData:b.xData.slice(),chart:e,destroyGroupedData:D};a.xData=a.xData.concat(c.getOverscrollPositions());a.options={dataGrouping:u?{enabled:!0,forced:!0,approximation:"open",units:[[u.unitName,[u.count]]]}:{enabled:!1}};
b.processData.apply(a);n.series.push(a)}),c.beforeSetTickPositions.apply(n),t[d]=n.ordinalPositions);return t[d]},getOverscrollPositions:function(){var q=this.options.overscroll,e=this.overscrollPointsRange,u=[],t=this.dataMax;if(c.defined(e))for(u.push(t);t<=this.dataMax+q;)t+=e,u.push(t);return u},getGroupIntervalFactor:function(c,e,u){var q;u=u.processedXData;var d=u.length,b=[];q=this.groupIntervalFactor;if(!q){for(q=0;q<d-1;q++)b[q]=u[q+1]-u[q];b.sort(function(b,d){return b-d});b=b[Math.floor(d/
2)];c=Math.max(c,u[0]);e=Math.min(e,u[d-1]);this.groupIntervalFactor=q=d*b/(e-c)}return q},postProcessTickInterval:function(c){var e=this.ordinalSlope;return e?this.options.breaks?this.closestPointRange||c:c/(e/this.closestPointRange):c}});B.prototype.ordinal2lin=B.prototype.val2lin;r(E,"pan",function(c){var e=this.xAxis[0],q=e.options.overscroll,l=c.originalEvent.chartX,d=!1;if(e.options.ordinal&&e.series.length){var b=this.mouseDownX,h=e.getExtremes(),n=h.dataMax,a=h.min,k=h.max,m=this.hoverPoints,
w=e.closestPointRange||e.overscrollPointsRange,b=(b-l)/(e.translationSlope*(e.ordinalSlope||w)),g={ordinalPositions:e.getExtendedPositions()},w=e.lin2val,p=e.val2lin,f;g.ordinalPositions?1<Math.abs(b)&&(m&&m.forEach(function(a){a.setState()}),0>b?(m=g,f=e.ordinalPositions?e:g):(m=e.ordinalPositions?e:g,f=g),g=f.ordinalPositions,n>g[g.length-1]&&g.push(n),this.fixedRange=k-a,b=e.toFixedRange(null,null,w.apply(m,[p.apply(m,[a,!0])+b,!0]),w.apply(f,[p.apply(f,[k,!0])+b,!0])),b.min>=Math.min(h.dataMin,
a)&&b.max<=Math.max(n,k)+q&&e.setExtremes(b.min,b.max,!0,!1,{trigger:"pan"}),this.mouseDownX=l,x(this.container,{cursor:"move"})):d=!0}else d=!0;d?q&&(e.max=e.dataMax+q):c.preventDefault()});r(B,"foundExtremes",function(){this.isXAxis&&l(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&l(this.userMin)&&(this.min+=this.options.overscroll))});
r(B,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)})});G(z,"modules/broken-axis.src.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(c,r){var B=r.isArray;r=c.addEvent;var E=c.pick,x=c.extend,l=c.find,y=c.fireEvent,D=c.Axis,A=c.Series,C=function(c,e){return l(e,function(e){return e.from<c&&c<e.to})};x(D.prototype,{isInBreak:function(c,e){var q=c.repeat||Infinity,l=c.from,d=c.to-c.from;e=
e>=l?(e-l)%q:q-(l-e)%q;return c.inclusive?e<=d:e<d&&0!==e},isInAnyBreak:function(c,e){var q=this.options.breaks,l=q&&q.length,d,b,h;if(l){for(;l--;)this.isInBreak(q[l],c)&&(d=!0,b||(b=E(q[l].showPoints,!this.isXAxis)));h=d&&e?d&&!b:d}return h}});r(D,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});r(D,"afterSetTickPositions",function(){if(this.isBroken){var c=this.tickPositions,e=this.tickPositions.info,l=[],t;for(t=0;t<c.length;t++)this.isInAnyBreak(c[t])||
l.push(c[t]);this.tickPositions=l;this.tickPositions.info=e}});r(D,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});D.prototype.setBreaks=function(c,e){function q(b){var c=b,a,k;for(k=0;k<d.breakArray.length;k++)if(a=d.breakArray[k],a.to<=b)c-=a.len;else if(a.from>=b)break;else if(d.isInBreak(a,b)){c-=b-a.from;break}return c}function l(b){var c,a;for(a=0;a<d.breakArray.length&&!(c=d.breakArray[a],c.from>=b);a++)c.to<b?b+=c.len:d.isInBreak(c,b)&&(b+=c.len);return b}var d=this,
b=B(c)&&!!c.length;d.isDirty=d.isBroken!==b;d.isBroken=b;d.options.breaks=d.userOptions.breaks=c;d.forceRedraw=!0;b||d.val2lin!==q||(delete d.val2lin,delete d.lin2val);b&&(d.userOptions.ordinal=!1,d.val2lin=q,d.lin2val=l,d.setExtremes=function(b,d,a,c,m){if(this.isBroken){for(var k,g=this.options.breaks;k=C(b,g);)b=k.to;for(;k=C(d,g);)d=k.from;d<b&&(d=b)}D.prototype.setExtremes.call(this,b,d,a,c,m)},d.setAxisTranslation=function(b){D.prototype.setAxisTranslation.call(this,b);this.unitLength=null;
if(this.isBroken){b=d.options.breaks;var c=[],a=[],k=0,m,e,g=d.userMin||d.min,p=d.userMax||d.max,f=E(d.pointRangePadding,0),v,h;b.forEach(function(a){e=a.repeat||Infinity;d.isInBreak(a,g)&&(g+=a.to%e-g%e);d.isInBreak(a,p)&&(p-=p%e-a.from%e)});b.forEach(function(a){v=a.from;for(e=a.repeat||Infinity;v-e>g;)v-=e;for(;v<g;)v+=e;for(h=v;h<p;h+=e)c.push({value:h,move:"in"}),c.push({value:h+(a.to-a.from),move:"out",size:a.breakSize})});c.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===
b.move?0:1):a.value-b.value});m=0;v=g;c.forEach(function(b){m+="in"===b.move?1:-1;1===m&&"in"===b.move&&(v=b.value);0===m&&(a.push({from:v,to:b.value,len:b.value-v-(b.size||0)}),k+=b.value-v-(b.size||0))});d.breakArray=a;d.unitLength=p-g-k+f;y(d,"afterBreaks");d.staticScale?d.transA=d.staticScale:d.unitLength&&(d.transA*=(p-d.min+f)/d.unitLength);f&&(d.minPixelPadding=d.transA*d.minPointOffset);d.min=g;d.max=p}});E(e,!0)&&this.chart.redraw()};r(A,"afterGeneratePoints",function(){var c=this.xAxis,
e=this.yAxis,l=this.points,t,d=l.length,b=this.options.connectNulls,h;if(c&&e&&(c.options.breaks||e.options.breaks))for(;d--;)t=l[d],h=null===t.y&&!1===b,h||!c.isInAnyBreak(t.x,!0)&&!e.isInAnyBreak(t.y,!0)||(l.splice(d,1),this.data[d]&&this.data[d].destroyElements())});r(A,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,E(this.pointArrayMap,["y"]))});c.Series.prototype.drawBreaks=function(c,e){var q=this,l=q.points,d,b,h,n;c&&e.forEach(function(a){d=c.breakArray||
[];b=c.isXAxis?c.min:E(q.options.threshold,c.min);l.forEach(function(k){n=E(k["stack"+a.toUpperCase()],k[a]);d.forEach(function(a){h=!1;if(b<a.from&&n>a.to||b>a.from&&n<a.from)h="pointBreak";else if(b<a.from&&n>a.from&&n<a.to||b>a.from&&n>a.to&&n<a.from)h="pointInBreak";h&&y(c,h,{point:k,brk:a})})})})};c.Series.prototype.gappedPath=function(){var q=this.currentDataGrouping,e=q&&q.gapSize,q=this.options.gapSize,l=this.points.slice(),t=l.length-1,d=this.yAxis;if(q&&0<t)for("value"!==this.options.gapUnit&&
(q*=this.closestPointRange),e&&e>q&&(q=e);t--;)l[t+1].x-l[t].x>q&&(e=(l[t].x+l[t+1].x)/2,l.splice(t+1,0,{isNull:!0,x:e}),this.options.stacking&&(e=d.stacks[this.stackKey][e]=new c.StackItem(d,d.options.stackLabels,!1,e,this.stack),e.total=0));return this.getGraphPath(l)}});G(z,"masters/modules/broken-axis.src.js",[],function(){});G(z,"parts/DataGrouping.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(c,r){var B=r.isNumber;r=c.addEvent;var E=c.arrayMax,x=c.arrayMin,l=c.Axis,y=c.defaultPlotOptions,
D=c.defined,A=c.extend,C=c.format,q=c.merge,e=c.pick,u=c.Point,t=c.Series,d=c.Tooltip,b=c.approximations={sum:function(a){var b=a.length,f;if(!b&&a.hasNulls)f=null;else if(b)for(f=0;b--;)f+=a[b];return f},average:function(a){var f=a.length;a=b.sum(a);B(a)&&f&&(a/=f);return a},averages:function(){var a=[];[].forEach.call(arguments,function(f){a.push(b.average(f))});return void 0===a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?E(a):a.hasNulls?
null:void 0},low:function(a){return a.length?x(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,d,c,g){a=b.open(a);d=b.high(d);c=b.low(c);g=b.close(g);if(B(a)||B(d)||B(c)||B(g))return[a,d,c,g]},range:function(a,d){a=b.low(a);d=b.high(d);if(B(a)||B(d))return[a,d];if(null===a&&null===d)return null}},h=function(a,d,c,g){var f=this,k=f.data,m=f.options&&f.options.data,p=[],e=[],v=[],h=a.length,w,n,F=!!d,l=[],N=f.pointArrayMap,t=N&&N.length,
u=["x"].concat(N||["y"]),r=0,y=0,A,x;g="function"===typeof g?g:b[g]?b[g]:b[f.getDGApproximation&&f.getDGApproximation()||"average"];t?N.forEach(function(){l.push([])}):l.push([]);A=t||1;for(x=0;x<=h&&!(a[x]>=c[0]);x++);for(x;x<=h;x++){for(;void 0!==c[r+1]&&a[x]>=c[r+1]||x===h;){w=c[r];f.dataGroupInfo={start:f.cropStart+y,length:l[0].length};n=g.apply(f,l);f.pointClass&&!D(f.dataGroupInfo.options)&&(f.dataGroupInfo.options=q(f.pointClass.prototype.optionsToObject.call({series:f},f.options.data[f.cropStart+
y])),u.forEach(function(a){delete f.dataGroupInfo.options[a]}));void 0!==n&&(p.push(w),e.push(n),v.push(f.dataGroupInfo));y=x;for(w=0;w<A;w++)l[w].length=0,l[w].hasNulls=!1;r+=1;if(x===h)break}if(x===h)break;if(N){w=f.cropStart+x;n=k&&k[w]||f.pointClass.prototype.applyOptions.apply({series:f},[m[w]]);var C;for(w=0;w<t;w++)C=n[N[w]],B(C)?l[w].push(C):null===C&&(l[w].hasNulls=!0)}else w=F?d[x]:null,B(w)?l[0].push(w):null===w&&(l[0].hasNulls=!0)}return{groupedXData:p,groupedYData:e,groupMap:v}},n={approximations:b,
groupData:h},a=t.prototype,k=a.processData,m=a.generatePoints,w={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],
year:["%Y","%Y","-%Y"]}},g={line:{},spline:{},area:{},areaspline:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},p=c.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];a.getDGApproximation=function(){return c.seriesTypes.arearange&&this instanceof c.seriesTypes.arearange?
"range":c.seriesTypes.ohlc&&this instanceof c.seriesTypes.ohlc?"ohlc":c.seriesTypes.column&&this instanceof c.seriesTypes.column?"sum":"average"};a.groupData=h;a.processData=function(){var b=this.chart,d=this.options.dataGrouping,c=!1!==this.allowDG&&d&&e(d.enabled,b.options.isStock),g=this.visible||!b.options.chart.ignoreHiddenSeries,m,h=this.currentDataGrouping,w,l=!1;this.forceCrop=c;this.groupPixelWidth=null;this.hasProcessed=!0;c&&!this.requireSorting&&(this.requireSorting=l=!0);c=!1===k.apply(this,
arguments)||!c;l&&(this.requireSorting=!1);if(!c){this.destroyGroupedData();var n,c=d.groupAll?this.xData:this.processedXData,q=d.groupAll?this.yData:this.processedYData,t=b.plotSizeX,b=this.xAxis,u=b.options.ordinal,r=this.groupPixelWidth=b.getGroupPixelWidth&&b.getGroupPixelWidth();if(r){this.isDirty=m=!0;this.points=null;l=b.getExtremes();w=l.min;var l=l.max,u=u&&b.getGroupIntervalFactor(w,l,this)||1,r=r*(l-w)/t*u,t=b.getTimeTicks(b.normalizeTimeTickInterval(r,d.units||p),Math.min(w,c[0]),Math.max(l,
c[c.length-1]),b.options.startOfWeek,c,this.closestPointRange),q=a.groupData.apply(this,[c,q,t,d.approximation]),c=q.groupedXData,u=q.groupedYData,x=0;if(d.smoothed&&c.length){n=c.length-1;for(c[n]=Math.min(c[n],l);n--&&0<n;)c[n]+=r/2;c[0]=Math.max(c[0],w)}for(n=1;n<t.length;n++)t.info.segmentStarts&&-1!==t.info.segmentStarts.indexOf(n)||(x=Math.max(t[n]-t[n-1],x));w=t.info;w.gapSize=x;this.closestPointRange=t.info.totalRange;this.groupMap=q.groupMap;if(D(c[0])&&c[0]<b.min&&g){if(!D(b.options.min)&&
b.min<=b.dataMin||b.min===b.dataMin)b.min=c[0];b.dataMin=c[0]}d.groupAll&&(d=this.cropData(c,u,b.min,b.max,1),c=d.xData,u=d.yData);this.processedXData=c;this.processedYData=u}else this.groupMap=null;this.hasGroupedData=m;this.currentDataGrouping=w;this.preventGraphAnimation=(h&&h.totalRange)!==(w&&w.totalRange)}};a.destroyGroupedData=function(){var a=this.groupedData;(a||[]).forEach(function(b,f){b&&(a[f]=b.destroy?b.destroy():null)});this.groupedData=null};a.generatePoints=function(){m.apply(this);
this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};r(u,"update",function(){if(this.dataGroup)return c.error(24,!1,this.series.chart),!1});r(d,"headerFormatter",function(a){var b=this.chart.time,f=a.labelConfig,c=f.series,d=c.tooltipOptions,g=c.options.dataGrouping,k=d.xDateFormat,m,p=c.xAxis,e,h=d[(a.isFooter?"footer":"header")+"Format"];p&&"datetime"===p.options.type&&g&&B(f.key)&&(e=c.currentDataGrouping,g=g.dateTimeLabelFormats||w.dateTimeLabelFormats,e?(d=g[e.unitName],
1===e.count?k=d[0]:(k=d[1],m=d[2])):!k&&g&&(k=this.getXDateFormat(f,d,p)),k=b.dateFormat(k,f.key),m&&(k+=b.dateFormat(m,f.key+e.totalRange-1)),c.chart.styledMode&&(h=this.styledModeFormat(h)),a.text=C(h,{point:A(f.point,{key:k}),series:c},b),a.preventDefault())});r(t,"destroy",a.destroyGroupedData);r(t,"afterSetOptions",function(a){a=a.options;var b=this.type,f=this.chart.options.plotOptions,c=y[b].dataGrouping,d=this.useCommonDataGrouping&&w;if(g[b]||d)c||(c=q(w,g[b])),a.dataGrouping=q(d,c,f.series&&
f.series.dataGrouping,f[b].dataGrouping,this.userOptions.dataGrouping)});r(l,"afterSetScale",function(){this.series.forEach(function(a){a.hasProcessed=!1})});l.prototype.getGroupPixelWidth=function(){var a=this.series,b=a.length,c,d=0,g=!1,k;for(c=b;c--;)(k=a[c].options.dataGrouping)&&(d=Math.max(d,e(k.groupPixelWidth,w.groupPixelWidth)));for(c=b;c--;)(k=a[c].options.dataGrouping)&&a[c].hasProcessed&&(b=(a[c].processedXData||a[c].data).length,a[c].groupPixelWidth||b>this.chart.plotSizeX/d||b&&k.forced)&&
(g=!0);return g?d:0};l.prototype.setDataGrouping=function(a,b){var f;b=e(b,!0);a||(a={forced:!1,units:null});if(this instanceof l)for(f=this.series.length;f--;)this.series[f].update({dataGrouping:a},!1);else this.chart.options.series.forEach(function(b){b.dataGrouping=a},!1);this.ordinalSlope=null;b&&this.chart.redraw()};c.dataGrouping=n;"";return n});G(z,"parts/OHLCSeries.js",[z["parts/Globals.js"]],function(c){var r=c.Point,B=c.seriesType,E=c.seriesTypes;B("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eOpen: {point.open}\x3cbr/\x3eHigh: {point.high}\x3cbr/\x3eLow: {point.low}\x3cbr/\x3eClose: {point.close}\x3cbr/\x3e'},
threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(c){return[c.open,c.high,c.low,c.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){E.column.prototype.init.apply(this,arguments);this.options.stacking=!1},pointAttribs:function(c,l){l=E.column.prototype.pointAttribs.call(this,c,l);var r=this.options;delete l.fill;!c.options.color&&r.upColor&&c.open<c.close&&
(l.stroke=r.upColor);return l},translate:function(){var c=this,l=c.yAxis,r=!!c.modifyValue,D=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];E.column.prototype.translate.apply(c);c.points.forEach(function(A){[A.open,A.high,A.low,A.close,A.low].forEach(function(y,q){null!==y&&(r&&(y=c.modifyValue(y)),A[D[q]]=l.toPixels(y,!0))});A.tooltipPos[1]=A.plotHigh+l.pos-c.chart.plotTop})},drawPoints:function(){var c=this,l=c.chart;c.points.forEach(function(r){var y,A,x,q,e=r.graphic,u,t=!e;void 0!==
r.plotY&&(e||(r.graphic=e=l.renderer.path().add(c.group)),l.styledMode||e.attr(c.pointAttribs(r,r.selected&&"select")),A=e.strokeWidth()%2/2,u=Math.round(r.plotX)-A,x=Math.round(r.shapeArgs.width/2),q=["M",u,Math.round(r.yBottom),"L",u,Math.round(r.plotHigh)],null!==r.open&&(y=Math.round(r.plotOpen)+A,q.push("M",u,y,"L",u-x,y)),null!==r.close&&(y=Math.round(r.plotClose)+A,q.push("M",u,y,"L",u+x,y)),e[t?"attr":"animate"]({d:q}).addClass(r.getClassName(),!0))})},animate:null},{getClassName:function(){return r.prototype.getClassName.call(this)+
(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}})});G(z,"parts/CandlestickSeries.js",[z["parts/Globals.js"]],function(c){var r=c.defaultPlotOptions,B=c.merge,E=c.seriesType,x=c.seriesTypes;E("candlestick","ohlc",B(r.column,{states:{hover:{lineWidth:2}},tooltip:r.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(c,r){var l=x.column.prototype.pointAttribs.call(this,c,r),A=this.options,y=c.open<c.close,q=A.lineColor||
this.color;l["stroke-width"]=A.lineWidth;l.fill=c.options.color||(y?A.upColor||this.color:this.color);l.stroke=c.lineColor||(y?A.upLineColor||q:q);r&&(c=A.states[r],l.fill=c.color||l.fill,l.stroke=c.lineColor||l.stroke,l["stroke-width"]=c.lineWidth||l["stroke-width"]);return l},drawPoints:function(){var c=this,r=c.chart,x=c.yAxis.reversed;c.points.forEach(function(l){var y=l.graphic,q,e,u,t,d,b,h,n=!y;void 0!==l.plotY&&(y||(l.graphic=y=r.renderer.path().add(c.group)),c.chart.styledMode||y.attr(c.pointAttribs(l,
l.selected&&"select")).shadow(c.options.shadow),d=y.strokeWidth()%2/2,b=Math.round(l.plotX)-d,q=l.plotOpen,e=l.plotClose,u=Math.min(q,e),q=Math.max(q,e),h=Math.round(l.shapeArgs.width/2),e=x?q!==l.yBottom:Math.round(u)!==Math.round(l.plotHigh),t=x?Math.round(u)!==Math.round(l.plotHigh):q!==l.yBottom,u=Math.round(u)+d,q=Math.round(q)+d,d=[],d.push("M",b-h,q,"L",b-h,u,"L",b+h,u,"L",b+h,q,"Z","M",b,u,"L",b,e?Math.round(x?l.yBottom:l.plotHigh):u,"M",b,q,"L",b,t?Math.round(x?l.plotHigh:l.yBottom):q),y[n?
"attr":"animate"]({d:d}).addClass(l.getClassName(),!0))})}})});G(z,"mixins/on-series.js",[z["parts/Globals.js"]],function(c){var r=c.defined,B=c.seriesTypes,E=c.stableSort;return{getPlotBox:function(){return c.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){B.column.prototype.translate.apply(this);var c=this,l=c.options,y=c.chart,z=c.points,A=z.length-1,C,q=l.onSeries,q=q&&y.get(q),l=l.onKey||"y",e=q&&q.options.step,u=q&&q.points,
t=u&&u.length,d=y.inverted,b=c.xAxis,h=c.yAxis,n=0,a,k,m,w;if(q&&q.visible&&t)for(n=(q.pointXOffset||0)+(q.barW||0)/2,y=q.currentDataGrouping,k=u[t-1].x+(y?y.totalRange:0),E(z,function(a,b){return a.x-b.x}),l="plot"+l[0].toUpperCase()+l.substr(1);t--&&z[A]&&!(a=u[t],y=z[A],y.y=a.y,a.x<=y.x&&void 0!==a[l]&&(y.x<=k&&(y.plotY=a[l],a.x<y.x&&!e&&(m=u[t+1])&&void 0!==m[l]&&(w=(y.x-a.x)/(m.x-a.x),y.plotY+=w*(m[l]-a[l]),y.y+=w*(m.y-a.y))),A--,t++,0>A)););z.forEach(function(a,k){var f;a.plotX+=n;if(void 0===
a.plotY||d)0<=a.plotX&&a.plotX<=b.len?d?(a.plotY=b.translate(a.x,0,1,0,1),a.plotX=r(a.y)?h.translate(a.y,0,0,0,1):0):a.plotY=(b.opposite?0:c.yAxis.len)+b.offset:a.shapeArgs={};(C=z[k-1])&&C.plotX===a.plotX&&(void 0===C.stackIndex&&(C.stackIndex=0),f=C.stackIndex+1);a.stackIndex=f});this.onSeries=q}}});G(z,"parts/FlagsSeries.js",[z["parts/Globals.js"],z["parts/Utilities.js"],z["mixins/on-series.js"]],function(c,r,B){function z(c){t[c+"pin"]=function(b,d,e,a,k){var m=k&&k.anchorX;k=k&&k.anchorY;var h;
"circle"===c&&a>e&&(b-=Math.round((a-e)/2),e=a);h=t[c](b,d,e,a);m&&k&&(h.push("M","circle"===c?b+e/2:h[1]+h[4]/2,d>k?d:d+a,"L",m,k),h=h.concat(t.circle(m-1,k-1,2,2)));return h}}var x=r.isNumber,l=c.addEvent,y=c.merge;r=c.noop;var D=c.defined,A=c.Renderer,C=c.Series,q=c.seriesType,e=c.TrackerMixin,u=c.VMLRenderer,t=c.SVGRenderer.prototype.symbols;q("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}\x3cbr/\x3e"},threshold:null,
y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:C.prototype.init,pointAttribs:function(c,b){var d=this.options,e=c&&c.color||this.color,a=d.lineColor,k=c&&c.lineWidth;c=c&&c.fillColor||d.fillColor;b&&(c=d.states[b].fillColor,a=d.states[b].lineColor,k=d.states[b].lineWidth);return{fill:c||e,stroke:a||
e,"stroke-width":k||d.lineWidth||0}},translate:B.translate,getPlotBox:B.getPlotBox,drawPoints:function(){var d=this.points,b=this.chart,e=b.renderer,l,a,k=b.inverted,m=this.options,w=m.y,g,p,f,v,q,F,r=this.yAxis,t={},u=[],x;for(p=d.length;p--;)f=d[p],F=(k?f.plotY:f.plotX)>this.xAxis.len,l=f.plotX,v=f.stackIndex,g=f.options.shape||m.shape,a=f.plotY,void 0!==a&&(a=f.plotY+w-(void 0!==v&&v*m.stackDistance)),f.anchorX=v?void 0:f.plotX,q=v?void 0:f.plotY,x="flag"!==g,v=f.graphic,void 0!==a&&0<=l&&!F?(v||
(v=f.graphic=e.label("",null,null,g,null,null,m.useHTML),b.styledMode||v.attr(this.pointAttribs(f)).css(y(m.style,f.style)),v.attr({align:x?"center":"left",width:m.width,height:m.height,"text-align":m.textAlign}).addClass("highcharts-point").add(this.markerGroup),f.graphic.div&&(f.graphic.div.point=f),b.styledMode||v.shadow(m.shadow),v.isNew=!0),0<l&&(l-=v.strokeWidth()%2),g={y:a,anchorY:q},m.allowOverlapX&&(g.x=l,g.anchorX=f.anchorX),v.attr({text:f.options.title||m.title||"A"})[v.isNew?"attr":"animate"](g),
m.allowOverlapX||(t[f.plotX]?t[f.plotX].size=Math.max(t[f.plotX].size,v.width):t[f.plotX]={align:x?.5:0,size:v.width,target:l,anchorX:l}),f.tooltipPos=[l,a+r.pos-b.plotTop]):v&&(f.graphic=v.destroy());m.allowOverlapX||(c.objectEach(t,function(a){a.plotX=a.anchorX;u.push(a)}),c.distribute(u,k?r.len:this.xAxis.len,100),d.forEach(function(a){var b=a.graphic&&t[a.plotX];b&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:b.pos+b.align*b.size,anchorX:a.anchorX}),D(b.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,
anchorX:-9999}),a.graphic.isNew=!0))}));m.useHTML&&c.wrap(this.markerGroup,"on",function(a){return c.SVGElement.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var c=this.points;e.drawTrackerPoint.apply(this);c.forEach(function(b){var d=b.graphic;d&&l(d.element,"mouseover",function(){0<b.stackIndex&&!b.raised&&(b._y=d.y,d.attr({y:b._y-8}),b.raised=!0);c.forEach(function(c){c!==b&&c.raised&&c.graphic&&(c.graphic.attr({y:c._y}),c.raised=
!1)})})})},animate:function(c){c?this.setClip():this.animate=null},setClip:function(){C.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},buildKDTree:r,invertGroups:r},{isValid:function(){return x(this.y)||void 0===this.y}});t.flag=function(c,b,e,l,a){var d=a&&a.anchorX||c;a=a&&a.anchorY||b;return t.circle(d-1,a-1,2,2).concat(["M",d,a,"L",c,b+l,c,b,c+e,b,c+e,b+l,c,b+l,"Z"])};z("circle");z("square");A===u&&["flag",
"circlepin","squarepin"].forEach(function(c){u.prototype.symbols[c]=t[c]})});G(z,"parts/RangeSelector.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(c,r){function B(a){this.init(a)}var z=r.isNumber,x=r.pInt,l=c.addEvent,y=c.Axis;r=c.Chart;var D=c.css,A=c.createElement,C=c.defaultOptions,q=c.defined,e=c.destroyObjectProperties,u=c.discardElement,t=c.extend,d=c.fireEvent,b=c.merge,h=c.pick,n=c.splat;t(C,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},
floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});C.lang=b(C.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});B.prototype={clickButton:function(a,b){var c=this.chart,d=this.buttonOptions[a],g=c.xAxis[0],k=c.scroller&&c.scroller.getUnionExtremes()||g||{},f=k.dataMin,e=k.dataMax,q,F=g&&Math.round(Math.min(g.max,h(e,g.max))),r=d.type,t,k=d._range,u,x,A,B=d.dataGrouping;if(null!==
f&&null!==e){c.fixedRange=k;B&&(this.forcedDataGrouping=!0,y.prototype.setDataGrouping.call(g||{chart:this.chart},B,!1),this.frozenStates=d.preserveDataGrouping);if("month"===r||"year"===r)g?(r={range:d,max:F,chart:c,dataMin:f,dataMax:e},q=g.minFromRange.call(r),z(r.newMax)&&(F=r.newMax)):k=d;else if(k)q=Math.max(F-k,f),F=Math.min(q+k,e);else if("ytd"===r)if(g)void 0===e&&(f=Number.MAX_VALUE,e=Number.MIN_VALUE,c.series.forEach(function(a){a=a.xData;f=Math.min(a[0],f);e=Math.max(a[a.length-1],e)}),
b=!1),F=this.getYTDExtremes(e,f,c.time.useUTC),q=u=F.min,F=F.max;else{this.deferredYTDClick=a;return}else"all"===r&&g&&(q=f,F=e);q+=d._offsetMin;F+=d._offsetMax;this.setSelected(a);g?g.setExtremes(q,F,h(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:d}):(t=n(c.options.xAxis)[0],A=t.range,t.range=k,x=t.min,t.min=u,l(c,"load",function(){t.range=A;t.min=x}))}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,
text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,c=a.options.rangeSelector,e=c.buttons||[].concat(b.defaultButtons),g=c.selected,p=function(){var a=b.minInput,c=b.maxInput;a&&a.blur&&d(a,"blur");c&&c.blur&&d(c,"blur")};b.chart=a;b.options=c;b.buttons=[];b.buttonOptions=e;this.unMouseDown=l(a.container,"mousedown",p);this.unResize=l(a,"resize",p);e.forEach(b.computeButtonRange);void 0!==g&&e[g]&&
this.clickButton(g,!1);l(a,"load",function(){a.xAxis&&a.xAxis[0]&&l(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&b.forcedDataGrouping&&!b.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,b=this.chart,c=b.xAxis[0],d=Math.round(c.max-c.min),g=!c.hasVisibleSeries,e=b.scroller&&b.scroller.getUnionExtremes()||c,f=e.dataMin,h=e.dataMax,b=a.getYTDExtremes(h,f,b.time.useUTC),l=b.min,
q=b.max,n=a.selected,r=z(n),t=a.options.allButtonsEnabled,u=a.buttons;a.buttonOptions.forEach(function(b,e){var k=b._range,m=b.type,p=b.count||1,v=u[e],w=0,F=b._offsetMax-b._offsetMin;b=e===n;var y=k>h-f,x=k<c.minRange,z=!1,A=!1,k=k===d;("month"===m||"year"===m)&&d+36E5>=864E5*{month:28,year:365}[m]*p-F&&d-36E5<=864E5*{month:31,year:366}[m]*p+F?k=!0:"ytd"===m?(k=q-l+F===d,z=!b):"all"===m&&(k=c.max-c.min>=h-f,A=!b&&r&&k);m=!t&&(y||x||A||g);p=b&&k||k&&!r&&!z||b&&a.frozenStates;m?w=3:p&&(r=!0,w=2);v.state!==
w&&(v.setState(w),0===w&&n===e&&a.setSelected(null))})},computeButtonRange:function(a){var b=a.type,c=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[b])a._range=d[b]*c;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*c;a._offsetMin=h(a.offsetMin,0);a._offsetMax=h(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,b){var c=this.chart.options.rangeSelector,d=this.chart.time,g=this[a+"Input"];q(b)&&(g.previousValue=
g.HCTime,g.HCTime=b);g.value=d.dateFormat(c.inputEditDateFormat||"%Y-%m-%d",g.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(c.inputDateFormat||"%b %e, %Y",g.HCTime)})},showInput:function(a){var b=this.inputGroup,c=this[a+"DateBox"];D(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})},hideInput:function(a){D(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function d(){var a=
n.value,b=(f.inputDateParser||Date.parse)(a),c=h.xAxis[0],d=h.scroller&&h.scroller.xAxis?h.scroller.xAxis:c,g=d.dataMin,d=d.dataMax;b!==n.previousValue&&(n.previousValue=b,z(b)||(b=a.split("-"),b=Date.UTC(x(b[0]),x(b[1])-1,x(b[2]))),z(b)&&(h.time.useUTC||(b+=6E4*(new Date).getTimezoneOffset()),q?b>e.maxInput.HCTime?b=void 0:b<g&&(b=g):b<e.minInput.HCTime?b=void 0:b>d&&(b=d),void 0!==b&&c.setExtremes(q?b:c.min,q?c.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}var e=this,h=e.chart,g=h.renderer.style||
{},p=h.renderer,f=h.options.rangeSelector,l=e.div,q="min"===a,n,r,u=this.inputGroup;this[a+"Label"]=r=p.label(C.lang[q?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(u);u.offset+=r.width+5;this[a+"DateBox"]=p=p.label("",u.offset).addClass("highcharts-range-input").attr({padding:2,width:f.inputBoxWidth||90,height:f.inputBoxHeight||17,"text-align":"center"}).on("click",function(){e.showInput(a);e[a+"Input"].focus()});h.styledMode||
p.attr({stroke:f.inputBoxBorderColor||"#cccccc","stroke-width":1});p.add(u);u.offset+=p.width+(q?10:0);this[a+"Input"]=n=A("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:h.plotTop+"px"},l);h.styledMode||(r.css(b(g,f.labelStyle)),p.css(b({color:"#333333"},g,f.inputStyle)),D(n,t({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:g.fontSize,fontFamily:g.fontFamily,top:"-9999em"},f.inputStyle)));n.onfocus=function(){e.showInput(a)};n.onblur=
function(){n===c.doc.activeElement&&d();e.hideInput(a);n.blur()};n.onchange=d;n.onkeypress=function(a){13===a.keyCode&&d()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector,a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}},getYTDExtremes:function(a,b,c){var d=this.chart.time,e=new d.Date(a),k=d.get("FullYear",e);c=c?d.Date.UTC(k,0,1):+new d.Date(k,0,1);b=Math.max(b||0,c);e=e.getTime();return{max:Math.min(a||
e,e),min:b}},render:function(a,b){var c=this,d=c.chart,e=d.renderer,k=d.container,f=d.options,l=f.exporting&&!1!==f.exporting.enabled&&f.navigation&&f.navigation.buttonOptions,q=C.lang,n=c.div,r=f.rangeSelector,t=h(f.chart.style&&f.chart.style.zIndex,0)+1,f=r.floating,u=c.buttons,n=c.inputGroup,y=r.buttonTheme,x=r.buttonPosition,z=r.inputPosition,B=r.inputEnabled,E=y&&y.states,D=d.plotLeft,G,I=c.buttonGroup,O;O=c.rendered;var P=c.options.verticalAlign,R=d.legend,S=R&&R.options,T=x.y,Q=z.y,U=O||!1,
V=U?"animate":"attr",M=0,K=0,L;if(!1!==r.enabled){O||(c.group=O=e.g("range-selector-group").attr({zIndex:7}).add(),c.buttonGroup=I=e.g("range-selector-buttons").add(O),c.zoomText=e.text(q.rangeSelectorZoom,0,15).add(I),d.styledMode||(c.zoomText.css(r.labelStyle),y["stroke-width"]=h(y["stroke-width"],0)),c.buttonOptions.forEach(function(a,b){u[b]=e.button(a.text,0,0,function(d){var f=a.events&&a.events.click,e;f&&(e=f.call(a,d));!1!==e&&c.clickButton(b);c.isActive=!0},y,E&&E.hover,E&&E.select,E&&E.disabled).attr({"text-align":"center"}).add(I)}),
!1!==B&&(c.div=n=A("div",null,{position:"relative",height:0,zIndex:t}),k.parentNode.insertBefore(n,k),c.inputGroup=n=e.g("input-group").add(O),n.offset=0,c.drawInput("min"),c.drawInput("max")));c.zoomText[V]({x:h(D+x.x,D)});G=h(D+x.x,D)+c.zoomText.getBBox().width+5;c.buttonOptions.forEach(function(a,b){u[b][V]({x:G});G+=u[b].width+h(r.buttonSpacing,5)});D=d.plotLeft-d.spacing[3];c.updateButtonStates();l&&this.titleCollision(d)&&"top"===P&&"right"===x.align&&x.y+I.getBBox().height-12<(l.y||0)+l.height&&
(M=-40);"left"===x.align?L=x.x-d.spacing[3]:"right"===x.align&&(L=x.x+M-d.spacing[1]);I.align({y:x.y,width:I.getBBox().width,align:x.align,x:L},!0,d.spacingBox);c.group.placed=U;c.buttonGroup.placed=U;!1!==B&&(M=l&&this.titleCollision(d)&&"top"===P&&"right"===z.align&&z.y-n.getBBox().height-12<(l.y||0)+l.height+d.spacing[0]?-40:0,"left"===z.align?L=D:"right"===z.align&&(L=-Math.max(d.axisOffset[1],-M)),n.align({y:z.y,width:n.getBBox().width,align:z.align,x:z.x+L-2},!0,d.spacingBox),k=n.alignAttr.translateX+
n.alignOptions.x-M+n.getBBox().x+2,l=n.alignOptions.width,q=I.alignAttr.translateX+I.getBBox().x,L=I.getBBox().width+20,(z.align===x.align||q+L>k&&k+l>q&&T<Q+n.getBBox().height)&&n.attr({translateX:n.alignAttr.translateX+(d.axisOffset[1]>=-M?0:-M),translateY:n.alignAttr.translateY+I.getBBox().height+10}),c.setInputValue("min",a),c.setInputValue("max",b),c.inputGroup.placed=U);c.group.align({verticalAlign:P},!0,d.spacingBox);a=c.group.getBBox().height+20;b=c.group.alignAttr.translateY;"bottom"===P&&
(R=S&&"bottom"===S.verticalAlign&&S.enabled&&!S.floating?R.legendHeight+h(S.margin,10):0,a=a+R-20,K=b-a-(f?0:r.y)-10);if("top"===P)f&&(K=0),d.titleOffset&&d.titleOffset[0]&&(K=d.titleOffset[0]+d.options.title.margin),K+=d.margin[0]-d.spacing[0]||0;else if("middle"===P)if(Q===T)K=0>Q?b+void 0:b;else if(Q||T)K=0>Q||0>T?K-Math.min(Q,T):b-a+NaN;c.group.translate(r.x,r.y+Math.floor(K));!1!==B&&(c.minInput.style.marginTop=c.group.translateY+"px",c.maxInput.style.marginTop=c.group.translateY+"px");c.rendered=
!0}},getHeight:function(){var a=this.options,b=this.group,c=a.y,d=a.buttonPosition.y,e=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+c:0;b=Math.min(e,d);if(0>e&&0>d||0<e&&0<d)a+=Math.abs(b);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var c=this.chart;b(!0,c.options.rangeSelector,a);this.destroy();this.init(c);c.rangeSelector.render()},destroy:function(){var a=this,b=a.minInput,d=a.maxInput;a.unMouseDown();
a.unResize();e(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);d&&(d.onfocus=d.onblur=d.onchange=null);c.objectEach(a,function(b,c){b&&"chart"!==c&&(b.destroy?b.destroy():b.nodeType&&u(this[c]));b!==B.prototype[c]&&(a[c]=null)},this)}};y.prototype.minFromRange=function(){var a=this.range,b={month:"Month",year:"FullYear"}[a.type],c,d=this.max,e,p,f=this.chart.time,l=function(a,c){var d=new f.Date(a),e=f.get(b,d);f.set(b,d,e+c);e===f.get(b,d)&&f.set("Date",d,0);return d.getTime()-a};z(a)?(c=d-a,
p=a):(c=d+l(d,-a.count),this.chart&&(this.chart.fixedRange=d-c));e=h(this.dataMin,Number.MIN_VALUE);z(c)||(c=e);c<=e&&(c=e,void 0===p&&(p=l(c,a.count)),this.newMax=Math.min(c+p,this.dataMax));z(d)||(c=void 0);return c};c.RangeSelector||(l(r,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new B(this))}),l(r,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(z(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();
a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),l(r,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;b&&b.enabled&&!q(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new B(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,
a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=!0)}),l(r,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),l(r,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&
(this.marginBottom+=a))}),r.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();z(c.min)&&d.render(c.min,c.max)}var c,d=a.rangeSelector,e,p;d&&(p=l(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)}),e=l(a,"redraw",b),b());l(a,"destroy",function(){d&&(e(),p())})}),c.RangeSelector=B)});G(z,"parts/StockChart.js",[z["parts/Globals.js"],z["parts/Utilities.js"]],function(c,r){var z=r.isNumber,E=r.isString;r=c.addEvent;var x=c.arrayMax,l=c.arrayMin,y=c.Axis,D=c.Chart,
A=c.defined,C=c.extend,q=c.format,e=c.merge,u=c.pick,t=c.Point,d=c.Renderer,b=c.Series,h=c.splat,n=c.SVGRenderer,a=c.VMLRenderer,k=b.prototype,m=k.init,w=k.processData,g=t.prototype.tooltipFormatter;c.StockChart=c.stockChart=function(a,b,d){var f=E(a)||a.nodeName,g=arguments[f?1:0],p=g,k=g.series,l=c.getOptions(),m,n=u(g.navigator&&g.navigator.enabled,l.navigator.enabled,!0),q=n?{startOnTick:!1,endOnTick:!1}:null;g.xAxis=h(g.xAxis||{}).map(function(a,b){return e({minPadding:0,maxPadding:0,overscroll:0,
ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},l.xAxis,l.xAxis&&l.xAxis[b],a,{type:"datetime",categories:null},q)});g.yAxis=h(g.yAxis||{}).map(function(a,b){m=u(a.opposite,!0);return e({labels:{y:-2},opposite:m,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},l.yAxis,l.yAxis&&l.yAxis[b],a)});g.series=null;g=e({chart:{panning:!0,pinchType:"x"},navigator:{enabled:n},scrollbar:{enabled:u(l.scrollbar.enabled,!0)},rangeSelector:{enabled:u(l.rangeSelector.enabled,
!0)},title:{text:null},tooltip:{split:u(l.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},g,{isStock:!0});g.series=p.series=k;return f?new D(a,g,d):new D(g,b)};r(b,"setOptions",function(a){function b(a){return c.seriesTypes[a]&&d instanceof c.seriesTypes[a]}var d=this,g;this.chart.options.isStock&&(b("column")||b("columnrange")?g={borderWidth:0,shadow:!1}:!b("line")||b("scatter")||b("sma")||(g={marker:{enabled:!1,radius:2}}),g&&(a.plotOptions[this.type]=e(a.plotOptions[this.type],g)))});r(y,
"autoLabelAlign",function(a){var b=this.chart,c=this.options,b=b._labelPanes=b._labelPanes||{},d=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled&&(15===d.x&&(d.x=0),void 0===d.align&&(d.align="right"),b[c]=this,a.align="right",a.preventDefault()))});r(y,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});r(y,"getPlotLinePath",function(a){function b(a){var b=
"xAxis"===a?"yAxis":"xAxis";a=d.options[b];return z(a)?[g[b][a]]:E(a)?[g.get(a)]:e.map(function(a){return a[b]})}var d=this,e=this.isLinked&&!this.series?this.linkedParent.series:this.series,g=d.chart,k=g.renderer,h=d.left,p=d.top,l,m,n,q,r=[],t=[],x,w,y=a.translatedValue,B=a.value,C=a.force,D;if(g.options.isStock&&!1!==a.acrossPanes&&"xAxis"===d.coll||"yAxis"===d.coll)a.preventDefault(),t=b(d.coll),x=d.isXAxis?g.yAxis:g.xAxis,x.forEach(function(a){if(A(a.options.id)?-1===a.options.id.indexOf("navigator"):
1){var b=a.isXAxis?"yAxis":"xAxis",b=A(a.options[b])?g[b][a.options[b]]:g[b][0];d===b&&t.push(a)}}),w=t.length?[]:[d.isXAxis?g.yAxis[0]:g.xAxis[0]],t.forEach(function(a){-1!==w.indexOf(a)||c.find(w,function(b){return b.pos===a.pos&&b.len===a.len})||w.push(a)}),D=u(y,d.translate(B,null,null,a.old)),z(D)&&(d.horiz?w.forEach(function(a){var b;m=a.pos;q=m+a.len;l=n=Math.round(D+d.transB);"pass"!==C&&(l<h||l>h+d.width)&&(C?l=n=Math.min(Math.max(h,l),h+d.width):b=!0);b||r.push("M",l,m,"L",n,q)}):w.forEach(function(a){var b;
l=a.pos;n=l+a.len;m=q=Math.round(p+d.height-D);"pass"!==C&&(m<p||m>p+d.height)&&(C?m=q=Math.min(Math.max(p,m),d.top+d.height):b=!0);b||r.push("M",l,m,"L",n,q)})),a.path=0<r.length?k.crispPolyLine(r,a.lineWidth||1):null});n.prototype.crispPolyLine=function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};d===a&&(a.prototype.crispPolyLine=n.prototype.crispPolyLine);r(y,"afterHideCrosshair",
function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});r(y,"afterDrawCrosshair",function(a){var b,c;if(A(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,e=this.options.crosshair.label,g=this.horiz;b=this.opposite;c=this.left;var k=this.top,h=this.crossLabel,l=e.format,p="",m="inside"===this.options.tickPosition,n=!1!==this.crosshair.snap,r=0,t=a.e||this.cross&&this.cross.e,w=a.point;a=this.lin2log;var x,y;this.isLog?(x=a(this.min),y=a(this.max)):(x=
this.min,y=this.max);a=g?"center":b?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";h||(h=this.crossLabel=d.renderer.label(null,null,null,e.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:e.align||a,padding:u(e.padding,8),r:u(e.borderRadius,3),zIndex:2}).add(this.labelGroup),d.styledMode||h.attr({fill:e.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:e.borderColor||
"","stroke-width":e.borderWidth||0}).css(C({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},e.style)));g?(a=n?w.plotX+c:t.chartX,k+=b?0:this.height):(a=b?this.width+c:0,k=n?w.plotY+k:t.chartY);l||e.formatter||(this.isDatetimeAxis&&(p="%b %d, %Y"),l="{value"+(p?":"+p:"")+"}");p=n?w[this.isXAxis?"x":"y"]:this.toValue(g?t.chartX:t.chartY);h.attr({text:l?q(l,{value:p},d.time):e.formatter.call(this,p),x:a,y:k,visibility:p<x||p>y?"hidden":"visible"});e=h.getBBox();if(g){if(m&&!b||
!m&&b)k=h.y-e.height}else k=h.y-e.height/2;g?(b=c-e.x,c=c+this.width-e.x):(b="left"===this.labelAlign?c:0,c="right"===this.labelAlign?c+this.width:d.chartWidth);h.translateX<b&&(r=b-h.translateX);h.translateX+e.width>=c&&(r=-(h.translateX+e.width-c));h.attr({x:a+r,y:k,anchorX:g?a:this.opposite?0:d.chartWidth,anchorY:g?this.opposite?d.chartHeight:0:k+e.height/2})}});k.init=function(){m.apply(this,arguments);this.setCompare(this.options.compare)};k.setCompare=function(a){this.modifyValue="value"===
a||"percent"===a?function(b,c){var d=this.compareValue;if(void 0!==b&&void 0!==d)return b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};k.processData=function(){var a,b=-1,c,d,e=!0===this.options.compareStart?0:1,g,h;w.apply(this,arguments);if(this.xAxis&&this.processedYData)for(c=this.processedXData,d=this.processedYData,g=d.length,this.pointArrayMap&&(b=this.pointArrayMap.indexOf(this.options.pointValKey||
this.pointValKey||"y")),a=0;a<g-e;a++)if(h=d[a]&&-1<b?d[a][b]:d[a],z(h)&&c[a+e]>=this.xAxis.min&&0!==h){this.compareValue=h;break}};r(b,"afterGetExtremes",function(){if(this.modifyValue){var a=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)];this.dataMin=l(a);this.dataMax=x(a)}});y.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),u(b,!0)&&this.chart.redraw())};t.prototype.tooltipFormatter=function(a){a=a.replace("{point.change}",(0<
this.change?"+":"")+c.numberFormat(this.change,u(this.series.tooltipOptions.changeDecimals,2)));return g.apply(this,[a])};r(b,"render",function(){var a=this.chart,b;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){b=this.yAxis.len;if(this.xAxis.axisLine){var c=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,d=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=c&&(b-=Math.max(d-c,0))}!this.clipBox&&this.animate?(this.clipBox=e(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=
b):a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len}))}});r(D,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(e(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)})});G(z,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map