/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 (c) 2016-2019 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/sunburst",["highcharts"],function(D){c(D);c.Highcharts=D;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function D(b,q,c,g){b.hasOwnProperty(q)||(b[q]=g.apply(null,c))}c=c?c._modules:{};D(c,"mixins/draw-point.js",[],function(){var b=function(b){var c=this,g=c.graphic,q=b.animatableAttribs,l=b.onComplete,x=b.css,E=b.renderer;
if(c.shouldDraw())g||(c.graphic=g=E[b.shapeType](b.shapeArgs).add(b.group)),g.css(x).attr(b.attribs).animate(q,b.isNew?!1:void 0,l);else if(g){var F=function(){c.graphic=g=g.destroy();"function"===typeof l&&l()};Object.keys(q).length?g.animate(q,void 0,function(){F()}):F()}};return function(c){(c.attribs=c.attribs||{})["class"]=this.getClassName();b.call(this,c)}});D(c,"mixins/tree-series.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(b,c){var q=c.isArray,g=c.isNumber,K=b.extend,l=b.isObject,
x=b.merge,E=b.pick;return{getColor:function(c,t){var A=t.index,g=t.mapOptionsToLevel,w=t.parentColor,F=t.parentColorIndex,q=t.series,y=t.colors,K=t.siblings,m=q.points,k=q.chart.options.chart,B,e,h,r;if(c){m=m[c.i];c=g[c.level]||{};if(g=m&&c.colorByPoint)e=m.index%(y?y.length:k.colorCount),B=y&&y[e];if(!q.chart.styledMode){y=m&&m.options.color;k=c&&c.color;if(h=w)h=(h=c&&c.colorVariation)&&"brightness"===h.key?b.color(w).brighten(A/K*h.to).get():w;h=E(y,k,B,h,q.color)}r=E(m&&m.options.colorIndex,
c&&c.colorIndex,e,F,t.colorIndex)}return{color:h,colorIndex:r}},getLevelOptions:function(b){var c=null,A,I,w,G;if(l(b))for(c={},w=g(b.from)?b.from:1,G=b.levels,I={},A=l(b.defaults)?b.defaults:{},q(G)&&(I=G.reduce(function(b,c){var t,m;l(c)&&g(c.level)&&(m=x({},c),t="boolean"===typeof m.levelIsConstant?m.levelIsConstant:A.levelIsConstant,delete m.levelIsConstant,delete m.level,c=c.level+(t?0:w-1),l(b[c])?K(b[c],m):b[c]=m);return b},{})),G=g(b.to)?b.to:1,b=0;b<=G;b++)c[b]=x({},A,l(I[b])?I[b]:{});return c},
setTreeValues:function t(b,c){var g=c.before,q=c.idRoot,A=c.mapIdToNode[q],l=c.points[b.i],x=l&&l.options||{},m=0,k=[];K(b,{levelDynamic:b.level-(("boolean"===typeof c.levelIsConstant?c.levelIsConstant:1)?0:A.level),name:E(l&&l.name,""),visible:q===b.id||("boolean"===typeof c.visible?c.visible:!1)});"function"===typeof g&&(b=g(b,c));b.children.forEach(function(g,e){var h=K({},c);K(h,{index:e,siblings:b.children.length,visible:b.visible});g=t(g,h);k.push(g);g.visible&&(m+=g.val)});b.visible=0<m||b.visible;
g=E(x.value,m);K(b,{children:k,childrenTotal:m,isLeaf:b.visible&&!m,val:g});return b},updateRootId:function(b){var c;l(b)&&(c=l(b.options)?b.options:{},c=E(b.rootNode,c.rootId,""),l(b.userOptions)&&(b.userOptions.rootId=c),b.rootNode=c);return c}}});D(c,"modules/treemap.src.js",[c["parts/Globals.js"],c["mixins/tree-series.js"],c["mixins/draw-point.js"],c["parts/Utilities.js"]],function(b,c,D,g){var q=g.isArray,l=g.isNumber,x=g.isString;g=b.seriesType;var E=b.seriesTypes,F=b.addEvent,t=b.merge,A=b.extend,
I=b.error,w=b.defined,G=b.noop,L=b.fireEvent,y=c.getColor,M=c.getLevelOptions,m=b.isObject,k=b.pick,B=b.Series,e=b.stableSort,h=b.Color,r=function(a,d,f){f=f||this;b.objectEach(a,function(n,p){d.call(f,n,p,a)})},v=function(a,d,f){f=f||this;a=d.call(f,a);!1!==a&&v(a,d,f)},J=c.updateRootId;g("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?this.point:{};return x(a.name)?
a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,opacity:.15,states:{hover:{borderColor:"#999999",brightness:E.heatmap?0:.1,halo:!1,
opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:G,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,d){a=q(a)?a:[];var f=q(d)?d:[];d=a.reduce(function(a,d,f){d=k(d.parent,"");void 0===a[d]&&(a[d]=[]);a[d].push(f);return a},{"":[]});r(d,function(a,d,b){""!==d&&-1===f.indexOf(d)&&(a.forEach(function(a){b[""].push(a)}),delete b[d])});return d},getTree:function(){var a=
this.data.map(function(a){return a.id}),a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},hasData:function(){return!!this.processedXData.length},init:function(a,d){var f=b.colorSeriesMixin;b.colorSeriesMixin&&(this.translateColors=f.translateColors,this.colorAttribs=f.colorAttribs,this.axisTypes=f.axisTypes);F(this,"setOptions",function(a){a=a.userOptions;w(a.allowDrillToNode)&&!w(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);
w(a.drillUpButton)&&!w(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});B.prototype.init.call(this,a,d);this.options.allowTraversingTree&&F(this,"click",this.onClickDrillToNode)},buildNode:function(a,d,f,n,p){var b=this,e=[],c=b.points[d],h=0,C;(n[a]||[]).forEach(function(d){C=b.buildNode(b.points[d].id,d,f+1,n,a);h=Math.max(C.height+1,h);e.push(C)});d={id:a,i:d,children:e,height:h,level:f,parent:p,visible:!1};b.nodeMap[d.id]=d;c&&(c.node=d);return d},setTreeValues:function(a){var d=
this,f=d.options,b=d.nodeMap[d.rootNode],f="boolean"===typeof f.levelIsConstant?f.levelIsConstant:!0,p=0,c=[],h,u=d.points[a.i];a.children.forEach(function(a){a=d.setTreeValues(a);c.push(a);a.ignore||(p+=a.val)});e(c,function(a,d){return a.sortIndex-d.sortIndex});h=k(u&&u.options.value,p);u&&(u.value=h);A(a,{children:c,childrenTotal:p,ignore:!(k(u&&u.visible,!0)&&0<h),isLeaf:a.visible&&!p,levelDynamic:a.level-(f?0:b.level),name:k(u&&u.name,""),sortIndex:k(u&&u.sortIndex,-h),val:h});return a},calculateChildrenAreas:function(a,
d){var f=this,b=f.options,p=f.mapOptionsToLevel[a.level+1],e=k(f[p&&p.layoutAlgorithm]&&p.layoutAlgorithm,b.layoutAlgorithm),c=b.alternateStartingDirection,h=[];a=a.children.filter(function(a){return!a.ignore});p&&p.layoutStartingDirection&&(d.direction="vertical"===p.layoutStartingDirection?0:1);h=f[e](d,a);a.forEach(function(a,b){b=h[b];a.values=t(b,{val:a.childrenTotal,direction:c?1-d.direction:d.direction});a.pointValues=t(b,{x:b.x/f.axisRatio,width:b.width/f.axisRatio});a.children.length&&f.calculateChildrenAreas(a,
a.values)})},setPointValues:function(){var a=this,d=a.xAxis,f=a.yAxis;a.points.forEach(function(b){var p=b.node,e=p.pointValues,c,n,h=0;a.chart.styledMode||(h=(a.pointAttribs(b)["stroke-width"]||0)%2/2);e&&p.visible?(p=Math.round(d.translate(e.x,0,0,0,1))-h,c=Math.round(d.translate(e.x+e.width,0,0,0,1))-h,n=Math.round(f.translate(e.y,0,0,0,1))-h,e=Math.round(f.translate(e.y+e.height,0,0,0,1))-h,b.shapeArgs={x:Math.min(p,c),y:Math.min(n,e),width:Math.abs(c-p),height:Math.abs(e-n)},b.plotX=b.shapeArgs.x+
b.shapeArgs.width/2,b.plotY=b.shapeArgs.y+b.shapeArgs.height/2):(delete b.plotX,delete b.plotY)})},setColorRecursive:function(a,d,b,e,p){var f=this,c=f&&f.chart,c=c&&c.options&&c.options.colors,n;if(a){n=y(a,{colors:c,index:e,mapOptionsToLevel:f.mapOptionsToLevel,parentColor:d,parentColorIndex:b,series:f,siblings:p});if(d=f.points[a.i])d.color=n.color,d.colorIndex=n.colorIndex;(a.children||[]).forEach(function(d,b){f.setColorRecursive(d,n.color,n.colorIndex,b,a.children.length)})}},algorithmGroup:function(a,
d,f,b){this.height=a;this.width=d;this.plot=b;this.startDirection=this.direction=f;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,d){return Math.max(a/d,d/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/
this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,d,f,e){var c,n,h,r,g=f.lW,C=f.lH,v=f.plot,q,m=0,l=f.elArr.length-1;d?(g=f.nW,C=f.nH):q=f.elArr[f.elArr.length-
1];f.elArr.forEach(function(a){if(d||m<l)0===f.direction?(c=v.x,n=v.y,h=g,r=a/h):(c=v.x,n=v.y,r=C,h=a/r),e.push({x:c,y:n,width:h,height:b.correctFloat(r)}),0===f.direction?v.y+=r:v.x+=h;m+=1});f.reset();0===f.direction?f.width-=g:f.height-=C;v.y=v.parent.y+(v.parent.height-f.height);v.x=v.parent.x+(v.parent.width-f.width);a&&(f.direction=1-f.direction);d||f.addElement(q)},algorithmLowAspectRatio:function(a,d,b){var f=[],e=this,c,h={x:d.x,y:d.y,parent:d},r=0,v=b.length-1,g=new this.algorithmGroup(d.height,
d.width,d.direction,h);b.forEach(function(b){c=b.val/d.val*d.height*d.width;g.addElement(c);g.lP.nR>g.lP.lR&&e.algorithmCalcPoints(a,!1,g,f,h);r===v&&e.algorithmCalcPoints(a,!0,g,f,h);r+=1});return f},algorithmFill:function(a,d,b){var f=[],e,c=d.direction,h=d.x,r=d.y,g=d.width,v=d.height,q,m,l,t;b.forEach(function(b){e=b.val/d.val*d.height*d.width;q=h;m=r;0===c?(t=v,l=e/t,g-=l,h+=l):(l=g,t=e/l,v-=t,r+=t);f.push({x:q,y:m,width:l,height:t});a&&(c=1-c)});return f},strip:function(a,d){return this.algorithmLowAspectRatio(!1,
a,d)},squarified:function(a,d){return this.algorithmLowAspectRatio(!0,a,d)},sliceAndDice:function(a,d){return this.algorithmFill(!0,a,d)},stripes:function(a,d){return this.algorithmFill(!1,a,d)},translate:function(){var a=this,d=a.options,b=J(a),e,c;B.prototype.translate.call(a);c=a.tree=a.getTree();e=a.nodeMap[b];a.renderTraverseUpButton(b);a.mapOptionsToLevel=M({from:e.level+1,levels:d.levels,to:c.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:d.colorByPoint}});""===b||
e&&e.children.length||(a.setRootNode("",!1),b=a.rootNode,e=a.nodeMap[b]);v(a.nodeMap[a.rootNode],function(d){var b=!1,e=d.parent;d.visible=!0;if(e||""===e)b=a.nodeMap[e];return b});v(a.nodeMap[a.rootNode].children,function(a){var d=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(d=(d||[]).concat(a.children))});return d});a.setTreeValues(c);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=b={x:0,y:0,width:100,height:100};a.nodeMap[""].values=b=t(b,{width:b.width*a.axisRatio,
direction:"vertical"===d.layoutStartingDirection?0:1,val:c.val});a.calculateChildrenAreas(c,b);a.colorAxis?a.translateColors():d.colorByPoint||a.setColorRecursive(a.tree);d.allowTraversingTree&&(d=e.pointValues,a.xAxis.setExtremes(d.x,d.x+d.width,!1),a.yAxis.setExtremes(d.y,d.y+d.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,d=a.mapOptionsToLevel,b,e;a.points.filter(function(a){return a.node.visible}).forEach(function(c){e=d[c.node.level];
b={style:{}};c.node.isLeaf||(b.enabled=!1);e&&e.dataLabels&&(b=t(b,e.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(b.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+"px"}));c.dlOptions=t(b,c.options.dataLabels)});B.prototype.drawDataLabels.call(this)},alignDataLabel:function(a,d,e){var c=e.style;!b.defined(c.textOverflow)&&d.text&&d.getBBox().width>d.text.textWidth&&d.css({textOverflow:"ellipsis",width:c.width+="px"});E.column.prototype.alignDataLabel.apply(this,
arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,d){var b=m(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},c=a&&b[a.node.level]||{},b=this.options,e=d&&b.states[d]||{},r=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||c.borderColor||e.borderColor||b.borderColor,"stroke-width":k(a&&a.borderWidth,c.borderWidth,e.borderWidth,b.borderWidth),dashstyle:a&&a.borderDashStyle||c.borderDashStyle||e.borderDashStyle||b.borderDashStyle,fill:a&&a.color||this.color};
-1!==r.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==r.indexOf("highcharts-internal-node-interactive")?(d=k(e.opacity,b.opacity),a.fill=h(a.fill).setOpacity(d).get(),a.cursor="pointer"):-1!==r.indexOf("highcharts-internal-node")?a.fill="none":d&&(a.fill=h(a.fill).brighten(e.brightness).get());return a},drawPoints:function(){var a=this,d=a.chart,b=d.renderer,e=d.styledMode,c=a.options,h=e?{}:c.shadow,r=c.borderRadius,g=d.pointCount<c.animationLimit,v=c.allowTraversingTree;
a.points.forEach(function(d){var f=d.node.levelDynamic,p={},n={},q={},m="level-group-"+f,l=!!d.graphic,u=g&&l,k=d.shapeArgs;d.shouldDraw()&&(r&&(n.r=r),t(!0,u?p:n,l?k:{},e?{}:a.pointAttribs(d,d.selected&&"select")),a.colorAttribs&&e&&A(q,a.colorAttribs(d)),a[m]||(a[m]=b.g(m).attr({zIndex:1E3-f}).add(a.group)));d.draw({animatableAttribs:p,attribs:n,css:q,group:a[m],renderer:b,shadow:h,shapeArgs:k,shapeType:"rect"});v&&d.graphic&&(d.drillId=c.interactByLeaf?a.drillToByLeaf(d):a.drillToByGroup(d))})},
onClickDrillToNode:function(a){var d=(a=a.point)&&a.drillId;x(d)&&(a.setState(""),this.setRootNode(d,!0,{trigger:"click"}))},drillToByGroup:function(a){var d=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(d=a.id);return d},drillToByLeaf:function(a){var d=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!d;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(d=a.id);return d},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&x(a.parent)&&this.setRootNode(a.parent,
!0,{trigger:"traverseUpButton"})},drillToNode:function(a,d){I("WARNING: treemap.drillToNode has been renamed to treemap.setRootNode, and will be removed in the next major version.");this.setRootNode(a,d)},setRootNode:function(a,d,b){a=A({newRootId:a,previousRootId:this.rootNode,redraw:k(d,!0),series:this},b);L(this,"setRootNode",a,function(a){var d=a.series;d.idPreviousRoot=a.previousRootId;d.rootNode=a.newRootId;d.isDirty=!0;a.redraw&&d.chart.redraw()})},renderTraverseUpButton:function(a){var d=
this,b=d.options.traverseUpButton,c=k(b.text,d.nodeMap[a].name,"\x3c Back"),e;""===a?d.drillUpButton&&(d.drillUpButton=d.drillUpButton.destroy()):this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:c}).align()):(e=(a=b.theme)&&a.states,this.drillUpButton=this.chart.renderer.button(c,null,null,function(){d.drillUp()},a,e&&e.hover,e&&e.select).addClass("highcharts-drillup-button").attr({align:b.position.align,zIndex:7}).add().align(b.position,!1,b.relativeTo||"plotBox"))},
buildKDTree:G,drawLegendSymbol:b.LegendSymbolMixin.drawRectangle,getExtremes:function(){B.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;B.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};B.prototype.bindAxes.call(this);b.extend(this.yAxis.options,a);b.extend(this.xAxis.options,
a)},setState:function(a){this.options.inactiveOtherPoints=!0;B.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:v}},{draw:D,getClassName:function(){var a=b.Point.prototype.getClassName.call(this),d=this.series,e=d.options;this.node.level<=d.nodeMap[d.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||k(e.interactByLeaf,!e.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},
isValid:function(){return this.id||l(this.value)},setState:function(a){b.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},setVisible:E.pie.prototype.pointClass.prototype.setVisible,shouldDraw:function(){return l(this.plotY)&&null!==this.y}})});D(c,"modules/sunburst.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["mixins/draw-point.js"],c["mixins/tree-series.js"]],function(b,c,D,g){var q=c.isNumber,l=c.isString;c=b.CenteredSeriesMixin;var x=
b.Series,E=b.extend,F=c.getCenter,t=g.getColor,A=g.getLevelOptions,I=c.getStartAndEndRadians,w=b.isObject,G=b.merge,L=180/Math.PI;c=b.seriesType;var y=g.setTreeValues,M=g.updateRootId,m=function(b,c){var e=[];if(q(b)&&q(c)&&b<=c)for(;b<=c;b++)e.push(b);return e},k=function(b,c){var e;c=w(c)?c:{};var h=0,g,a,d,f;w(b)&&(e=G({},b),b=q(c.from)?c.from:0,f=q(c.to)?c.to:0,a=m(b,f),b=Object.keys(e).filter(function(d){return-1===a.indexOf(+d)}),g=d=q(c.diffRadius)?c.diffRadius:0,a.forEach(function(a){a=e[a];
var b=a.levelSize.unit,c=a.levelSize.value;"weight"===b?h+=c:"percentage"===b?(a.levelSize={unit:"pixels",value:c/100*g},d-=a.levelSize.value):"pixels"===b&&(d-=c)}),a.forEach(function(a){var b=e[a];"weight"===b.levelSize.unit&&(b=b.levelSize.value,e[a].levelSize={unit:"pixels",value:b/h*d})}),b.forEach(function(a){e[a].levelSize={value:0,unit:"pixels"}}));return e},B=function(b,c){var e=c.mapIdToNode[b.parent],h=c.series,g=h.chart,a=h.points[b.i],e=t(b,{colors:h.options.colors||g&&g.options.colors,
colorIndex:h.colorIndex,index:c.index,mapOptionsToLevel:c.mapOptionsToLevel,parentColor:e&&e.color,parentColorIndex:e&&e.colorIndex,series:c.series,siblings:c.siblings});b.color=e.color;b.colorIndex=e.colorIndex;a&&(a.color=b.color,a.colorIndex=b.colorIndex,b.sliced=b.id!==c.idRoot?a.sliced:!1);return b};c("sunburst","treemap",{center:["50%","50%"],colorByPoint:!1,opacity:1,dataLabels:{allowOverlap:!0,defer:!0,rotationMode:"auto",style:{textOverflow:"ellipsis"}},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,
unit:"weight"},slicedOffset:10},{drawDataLabels:b.noop,drawPoints:function(){var b=this,c=b.mapOptionsToLevel,g=b.shapeRoot,v=b.group,m=b.hasRendered,a=b.rootNode,d=b.idPreviousRoot,f=b.nodeMap,n=f[d],p=n&&n.shapeArgs,n=b.points,l=b.startAndEndRadians,t=b.chart,k=t&&t.options&&t.options.chart||{},A="boolean"===typeof k.animation?k.animation:!0,C=b.center[3]/2,D=b.chart.renderer,B,y=!1,F=!1;if(k=!!(A&&m&&a!==d&&b.dataLabelsGroup))b.dataLabelsGroup.attr({opacity:0}),B=function(){y=!0;b.dataLabelsGroup&&
b.dataLabelsGroup.animate({opacity:1,visibility:"visible"})};n.forEach(function(e){var h,n,r=e.node,k=c[r.level];h=e.shapeExisting||{};var u=r.shapeArgs||{},x,y=!(!r.visible||!r.shapeArgs);if(m&&A){var J={};n={end:u.end,start:u.start,innerR:u.innerR,r:u.r,x:u.x,y:u.y};y?!e.graphic&&p&&(J=a===e.id?{start:l.start,end:l.end}:p.end<=u.start?{start:l.end,end:l.end}:{start:l.start,end:l.start},J.innerR=J.r=C):e.graphic&&(d===e.id?n={innerR:C,r:C}:g&&(n=g.end<=h.start?{innerR:C,r:C,start:l.end,end:l.end}:
{innerR:C,r:C,start:l.start,end:l.start}));h=J}else n=u,h={};var J=[u.plotX,u.plotY],z;e.node.isLeaf||(a===e.id?(z=f[a],z=z.parent):z=e.id);E(e,{shapeExisting:u,tooltipPos:J,drillId:z,name:""+(e.name||e.id||e.index),plotX:u.plotX,plotY:u.plotY,value:r.val,isNull:!y});z=e.options;r=w(u)?u:{};z=w(z)?z.dataLabels:{};var k=w(k)?k.dataLabels:{},k=G({style:{}},k,z),H;z=k.rotationMode;q(k.rotation)||("auto"===z&&(1>e.innerArcLength&&e.outerArcLength>r.radius?H=0:z=1<e.innerArcLength&&e.outerArcLength>1.5*
r.radius?"parallel":"perpendicular"),"auto"!==z&&(H=r.end-(r.end-r.start)/2),k.style.width="parallel"===z?Math.min(2.5*r.radius,(e.outerArcLength+e.innerArcLength)/2):r.radius,"perpendicular"===z&&e.series.chart.renderer.fontMetrics(k.style.fontSize).h>e.outerArcLength&&(k.style.width=1),k.style.width=Math.max(k.style.width-2*(k.padding||0),1),H=H*L%180,"parallel"===z&&(H-=90),90<H?H-=180:-90>H&&(H+=180),k.rotation=H);0===k.rotation&&(k.rotation=.001);e.dlOptions=k;!F&&y&&(F=!0,x=B);e.draw({animatableAttribs:n,
attribs:E(h,!t.styledMode&&b.pointAttribs(e,e.selected&&"select")),onComplete:x,group:v,renderer:D,shapeType:"arc",shapeArgs:u})});k&&F?(b.hasRendered=!1,b.options.dataLabels.defer=!0,x.prototype.drawDataLabels.call(b),b.hasRendered=!0,y&&B()):x.prototype.drawDataLabels.call(b)},pointAttribs:b.seriesTypes.column.prototype.pointAttribs,layoutAlgorithm:function(b,c,g){var e=b.start,h=b.end-e,a=b.val,d=b.x,f=b.y,n=g&&w(g.levelSize)&&q(g.levelSize.value)?g.levelSize.value:0,r=b.r,k=r+n,l=g&&q(g.slicedOffset)?
g.slicedOffset:0;return(c||[]).reduce(function(b,c){var g=1/a*c.val*h,p=e+g/2,m=d+Math.cos(p)*l,p=f+Math.sin(p)*l;c={x:c.sliced?m:d,y:c.sliced?p:f,innerR:r,r:k,radius:n,start:e,end:e+g};b.push(c);e=c.end;return b},[])},setShapeArgs:function(b,c,g){var e=[],h=g[b.level+1];b=b.children.filter(function(a){return a.visible});e=this.layoutAlgorithm(c,b,h);b.forEach(function(a,b){b=e[b];var c=b.start+(b.end-b.start)/2,d=b.innerR+(b.r-b.innerR)/2,h=b.end-b.start,d=0===b.innerR&&6.28<h?{x:b.x,y:b.y}:{x:b.x+
Math.cos(c)*d,y:b.y+Math.sin(c)*d},k=a.val?a.childrenTotal>a.val?a.childrenTotal:a.val:a.childrenTotal;this.points[a.i]&&(this.points[a.i].innerArcLength=h*b.innerR,this.points[a.i].outerArcLength=h*b.r);a.shapeArgs=G(b,{plotX:d.x,plotY:d.y+4*Math.abs(Math.cos(c))});a.values=G(b,{val:k});a.children.length&&this.setShapeArgs(a,a.values,g)},this)},translate:function(){var c=this,h=c.options,g=c.center=F.call(c),m=c.startAndEndRadians=I(h.startAngle,h.endAngle),q=g[3]/2,a=g[2]/2-q,d=M(c),f=c.nodeMap,
n,p=f&&f[d],t,w,u={};c.shapeRoot=p&&p.shapeArgs;x.prototype.translate.call(c);w=c.tree=c.getTree();c.renderTraverseUpButton(d);f=c.nodeMap;p=f[d];n=l(p.parent)?p.parent:"";t=f[n];n=A({from:0<p.level?p.level:1,levels:c.options.levels,to:w.height,defaults:{colorByPoint:h.colorByPoint,dataLabels:h.dataLabels,levelIsConstant:h.levelIsConstant,levelSize:h.levelSize,slicedOffset:h.slicedOffset}});n=k(n,{diffRadius:a,from:0<p.level?p.level:1,to:w.height});y(w,{before:B,idRoot:d,levelIsConstant:h.levelIsConstant,
mapOptionsToLevel:n,mapIdToNode:f,points:c.points,series:c});h=f[""].shapeArgs={end:m.end,r:q,start:m.start,val:p.val,x:g[0],y:g[1]};this.setShapeArgs(t,h,n);c.mapOptionsToLevel=n;c.data.forEach(function(a){u[a.id]&&b.error(31,!1,c.chart);u[a.id]=!0});u={}},animate:function(b){var c=this.chart,e=[c.plotWidth/2,c.plotHeight/2],g=c.plotLeft,k=c.plotTop,c=this.group;b?(b={translateX:e[0]+g,translateY:e[1]+k,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},c.attr(b)):(b={translateX:g,translateY:k,scaleX:1,
scaleY:1,rotation:0,opacity:1},c.animate(b,this.options.animation),this.animate=null)},utils:{calculateLevelSizes:k,range:m}},{draw:D,shouldDraw:function(){return!this.isNull},isValid:function(){return!0}})});D(c,"masters/modules/sunburst.src.js",[],function(){})});
//# sourceMappingURL=sunburst.js.map