/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Timeline series

 (c) 2010-2019 Highsoft AS
 Author: Daniel Studencki

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/timeline",["highcharts"],function(e){b(e);b.Highcharts=e;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function e(p,b,e,k){p.hasOwnProperty(b)||(p[b]=k.apply(null,e))}b=b?b._modules:{};e(b,"modules/timeline.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,e){var p=e.isNumber,k=b.addEvent,r=b.defined,
q=b.merge,n=b.pick,v=b.Point,m=b.Series;e=b.seriesType;var t=b.seriesTypes;e("timeline","line",{colorByPoint:!0,stickyTracking:!1,ignoreHiddenPoint:!0,legendType:"point",lineWidth:4,tooltip:{headerFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cspan style\x3d"font-size: 10px"\x3e {point.key}\x3c/span\x3e\x3cbr/\x3e',pointFormat:"{point.description}"},states:{hover:{lineWidthPlus:0}},dataLabels:{enabled:!0,allowOverlap:!0,connectorWidth:1,backgroundColor:"#ffffff",formatter:function(){var a;
a=this.series.chart.styledMode?"\x3cspan\x3e\u25cf \x3c/span\x3e":'\x3cspan style\x3d"color:'+this.point.color+'"\x3e\u25cf \x3c/span\x3e';return a+='\x3cspan class\x3d"highcharts-strong"\x3e'+(this.key||"")+"\x3c/span\x3e\x3cbr/\x3e"+(this.point.label||"")},borderWidth:1,borderColor:"#999999",borderRadius:3,distance:100,alternate:!0,verticalAlign:"middle",color:"#333333",style:{textOutline:"none",fontWeight:"normal",fontSize:"12px"},shadow:!1},marker:{enabledThreshold:0,symbol:"square",radius:6,
lineWidth:2,height:15},showInLegend:!1},{trackerGroups:["markerGroup","dataLabelsGroup"],drawLegendSymbol:b.LegendSymbolMixin.drawRectangle,drawTracker:b.TrackerMixin.drawTrackerPoint,init:function(){var a=this;m.prototype.init.apply(a,arguments);k(a,"afterTranslate",function(){var c,d=Number.MAX_VALUE;a.points.forEach(function(a){a.isInside=a.isInside&&a.visible;a.visible&&!a.isNull&&(r(c)&&(d=Math.min(d,Math.abs(a.plotX-c))),c=a.plotX)});a.closestPointRangePx=d});k(a,"drawDataLabels",function(){a.distributeDL()});
k(a,"afterDrawDataLabels",function(){var c;a.points.forEach(function(a){if(c=a.dataLabel)return c.animate=function(a){this.targetPosition&&(this.targetPosition=a);return b.SVGElement.prototype.animate.apply(this,arguments)},c.targetPosition||(c.targetPosition={}),a.drawConnector()})});k(a.chart,"afterHideOverlappingLabels",function(){a.points.forEach(function(a){a.connector&&a.dataLabel&&a.dataLabel.oldOpacity!==a.dataLabel.newOpacity&&a.alignConnector()})})},alignDataLabel:function(a,c){var d=this.chart.inverted,
b=this.visibilityMap.filter(function(a){return a}),f=this.visiblePointsCount,h=b.indexOf(a),b=this.options.dataLabels,g=a.userDLOptions||{},h=b.alternate?h&&h!==f-1?2:1.5:1,u,f=Math.floor(this.xAxis.len/f),e=c.padding;a.visible&&(u=Math.abs(g.x||a.options.dataLabels.x),d?(d=2*(u-e)-a.itemHeight/2,d={width:d,textOverflow:c.width/d*c.height/2>f*h?"ellipsis":"none"}):d={width:g.width||b.width||f*h-2*e},c.css(d),this.chart.styledMode||c.shadow(b.shadow));m.prototype.alignDataLabel.apply(this,arguments)},
processData:function(){var a=0,c;this.visibilityMap=this.getVisibilityMap();this.visibilityMap.forEach(function(c){c&&a++});this.visiblePointsCount=a;for(c=0;c<this.xData.length;c++)this.yData[c]=1;m.prototype.processData.call(this,arguments)},getXExtremes:function(a){var c=this;a=a.filter(function(a,b){return c.points[b].isValid()&&c.points[b].visible});return{min:b.arrayMin(a),max:b.arrayMax(a)}},generatePoints:function(){var a=this;m.prototype.generatePoints.apply(a);a.points.forEach(function(c,
b){c.applyOptions({x:a.xData[b]},a.xData[b])})},getVisibilityMap:function(){return(this.data.length?this.data:this.userOptions.data).map(function(a){return a&&!1!==a.visible&&!a.isNull?a:!1})},distributeDL:function(){var a=this,c=a.options.dataLabels,b,l,f={},h=1,g=c.distance;a.points.forEach(function(d){d.visible&&!d.isNull&&(b=d.options,l=d.options.dataLabels,a.hasRendered||(d.userDLOptions=q({},l)),f[a.chart.inverted?"x":"y"]=c.alternate&&h%2?-g:g,b.dataLabels=q(f,d.userDLOptions),h++)})},markerAttribs:function(a,
c){var b=this.options.marker,l=a.marker||{},f=l.symbol||b.symbol,h=n(l.width,b.width,this.closestPointRangePx),g=n(l.height,b.height),e=0;if(this.xAxis.isDatetimeAxis)return t.line.prototype.markerAttribs.call(this,a,c);c&&(b=b.states[c]||{},c=l.states&&l.states[c]||{},e=n(c.radius,b.radius,e+(b.radiusPlus||0)));a.hasImage=f&&0===f.indexOf("url");return{x:Math.floor(a.plotX)-h/2-e/2,y:a.plotY-g/2-e/2,width:h+e,height:g+e}},bindAxes:function(){var a=this;m.prototype.bindAxes.call(a);["xAxis","yAxis"].forEach(function(b){"xAxis"!==
b||a[b].userOptions.type||(a[b].categories=a[b].hasNames=!0)})}},{init:function(){var a=v.prototype.init.apply(this,arguments);a.name=n(a.name,"Event");a.y=1;return a},isValid:function(){return null!==this.options.y},setVisible:function(a,b){var c=this.series;b=n(b,c.options.ignoreHiddenPoint);t.pie.prototype.pointClass.prototype.setVisible.call(this,a,!1);c.processData();b&&c.chart.redraw()},setState:function(){var a=m.prototype.pointClass.prototype.setState;this.isNull||a.apply(this,arguments)},
getConnectorPath:function(){var a=this.series.chart,c=this.series.xAxis.len,d=a.inverted,e=d?"x2":"y2",f=this.dataLabel,h=f.targetPosition,g={x1:this.plotX,y1:this.plotY,x2:this.plotX,y2:p(h.y)?h.y:f.y},k=(f.alignAttr||f)[e[0]]<this.series.yAxis.len/2;d&&(g={x1:this.plotY,y1:c-this.plotX,x2:h.x||f.x,y2:c-this.plotX});k&&(g[e]+=f[d?"width":"height"]);b.objectEach(g,function(a,b){g[b]-=(f.alignAttr||f)[b[0]]});return a.renderer.crispLine(["M",g.x1,g.y1,"L",g.x2,g.y2],f.options.connectorWidth)},drawConnector:function(){var a=
this.series;this.connector||(this.connector=a.chart.renderer.path(this.getConnectorPath()).attr({zIndex:-1}).add(this.dataLabel));this.series.chart.isInsidePlot(this.dataLabel.x,this.dataLabel.y)&&this.alignConnector()},alignConnector:function(){var a=this.series,b=this.connector,d=this.dataLabel,e=this.dataLabel.options=q(a.options.dataLabels,this.options.dataLabels),f=this.series.chart,h=b.getBBox(),g=h.x+d.translateX,h=h.y+d.translateY;f.inverted?h-=d.options.connectorWidth/2:g+=d.options.connectorWidth/
2;f=f.isInsidePlot(g,h);b[f?"animate":"attr"]({d:this.getConnectorPath()});a.chart.styledMode||b.attr({stroke:e.connectorColor||this.color,"stroke-width":e.connectorWidth,opacity:d[r(d.newOpacity)?"newOpacity":"opacity"]})}})});e(b,"masters/modules/timeline.src.js",[],function(){})});
//# sourceMappingURL=timeline.js.map