/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 (c) 2014-2019 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/treemap",["highcharts"],function(x){c(x);c.Highcharts=x;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function x(b,f,c,p){b.hasOwnProperty(f)||(b[f]=p.apply(null,c))}c=c?c._modules:{};x(c,"mixins/tree-series.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(b,c){var f=c.isArray,p=c.isNumber,y=b.extend,k=
b.isObject,v=b.merge,m=b.pick;return{getColor:function(l,g){var w=g.index,c=g.mapOptionsToLevel,f=g.parentColor,p=g.parentColorIndex,k=g.series,C=g.colors,y=g.siblings,t=k.points,n=k.chart.options.chart,B,v,z,x;if(l){t=t[l.i];l=c[l.level]||{};if(c=t&&l.colorByPoint)v=t.index%(C?C.length:n.colorCount),B=C&&C[v];if(!k.chart.styledMode){C=t&&t.options.color;n=l&&l.color;if(z=f)z=(z=l&&l.colorVariation)&&"brightness"===z.key?b.color(f).brighten(w/y*z.to).get():f;z=m(C,n,B,z,k.color)}x=m(t&&t.options.colorIndex,
l&&l.colorIndex,v,p,g.colorIndex)}return{color:z,colorIndex:x}},getLevelOptions:function(b){var c=null,w,l,D,m;if(k(b))for(c={},D=p(b.from)?b.from:1,m=b.levels,l={},w=k(b.defaults)?b.defaults:{},f(m)&&(l=m.reduce(function(b,c){var f,g;k(c)&&p(c.level)&&(g=v({},c),f="boolean"===typeof g.levelIsConstant?g.levelIsConstant:w.levelIsConstant,delete g.levelIsConstant,delete g.level,c=c.level+(f?0:D-1),k(b[c])?y(b[c],g):b[c]=g);return b},{})),m=p(b.to)?b.to:1,b=0;b<=m;b++)c[b]=v({},w,k(l[b])?l[b]:{});return c},
setTreeValues:function g(b,c){var f=c.before,p=c.idRoot,k=c.mapIdToNode[p],w=c.points[b.i],v=w&&w.options||{},t=0,n=[];y(b,{levelDynamic:b.level-(("boolean"===typeof c.levelIsConstant?c.levelIsConstant:1)?0:k.level),name:m(w&&w.name,""),visible:p===b.id||("boolean"===typeof c.visible?c.visible:!1)});"function"===typeof f&&(b=f(b,c));b.children.forEach(function(f,p){var k=y({},c);y(k,{index:p,siblings:b.children.length,visible:b.visible});f=g(f,k);n.push(f);f.visible&&(t+=f.val)});b.visible=0<t||b.visible;
f=m(v.value,t);y(b,{children:n,childrenTotal:t,isLeaf:b.visible&&!t,val:f});return b},updateRootId:function(b){var c;k(b)&&(c=k(b.options)?b.options:{},c=m(b.rootNode,c.rootId,""),k(b.userOptions)&&(b.userOptions.rootId=c),b.rootNode=c);return c}}});x(c,"mixins/draw-point.js",[],function(){var b=function(b){var c=this,f=c.graphic,y=b.animatableAttribs,k=b.onComplete,v=b.css,m=b.renderer;if(c.shouldDraw())f||(c.graphic=f=m[b.shapeType](b.shapeArgs).add(b.group)),f.css(v).attr(b.attribs).animate(y,
b.isNew?!1:void 0,k);else if(f){var l=function(){c.graphic=f=f.destroy();"function"===typeof k&&k()};Object.keys(y).length?f.animate(y,void 0,function(){l()}):l()}};return function(c){(c.attribs=c.attribs||{})["class"]=this.getClassName();b.call(this,c)}});x(c,"modules/treemap.src.js",[c["parts/Globals.js"],c["mixins/tree-series.js"],c["mixins/draw-point.js"],c["parts/Utilities.js"]],function(b,c,x,p){var f=p.isArray,k=p.isNumber,v=p.isString;p=b.seriesType;var m=b.seriesTypes,l=b.addEvent,g=b.merge,
w=b.extend,H=b.error,D=b.defined,G=b.noop,I=b.fireEvent,C=c.getColor,J=c.getLevelOptions,t=b.isObject,n=b.pick,B=b.Series,K=b.stableSort,z=b.Color,L=function(a,d,e){e=e||this;b.objectEach(a,function(b,r){d.call(e,b,r,a)})},E=function(a,d,e){e=e||this;a=d.call(e,a);!1!==a&&E(a,d,e)},M=c.updateRootId;p("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=this&&this.point?this.point:{};return v(a.name)?
a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"\x3cb\x3e{point.name}\x3c/b\x3e: {point.value}\x3cbr/\x3e"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,opacity:.15,states:{hover:{borderColor:"#999999",brightness:m.heatmap?0:.1,halo:!1,
opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:G,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,d){a=f(a)?a:[];var e=f(d)?d:[];d=a.reduce(function(a,d,e){d=n(d.parent,"");void 0===a[d]&&(a[d]=[]);a[d].push(e);return a},{"":[]});L(d,function(a,d,b){""!==d&&-1===e.indexOf(d)&&(a.forEach(function(a){b[""].push(a)}),delete b[d])});return d},getTree:function(){var a=
this.data.map(function(a){return a.id}),a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},hasData:function(){return!!this.processedXData.length},init:function(a,d){var e=b.colorSeriesMixin;b.colorSeriesMixin&&(this.translateColors=e.translateColors,this.colorAttribs=e.colorAttribs,this.axisTypes=e.axisTypes);l(this,"setOptions",function(a){a=a.userOptions;D(a.allowDrillToNode)&&!D(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);
D(a.drillUpButton)&&!D(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});B.prototype.init.call(this,a,d);this.options.allowTraversingTree&&l(this,"click",this.onClickDrillToNode)},buildNode:function(a,d,e,b,r){var c=this,q=[],h=c.points[d],F=0,u;(b[a]||[]).forEach(function(d){u=c.buildNode(c.points[d].id,d,e+1,b,a);F=Math.max(u.height+1,F);q.push(u)});d={id:a,i:d,children:q,height:F,level:e,parent:r,visible:!1};c.nodeMap[d.id]=d;h&&(h.node=d);return d},setTreeValues:function(a){var d=
this,e=d.options,b=d.nodeMap[d.rootNode],e="boolean"===typeof e.levelIsConstant?e.levelIsConstant:!0,r=0,c=[],A,h=d.points[a.i];a.children.forEach(function(a){a=d.setTreeValues(a);c.push(a);a.ignore||(r+=a.val)});K(c,function(a,d){return a.sortIndex-d.sortIndex});A=n(h&&h.options.value,r);h&&(h.value=A);w(a,{children:c,childrenTotal:r,ignore:!(n(h&&h.visible,!0)&&0<A),isLeaf:a.visible&&!r,levelDynamic:a.level-(e?0:b.level),name:n(h&&h.name,""),sortIndex:n(h&&h.sortIndex,-A),val:A});return a},calculateChildrenAreas:function(a,
d){var e=this,b=e.options,c=e.mapOptionsToLevel[a.level+1],N=n(e[c&&c.layoutAlgorithm]&&c.layoutAlgorithm,b.layoutAlgorithm),A=b.alternateStartingDirection,h=[];a=a.children.filter(function(a){return!a.ignore});c&&c.layoutStartingDirection&&(d.direction="vertical"===c.layoutStartingDirection?0:1);h=e[N](d,a);a.forEach(function(a,b){b=h[b];a.values=g(b,{val:a.childrenTotal,direction:A?1-d.direction:d.direction});a.pointValues=g(b,{x:b.x/e.axisRatio,width:b.width/e.axisRatio});a.children.length&&e.calculateChildrenAreas(a,
a.values)})},setPointValues:function(){var a=this,d=a.xAxis,e=a.yAxis;a.points.forEach(function(b){var c=b.node,q=c.pointValues,A,h,f=0;a.chart.styledMode||(f=(a.pointAttribs(b)["stroke-width"]||0)%2/2);q&&c.visible?(c=Math.round(d.translate(q.x,0,0,0,1))-f,A=Math.round(d.translate(q.x+q.width,0,0,0,1))-f,h=Math.round(e.translate(q.y,0,0,0,1))-f,q=Math.round(e.translate(q.y+q.height,0,0,0,1))-f,b.shapeArgs={x:Math.min(c,A),y:Math.min(h,q),width:Math.abs(A-c),height:Math.abs(q-h)},b.plotX=b.shapeArgs.x+
b.shapeArgs.width/2,b.plotY=b.shapeArgs.y+b.shapeArgs.height/2):(delete b.plotX,delete b.plotY)})},setColorRecursive:function(a,d,b,c,r){var e=this,q=e&&e.chart,q=q&&q.options&&q.options.colors,h;if(a){h=C(a,{colors:q,index:c,mapOptionsToLevel:e.mapOptionsToLevel,parentColor:d,parentColorIndex:b,series:e,siblings:r});if(d=e.points[a.i])d.color=h.color,d.colorIndex=h.colorIndex;(a.children||[]).forEach(function(d,b){e.setColorRecursive(d,h.color,h.colorIndex,b,a.children.length)})}},algorithmGroup:function(a,
d,b,c){this.height=a;this.width=d;this.plot=c;this.startDirection=this.direction=b;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,d){return Math.max(a/d,d/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/
this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,d,e,c){var r,q,f,h,k=e.lW,u=e.lH,g=e.plot,l,p=0,n=e.elArr.length-1;d?(k=e.nW,u=e.nH):l=e.elArr[e.elArr.length-
1];e.elArr.forEach(function(a){if(d||p<n)0===e.direction?(r=g.x,q=g.y,f=k,h=a/f):(r=g.x,q=g.y,h=u,f=a/h),c.push({x:r,y:q,width:f,height:b.correctFloat(h)}),0===e.direction?g.y+=h:g.x+=f;p+=1});e.reset();0===e.direction?e.width-=k:e.height-=u;g.y=g.parent.y+(g.parent.height-e.height);g.x=g.parent.x+(g.parent.width-e.width);a&&(e.direction=1-e.direction);d||e.addElement(l)},algorithmLowAspectRatio:function(a,d,b){var e=[],c=this,f,g={x:d.x,y:d.y,parent:d},h=0,k=b.length-1,u=new this.algorithmGroup(d.height,
d.width,d.direction,g);b.forEach(function(b){f=b.val/d.val*d.height*d.width;u.addElement(f);u.lP.nR>u.lP.lR&&c.algorithmCalcPoints(a,!1,u,e,g);h===k&&c.algorithmCalcPoints(a,!0,u,e,g);h+=1});return e},algorithmFill:function(a,d,b){var e=[],c,f=d.direction,g=d.x,h=d.y,k=d.width,u=d.height,l,p,n,m;b.forEach(function(b){c=b.val/d.val*d.height*d.width;l=g;p=h;0===f?(m=u,n=c/m,k-=n,g+=n):(n=k,m=c/n,u-=m,h+=m);e.push({x:l,y:p,width:n,height:m});a&&(f=1-f)});return e},strip:function(a,d){return this.algorithmLowAspectRatio(!1,
a,d)},squarified:function(a,d){return this.algorithmLowAspectRatio(!0,a,d)},sliceAndDice:function(a,d){return this.algorithmFill(!0,a,d)},stripes:function(a,d){return this.algorithmFill(!1,a,d)},translate:function(){var a=this,d=a.options,b=M(a),c,r;B.prototype.translate.call(a);r=a.tree=a.getTree();c=a.nodeMap[b];a.renderTraverseUpButton(b);a.mapOptionsToLevel=J({from:c.level+1,levels:d.levels,to:r.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:d.colorByPoint}});""===b||
c&&c.children.length||(a.setRootNode("",!1),b=a.rootNode,c=a.nodeMap[b]);E(a.nodeMap[a.rootNode],function(d){var b=!1,c=d.parent;d.visible=!0;if(c||""===c)b=a.nodeMap[c];return b});E(a.nodeMap[a.rootNode].children,function(a){var d=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(d=(d||[]).concat(a.children))});return d});a.setTreeValues(r);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=b={x:0,y:0,width:100,height:100};a.nodeMap[""].values=b=g(b,{width:b.width*a.axisRatio,
direction:"vertical"===d.layoutStartingDirection?0:1,val:r.val});a.calculateChildrenAreas(r,b);a.colorAxis?a.translateColors():d.colorByPoint||a.setColorRecursive(a.tree);d.allowTraversingTree&&(d=c.pointValues,a.xAxis.setExtremes(d.x,d.x+d.width,!1),a.yAxis.setExtremes(d.y,d.y+d.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,d=a.mapOptionsToLevel,b,c;a.points.filter(function(a){return a.node.visible}).forEach(function(e){c=d[e.node.level];
b={style:{}};e.node.isLeaf||(b.enabled=!1);c&&c.dataLabels&&(b=g(b,c.dataLabels),a._hasPointLabels=!0);e.shapeArgs&&(b.style.width=e.shapeArgs.width,e.dataLabel&&e.dataLabel.css({width:e.shapeArgs.width+"px"}));e.dlOptions=g(b,e.options.dataLabels)});B.prototype.drawDataLabels.call(this)},alignDataLabel:function(a,d,c){var e=c.style;!b.defined(e.textOverflow)&&d.text&&d.getBBox().width>d.text.textWidth&&d.css({textOverflow:"ellipsis",width:e.width+="px"});m.column.prototype.alignDataLabel.apply(this,
arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var d=t(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},c=a&&d[a.node.level]||{},d=this.options,f=b&&d.states[b]||{},g=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||c.borderColor||f.borderColor||d.borderColor,"stroke-width":n(a&&a.borderWidth,c.borderWidth,f.borderWidth,d.borderWidth),dashstyle:a&&a.borderDashStyle||c.borderDashStyle||f.borderDashStyle||d.borderDashStyle,fill:a&&a.color||this.color};
-1!==g.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==g.indexOf("highcharts-internal-node-interactive")?(b=n(f.opacity,d.opacity),a.fill=z(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==g.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=z(a.fill).brighten(f.brightness).get());return a},drawPoints:function(){var a=this,b=a.chart,c=b.renderer,f=b.styledMode,r=a.options,k=f?{}:r.shadow,l=r.borderRadius,h=b.pointCount<r.animationLimit,n=r.allowTraversingTree;
a.points.forEach(function(b){var d=b.node.levelDynamic,e={},q={},p={},m="level-group-"+d,t=!!b.graphic,u=h&&t,v=b.shapeArgs;b.shouldDraw()&&(l&&(q.r=l),g(!0,u?e:q,t?v:{},f?{}:a.pointAttribs(b,b.selected&&"select")),a.colorAttribs&&f&&w(p,a.colorAttribs(b)),a[m]||(a[m]=c.g(m).attr({zIndex:1E3-d}).add(a.group)));b.draw({animatableAttribs:e,attribs:q,css:p,group:a[m],renderer:c,shadow:k,shapeArgs:v,shapeType:"rect"});n&&b.graphic&&(b.drillId=r.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},
onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;v(b)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&v(a.parent)&&this.setRootNode(a.parent,
!0,{trigger:"traverseUpButton"})},drillToNode:function(a,b){H("WARNING: treemap.drillToNode has been renamed to treemap.setRootNode, and will be removed in the next major version.");this.setRootNode(a,b)},setRootNode:function(a,b,c){a=w({newRootId:a,previousRootId:this.rootNode,redraw:n(b,!0),series:this},c);I(this,"setRootNode",a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})},renderTraverseUpButton:function(a){var b=
this,c=b.options.traverseUpButton,f=n(c.text,b.nodeMap[a].name,"\x3c Back"),g;""===a?b.drillUpButton&&(b.drillUpButton=b.drillUpButton.destroy()):this.drillUpButton?(this.drillUpButton.placed=!1,this.drillUpButton.attr({text:f}).align()):(g=(a=c.theme)&&a.states,this.drillUpButton=this.chart.renderer.button(f,null,null,function(){b.drillUp()},a,g&&g.hover,g&&g.select).addClass("highcharts-drillup-button").attr({align:c.position.align,zIndex:7}).add().align(c.position,!1,c.relativeTo||"plotBox"))},
buildKDTree:G,drawLegendSymbol:b.LegendSymbolMixin.drawRectangle,getExtremes:function(){B.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;B.prototype.getExtremes.call(this)},getExtremesFromAll:!0,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};B.prototype.bindAxes.call(this);b.extend(this.yAxis.options,a);b.extend(this.xAxis.options,
a)},setState:function(a){this.options.inactiveOtherPoints=!0;B.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:E}},{draw:x,getClassName:function(){var a=b.Point.prototype.getClassName.call(this),c=this.series,e=c.options;this.node.level<=c.nodeMap[c.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||n(e.interactByLeaf,!e.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},
isValid:function(){return this.id||k(this.value)},setState:function(a){b.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},setVisible:m.pie.prototype.pointClass.prototype.setVisible,shouldDraw:function(){return k(this.plotY)&&null!==this.y}})});x(c,"masters/modules/treemap.src.js",[],function(){})});
//# sourceMappingURL=treemap.js.map