/*
 Highcharts Gantt JS v7.1.2-modified (2019-07-03)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(k){"object"===typeof module&&module.exports?(k["default"]=k,module.exports=k):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(z){k(z);k.Highcharts=z;return k}):k("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(k){function z(c,k,E,u){c.hasOwnProperty(k)||(c[k]=u.apply(null,E))}k=k?k._modules:{};z(k,"parts-gantt/GridAxis.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(c,k){var A=k.isArray,u=k.isNumber,w=c.addEvent,
y=c.dateFormat,x=c.defined,r=function(a){return c.isObject(a,!0)},g=c.merge,q=c.pick,d=c.wrap;k=c.Chart;var e=c.Axis,m=c.Tick,l=function(a){var b=a.options,h=b&&r(b.grid)?b.grid:{},f=25/11,d=a.chart.renderer.fontMetrics(b.labels.style.fontSize);b.labels||(b.labels={});b.labels.align=q(b.labels.align,"center");a.categories||(b.showLastLabel=!1);a.horiz&&(b.tickLength=h.cellHeight||d.h*f);a.labelRotation=0;b.labels.rotation=0},f={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};
e.prototype.isOuterAxis=function(){var a=this,b=a.columnIndex,h=a.linkedParent&&a.linkedParent.columns||a.columns,f=b?a.linkedParent:a,d=-1,e=0;a.chart[a.coll].forEach(function(b,h){b.side!==a.side||b.options.isInternal||(e=h,b===f&&(d=h))});return e===d&&(u(b)?h.length===b:!0)};e.prototype.getMaxLabelDimensions=function(a,b){var h={width:0,height:0};b.forEach(function(b){b=a[b];var f;r(b)&&(f=r(b.label)?b.label:{},b=f.getBBox?f.getBBox().height:0,f.textStr&&!u(f.textPxLength)&&(f.textPxLength=f.getBBox().width),
f=u(f.textPxLength)?f.textPxLength:0,h.height=Math.max(b,h.height),h.width=Math.max(f,h.width))});return h};c.dateFormats.W=function(a){a=new Date(a);var b;a.setHours(0,0,0,0);a.setDate(a.getDate()-(a.getDay()||7));b=new Date(a.getFullYear(),0,1);return Math.ceil(((a-b)/864E5+1)/7)};c.dateFormats.E=function(a){return y("%a",a,!0).charAt(0)};w(m,"afterGetLabelPosition",function(a){var b=this.label,h=this.axis,d=h.reversed,e=h.chart,t=h.options,m=t&&r(t.grid)?t.grid:{},t=h.options.labels,l=t.align,
c=f[h.side],g=a.tickmarkOffset,v=h.tickPositions,p=this.pos-g,v=u(v[a.index+1])?v[a.index+1]-g:h.max+g,B=h.tickSize("tick",!0),g=A(B)?B[0]:0,B=B&&B[1]/2,C;!0===m.enabled&&("top"===c?(m=h.top+h.offset,C=m-g):"bottom"===c?(C=e.chartHeight-h.bottom+h.offset,m=C+g):(m=h.top+h.len-h.translate(d?v:p),C=h.top+h.len-h.translate(d?p:v)),"right"===c?(c=e.chartWidth-h.right+h.offset,d=c+g):"left"===c?(d=h.left+h.offset,c=d-g):(c=Math.round(h.left+h.translate(d?v:p))-B,d=Math.round(h.left+h.translate(d?p:v))-
B),this.slotWidth=d-c,a.pos.x="left"===l?c:"right"===l?d:c+(d-c)/2,a.pos.y=C+(m-C)/2,e=e.renderer.fontMetrics(t.style.fontSize,b.element),b=b.getBBox().height,t.useHTML?a.pos.y+=e.b+-(b/2):(b=Math.round(b/e.h),a.pos.y+=(e.b-(e.h-e.f))/2+-((b-1)*e.h/2)),a.pos.x+=h.horiz&&t.x||0)});w(e,"afterTickSize",function(a){var b=this.maxLabelDimensions,h=this.options;!0===(h&&r(h.grid)?h.grid:{}).enabled&&(h=2*Math.abs(this.defaultLeftAxisOptions.labels.x),b=h+(this.horiz?b.height:b.width),A(a.tickSize)?a.tickSize[0]=
b:a.tickSize=[b])});w(e,"afterGetTitlePosition",function(a){var b=this.options;if(!0===(b&&r(b.grid)?b.grid:{}).enabled){var h=this.axisTitle,d=h&&h.getBBox().width,e=this.horiz,m=this.left,c=this.top,l=this.width,g=this.height,n=b.title,b=this.opposite,v=this.offset,p=this.tickSize()||[0],B=n.x||0,C=n.y||0,H=q(n.margin,e?5:10),h=this.chart.renderer.fontMetrics(n.style&&n.style.fontSize,h).f,p=(e?c+g:m)+p[0]/2*(b?-1:1)*(e?1:-1)+(this.side===f.bottom?h:0);a.titlePosition.x=e?m-d/2-H+B:p+(b?l:0)+v+
B;a.titlePosition.y=e?p-(b?g:0)+(b?h:-h)/2+v+C:c-H+C}});d(e.prototype,"unsquish",function(a){var b=this.options;return!0===(b&&r(b.grid)?b.grid:{}).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))});w(e,"afterSetOptions",function(a){var b=this.options;a=a.userOptions;var h,f=b&&r(b.grid)?b.grid:{};!0===f.enabled&&(h=g(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b",
"%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a),"xAxis"===this.coll&&(x(a.linkedTo)&&!x(a.tickPixelInterval)&&(h.tickPixelInterval=350),x(a.tickPixelInterval)||!x(a.linkedTo)||x(a.tickPositioner)||x(a.tickInterval)||(h.tickPositioner=
function(a,b){var f=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(f){var d,e,m,v,p=h.units;for(v=0;v<p.length;v++)if(p[v][0]===f.unitName){d=v;break}if(p[d][1])return p[d+1]&&(m=p[d+1][0],e=(p[d+1][1]||[1])[0]),f=c.timeUnits[m],this.tickInterval=f*e,this.getTimeTicks({unitRange:f,count:e,unitName:m},a,b,this.options.startOfWeek)}})),g(!0,this.options,h),this.horiz&&(b.minPadding=q(a.minPadding,0),b.maxPadding=q(a.maxPadding,0)),u(b.grid.borderWidth)&&
(b.tickWidth=b.lineWidth=f.borderWidth))});w(e,"afterSetAxisTranslation",function(){var a=this.options,b=a&&r(a.grid)?a.grid:{},f=this.tickPositions&&this.tickPositions.info,d=this.userOptions.labels||{};this.horiz&&(!0===b.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),f&&(!1===a.dateTimeLabelFormats[f.unitName].range||1<f.count)&&!x(d.align)&&(a.labels.align="left",x(d.x)||(a.labels.x=3)))});w(e,"trimTicks",function(){var a=this.options,b=a&&r(a.grid)?a.grid:{},f=this.categories,
d=this.tickPositions,e=d[0],m=d[d.length-1],c=this.linkedParent&&this.linkedParent.min||this.min,l=this.linkedParent&&this.linkedParent.max||this.max,g=this.tickInterval;!0!==b.enabled||f||!this.horiz&&!this.isLinked||(e<c&&e+g>c&&!a.startOnTick&&(d[0]=c),m>l&&m-g<l&&!a.endOnTick&&(d[d.length-1]=l))});w(e,"afterRender",function(){var a=this.options,b=a&&r(a.grid)?a.grid:{},d,e,m,c,l,g,n=this.chart.renderer,q=this.horiz;if(!0===b.enabled){b=2*Math.abs(this.defaultLeftAxisOptions.labels.x);this.maxLabelDimensions=
this.getMaxLabelDimensions(this.ticks,this.tickPositions);b=this.maxLabelDimensions.width+b;d=a.lineWidth;this.rightWall&&this.rightWall.destroy();e=this.axisGroup.getBBox();if(this.isOuterAxis()&&this.axisLine&&(q&&(b=e.height-1),d)){e=this.getLinePath(d);l=e.indexOf("M")+1;g=e.indexOf("L")+1;m=e.indexOf("M")+2;c=e.indexOf("L")+2;if(this.side===f.top||this.side===f.left)b=-b;q?(e[m]+=b,e[c]+=b):(e[l]+=b,e[g]+=b);this.axisLineExtra?this.axisLineExtra.animate({d:e}):this.axisLineExtra=n.path(e).attr({stroke:a.lineColor,
"stroke-width":d,zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup);this.axisLine[this.showAxis?"show":"hide"](!0)}(this.columns||[]).forEach(function(a){a.render()})}});var n={afterGetOffset:function(){(this.columns||[]).forEach(function(a){a.getOffset()})},afterInit:function(){var a=this.chart,b=this.userOptions,f=this.options,f=f&&r(f.grid)?f.grid:{};f.enabled&&(l(this),d(this,"labelFormatter",function(a){var b=this.axis,f=b.tickPositions,d=this.value,e=(b.isLinked?b.linkedParent:
b).series[0],p=d===f[0],f=d===f[f.length-1],e=e&&c.find(e.options.data,function(a){return a[b.isXAxis?"x":"y"]===d});this.isFirst=p;this.isLast=f;this.point=e;return a.call(this)}));if(f.columns)for(var m=this.columns=[],n=this.columnIndex=0;++n<f.columns.length;){var t=g(b,f.columns[f.columns.length-n-1],{linkedTo:0,type:"category"});delete t.grid.columns;t=new e(this.chart,t,!0);t.isColumn=!0;t.columnIndex=n;c.erase(a.axes,t);c.erase(a[this.coll],t);m.push(t)}},afterSetOptions:function(a){a=(a=
a.userOptions)&&r(a.grid)?a.grid:{};var b=a.columns;a.enabled&&b&&g(!0,this.options,b[b.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(a){a.setScale()})},destroy:function(a){(this.columns||[]).forEach(function(b){b.destroy(a.keepEvents)})},init:function(a){var b=(a=a.userOptions)&&r(a.grid)?a.grid:{};b.enabled&&x(b.borderColor)&&(a.tickColor=a.lineColor=b.borderColor)}};Object.keys(n).forEach(function(a){w(e,a,n[a])});w(k,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.columns||
[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})})});z(k,"parts-gantt/Tree.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(c,k){var A=k.isNumber,u=c.extend,w=c.pick,y=function(c,g){var q=c.reduce(function(d,e){var m=w(e.parent,"");void 0===d[m]&&(d[m]=[]);d[m].push(e);return d},{});Object.keys(q).forEach(function(d,e){var m=q[d];""!==d&&-1===g.indexOf(d)&&(m.forEach(function(d){e[""].push(d)}),delete e[d])});return q},x=function(c,g,q,d,e,m){var l=0,f=0,n=m&&m.after,
a=m&&m.before;g={data:d,depth:q-1,id:c,level:q,parent:g};var b,h;"function"===typeof a&&a(g,m);a=(e[c]||[]).map(function(a){var d=x(a.id,c,q+1,a,e,m),g=a.start;a=!0===a.milestone?g:a.end;b=!A(b)||g<b?g:b;h=!A(h)||a>h?a:h;l=l+1+d.descendants;f=Math.max(d.height+1,f);return d});d&&(d.start=w(d.start,b),d.end=w(d.end,h));u(g,{children:a,descendants:l,height:f});"function"===typeof n&&n(g,m);return g};return{getListOfParents:y,getNode:x,getTree:function(c,g){var q=c.map(function(d){return d.id});c=y(c,
q);return x("",null,1,null,c,g)}}});z(k,"mixins/tree-series.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(c,k){var A=k.isArray,u=k.isNumber,w=c.extend,y=c.isObject,x=c.merge,r=c.pick;return{getColor:function(g,q){var d=q.index,e=q.mapOptionsToLevel,m=q.parentColor,l=q.parentColorIndex,f=q.series,n=q.colors,a=q.siblings,b=f.points,h=f.chart.options.chart,k,D,t,u;if(g){b=b[g.i];g=e[g.level]||{};if(e=b&&g.colorByPoint)D=b.index%(n?n.length:h.colorCount),k=n&&n[D];if(!f.chart.styledMode){n=
b&&b.options.color;h=g&&g.color;if(t=m)t=(t=g&&g.colorVariation)&&"brightness"===t.key?c.color(m).brighten(d/a*t.to).get():m;t=r(n,h,k,t,f.color)}u=r(b&&b.options.colorIndex,g&&g.colorIndex,D,l,q.colorIndex)}return{color:t,colorIndex:u}},getLevelOptions:function(c){var g=null,d,e,m,l;if(y(c))for(g={},m=u(c.from)?c.from:1,l=c.levels,e={},d=y(c.defaults)?c.defaults:{},A(l)&&(e=l.reduce(function(f,e){var a,b;y(e)&&u(e.level)&&(b=x({},e),a="boolean"===typeof b.levelIsConstant?b.levelIsConstant:d.levelIsConstant,
delete b.levelIsConstant,delete b.level,e=e.level+(a?0:m-1),y(f[e])?w(f[e],b):f[e]=b);return f},{})),l=u(c.to)?c.to:1,c=0;c<=l;c++)g[c]=x({},d,y(e[c])?e[c]:{});return g},setTreeValues:function q(d,e){var c=e.before,l=e.idRoot,f=e.mapIdToNode[l],n=e.points[d.i],a=n&&n.options||{},b=0,h=[];w(d,{levelDynamic:d.level-(("boolean"===typeof e.levelIsConstant?e.levelIsConstant:1)?0:f.level),name:r(n&&n.name,""),visible:l===d.id||("boolean"===typeof e.visible?e.visible:!1)});"function"===typeof c&&(d=c(d,
e));d.children.forEach(function(a,f){var c=w({},e);w(c,{index:f,siblings:d.children.length,visible:d.visible});a=q(a,c);h.push(a);a.visible&&(b+=a.val)});d.visible=0<b||d.visible;c=r(a.value,b);w(d,{children:h,childrenTotal:b,isLeaf:d.visible&&!b,val:c});return d},updateRootId:function(c){var d;y(c)&&(d=y(c.options)?c.options:{},d=r(c.rootNode,d.rootId,""),y(c.userOptions)&&(c.userOptions.rootId=d),c.rootNode=d);return d}}});z(k,"modules/broken-axis.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],
function(c,k){var A=k.isArray;k=c.addEvent;var u=c.pick,w=c.extend,y=c.find,x=c.fireEvent,r=c.Axis,g=c.Series,q=function(d,e){return y(e,function(e){return e.from<d&&d<e.to})};w(r.prototype,{isInBreak:function(d,e){var c=d.repeat||Infinity,l=d.from,f=d.to-d.from;e=e>=l?(e-l)%c:c-(l-e)%c;return d.inclusive?e<=f:e<f&&0!==e},isInAnyBreak:function(d,e){var c=this.options.breaks,l=c&&c.length,f,g,a;if(l){for(;l--;)this.isInBreak(c[l],d)&&(f=!0,g||(g=u(c[l].showPoints,!this.isXAxis)));a=f&&e?f&&!g:f}return a}});
k(r,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});k(r,"afterSetTickPositions",function(){if(this.isBroken){var d=this.tickPositions,e=this.tickPositions.info,c=[],l;for(l=0;l<d.length;l++)this.isInAnyBreak(d[l])||c.push(d[l]);this.tickPositions=c;this.tickPositions.info=e}});k(r,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});r.prototype.setBreaks=function(d,e){function c(a){var b=a,d,c;for(c=0;c<f.breakArray.length;c++)if(d=
f.breakArray[c],d.to<=a)b-=d.len;else if(d.from>=a)break;else if(f.isInBreak(d,a)){b-=a-d.from;break}return b}function l(a){var b,d;for(d=0;d<f.breakArray.length&&!(b=f.breakArray[d],b.from>=a);d++)b.to<a?a+=b.len:f.isInBreak(b,a)&&(a+=b.len);return a}var f=this,g=A(d)&&!!d.length;f.isDirty=f.isBroken!==g;f.isBroken=g;f.options.breaks=f.userOptions.breaks=d;f.forceRedraw=!0;g||f.val2lin!==c||(delete f.val2lin,delete f.lin2val);g&&(f.userOptions.ordinal=!1,f.val2lin=c,f.lin2val=l,f.setExtremes=function(a,
b,d,f,c){if(this.isBroken){for(var e,h=this.options.breaks;e=q(a,h);)a=e.to;for(;e=q(b,h);)b=e.from;b<a&&(b=a)}r.prototype.setExtremes.call(this,a,b,d,f,c)},f.setAxisTranslation=function(a){r.prototype.setAxisTranslation.call(this,a);this.unitLength=null;if(this.isBroken){a=f.options.breaks;var b=[],d=[],c=0,e,l,g=f.userMin||f.min,m=f.userMax||f.max,k=u(f.pointRangePadding,0),n,v;a.forEach(function(a){l=a.repeat||Infinity;f.isInBreak(a,g)&&(g+=a.to%l-g%l);f.isInBreak(a,m)&&(m-=m%l-a.from%l)});a.forEach(function(a){n=
a.from;for(l=a.repeat||Infinity;n-l>g;)n-=l;for(;n<g;)n+=l;for(v=n;v<m;v+=l)b.push({value:v,move:"in"}),b.push({value:v+(a.to-a.from),move:"out",size:a.breakSize})});b.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});e=0;n=g;b.forEach(function(a){e+="in"===a.move?1:-1;1===e&&"in"===a.move&&(n=a.value);0===e&&(d.push({from:n,to:a.value,len:a.value-n-(a.size||0)}),c+=a.value-n-(a.size||0))});f.breakArray=d;f.unitLength=m-g-c+k;x(f,"afterBreaks");
f.staticScale?f.transA=f.staticScale:f.unitLength&&(f.transA*=(m-f.min+k)/f.unitLength);k&&(f.minPixelPadding=f.transA*f.minPointOffset);f.min=g;f.max=m}});u(e,!0)&&this.chart.redraw()};k(g,"afterGeneratePoints",function(){var d=this.xAxis,c=this.yAxis,g=this.points,l,f=g.length,k=this.options.connectNulls,a;if(d&&c&&(d.options.breaks||c.options.breaks))for(;f--;)l=g[f],a=null===l.y&&!1===k,a||!d.isInAnyBreak(l.x,!0)&&!c.isInAnyBreak(l.y,!0)||(g.splice(f,1),this.data[f]&&this.data[f].destroyElements())});
k(g,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,u(this.pointArrayMap,["y"]))});c.Series.prototype.drawBreaks=function(d,c){var e=this,l=e.points,f,g,a,b;d&&c.forEach(function(c){f=d.breakArray||[];g=d.isXAxis?d.min:u(e.options.threshold,d.min);l.forEach(function(e){b=u(e["stack"+c.toUpperCase()],e[c]);f.forEach(function(c){a=!1;if(g<c.from&&b>c.to||g>c.from&&b<c.from)a="pointBreak";else if(g<c.from&&b>c.from&&b<c.to||g>c.from&&b>c.to&&b<c.from)a="pointInBreak";
a&&x(d,a,{point:e,brk:c})})})})};c.Series.prototype.gappedPath=function(){var d=this.currentDataGrouping,e=d&&d.gapSize,d=this.options.gapSize,g=this.points.slice(),l=g.length-1,f=this.yAxis;if(d&&0<l)for("value"!==this.options.gapUnit&&(d*=this.closestPointRange),e&&e>d&&(d=e);l--;)g[l+1].x-g[l].x>d&&(e=(g[l].x+g[l+1].x)/2,g.splice(l+1,0,{isNull:!0,x:e}),this.options.stacking&&(e=f.stacks[this.stackKey][e]=new c.StackItem(f,f.options.stackLabels,!1,e,this.stack),e.total=0));return this.getGraphPath(g)}});
z(k,"parts-gantt/TreeGrid.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["parts-gantt/Tree.js"],k["mixins/tree-series.js"]],function(c,k,z,u){var w=k.isNumber,y=k.isString,x=c.addEvent,r=function(a){return Array.prototype.slice.call(a,1)},g=c.defined;k=c.extend;var q=c.find,d=c.fireEvent,e=u.getLevelOptions,m=c.merge,l=function(a){return c.isObject(a,!0)},f=c.pick,n=c.wrap;u=c.Axis;var a=c.Tick,b=function(a,b){var c,d;for(c in b)b.hasOwnProperty(c)&&(d=b[c],n(a,c,d))},h=function(a,b){var c=
a.collapseStart;a=a.collapseEnd;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}},A=function(a){return Object.keys(a.mapOfPosToGridNode).reduce(function(b,c){c=+c;a.min<=c&&a.max>=c&&!a.isInAnyBreak(c)&&b.push(c);return b},[])},D=function(a,c){var b=a.options.breaks||[],d=h(c,a.max);return b.some(function(a){return a.from===d.from&&a.to===d.to})},t=function(a,c){var b=a.options.breaks||[];a=h(c,a.max);b.push(a);return b},F=function(a,c){var b=a.options.breaks||[],d=h(c,a.max);return b.reduce(function(a,
c){c.to===d.to&&c.from===d.from||a.push(c);return a},[])},E=function(a,c){var b=a.labelIcon,d=!b,e=c.renderer,g=c.xy,p=c.options,l=p.width,h=p.height,k=g.x-l/2-p.padding,g=g.y-h/2,m=c.collapsed?90:180,v=c.show&&w(g);d&&(a.labelIcon=b=e.path(e.symbols[p.type](p.x,p.y,l,h)).addClass("highcharts-label-icon").add(c.group));v||b.attr({y:-9999});e.styledMode||b.attr({"stroke-width":1,fill:f(c.color,"#666666")}).css({cursor:"pointer",stroke:p.lineColor,strokeWidth:p.lineWidth});b[d?"attr":"animate"]({translateX:k,
translateY:g,rotation:m})},I=function(a,c,b){var d=[],e=[],f={},g={},p=-1,h="boolean"===typeof c?c:!1;a=z.getTree(a,{after:function(a){a=g[a.pos];var c=0,b=0;a.children.forEach(function(a){b+=a.descendants+1;c=Math.max(a.height+1,c)});a.descendants=b;a.height=c;a.collapsed&&e.push(a)},before:function(a){var c=l(a.data)?a.data:{},b=y(c.name)?c.name:"",e=f[a.parent],e=l(e)?g[e.pos]:null,k=function(a){return a.name===b},m;h&&l(e)&&(m=q(e.children,k))?(k=m.pos,m.nodes.push(a)):k=p++;g[k]||(g[k]=m={depth:e?
e.depth+1:0,name:b,nodes:[a],children:[],pos:k},-1!==k&&d.push(b),l(e)&&e.children.push(m));y(a.id)&&(f[a.id]=a);!0===c.collapsed&&(m.collapsed=!0);a.pos=k}});g=function(a,c){var b=function(a,d,e){var f=d+(-1===d?0:c-1),g=(f-d)/2,p=d+g;a.nodes.forEach(function(a){var c=a.data;l(c)&&(c.y=d+c.seriesIndex,delete c.seriesIndex);a.pos=p});e[p]=a;a.pos=p;a.tickmarkOffset=g+.5;a.collapseStart=f+.5;a.children.forEach(function(a){b(a,f+1,e);f=a.collapseEnd-.5});a.collapseEnd=f+.5;return e};return b(a["-1"],
-1,{})}(g,b);return{categories:d,mapOfIdToNode:f,mapOfPosToGridNode:g,collapsedNodes:e,tree:a}},G=function(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(b){var d=b.options||{},f=d.labels,g,h=d.uniqueNames,p=0,k;if(!b.mapOfPosToGridNode||b.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty}))d=b.series.reduce(function(a,b){b.visible&&(b.options.data.forEach(function(b){l(b)&&(b.seriesIndex=p,a.push(b))}),!0===h&&p++);return a},[]),k=I(d,
h,!0===h?p:1),b.categories=k.categories,b.mapOfPosToGridNode=k.mapOfPosToGridNode,b.hasNames=!0,b.tree=k.tree,b.series.forEach(function(a){var b=a.options.data.map(function(a){return l(a)?m(a):a});a.visible&&a.setData(b,!1)}),b.mapOptionsToLevel=e({defaults:f,from:1,levels:f.levels,to:b.tree.height}),"beforeRender"===a.type&&(g=c.addEvent(b,"foundExtremes",function(){k.collapsedNodes.forEach(function(a){a=t(b,a);b.setBreaks(a,!1)});g()}))})};b(u.prototype,{init:function(a,b,c){var d="treegrid"===
c.type;d&&(x(b,"beforeRender",G),x(b,"beforeRedraw",G),c=m({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));a.apply(this,[b,c]);d&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(a){var b=this.options,c=b&&b.labels,b=c&&w(c.indentation)?b.labels.indentation:0,c=a.apply(this,r(arguments)),d;"treegrid"===
this.options.type&&this.mapOfPosToGridNode&&(d=this.mapOfPosToGridNode[-1].height,c.width+=b*(d-1));return c},generateTick:function(b,c){var d=l(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},e=this.ticks,f=e[c],g,h;"treegrid"===this.options.type?(h=this.mapOfPosToGridNode[c],(d=d[h.depth])&&(g={labels:d}),f?(f.parameters.category=h.name,f.options=g,f.addLabel()):e[c]=new a(this,c,null,void 0,{category:h.name,tickmarkOffset:h.tickmarkOffset,options:g})):b.apply(this,r(arguments))},setTickInterval:function(a){var b=
this.options;"treegrid"===b.type?(this.min=f(this.userMin,b.min,this.dataMin),this.max=f(this.userMax,b.max,this.dataMax),d(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?A(this):[]):a.apply(this,r(arguments))}});b(a.prototype,{getLabelPosition:function(a,b,c,d,e,g,h,k,m){var p=f(this.options&&this.options.labels,g);g=this.pos;var n=this.axis,r="treegrid"===n.options.type;a=a.apply(this,[b,c,d,e,p,h,k,m]);r&&
(b=p&&l(p.symbol)?p.symbol:{},p=p&&w(p.indentation)?p.indentation:0,g=(g=(n=n.mapOfPosToGridNode)&&n[g])&&g.depth||1,a.x+=b.width+2*b.padding+(g-1)*p);return a},renderLabel:function(a){var b=this,d=b.pos,e=b.axis,h=b.label,k=e.mapOfPosToGridNode,m=e.options,n=f(b.options&&b.options.labels,m&&m.labels),q=n&&l(n.symbol)?n.symbol:{},t=(k=k&&k[d])&&k.depth,m="treegrid"===m.type,v=!(!h||!h.element),u=-1<e.tickPositions.indexOf(d),d=e.chart.styledMode;m&&k&&v&&h.addClass("highcharts-treegrid-node-level-"+
t);a.apply(b,r(arguments));m&&k&&v&&0<k.descendants&&(e=D(e,k),E(b,{color:!d&&h.styles.color,collapsed:e,group:h.parentGroup,options:q,renderer:h.renderer,show:u,xy:h.xy}),q="highcharts-treegrid-node-"+(e?"expanded":"collapsed"),h.addClass("highcharts-treegrid-node-"+(e?"collapsed":"expanded")).removeClass(q),d||h.css({cursor:"pointer"}),[h,b.labelIcon].forEach(function(a){a.attachedTreeGridEvents||(c.addEvent(a.element,"mouseover",function(){var a=h;a.addClass("highcharts-treegrid-node-active");
a.renderer.styledMode||a.css({textDecoration:"underline"})}),c.addEvent(a.element,"mouseout",function(){var a=h,b=n,b=g(b.style)?b.style:{};a.removeClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:b.textDecoration})}),c.addEvent(a.element,"click",function(){b.toggleCollapse()}),a.attachedTreeGridEvents=!0)}))}});k(a.prototype,{collapse:function(a){var b=this.axis,c=t(b,b.mapOfPosToGridNode[this.pos]);b.setBreaks(c,f(a,!0))},expand:function(a){var b=this.axis,c=
F(b,b.mapOfPosToGridNode[this.pos]);b.setBreaks(c,f(a,!0))},toggleCollapse:function(a){var b=this.axis,c;c=b.mapOfPosToGridNode[this.pos];c=D(b,c)?F(b,c):t(b,c);b.setBreaks(c,f(a,!0))}});u.prototype.utils={getNode:z.getNode}});z(k,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map