/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 (c) 2017-2019 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/venn",["highcharts"],function(q){a(q);a.Highcharts=q;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function q(a,d,b,x){a.hasOwnProperty(d)||(a[d]=x.apply(null,b))}a=a?a._modules:{};q(a,"mixins/draw-point.js",[],function(){var a=function(d){var b=this,a=b.graphic,k=d.animatableAttribs,g=d.onComplete,B=d.css,r=d.renderer;
if(b.shouldDraw())a||(b.graphic=a=r[d.shapeType](d.shapeArgs).add(d.group)),a.css(B).attr(d.attribs).animate(k,d.isNew?!1:void 0,g);else if(a){var p=function(){b.graphic=a=a.destroy();"function"===typeof g&&g()};Object.keys(k).length?a.animate(k,void 0,function(){p()}):p()}};return function(d){(d.attribs=d.attribs||{})["class"]=this.getClassName();a.call(this,d)}});q(a,"mixins/geometry.js",[],function(){return{getAngleBetweenPoints:function(a,d){return Math.atan2(d.x-a.x,d.y-a.y)},getCenterOfPoints:function(a){var d=
a.reduce(function(b,a){b.x+=a.x;b.y+=a.y;return b},{x:0,y:0});return{x:d.x/a.length,y:d.y/a.length}},getDistanceBetweenPoints:function(a,d){return Math.sqrt(Math.pow(d.x-a.x,2)+Math.pow(d.y-a.y,2))}}});q(a,"mixins/geometry-circles.js",[a["mixins/geometry.js"]],function(a){var d=a.getAngleBetweenPoints,b=a.getCenterOfPoints,x=a.getDistanceBetweenPoints,k=function(e,c){c=Math.pow(10,c);return Math.round(e*c)/c},g=function(e){if(0>=e)throw Error("radius of circle must be a positive number.");return Math.PI*
e*e},C=function(e,c){return e*e*Math.acos(1-c/e)-(e-c)*Math.sqrt(c*(2*e-c))},r=function(e,c){var a=x(e,c),b=e.r,d=c.r,y=[];if(a<b+d&&a>Math.abs(b-d)){var b=b*b,w=(b-d*d+a*a)/(2*a),d=Math.sqrt(b-w*w),b=e.x,y=c.x;e=e.y;var g=c.y;c=b+w*(y-b)/a;w=e+w*(g-e)/a;e=d/a*-(g-e);a=d/a*-(y-b);y=[{x:k(c+e,14),y:k(w-a,14)},{x:k(c-e,14),y:k(w+a,14)}]}return y},p=function(a){return a.reduce(function(c,a,b,e){e=e.slice(b+1).reduce(function(c,e,d){var z=[b,d+b+1];return c.concat(r(a,e).map(function(c){c.indexes=z;return c}))},
[]);return c.concat(e)},[])},t=function(a,c){return x(a,c)<=c.r+1e-10},u=function(a,c){return!c.some(function(c){return!t(a,c)})};return{getAreaOfCircle:g,getAreaOfIntersectionBetweenCircles:function(a){var c=p(a).filter(function(c){return u(c,a)}),e;if(1<c.length){var m=b(c),c=c.map(function(c){c.angle=d(m,c);return c}).sort(function(c,a){return a.angle-c.angle}),g=c[c.length-1],c=c.reduce(function(c,e){var g=c.startPoint,z=b([g,e]),m=e.indexes.filter(function(c){return-1<g.indexes.indexOf(c)}).reduce(function(c,
b){b=a[b];var m=d(b,e),k=d(b,g),m=k-(k-m+(k<m?2*Math.PI:0))/2,m=x(z,{x:b.x+b.r*Math.sin(m),y:b.y+b.r*Math.cos(m)});b=b.r;m>2*b&&(m=2*b);if(!c||c.width>m)c={r:b,largeArc:m>b?1:0,width:m,x:e.x,y:e.y};return c},null);if(m){var k=m.r;c.arcs.push(["A",k,k,0,m.largeArc,1,m.x,m.y]);c.startPoint=e}return c},{startPoint:g,arcs:[]}).arcs;0!==c.length&&1!==c.length&&(c.unshift(["M",g.x,g.y]),e={center:m,d:c})}return e},getCircleCircleIntersection:r,getCirclesIntersectionPoints:p,getCircularSegmentArea:C,getOverlapBetweenCircles:function(a,
c,b){var d=0;b<a+c&&(b<=Math.abs(c-a)?d=g(a<c?a:c):(d=(a*a-c*c+b*b)/(2*b),b-=d,d=C(a,a-d)+C(c,c-b)),d=k(d,14));return d},isPointInsideCircle:t,isPointInsideAllCircles:u,isPointOutsideAllCircles:function(a,c){return!c.some(function(c){return t(a,c)})},round:k}});q(a,"mixins/nelder-mead.js",[],function(){var a=function(a){a=a.slice(0,-1);for(var b=a.length,d=[],k=function(a,b){a.sum+=b[a.i];return a},g=0;g<b;g++)d[g]=a.reduce(k,{sum:0,i:g}).sum/b;return d};return{getCentroid:a,nelderMead:function(d,
b){var x=function(a,b){return a.fx-b.fx},k=function(a,b,d,e){return b.map(function(c,b){return a*c+d*e[b]})},g=function(a,b){b.fx=d(b);a[a.length-1]=b;return a},q=function(a){var b=a[0];return a.map(function(a){a=k(.5,b,.5,a);a.fx=d(a);return a})},r=function(a,b,e,g){a=k(e,a,g,b);a.fx=d(a);return a};b=function(a){var b=a.length,c=Array(b+1);c[0]=a;c[0].fx=d(a);for(var e=0;e<b;++e){var g=a.slice();g[e]=g[e]?1.05*g[e]:.001;g.fx=d(g);c[e+1]=g}return c}(b);for(var p=0;100>p;p++){b.sort(x);var t=b[b.length-
1],u=a(b),e=r(u,t,2,-1);e.fx<b[0].fx?(t=r(u,t,3,-2),b=g(b,t.fx<e.fx?t:e)):e.fx>=b[b.length-2].fx?e.fx>t.fx?(u=r(u,t,.5,.5),b=u.fx<t.fx?g(b,u):q(b)):(u=r(u,t,1.5,-.5),b=u.fx<e.fx?g(b,u):q(b)):b=g(b,e)}return b[0]}}});q(a,"modules/venn.src.js",[a["mixins/draw-point.js"],a["mixins/geometry.js"],a["mixins/geometry-circles.js"],a["mixins/nelder-mead.js"],a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,d,b,q,k,g){var x=q.nelderMead,r=g.isArray,p=g.isNumber,t=g.isString;g=k.addEvent;var u=k.Color,
e=k.extend,c=b.getAreaOfCircle,z=b.getAreaOfIntersectionBetweenCircles,m=b.getCircleCircleIntersection,B=d.getCenterOfPoints,y=d.getDistanceBetweenPoints,w=b.getOverlapBetweenCircles,F=k.isObject,G=b.isPointInsideAllCircles,R=b.isPointInsideCircle,I=b.isPointOutsideAllCircles,S=k.merge,T=k.seriesType,H=k.seriesTypes,U=function(a){return Object.keys(a).map(function(b){return a[b]})},V=function(a){var b=0;2===a.length&&(b=a[0],a=a[1],b=w(b.r,a.r,y(b,a)));return b},J=function(a,b){return b.reduce(function(b,
c){var h=0;1<c.sets.length&&(h=c.value,c=V(c.sets.map(function(b){return a[b]})),c=h-c,h=Math.round(c*c*1E11)/1E11);return b+h},0)},K=function(a,b,c,v,h){var f=a(b),n=a(c);h=h||100;v=v||1e-10;var d=c-b,e=1,l,g;if(b>=c)throw Error("a must be smaller than b.");if(0<f*n)throw Error("f(a) and f(b) must have opposite signs.");if(0===f)l=b;else if(0===n)l=c;else for(;e++<=h&&0!==g&&d>v;)d=(c-b)/2,l=b+d,g=a(l),0<f*g?b=l:c=l;return l},D=function(a,b,n){var f=a+b;return 0>=n?f:c(a<b?a:b)<=n?0:K(function(c){c=
w(a,b,c);return n-c},0,f)},A=function(a){return r(a.sets)&&1===a.sets.length},E=function(a,b,c){b=b.reduce(function(b,c){c=c.r-y(a,c);return c<=b?c:b},Number.MAX_VALUE);return b=c.reduce(function(b,c){c=y(a,c)-c.r;return c<=b?c:b},b)},W=function(a,b){var c=a.reduce(function(c,h){var f=h.r/2;return[{x:h.x,y:h.y},{x:h.x+f,y:h.y},{x:h.x-f,y:h.y},{x:h.x,y:h.y+f},{x:h.x,y:h.y-f}].reduce(function(c,h){var f=E(h,a,b);c.margin<f&&(c.point=h,c.margin=f);return c},c)},{point:void 0,margin:-Number.MAX_VALUE}).point,
c=x(function(c){return-E({x:c[0],y:c[1]},a,b)},[c.x,c.y]),c={x:c[0],y:c[1]};G(c,a)&&I(c,b)||(c=B(a));return c},L=function(a,b,c){var f=b.reduce(function(a,b){return Math.min(b.r,a)},Infinity),h=c.filter(function(b){return!R(a,b)});c=function(c,f){return K(function(d){var n={x:a.x+f*d,y:a.y},n=G(n,b)&&I(n,h);return-(c-d)+(n?0:Number.MAX_VALUE)},0,c)};return 2*Math.min(c(f,-1),c(f,1))},X=function(a){var b=a.filter(A);return a.reduce(function(a,c){if(c.value){var h=c.sets;c=h.join();var f=b.reduce(function(a,
b){var c=-1<h.indexOf(b.sets[0]);a[c?"internal":"external"].push(b.circle);return a},{internal:[],external:[]}),d=W(f.internal,f.external),f=L(d,f.internal,f.external);a[c]={position:d,width:f}}return a},{})},M=function(a){var b=a.filter(function(a){return 2===a.sets.length}).reduce(function(a,b){b.sets.forEach(function(c,f,d){F(a[c])||(a[c]={overlapping:{},totalOverlap:0});a[c].totalOverlap+=b.value;a[c].overlapping[d[1-f]]=b.value});return a},{});a.filter(A).forEach(function(a){e(a,b[a.sets[0]])});
return a},N=function(a,b){return b.totalOverlap-a.totalOverlap},O=function(a){var b=[],c={};a.filter(function(a){return 1===a.sets.length}).forEach(function(a){c[a.sets[0]]=a.circle={x:Number.MAX_VALUE,y:Number.MAX_VALUE,r:Math.sqrt(a.value/Math.PI)}});var f=function(a,c){var f=a.circle;f.x=c.x;f.y=c.y;b.push(a)};M(a);var h=a.filter(A).sort(N);f(h.shift(),{x:0,y:0});var d=a.filter(function(a){return 2===a.sets.length});h.forEach(function(a){var h=a.circle,e=h.r,n=a.overlapping,g=b.reduce(function(a,
f,g){var v=f.circle,l=D(e,v.r,n[f.sets[0]]),k=[{x:v.x+l,y:v.y},{x:v.x-l,y:v.y},{x:v.x,y:v.y+l},{x:v.x,y:v.y-l}];b.slice(g+1).forEach(function(a){var b=a.circle;a=D(e,b.r,n[a.sets[0]]);k=k.concat(m({x:v.x,y:v.y,r:l},{x:b.x,y:b.y,r:a}))});k.forEach(function(b){h.x=b.x;h.y=b.y;var f=J(c,d);f<a.loss&&(a.loss=f,a.coordinates=b)});return a},{loss:Number.MAX_VALUE,coordinates:void 0});f(a,g.coordinates)});return c},Y=function(a){var b={};0<a.length&&(b=O(a),a.filter(function(a){return!A(a)}).forEach(function(a){var c=
a.sets;a=c.join();c=c.map(function(a){return b[a]});b[a]=z(c)}));return b},P=function(a){var b={};return F(a)&&p(a.value)&&-1<a.value&&r(a.sets)&&0<a.sets.length&&!a.sets.some(function(a){var c=!1;!b[a]&&t(a)?b[a]=!0:c=!0;return c})},Q=function(a){a=r(a)?a:[];var b=a.reduce(function(a,b){P(b)&&A(b)&&0<b.value&&-1===a.indexOf(b.sets[0])&&a.push(b.sets[0]);return a},[]).sort(),c=a.reduce(function(a,c){P(c)&&!c.sets.some(function(a){return-1===b.indexOf(a)})&&(a[c.sets.sort().join()]=c);return a},{});
b.reduce(function(a,b,c,d){d.slice(c+1).forEach(function(c){a.push(b+","+c)});return a},[]).forEach(function(a){if(!c[a]){var b={sets:a.split(","),value:0};c[a]=b}});return U(c)},Z=function(a,b,c){var d=c.bottom-c.top,f=c.right-c.left,d=Math.min(0<f?1/f*a:1,0<d?1/d*b:1);return{scale:d,centerX:a/2-(c.right+c.left)/2*d,centerY:b/2-(c.top+c.bottom)/2*d}};T("venn","scatter",{borderColor:"#cccccc",borderDashStyle:"solid",borderWidth:1,brighten:0,clip:!1,colorByPoint:!0,dataLabels:{enabled:!0,verticalAlign:"middle",
formatter:function(){return this.point.name}},inactiveOtherPoints:!0,marker:!1,opacity:.75,showInLegend:!1,states:{hover:{opacity:1,borderColor:"#333333"},select:{color:"#cccccc",borderColor:"#000000",animation:!1}},tooltip:{pointFormat:"{point.name}: {point.value}"}},{isCartesian:!1,axisTypes:[],directTouch:!0,pointArrayMap:["value"],translate:function(){var a=this.chart;this.processedXData=this.xData;this.generatePoints();var b=Q(this.options.data),c=Y(b),d=X(b),b=Object.keys(c).filter(function(a){return(a=
c[a])&&p(a.r)}).reduce(function(a,b){var d=c[b];b=d.x-d.r;var e=d.x+d.r,f=d.y+d.r,d=d.y-d.r;if(!p(a.left)||a.left>b)a.left=b;if(!p(a.right)||a.right<e)a.right=e;if(!p(a.top)||a.top>d)a.top=d;if(!p(a.bottom)||a.bottom<f)a.bottom=f;return a},{top:0,bottom:0,left:0,right:0}),a=Z(a.plotWidth,a.plotHeight,b),e=a.scale,g=a.centerX,k=a.centerY;this.points.forEach(function(a){var b=r(a.sets)?a.sets:[],f=b.join(),h=c[f],n,l=d[f]||{},f=l.width,l=l.position;h&&(h.r?n={x:g+h.x*e,y:k+h.y*e,r:h.r*e}:h.d&&(n={d:h.d.reduce(function(a,
b){"M"===b[0]?(b[1]=g+b[1]*e,b[2]=k+b[2]*e):"A"===b[0]&&(b[1]*=e,b[2]*=e,b[6]=g+b[6]*e,b[7]=k+b[7]*e);return a.concat(b)},[]).join(" ")}),l?(l.x=g+l.x*e,l.y=k+l.y*e):l={},p(f)&&(f=Math.round(f*e)));a.shapeArgs=n;l&&n&&(a.plotX=l.x,a.plotY=l.y);f&&n&&(a.dlOptions={style:{width:f}});a.name=a.options.name||b.join("\u2229")})},drawPoints:function(){var a=this,b=a.chart,c=a.group,d=b.renderer;(a.points||[]).forEach(function(f){var g={zIndex:r(f.sets)?f.sets.length:0},h=f.shapeArgs;b.styledMode||e(g,a.pointAttribs(f,
f.state));f.draw({isNew:!f.graphic,animatableAttribs:h,attribs:g,group:c,renderer:d,shapeType:h&&h.d?"path":"circle"})})},pointAttribs:function(a,b){var c=this.options||{};a=S(c,{color:a&&a.color},a&&a.options||{},b&&c.states[b]||{});return{fill:u(a.color).setOpacity(a.opacity).brighten(a.brightness).get(),stroke:a.borderColor,"stroke-width":a.borderWidth,dashstyle:a.borderDashStyle}},animate:function(a){if(!a){var b=k.animObject(this.options.animation);this.points.forEach(function(a){var c=a.shapeArgs;
if(a.graphic&&c){var d={},e={};c.d?d.opacity=.001:(d.r=0,e.r=c.r);a.graphic.attr(d).animate(e,b);c.d&&setTimeout(function(){a&&a.graphic&&a.graphic.animate({opacity:1})},b.duration)}},this);this.animate=null}},utils:{addOverlapToSets:M,geometry:d,geometryCircles:b,getLabelWidth:L,getMarginFromCircles:E,getDistanceBetweenCirclesByOverlap:D,layoutGreedyVenn:O,loss:J,nelderMead:q,processVennData:Q,sortByTotalOverlap:N}},{draw:a,shouldDraw:function(){return!!this.shapeArgs},isValid:function(){return p(this.value)}});
g(H.venn,"afterSetOptions",function(a){var b=a.options.states;this instanceof H.venn&&Object.keys(b).forEach(function(a){b[a].halo=!1})})});q(a,"masters/modules/venn.src.js",[],function(){})});
//# sourceMappingURL=venn.js.map