/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 Wind barb series module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/windbarb",["highcharts"],function(f){b(f);b.Highcharts=f;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function f(b,l,f,m){b.hasOwnProperty(l)||(b[l]=m.apply(null,f))}b=b?b._modules:{};f(b,"mixins/on-series.js",[b["parts/Globals.js"]],function(b){var x=b.defined,f=b.seriesTypes,m=b.stableSort;return{getPlotBox:function(){return b.Series.prototype.getPlotBox.call(this.options.onSeries&&
this.chart.get(this.options.onSeries)||this)},translate:function(){f.column.prototype.translate.apply(this);var b=this,g=b.options,a=b.chart,h=b.points,e=h.length-1,d,c=g.onSeries,c=c&&a.get(c),g=g.onKey||"y",l=c&&c.options.step,q=c&&c.points,n=q&&q.length,p=a.inverted,t=b.xAxis,y=b.yAxis,v=0,k,w,r,u;if(c&&c.visible&&n)for(v=(c.pointXOffset||0)+(c.barW||0)/2,a=c.currentDataGrouping,w=q[n-1].x+(a?a.totalRange:0),m(h,function(a,c){return a.x-c.x}),g="plot"+g[0].toUpperCase()+g.substr(1);n--&&h[e]&&
!(k=q[n],a=h[e],a.y=k.y,k.x<=a.x&&void 0!==k[g]&&(a.x<=w&&(a.plotY=k[g],k.x<a.x&&!l&&(r=q[n+1])&&void 0!==r[g]&&(u=(a.x-k.x)/(r.x-k.x),a.plotY+=u*(r[g]-k[g]),a.y+=u*(r.y-k.y))),e--,n++,0>e)););h.forEach(function(a,c){var e;a.plotX+=v;if(void 0===a.plotY||p)0<=a.plotX&&a.plotX<=t.len?p?(a.plotY=t.translate(a.x,0,1,0,1),a.plotX=x(a.y)?y.translate(a.y,0,0,0,1):0):a.plotY=(t.opposite?0:b.yAxis.len)+t.offset:a.shapeArgs={};(d=h[c-1])&&d.plotX===a.plotX&&(void 0===d.stackIndex&&(d.stackIndex=0),e=d.stackIndex+
1);a.stackIndex=e});this.onSeries=c}}});f(b,"modules/windbarb.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["mixins/on-series.js"]],function(b,f,p){function m(){b.approximations&&!b.approximations.windbarb&&(b.approximations.windbarb=function(a,h){var e=0,d=0,c,f=a.length;for(c=0;c<f;c++)e+=a[c]*Math.cos(h[c]*b.deg2rad),d+=a[c]*Math.sin(h[c]*b.deg2rad);return[a.reduce(function(a,c){return a+c},0)/a.length,Math.atan2(d,e)/b.deg2rad]})}var l=f.isNumber;f=b.noop;var g=b.seriesType;m();g("windbarb",
"column",{dataGrouping:{enabled:!0,approximation:"windbarb",groupPixelWidth:30},lineWidth:2,onSeries:null,states:{hover:{lineWidthPlus:0}},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.value}\x3c/b\x3e ({point.beaufort})\x3cbr/\x3e'},vectorLength:20,yOffset:-20,xOffset:0},{pointArrayMap:["value","direction"],parallelArrays:["x","value","direction"],beaufortName:"Calm;Light air;Light breeze;Gentle breeze;Moderate breeze;Fresh breeze;Strong breeze;Near gale;Gale;Strong gale;Storm;Violent storm;Hurricane".split(";"),
beaufortFloor:[0,.3,1.6,3.4,5.5,8,10.8,13.9,17.2,20.8,24.5,28.5,32.7],trackerGroups:["markerGroup"],init:function(a,h){m();b.Series.prototype.init.call(this,a,h)},pointAttribs:function(a,b){var e=this.options;a=a.color||this.color;var d=this.options.lineWidth;b&&(a=e.states[b].color||a,d=(e.states[b].lineWidth||d)+(e.states[b].lineWidthPlus||0));return{stroke:a,"stroke-width":d}},markerAttribs:function(){},getPlotBox:p.getPlotBox,windArrow:function(a){var b=1.943844*a.value,e,d=this.options.vectorLength/
20,c=-10;if(a.isNull)return[];if(0===a.beaufortLevel)return this.chart.renderer.symbols.circle(-10*d,-10*d,20*d,20*d);a=["M",0,7*d,"L",-1.5*d,7*d,0,10*d,1.5*d,7*d,0,7*d,0,-10*d];e=(b-b%50)/50;if(0<e)for(;e--;)a.push(-10===c?"L":"M",0,c*d,"L",5*d,c*d+2,"L",0,c*d+4),b-=50,c+=7;e=(b-b%10)/10;if(0<e)for(;e--;)a.push(-10===c?"L":"M",0,c*d,"L",7*d,c*d),b-=10,c+=3;e=(b-b%5)/5;if(0<e)for(;e--;)a.push(-10===c?"L":"M",0,c*d,"L",4*d,c*d),b-=5,c+=3;return a},translate:function(){var a=this.beaufortFloor,b=this.beaufortName;
p.translate.call(this);this.points.forEach(function(e){for(var d=0;d<a.length&&!(a[d]>e.value);d++);e.beaufortLevel=d-1;e.beaufort=b[d-1]})},drawPoints:function(){var a=this.chart,b=this.yAxis,e=a.inverted,d=this.options.vectorLength/2;this.points.forEach(function(c){var f=c.plotX,g=c.plotY;!1===this.options.clip||a.isInsidePlot(f,0,!1)?(c.graphic||(c.graphic=this.chart.renderer.path().add(this.markerGroup)),c.graphic.attr({d:this.windArrow(c),translateX:f+this.options.xOffset,translateY:g+this.options.yOffset,
rotation:c.direction}).attr(this.pointAttribs(c))):c.graphic&&(c.graphic=c.graphic.destroy());c.tooltipPos=[f+this.options.xOffset+(e&&!this.onSeries?d:0),g+this.options.yOffset-(e?0:d+b.pos-a.plotTop)]},this)},animate:function(a){a?this.markerGroup.attr({opacity:.01}):(this.markerGroup.animate({opacity:1},b.animObject(this.options.animation)),this.animate=null)},invertGroups:f,getExtremes:f},{isValid:function(){return l(this.value)&&0<=this.value}})});f(b,"masters/modules/windbarb.src.js",[],function(){})});
//# sourceMappingURL=windbarb.js.map