/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 (c) 2016-2019 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/wordcloud",["highcharts"],function(h){a(h);a.Highcharts=h;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function h(a,g,y,k){a.hasOwnProperty(g)||(a[g]=k.apply(null,y))}a=a?a._modules:{};h(a,"mixins/draw-point.js",[],function(){var a=function(a){var g=this,k=g.graphic,r=a.animatableAttribs,t=a.onComplete,h=a.css,x=
a.renderer;if(g.shouldDraw())k||(g.graphic=k=x[a.shapeType](a.shapeArgs).add(a.group)),k.css(h).attr(a.attribs).animate(r,a.isNew?!1:void 0,t);else if(k){var n=function(){g.graphic=k=k.destroy();"function"===typeof t&&t()};Object.keys(r).length?k.animate(r,void 0,function(){n()}):n()}};return function(g){(g.attribs=g.attribs||{})["class"]=this.getClassName();a.call(this,g)}});h(a,"mixins/polygon.js",[a["parts/Globals.js"],a["parts/Utilities.js"]],function(a,g){var r=g.isArray,k=g.isNumber,h=a.deg2rad,
t=a.find,B=function(b,c){c=k(c)?c:14;c=Math.pow(10,c);return Math.round(b*c)/c},x=function(b,c){var v=c[0]-b[0];b=c[1]-b[1];return[[-b,v],[b,-v]]},n=function(b,c){b=b.map(function(b){return b[0]*c[0]+b[1]*c[1]});return{min:Math.min.apply(this,b),max:Math.max.apply(this,b)}},C=function(b,c){var a=b[0];b=b[1];var m=h*-c;c=Math.cos(m);m=Math.sin(m);return[B(a*c-b*m),B(a*m+b*c)]},z=function(b,c,a){b=C([b[0]-c[0],b[1]-c[1]],a);return[b[0]+c[0],b[1]+c[1]]},A=function(b){var c,a=b.axes;r(a)||(a=[],c=c=b.concat([b[0]]),
c.reduce(function(c,b){var m=x(c,b)[0];t(a,function(c){return c[0]===m[0]&&c[1]===m[1]})||a.push(m);return b}),b.axes=a);return a},D=function(b,c){b=A(b);c=A(c);return b.concat(c)};return{getBoundingBoxFromPolygon:function(b){return b.reduce(function(c,b){var a=b[0];b=b[1];c.left=Math.min(a,c.left);c.right=Math.max(a,c.right);c.bottom=Math.max(b,c.bottom);c.top=Math.min(b,c.top);return c},{left:Number.MAX_VALUE,right:-Number.MAX_VALUE,bottom:-Number.MAX_VALUE,top:Number.MAX_VALUE})},getPolygon:function(b,
c,a,m,g){var k=[b,c],r=b-a/2;b+=a/2;a=c-m/2;c+=m/2;return[[r,a],[b,a],[b,c],[r,c]].map(function(c){return z(c,k,-g)})},isPolygonsColliding:function(a,c){var b=D(a,c);return!t(b,function(b){var g=n(a,b);b=n(c,b);return!!(b.min>g.max||b.max<g.min)})},movePolygon:function(b,c,a){return a.map(function(a){return[a[0]+b,a[1]+c]})},rotate2DToOrigin:C,rotate2DToPoint:z}});h(a,"modules/wordcloud.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/draw-point.js"],a["mixins/polygon.js"]],function(a,
g,h,k){function r(f,d){var e=!1,a=f.rect,c=f.polygon,b=f.lastCollidedWith,g=function(d){var e;e=d.rect;(e=!(e.left>a.right||e.right<a.left||e.top>a.bottom||e.bottom<a.top))&&(f.rotation%90||d.roation%90)&&(e=E(c,d.polygon));return e};b&&((e=g(b))||delete f.lastCollidedWith);e||(e=!!I(d,function(d){var e=g(d);e&&(f.lastCollidedWith=d);return e}));return e}function t(f){var d=4*f,e=Math.ceil((Math.sqrt(d)-1)/2),a=2*e+1,c=Math.pow(a,2),b=!1,a=a-1;1E4>=f&&("boolean"===typeof b&&d>=c-a&&(b={x:e-(c-d),
y:-e}),c-=a,"boolean"===typeof b&&d>=c-a&&(b={x:-e,y:-e+(c-d)}),c-=a,"boolean"===typeof b&&(b=d>=c-a?{x:-e+(c-d),y:e}:{x:e,y:e-(c-d-a)}),b.x*=5,b.y*=5);return b}function B(f,d,a){var e=2*Math.max(Math.abs(a.top),Math.abs(a.bottom));a=2*Math.max(Math.abs(a.left),Math.abs(a.right));return Math.min(0<a?1/a*f:1,0<e?1/e*d:1)}function x(a,d,e){e=e.reduce(function(a,d){d=d.dimensions;var f=Math.max(d.width,d.height);a.maxHeight=Math.max(a.maxHeight,d.height);a.maxWidth=Math.max(a.maxWidth,d.width);a.area+=
f*f;return a},{maxHeight:0,maxWidth:0,area:0});e=Math.max(e.maxHeight,e.maxWidth,.85*Math.sqrt(e.area));var f=a>d?a/d:1;a=d>a?d/a:1;return{width:e*f,height:e*a,ratioX:f,ratioY:a}}function n(a,d,e,b){var f=!1;c(a)&&c(d)&&c(e)&&c(b)&&0<a&&-1<d&&b>e&&(f=e+d%a*((b-e)/(a-1||1)));return f}function C(a,d){var f,b=[];for(f=1;1E4>f;f++)b.push(a(f,d));return function(a){return 1E4>=a?b[a-1]:!1}}function z(a,d){var f=d.width/2,b=-(d.height/2),c=d.height/2;return!(-(d.width/2)<a.left&&f>a.right&&b<a.top&&c>a.bottom)}
function A(a,d){var b=d.placed,f=d.field,c=d.rectangle,g=d.polygon,k=d.spiral,h=1,q={x:0,y:0},p=a.rect=v({},c);a.polygon=g;for(a.rotation=d.rotation;!1!==q&&(r(a,b)||z(p,f));)q=k(h),m(q)&&(p.left=c.left+q.x,p.right=c.right+q.x,p.top=c.top+q.y,p.bottom=c.bottom+q.y,a.polygon=L(q.x,q.y,g)),h++;return q}function D(a,d){var b,c,f;m(a)&&m(d)&&(b=d.bottom-d.top,c=d.right-d.left,d=a.ratioX,f=a.ratioY,b=c*d>b*f?c:b,a=y(a,{width:a.width+b*d*2,height:a.height+b*f*2}));return a}var b=g.isArray,c=g.isNumber,
v=a.extend,m=a.isObject,y=a.merge;g=a.noop;var I=a.find,J=k.getBoundingBoxFromPolygon,K=k.getPolygon,E=k.isPolygonsColliding,L=k.movePolygon,F=a.Series;a.seriesType("wordcloud","column",{allowExtendPlayingField:!0,animation:{duration:500},borderWidth:0,clip:!1,colorByPoint:!0,minFontSize:1,maxFontSize:25,placementStrategy:"center",rotation:{from:0,orientations:2,to:90},showInLegend:!1,spiral:"rectangular",style:{fontFamily:"sans-serif",fontWeight:"900",whiteSpace:"nowrap"},tooltip:{followPointer:!0,
pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.weight}\x3c/b\x3e\x3cbr/\x3e'}},{animate:F.prototype.animate,animateDrilldown:g,animateDrillupFrom:g,setClip:g,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};F.prototype.bindAxes.call(this);v(this.yAxis.options,a);v(this.xAxis.options,a)},pointAttribs:function(b,d){b=a.seriesTypes.column.prototype.pointAttribs.call(this,
b,d);delete b.stroke;delete b["stroke-width"];return b},deriveFontSize:function(a,b,e){a=c(a)?a:0;b=c(b)?b:1;e=c(e)?e:1;return Math.floor(Math.max(e,a*b))},drawPoints:function(){var a=this,b=a.hasRendered,e=a.xAxis,g=a.yAxis,k=a.group,h=a.options,r=h.animation,t=h.allowExtendPlayingField,q=a.chart.renderer,p=q.text().add(k),n=[],z=a.placementStrategy[h.placementStrategy],y,E=h.rotation,F=a.points.map(function(a){return a.weight}),H=Math.max.apply(null,F),G=a.points.sort(function(a,b){return b.weight-
a.weight}),u;G.forEach(function(b){var c=a.deriveFontSize(1/H*b.weight,h.maxFontSize,h.minFontSize),c=v({fontSize:c+"px"},h.style);p.css(c).attr({x:0,y:0,text:b.name});c=p.getBBox(!0);b.dimensions={height:c.height,width:c.width}});u=x(e.len,g.len,G);y=C(a.spirals[h.spiral],{field:u});G.forEach(function(d){var e=a.deriveFontSize(1/H*d.weight,h.maxFontSize,h.minFontSize),e=v({fontSize:e+"px"},h.style),f=z(d,{data:G,field:u,placed:n,rotation:E}),g=v(a.pointAttribs(d,d.selected&&"select"),{align:"center",
"alignment-baseline":"middle",x:f.x,y:f.y,text:d.name,rotation:f.rotation}),p=K(f.x,f.y,d.dimensions.width,d.dimensions.height,f.rotation),l=J(p),w=A(d,{rectangle:l,polygon:p,field:u,placed:n,spiral:y,rotation:f.rotation}),x;!w&&t&&(u=D(u,l),w=A(d,{rectangle:l,polygon:p,field:u,placed:n,spiral:y,rotation:f.rotation}));if(m(w)){g.x+=w.x;g.y+=w.y;l.left+=w.x;l.right+=w.x;l.top+=w.y;l.bottom+=w.y;f=u;if(!c(f.left)||f.left>l.left)f.left=l.left;if(!c(f.right)||f.right<l.right)f.right=l.right;if(!c(f.top)||
f.top>l.top)f.top=l.top;if(!c(f.bottom)||f.bottom<l.bottom)f.bottom=l.bottom;u=f;n.push(d);d.isNull=!1}else d.isNull=!0;r&&(x={x:g.x,y:g.y},b?(delete g.x,delete g.y):(g.x=0,g.y=0));d.draw({animatableAttribs:x,attribs:g,css:e,group:k,renderer:q,shapeArgs:void 0,shapeType:"text"})});p=p.destroy();e=B(e.len,g.len,u);a.group.attr({scaleX:e,scaleY:e})},hasData:function(){return m(this)&&!0===this.visible&&b(this.points)&&0<this.points.length},placementStrategy:{random:function(a,b){var c=b.field;b=b.rotation;
return{x:Math.round(c.width*(Math.random()+.5)/2)-c.width/2,y:Math.round(c.height*(Math.random()+.5)/2)-c.height/2,rotation:n(b.orientations,a.index,b.from,b.to)}},center:function(a,b){b=b.rotation;return{x:0,y:0,rotation:n(b.orientations,a.index,b.from,b.to)}}},pointArrayMap:["weight"],spirals:{archimedean:function(a,b){var c=b.field;b=!1;var c=c.width*c.width+c.height*c.height,d=.8*a;1E4>=a&&(b={x:d*Math.cos(d),y:d*Math.sin(d)},Math.min(Math.abs(b.x),Math.abs(b.y))<c||(b=!1));return b},rectangular:function(a,
b){a=t(a,b);b=b.field;a&&(a.x*=b.ratioX,a.y*=b.ratioY);return a},square:t},utils:{extendPlayingField:D,getRotation:n,isPolygonsColliding:E,rotate2DToOrigin:k.rotate2DToOrigin,rotate2DToPoint:k.rotate2DToPoint},getPlotBox:function(){var a=this.chart,b=a.inverted,c=this[b?"yAxis":"xAxis"],b=this[b?"xAxis":"yAxis"];return{translateX:(c?c.left:a.plotLeft)+(c?c.len:a.plotWidth)/2,translateY:(b?b.top:a.plotTop)+(b?b.len:a.plotHeight)/2,scaleX:1,scaleY:1}}},{draw:h,shouldDraw:function(){return!this.isNull},
isValid:function(){return!0},weight:1})});h(a,"masters/modules/wordcloud.src.js",[],function(){})});
//# sourceMappingURL=wordcloud.js.map