/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 X-range series

 (c) 2010-2019 Torstein Honsi, Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/xrange",["highcharts"],function(l){c(l);c.Highcharts=l;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function l(e,c,l,q){e.hasOwnProperty(c)||(e[c]=q.apply(null,l))}c=c?c._modules:{};l(c,"modules/xrange.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(e,c){var l=c.isNumber;c=e.addEvent;var q=e.defined,
y=e.Color,z=e.seriesTypes.column,A=e.correctFloat,u=e.isObject,r=e.merge,v=e.pick,B=e.seriesType,C=e.Axis,x=e.Point,D=e.Series;B("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;u(a)&&(a=a.amount);if(l(a)&&0<a)return A(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'\x3cspan style\x3d"font-size: 10px"\x3e{point.x} - {point.x2}\x3c/span\x3e\x3cbr/\x3e',pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.yCategory}\x3c/b\x3e\x3cbr/\x3e'},
borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:e.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:e.noop,buildKDTree:e.noop,getColumnMetrics:function(){function a(){f.series.forEach(function(a){var b=a.xAxis;a.xAxis=a.yAxis;a.yAxis=b})}var b,f=this.chart;a();b=z.prototype.getColumnMetrics.call(this);a();return b},cropData:function(a,b,f,h){b=D.prototype.cropData.call(this,this.x2Data,b,f,h);b.xData=a.slice(b.start,
b.end);return b},findPointIndex:function(a){var b=this.data,f=this.points,h=a.id,d,g;h&&(g=(d=e.find(b,function(a){return a.id===h}))?d.index:void 0);void 0===g&&(g=(d=e.find(b,function(b){return b.x===a.x&&b.x2===a.x2&&!(f[g]&&f[g].touched)}))?d.index:void 0);this.cropped&&g>=this.cropStart&&(g-=this.cropStart);return g},translatePoint:function(a){var b=this.xAxis,f=this.yAxis,h=this.columnMetrics,d=this.options,g=d.minPointLength||0,c=a.plotX,e=v(a.x2,a.x+(a.len||0)),k=b.translate(e,0,0,0,1),e=
Math.abs(k-c),p=this.chart.inverted,t=v(d.borderWidth,1)%2/2,m=h.offset,n=Math.round(h.width);g&&(g-=e,0>g&&(g=0),c-=g/2,k+=g/2);c=Math.max(c,-10);k=Math.min(Math.max(k,-10),b.len+10);q(a.options.pointWidth)&&(m-=(Math.ceil(a.options.pointWidth)-n)/2,n=Math.ceil(a.options.pointWidth));d.pointPlacement&&l(a.plotY)&&f.categories&&(a.plotY=f.translate(a.y,0,1,0,1,d.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(c,k))+t,y:Math.floor(a.plotY+m)+t,width:Math.round(Math.abs(k-c)),height:n,r:this.options.borderRadius};
d=a.shapeArgs.x;g=d+a.shapeArgs.width;0>d||g>b.len?(d=Math.min(b.len,Math.max(0,d)),g=Math.max(0,Math.min(g,b.len)),k=g-d,a.dlBox=r(a.shapeArgs,{x:d,width:g-d,centerX:k?k/2:null})):a.dlBox=null;p?(a.tooltipPos[1]+=e/2*(b.reversed?1:-1),a.tooltipPos[0]+=h.width/2,a.tooltipPos[1]=Math.max(Math.min(a.tooltipPos[1],b.len-1),0),a.tooltipPos[0]=Math.max(Math.min(a.tooltipPos[0],f.len-1),0)):(a.tooltipPos[0]+=e/2*(b.reversed?-1:1),a.tooltipPos[1]-=h.width/2,a.tooltipPos[0]=Math.max(Math.min(a.tooltipPos[0],
b.len-1),0),a.tooltipPos[1]=Math.max(Math.min(a.tooltipPos[1],f.len-1),0));if(h=a.partialFill)u(h)&&(h=h.amount),l(h)||(h=0),f=a.shapeArgs,a.partShapeArgs={x:f.x,y:f.y,width:f.width,height:f.height,r:this.options.borderRadius},c=Math.max(Math.round(e*h+a.plotX-c),0),a.clipRectArgs={x:b.reversed?f.x+e-c:f.x,y:f.y,width:c,height:f.height}},translate:function(){z.prototype.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,b){var f=this.options,
c=this.chart.renderer,d=a.graphic,e=a.shapeType,l=a.shapeArgs,w=a.partShapeArgs,k=a.clipRectArgs,p=a.partialFill,t=f.stacking&&!f.borderRadius,m=a.state,n=f.states[m||"normal"]||{},q=void 0===m?"attr":b,m=this.pointAttribs(a,m),n=v(this.chart.options.chart.animation,n.animation);if(a.isNull)d&&(a.graphic=d.destroy());else{if(d)d.rect[b](l);else a.graphic=d=c.g("point").addClass(a.getClassName()).add(a.group||this.group),d.rect=c[e](r(l)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(d);
w&&(d.partRect?(d.partRect[b](r(w)),d.partialClipRect[b](r(k))):(d.partialClipRect=c.clipRect(k.x,k.y,k.width,k.height),d.partRect=c[e](w).addClass("highcharts-partfill-overlay").add(d).clip(d.partialClipRect)));this.chart.styledMode||(d.rect[b](m,n).shadow(f.shadow,null,t),w&&(u(p)||(p={}),u(f.partialFill)&&(p=r(p,f.partialFill)),a=p.fill||y(m.fill).brighten(-.3).get()||y(a.color||this.color).brighten(-.3).get(),m.fill=a,d.partRect[q](m,n).shadow(f.shadow,null,t)))}},drawPoints:function(){var a=
this,b=a.getAnimationVerb();a.points.forEach(function(c){a.drawPoint(c,b)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a,b=this.series;if(b.options.colorByPoint&&!this.options.color){a=b.options.colors||b.chart.options.colors;var c=this.y%(a?a.length:b.chart.options.chart.colorCount);a=a&&a[c];b.chart.styledMode||(this.color=a);this.options.colorIndex||(this.colorIndex=c)}else this.color||(this.color=
b.color)},init:function(){x.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){x.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var a=x.prototype.getLabelConfig.call(this),b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});c(C,"afterGetSeriesExtremes",
function(){var a=this.series,b,c;this.isXAxis&&(b=v(this.dataMax,-Number.MAX_VALUE),a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(a){a>b&&(b=a,c=!0)})}),c&&(this.dataMax=b))})});l(c,"masters/modules/xrange.src.js",[],function(){})});
//# sourceMappingURL=xrange.js.map