/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(r){"object"===typeof module&&module.exports?(r["default"]=r,module.exports=r):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(y){r(y);r.Highcharts=y;return r}):r("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(r){function y(c,e,h,b){c.hasOwnProperty(e)||(c[e]=b.apply(null,h))}r=r?r._modules:{};y(r,"parts-more/Pane.js",[r["parts/Globals.js"]],function(c){function e(a,g){this.init(a,g)}var h=c.CenteredSeriesMixin,b=c.extend,
p=c.merge,a=c.splat;b(e.prototype,{coll:"pane",init:function(a,g){this.chart=g;this.background=[];g.pane.push(this);this.setOptions(a)},setOptions:function(a){this.options=p(this.defaultOptions,this.chart.angular?{background:{}}:void 0,a)},render:function(){var b=this.options,g=this.options.background,f=this.chart.renderer;this.group||(this.group=f.g("pane-group").attr({zIndex:b.zIndex||0}).add());this.updateCenter();if(g)for(g=a(g),b=Math.max(g.length,this.background.length||0),f=0;f<b;f++)g[f]&&
this.axis?this.renderBackground(p(this.defaultBackgroundOptions,g[f]),f):this.background[f]&&(this.background[f]=this.background[f].destroy(),this.background.splice(f,1))},renderBackground:function(a,g){var f="animate",c={"class":"highcharts-pane "+(a.className||"")};this.chart.styledMode||b(c,{fill:a.backgroundColor,stroke:a.borderColor,"stroke-width":a.borderWidth});this.background[g]||(this.background[g]=this.chart.renderer.path().add(this.group),f="attr");this.background[g][f]({d:this.axis.getPlotBandPath(a.from,
a.to,a)}).attr(c)},defaultOptions:{center:["50%","50%"],size:"85%",startAngle:0},defaultBackgroundOptions:{shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"},updateCenter:function(a){this.center=(a||this.axis||{}).center=h.getCenter.call(this)},update:function(a,g){p(!0,this.options,a);p(!0,this.chart.options.pane,a);this.setOptions(this.options);
this.render();this.chart.axes.forEach(function(a){a.pane===this&&(a.pane=null,a.update({},g))},this)}});c.Pane=e});y(r,"parts-more/RadialAxis.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(c,e){var h=e.pInt;e=c.addEvent;var b=c.Axis,p=c.extend,a=c.merge,l=c.noop,g=c.pick,f=c.Tick,u=c.wrap,n=c.correctFloat,w,t,x=b.prototype,d=f.prototype;w={getOffset:l,redraw:function(){this.isDirty=!1},render:function(){this.isDirty=!1},setScale:l,setCategories:l,setTitle:l};t={defaultRadialGaugeOptions:{labels:{align:"center",
x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},defaultRadialXOptions:{gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},defaultRadialYOptions:{gridLineInterpolation:"circle",labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}},
setOptions:function(d){d=this.options=a(this.defaultOptions,this.defaultRadialOptions,d);d.plotBands||(d.plotBands=[]);c.fireEvent(this,"afterSetOptions")},getOffset:function(){x.getOffset.call(this);this.chart.axisOffset[this.side]=0},getLinePath:function(d,m){d=this.center;var k=this.chart,q=g(m,d[2]/2-this.offset);this.isCircular||void 0!==m?(m=this.chart.renderer.symbols.arc(this.left+d[0],this.top+d[1],q,q,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),m.xBounds=[this.left+
d[0]],m.yBounds=[this.top+d[1]-q]):(m=this.postTranslate(this.angleRad,q),m=["M",d[0]+k.plotLeft,d[1]+k.plotTop,"L",m.x,m.y]);return m},setAxisTranslation:function(){x.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):this.center[2]/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)},beforeSetTickPositions:function(){if(this.autoConnect=this.isCircular&&void 0===g(this.userMax,
this.options.max)&&n(this.endAngleRad-this.startAngleRad)===n(2*Math.PI))this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0},setAxisSize:function(){x.setAxisSize.call(this);this.isRadial&&(this.pane.updateCenter(this),this.isCircular&&(this.sector=this.endAngleRad-this.startAngleRad),this.len=this.width=this.height=this.center[2]*g(this.sector,1)/2)},getPosition:function(d,m){return this.postTranslate(this.isCircular?this.translate(d):this.angleRad,g(this.isCircular?m:this.translate(d),
this.center[2]/2)-this.offset)},postTranslate:function(d,m){var k=this.chart,q=this.center;d=this.startAngleRad+d;return{x:k.plotLeft+q[0]+Math.cos(d)*m,y:k.plotTop+q[1]+Math.sin(d)*m}},getPlotBandPath:function(d,m,k){var q=this.center,v=this.startAngleRad,a=q[2]/2,f=[g(k.outerRadius,"100%"),k.innerRadius,g(k.thickness,10)],b=Math.min(this.offset,0),c=/%$/,n,u;n=this.isCircular;"polygon"===this.options.gridLineInterpolation?f=this.getPlotLinePath({value:d}).concat(this.getPlotLinePath({value:m,reverse:!0})):
(d=Math.max(d,this.min),m=Math.min(m,this.max),n||(f[0]=this.translate(d),f[1]=this.translate(m)),f=f.map(function(k){c.test(k)&&(k=h(k,10)*a/100);return k}),"circle"!==k.shape&&n?(d=v+this.translate(d),m=v+this.translate(m)):(d=-Math.PI/2,m=1.5*Math.PI,u=!0),f[0]-=b,f[2]-=b,f=this.chart.renderer.symbols.arc(this.left+q[0],this.top+q[1],f[0],f[0],{start:Math.min(d,m),end:Math.max(d,m),innerR:g(f[1],f[0]-f[2]),open:u}),n&&(n=(m+d)/2,b=this.left+q[0]+q[2]/2*Math.cos(n),f.xBounds=n>-Math.PI/2&&n<Math.PI/
2?[b,this.chart.plotWidth]:[0,b],f.yBounds=[this.top+q[1]+q[2]/2*Math.sin(n)],f.yBounds[0]+=n>-Math.PI&&0>n||n>Math.PI?-10:10));return f},getPlotLinePath:function(d){var m=this,k=m.center,q=m.chart,a=d.value;d=d.reverse;var v=m.getPosition(a),f,g,n;m.isCircular?n=["M",k[0]+q.plotLeft,k[1]+q.plotTop,"L",v.x,v.y]:"circle"===m.options.gridLineInterpolation?(a=m.translate(a),n=m.getLinePath(0,a)):(q.xAxis.forEach(function(k){k.pane===m.pane&&(f=k)}),n=[],a=m.translate(a),k=f.tickPositions,f.autoConnect&&
(k=k.concat([k[0]])),d&&(k=[].concat(k).reverse()),k.forEach(function(k,d){g=f.getPosition(k,a);n.push(d?"L":"M",g.x,g.y)}));return n},getTitlePosition:function(){var d=this.center,m=this.chart,k=this.options.title;return{x:m.plotLeft+d[0]+(k.x||0),y:m.plotTop+d[1]-{high:.5,middle:.25,low:0}[k.align]*d[2]+(k.y||0)}}};e(b,"init",function(d){var m=this,k=this.chart,q=k.angular,v=k.polar,f=this.isXAxis,g=q&&f,n,b=k.options;d=d.userOptions.pane||0;d=this.pane=k.pane&&k.pane[d];if(q){if(p(this,g?w:t),
n=!f)this.defaultRadialOptions=this.defaultRadialGaugeOptions}else v&&(p(this,t),this.defaultRadialOptions=(n=f)?this.defaultRadialXOptions:a(this.defaultYAxisOptions,this.defaultRadialYOptions));q||v?(this.isRadial=!0,k.inverted=!1,b.chart.zoomType=null,k.labelCollectors.push(function(){if(m.isRadial&&m.tickPositions&&!0!==m.options.labels.allowOverlap)return m.tickPositions.map(function(d){return m.ticks[d]&&m.ticks[d].label}).filter(function(d){return!!d})})):this.isRadial=!1;d&&n&&(d.axis=this);
this.isCircular=n});e(b,"afterInit",function(){var d=this.chart,m=this.options,k=this.pane,q=k&&k.options;d.angular&&this.isXAxis||!k||!d.angular&&!d.polar||(this.angleRad=(m.angle||0)*Math.PI/180,this.startAngleRad=(q.startAngle-90)*Math.PI/180,this.endAngleRad=(g(q.endAngle,q.startAngle+360)-90)*Math.PI/180,this.offset=m.offset||0)});e(b,"autoLabelAlign",function(d){this.isRadial&&(d.align=void 0,d.preventDefault())});e(f,"afterGetPosition",function(d){this.axis.getPosition&&p(d.pos,this.axis.getPosition(this.pos))});
e(f,"afterGetLabelPosition",function(d){var m=this.axis,k=this.label,q=k.getBBox(),a=m.options.labels,v=a.y,f,n=20,b=a.align,u=(m.translate(this.pos)+m.startAngleRad+Math.PI/2)/Math.PI*180%360,l=Math.round(u),p="end",e=0>l?l+360:l,w=e,x=0,h=0,t=null===a.y?.3*-q.height:0;if(m.isRadial){f=m.getPosition(this.pos,m.center[2]/2+c.relativeLength(g(a.distance,-25),m.center[2]/2,-m.center[2]/2));"auto"===a.rotation?k.attr({rotation:u}):null===v&&(v=m.chart.renderer.fontMetrics(k.styles&&k.styles.fontSize).b-
q.height/2);null===b&&(m.isCircular?(q.width>m.len*m.tickInterval/(m.max-m.min)&&(n=0),b=u>n&&u<180-n?"left":u>180+n&&u<360-n?"right":"center"):b="center",k.attr({align:b}));if("auto"===b&&2===m.tickPositions.length&&m.isCircular){90<e&&180>e?e=180-e:270<e&&360>=e&&(e=540-e);180<w&&360>=w&&(w=360-w);if(m.pane.options.startAngle===l||m.pane.options.startAngle===l+360||m.pane.options.startAngle===l-360)p="start";b=-90<=l&&90>=l||-360<=l&&-270>=l||270<=l&&360>=l?"start"===p?"right":"left":"start"===
p?"left":"right";70<w&&110>w&&(b="center");15>e||180<=e&&195>e?x=.3*q.height:15<=e&&35>=e?x="start"===p?0:.75*q.height:195<=e&&215>=e?x="start"===p?.75*q.height:0:35<e&&90>=e?x="start"===p?.25*-q.height:q.height:215<e&&270>=e&&(x="start"===p?q.height:.25*-q.height);15>w?h="start"===p?.15*-q.height:.15*q.height:165<w&&180>=w&&(h="start"===p?.15*q.height:.15*-q.height);k.attr({align:b});k.translate(h,x+t)}d.pos.x=f.x+a.x;d.pos.y=f.y+v}});u(d,"getMarkPath",function(d,m,k,q,a,f,g){var v=this.axis;v.isRadial?
(d=v.getPosition(this.pos,v.center[2]/2+q),m=["M",m,k,"L",d.x,d.y]):m=d.call(this,m,k,q,a,f,g);return m})});y(r,"parts-more/AreaRangeSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(c,e){var h=e.isArray,b=c.pick,p=c.extend,a=c.defined;e=c.seriesType;var l=c.seriesTypes,g=c.Series.prototype,f=c.Point.prototype;e("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'\x3cspan style\x3d"color:{series.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.low}\x3c/b\x3e - \x3cb\x3e{point.high}\x3c/b\x3e\x3cbr/\x3e'},
trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],toYData:function(a){return[a.low,a.high]},pointValKey:"low",deferTranslatePolar:!0,highToXY:function(a){var f=this.chart,g=this.xAxis.postTranslate(a.rectPlotX,this.yAxis.len-a.plotHigh);a.plotHighX=g.x-f.plotLeft;a.plotHigh=g.y-f.plotTop;a.plotLowX=a.plotX},translate:function(){var a=this,f=a.yAxis,g=!!a.modifyValue;l.area.prototype.translate.apply(a);a.points.forEach(function(n){var b=
n.low,d=n.high,v=n.plotY;null===d||null===b?(n.isNull=!0,n.plotY=null):(n.plotLow=v,n.plotHigh=f.translate(g?a.modifyValue(d,n):d,0,1,0,1),g&&(n.yBottom=n.plotHigh))});this.chart.polar&&this.points.forEach(function(f){a.highToXY(f);f.tooltipPos=[(f.plotHighX+f.plotLowX)/2,(f.plotHigh+f.plotLow)/2]})},getGraphPath:function(a){var f=[],g=[],c,e=l.area.prototype.getGraphPath,d,v,m;m=this.options;var k=this.chart.polar&&!1!==m.connectEnds,q=m.connectNulls,B=m.step;a=a||this.points;for(c=a.length;c--;)d=
a[c],d.isNull||k||q||a[c+1]&&!a[c+1].isNull||g.push({plotX:d.plotX,plotY:d.plotY,doCurve:!1}),v={polarPlotY:d.polarPlotY,rectPlotX:d.rectPlotX,yBottom:d.yBottom,plotX:b(d.plotHighX,d.plotX),plotY:d.plotHigh,isNull:d.isNull},g.push(v),f.push(v),d.isNull||k||q||a[c-1]&&!a[c-1].isNull||g.push({plotX:d.plotX,plotY:d.plotY,doCurve:!1});a=e.call(this,a);B&&(!0===B&&(B="left"),m.step={left:"right",center:"center",right:"left"}[B]);f=e.call(this,f);g=e.call(this,g);m.step=B;m=[].concat(a,f);this.chart.polar||
"M"!==g[0]||(g[0]="L");this.graphPath=m;this.areaPath=a.concat(g);m.isArea=!0;m.xMap=a.xMap;this.areaPath.xMap=a.xMap;return m},drawDataLabels:function(){var a=this.points,f=a.length,b,c=[],e=this.options.dataLabels,d,v,m=this.chart.inverted,k,q;h(e)?1<e.length?(k=e[0],q=e[1]):(k=e[0],q={enabled:!1}):(k=p({},e),k.x=e.xHigh,k.y=e.yHigh,q=p({},e),q.x=e.xLow,q.y=e.yLow);if(k.enabled||this._hasPointLabels){for(b=f;b--;)if(d=a[b])v=k.inside?d.plotHigh<d.plotLow:d.plotHigh>d.plotLow,d.y=d.high,d._plotY=
d.plotY,d.plotY=d.plotHigh,c[b]=d.dataLabel,d.dataLabel=d.dataLabelUpper,d.below=v,m?k.align||(k.align=v?"right":"left"):k.verticalAlign||(k.verticalAlign=v?"top":"bottom");this.options.dataLabels=k;g.drawDataLabels&&g.drawDataLabels.apply(this,arguments);for(b=f;b--;)if(d=a[b])d.dataLabelUpper=d.dataLabel,d.dataLabel=c[b],delete d.dataLabels,d.y=d.low,d.plotY=d._plotY}if(q.enabled||this._hasPointLabels){for(b=f;b--;)if(d=a[b])v=q.inside?d.plotHigh<d.plotLow:d.plotHigh>d.plotLow,d.below=!v,m?q.align||
(q.align=v?"left":"right"):q.verticalAlign||(q.verticalAlign=v?"bottom":"top");this.options.dataLabels=q;g.drawDataLabels&&g.drawDataLabels.apply(this,arguments)}if(k.enabled)for(b=f;b--;)if(d=a[b])d.dataLabels=[d.dataLabelUpper,d.dataLabel].filter(function(d){return!!d});this.options.dataLabels=e},alignDataLabel:function(){l.column.prototype.alignDataLabel.apply(this,arguments)},drawPoints:function(){var f=this.points.length,b,e;g.drawPoints.apply(this,arguments);for(e=0;e<f;)b=this.points[e],b.origProps=
{plotY:b.plotY,plotX:b.plotX,isInside:b.isInside,negative:b.negative,zone:b.zone,y:b.y},b.lowerGraphic=b.graphic,b.graphic=b.upperGraphic,b.plotY=b.plotHigh,a(b.plotHighX)&&(b.plotX=b.plotHighX),b.y=b.high,b.negative=b.high<(this.options.threshold||0),b.zone=this.zones.length&&b.getZone(),this.chart.polar||(b.isInside=b.isTopInside=void 0!==b.plotY&&0<=b.plotY&&b.plotY<=this.yAxis.len&&0<=b.plotX&&b.plotX<=this.xAxis.len),e++;g.drawPoints.apply(this,arguments);for(e=0;e<f;)b=this.points[e],b.upperGraphic=
b.graphic,b.graphic=b.lowerGraphic,c.extend(b,b.origProps),delete b.origProps,e++},setStackedPoints:c.noop},{setState:function(){var b=this.state,g=this.series,e=g.chart.polar;a(this.plotHigh)||(this.plotHigh=g.yAxis.toPixels(this.high,!0));a(this.plotLow)||(this.plotLow=this.plotY=g.yAxis.toPixels(this.low,!0));g.stateMarkerGraphic&&(g.lowerStateMarkerGraphic=g.stateMarkerGraphic,g.stateMarkerGraphic=g.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;e&&(this.plotX=
this.plotHighX);f.setState.apply(this,arguments);this.state=b;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;e&&(this.plotX=this.plotLowX);g.stateMarkerGraphic&&(g.upperStateMarkerGraphic=g.stateMarkerGraphic,g.stateMarkerGraphic=g.lowerStateMarkerGraphic,g.lowerStateMarkerGraphic=void 0);f.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,b=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(b=f.haloPath.apply(this,arguments));this.plotY=
this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(b=b.concat(f.haloPath.apply(this,arguments)));return b},destroyElements:function(){["lowerGraphic","upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return f.destroyElements.apply(this,arguments)}})});y(r,"parts-more/AreaSplineRangeSeries.js",[r["parts/Globals.js"]],function(c){var e=c.seriesType;e("areasplinerange","arearange",null,{getPointSpline:c.seriesTypes.spline.prototype.getPointSpline})});
y(r,"parts-more/ColumnRangeSeries.js",[r["parts/Globals.js"]],function(c){var e=c.defaultPlotOptions,h=c.merge,b=c.noop,p=c.pick,a=c.seriesType,l=c.seriesTypes.column.prototype;a("columnrange","arearange",h(e.column,e.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{translate:function(){var a=this,b=a.yAxis,e=a.xAxis,c=e.startAngleRad,h,t=a.chart,x=a.xAxis.isRadial,d=Math.max(t.chartWidth,t.chartHeight)+999,v;l.translate.apply(a);a.points.forEach(function(m){var k=m.shapeArgs,q=
a.options.minPointLength,f,g;m.plotHigh=v=Math.min(Math.max(-d,b.translate(m.high,0,1,0,1)),d);m.plotLow=Math.min(Math.max(-d,m.plotY),d);g=v;f=p(m.rectPlotY,m.plotY)-v;Math.abs(f)<q?(q-=f,f+=q,g-=q/2):0>f&&(f*=-1,g-=f);x?(h=m.barX+c,m.shapeType="path",m.shapeArgs={d:a.polarArc(g+f,g,h,h+m.pointWidth)}):(k.height=f,k.y=g,m.tooltipPos=t.inverted?[b.len+b.pos-t.plotLeft-g-f/2,e.len+e.pos-t.plotTop-k.x-k.width/2,f]:[e.left-t.plotLeft+k.x+k.width/2,b.pos-t.plotTop+g+f/2,f])})},directTouch:!0,trackerGroups:["group",
"dataLabelsGroup"],drawGraph:b,getSymbol:b,crispCol:function(){return l.crispCol.apply(this,arguments)},drawPoints:function(){return l.drawPoints.apply(this,arguments)},drawTracker:function(){return l.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return l.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return l.pointAttribs.apply(this,arguments)},animate:function(){return l.animate.apply(this,arguments)},polarArc:function(){return l.polarArc.apply(this,arguments)},
translate3dPoints:function(){return l.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return l.translate3dShapes.apply(this,arguments)}},{setState:l.pointClass.prototype.setState})});y(r,"parts-more/ColumnPyramidSeries.js",[r["parts/Globals.js"]],function(c){var e=c.pick,h=c.seriesType,b=c.seriesTypes.column.prototype;h("columnpyramid","column",{},{translate:function(){var c=this,a=c.chart,l=c.options,g=c.dense=2>c.closestPointRange*c.xAxis.transA,g=c.borderWidth=e(l.borderWidth,
g?0:1),f=c.yAxis,u=l.threshold,n=c.translatedThreshold=f.getThreshold(u),h=e(l.minPointLength,5),t=c.getColumnMetrics(),x=t.width,d=c.barW=Math.max(x,1+2*g),v=c.pointXOffset=t.offset;a.inverted&&(n-=.5);l.pointPadding&&(d=Math.ceil(d));b.translate.apply(c);c.points.forEach(function(m){var k=e(m.yBottom,n),q=999+Math.abs(k),b=Math.min(Math.max(-q,m.plotY),f.len+q),q=m.plotX+v,g=d/2,p=Math.min(b,k),k=Math.max(b,k)-p,A,C,E,w,t,D;m.barX=q;m.pointWidth=x;m.tooltipPos=a.inverted?[f.len+f.pos-a.plotLeft-
b,c.xAxis.len-q-g,k]:[q+g,b+f.pos-a.plotTop,k];b=u+(m.total||m.y);"percent"===l.stacking&&(b=u+(0>m.y)?-100:100);b=f.toPixels(b,!0);A=a.plotHeight-b-(a.plotHeight-n);C=g*(p-b)/A;E=g*(p+k-b)/A;A=q-C+g;C=q+C+g;w=q+E+g;E=q-E+g;t=p-h;D=p+k;0>m.y&&(t=p,D=p+k+h);a.inverted&&(w=a.plotWidth-p,A=b-(a.plotWidth-n),C=g*(b-w)/A,E=g*(b-(w-k))/A,A=q+g+C,C=A-2*C,w=q-E+g,E=q+E+g,t=p,D=p+k-h,0>m.y&&(D=p+k+h));m.shapeType="path";m.shapeArgs={x:A,y:t,width:C-A,height:k,d:["M",A,t,"L",C,t,w,D,E,D,"Z"]}})}})});y(r,"parts-more/GaugeSeries.js",
[r["parts/Globals.js"],r["parts/Utilities.js"]],function(c,e){var h=e.isNumber,b=e.pInt,p=c.merge,a=c.pick,l=c.Series;e=c.seriesType;var g=c.TrackerMixin;e("gauge","line",{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:c.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var f=
this.yAxis,g=this.options,c=f.center;this.generatePoints();this.points.forEach(function(e){var l=p(g.dial,e.dial),n=b(a(l.radius,80))*c[2]/200,d=b(a(l.baseLength,70))*n/100,v=b(a(l.rearLength,10))*n/100,m=l.baseWidth||3,k=l.topWidth||1,q=g.overshoot,B=f.startAngleRad+f.translate(e.y,null,null,null,!0);h(q)?(q=q/180*Math.PI,B=Math.max(f.startAngleRad-q,Math.min(f.endAngleRad+q,B))):!1===g.wrap&&(B=Math.max(f.startAngleRad,Math.min(f.endAngleRad,B)));B=180*B/Math.PI;e.shapeType="path";e.shapeArgs={d:l.path||
["M",-v,-m/2,"L",d,-m/2,n,-k/2,n,k/2,d,m/2,-v,m/2,"z"],translateX:c[0],translateY:c[1],rotation:B};e.plotX=c[0];e.plotY=c[1]})},drawPoints:function(){var b=this,g=b.chart,c=b.yAxis.center,e=b.pivot,l=b.options,h=l.pivot,d=g.renderer;b.points.forEach(function(a){var m=a.graphic,k=a.shapeArgs,q=k.d,f=p(l.dial,a.dial);m?(m.animate(k),k.d=q):a.graphic=d[a.shapeType](k).attr({rotation:k.rotation,zIndex:1}).addClass("highcharts-dial").add(b.group);if(!g.styledMode)a.graphic[m?"animate":"attr"]({stroke:f.borderColor||
"none","stroke-width":f.borderWidth||0,fill:f.backgroundColor||"#000000"})});e?e.animate({translateX:c[0],translateY:c[1]}):(b.pivot=d.circle(0,0,a(h.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(c[0],c[1]).add(b.group),g.styledMode||b.pivot.attr({"stroke-width":h.borderWidth||0,stroke:h.borderColor||"#cccccc",fill:h.backgroundColor||"#000000"}))},animate:function(a){var b=this;a||(b.points.forEach(function(a){var f=a.graphic;f&&(f.attr({rotation:180*b.yAxis.startAngleRad/Math.PI}),
f.animate({rotation:a.shapeArgs.rotation},b.options.animation))}),b.animate=null)},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);l.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(b,g){l.prototype.setData.call(this,b,!1);this.processData();this.generatePoints();a(g,!0)&&this.chart.redraw()},hasData:function(){return!!this.points.length},drawTracker:g&&g.drawTrackerPoint},{setState:function(a){this.state=
a}})});y(r,"parts-more/BoxPlotSeries.js",[r["parts/Globals.js"]],function(c){var e=c.noop,h=c.pick,b=c.seriesType,p=c.seriesTypes;b("boxplot","column",{threshold:null,tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eMaximum: {point.high}\x3cbr/\x3eUpper quartile: {point.q3}\x3cbr/\x3eMedian: {point.median}\x3cbr/\x3eLower quartile: {point.q1}\x3cbr/\x3eMinimum: {point.low}\x3cbr/\x3e'},whiskerLength:"50%",fillColor:"#ffffff",
lineWidth:1,medianWidth:2,whiskerWidth:2},{pointArrayMap:["low","q1","median","q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:e,translate:function(){var a=this.yAxis,b=this.pointArrayMap;p.column.prototype.translate.apply(this);this.points.forEach(function(g){b.forEach(function(b){null!==g[b]&&(g[b+"Plot"]=a.translate(g[b],0,1,0,1))})})},drawPoints:function(){var a=this,b=a.options,g=a.chart,f=g.renderer,
c,e,p,t,x,d,v=0,m,k,q,B,F=!1!==a.doQuartiles,G,A=a.options.whiskerLength;a.points.forEach(function(l){var n=l.graphic,u=n?"animate":"attr",w=l.shapeArgs,C={},r={},K={},L={},z=l.color||a.color;void 0!==l.plotY&&(m=w.width,k=Math.floor(w.x),q=k+m,B=Math.round(m/2),c=Math.floor(F?l.q1Plot:l.lowPlot),e=Math.floor(F?l.q3Plot:l.lowPlot),p=Math.floor(l.highPlot),t=Math.floor(l.lowPlot),n||(l.graphic=n=f.g("point").add(a.group),l.stem=f.path().addClass("highcharts-boxplot-stem").add(n),A&&(l.whiskers=f.path().addClass("highcharts-boxplot-whisker").add(n)),
F&&(l.box=f.path(void 0).addClass("highcharts-boxplot-box").add(n)),l.medianShape=f.path(void 0).addClass("highcharts-boxplot-median").add(n)),g.styledMode||(r.stroke=l.stemColor||b.stemColor||z,r["stroke-width"]=h(l.stemWidth,b.stemWidth,b.lineWidth),r.dashstyle=l.stemDashStyle||b.stemDashStyle,l.stem.attr(r),A&&(K.stroke=l.whiskerColor||b.whiskerColor||z,K["stroke-width"]=h(l.whiskerWidth,b.whiskerWidth,b.lineWidth),l.whiskers.attr(K)),F&&(C.fill=l.fillColor||b.fillColor||z,C.stroke=b.lineColor||
z,C["stroke-width"]=b.lineWidth||0,l.box.attr(C)),L.stroke=l.medianColor||b.medianColor||z,L["stroke-width"]=h(l.medianWidth,b.medianWidth,b.lineWidth),l.medianShape.attr(L)),d=l.stem.strokeWidth()%2/2,v=k+B+d,l.stem[u]({d:["M",v,e,"L",v,p,"M",v,c,"L",v,t]}),F&&(d=l.box.strokeWidth()%2/2,c=Math.floor(c)+d,e=Math.floor(e)+d,k+=d,q+=d,l.box[u]({d:["M",k,e,"L",k,c,"L",q,c,"L",q,e,"L",k,e,"z"]})),A&&(d=l.whiskers.strokeWidth()%2/2,p+=d,t+=d,G=/%$/.test(A)?B*parseFloat(A)/100:A/2,l.whiskers[u]({d:["M",
v-G,p,"L",v+G,p,"M",v-G,t,"L",v+G,t]})),x=Math.round(l.medianPlot),d=l.medianShape.strokeWidth()%2/2,x+=d,l.medianShape[u]({d:["M",k,x,"L",q,x]}))})},setStackedPoints:e})});y(r,"parts-more/ErrorBarSeries.js",[r["parts/Globals.js"]],function(c){var e=c.noop,h=c.seriesType,b=c.seriesTypes;h("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.low}\x3c/b\x3e - \x3cb\x3e{point.high}\x3c/b\x3e\x3cbr/\x3e'},
whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(b){return[b.low,b.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:b.arearange?function(){var c=this.pointValKey;b.arearange.prototype.drawDataLabels.call(this);this.data.forEach(function(a){a.y=a[c]})}:e,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||b.column.prototype.getColumnMetrics.call(this)}})});y(r,"parts-more/WaterfallSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],
function(c,e){var h=e.isNumber,b=c.correctFloat,p=c.pick,a=c.objectEach,l=c.arrayMin,g=c.arrayMax;e=c.addEvent;var f=c.Axis,u=c.Chart,n=c.Point,w=c.Series,t=c.StackItem,x=c.seriesType,d=c.seriesTypes;e(f,"afterInit",function(){this.isXAxis||(this.waterfallStacks={changed:!1})});e(u,"beforeRedraw",function(){for(var d=this.axes,a=this.series,k=a.length;k--;)a[k].options.stacking&&(d.forEach(function(d){d.isXAxis||(d.waterfallStacks.changed=!0)}),k=0)});e(f,"afterRender",function(){var d=this.options.stackLabels;
d&&d.enabled&&this.waterfallStacks&&this.renderWaterfallStackTotals()});f.prototype.renderWaterfallStackTotals=function(){var d=this.waterfallStacks,b=this.stackTotalGroup,k=new t(this,this.options.stackLabels,!1,0,void 0);this.dummyStackItem=k;a(d,function(d){a(d,function(d){k.total=d.stackTotal;d.label&&(k.label=d.label);t.prototype.render.call(k,b);d.label=k.label;delete k.label})});k.total=null};x("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",
states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,generatePoints:function(){var a,m,k,q;d.column.prototype.generatePoints.apply(this);k=0;for(m=this.points.length;k<m;k++)if(a=this.points[k],q=this.processedYData[k],a.isIntermediateSum||a.isSum)a.y=b(q)},translate:function(){var a=this.options,b=this.yAxis,k,q,g,f,c,e,l,n,h,u=p(a.minPointLength,5),x=u/2,t=a.threshold,w=a.stacking,r=b.waterfallStacks[this.stackKey],z;d.column.prototype.translate.apply(this);l=n=t;q=this.points;k=0;for(a=
q.length;k<a;k++){g=q[k];e=this.processedYData[k];f=g.shapeArgs;h=[0,e];z=g.y;if(w){if(r&&(h=r[k],"overlap"===w?(c=h.stackState[h.stateIndex--],c=0<=z?c:c-z,h.hasOwnProperty("absolutePos")&&delete h.absolutePos,h.hasOwnProperty("absoluteNeg")&&delete h.absoluteNeg):(0<=z?(c=h.threshold+h.posTotal,h.posTotal-=z):(c=h.threshold+h.negTotal,h.negTotal-=z,c-=z),!h.posTotal&&h.hasOwnProperty("absolutePos")&&(h.posTotal=h.absolutePos,delete h.absolutePos),!h.negTotal&&h.hasOwnProperty("absoluteNeg")&&(h.negTotal=
h.absoluteNeg,delete h.absoluteNeg)),g.isSum||(h.connectorThreshold=h.threshold+h.stackTotal),b.reversed?(e=0<=z?c-z:c+z,z=c):(e=c,z=c-z),g.below=e<=p(t,0),f.y=b.translate(e,0,1,0,1),f.height=Math.abs(f.y-b.translate(z,0,1,0,1))),z=b.dummyStackItem)z.x=k,z.label=r[k].label,z.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[k],this.stackedYPos[k])}else c=Math.max(l,l+z)+h[0],f.y=b.translate(c,0,1,0,1),g.isSum?(f.y=b.translate(h[1],0,1,0,1),f.height=Math.min(b.translate(h[0],0,1,0,1),b.len)-
f.y):g.isIntermediateSum?(0<=z?(e=h[1]+n,z=n):(e=n,z=h[1]+n),b.reversed&&(e^=z,z^=e,e^=z),f.y=b.translate(e,0,1,0,1),f.height=Math.abs(f.y-Math.min(b.translate(z,0,1,0,1),b.len)),n+=h[1]):(f.height=0<e?b.translate(l,0,1,0,1)-f.y:b.translate(l,0,1,0,1)-b.translate(l-e,0,1,0,1),l+=e,g.below=l<p(t,0)),0>f.height&&(f.y+=f.height,f.height*=-1);g.plotY=f.y=Math.round(f.y)-this.borderWidth%2/2;f.height=Math.max(Math.round(f.height),.001);g.yBottom=f.y+f.height;f.height<=u&&!g.isNull?(f.height=u,f.y-=x,g.plotY=
f.y,g.minPointLengthOffset=0>g.y?-x:x):(g.isNull&&(f.width=0),g.minPointLengthOffset=0);f=g.plotY+(g.negative?f.height:0);this.chart.inverted?g.tooltipPos[0]=b.len-f:g.tooltipPos[1]=f}},processData:function(d){var a=this.options,k=this.yData,q=a.data,f,g=k.length,c=a.threshold||0,e,v,l,h,p,n;for(n=v=e=l=h=0;n<g;n++)p=k[n],f=q&&q[n]?q[n]:{},"sum"===p||f.isSum?k[n]=b(v):"intermediateSum"===p||f.isIntermediateSum?(k[n]=b(e),e=0):(v+=p,e+=p),l=Math.min(v,l),h=Math.max(v,h);w.prototype.processData.call(this,
d);a.stacking||(this.dataMin=l+c,this.dataMax=h)},toYData:function(d){return d.isSum?0===d.x?null:"sum":d.isIntermediateSum?0===d.x?null:"intermediateSum":d.y},pointAttribs:function(a,b){var k=this.options.upColor;k&&!a.options.color&&(a.color=0<a.y?k:null);a=d.column.prototype.pointAttribs.call(this,a,b);delete a.dashstyle;return a},getGraphPath:function(){return["M",0,0]},getCrispPath:function(){var d=this.data,a=this.yAxis,k=d.length,b=Math.round(this.graph.strokeWidth())%2/2,f=Math.round(this.borderWidth)%
2/2,g=this.xAxis.reversed,e=this.yAxis.reversed,c=this.options.stacking,l=[],h,p,n,u,x,t,w;for(t=1;t<k;t++){x=d[t].shapeArgs;p=d[t-1];u=d[t-1].shapeArgs;h=a.waterfallStacks[this.stackKey];n=0<p.y?-u.height:0;h&&(h=h[t-1],c?(h=h.connectorThreshold,n=Math.round(a.translate(h,0,1,0,1)+(e?n:0))-b):n=u.y+p.minPointLengthOffset+f-b,w=["M",u.x+(g?0:u.width),n,"L",x.x+(g?x.width:0),n]);if(!c&&0>p.y&&!e||0<p.y&&e)w[2]+=u.height,w[5]+=u.height;l=l.concat(w)}return l},drawGraph:function(){w.prototype.drawGraph.call(this);
this.graph.attr({d:this.getCrispPath()})},setStackedPoints:function(){function d(d,a,k,b){if(x)for(k;k<x;k++)h.stackState[k]+=b;else h.stackState[0]=d,x=h.stackState.length;h.stackState.push(h.stackState[x-1]+a)}var a=this.options,k=this.yAxis.waterfallStacks,b=a.threshold,f=b||0,g=f,e=this.stackKey,c=this.xData,l=c.length,h,p,n,u,x,t,w,r,y;this.yAxis.usePercentage=!1;p=n=u=f;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){k[e]||(k[e]={});for(var e=k[e],H=0;H<l;H++){t=c[H];if(!e[t]||
k.changed)e[t]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:k.changed&&e[t]?e[t].label:void 0};h=e[t];y=this.yData[H];0<=y?h.posTotal+=y:h.negTotal+=y;r=a.data[H];t=h.absolutePos=h.posTotal;w=h.absoluteNeg=h.negTotal;h.stackTotal=t+w;x=h.stackState.length;r&&r.isIntermediateSum?(d(u,n,0,u),u=n,n=b,f^=g,g^=f,f^=g):r&&r.isSum?(d(b,p,x),f=b):(d(f,y,0,p),r&&(p+=y,n+=y));h.stateIndex++;h.threshold=f;f+=h.stackTotal}k.changed=!1}},getExtremes:function(){var d=this.options.stacking,
b,k,q;d&&(b=this.yAxis,b=b.waterfallStacks,k=this.stackedYNeg=[],q=this.stackedYPos=[],"overlap"===d?a(b[this.stackKey],function(d){k.push(l(d.stackState));q.push(g(d.stackState))}):a(b[this.stackKey],function(d){k.push(d.negTotal+d.threshold);q.push(d.posTotal+d.threshold)}),this.dataMin=l(k),this.dataMax=g(q))}},{getClassName:function(){var d=n.prototype.getClassName.call(this);this.isSum?d+=" highcharts-sum":this.isIntermediateSum&&(d+=" highcharts-intermediate-sum");return d},isValid:function(){return h(this.y)||
this.isSum||this.isIntermediateSum}})});y(r,"parts-more/PolygonSeries.js",[r["parts/Globals.js"]],function(c){var e=c.Series,h=c.seriesType,b=c.seriesTypes;h("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var b=e.prototype.getGraphPath.call(this),a=b.length+1;a--;)(a===b.length||"M"===b[a])&&0<a&&b.splice(a,0,"z");return this.areaPath=b},drawGraph:function(){this.options.fillColor=
this.color;b.area.prototype.drawGraph.call(this)},drawLegendSymbol:c.LegendSymbolMixin.drawRectangle,drawTracker:e.prototype.drawTracker,setStackedPoints:c.noop})});y(r,"parts-more/BubbleLegend.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(c,e){var h=e.isNumber;e=c.Series;var b=c.Legend,p=c.Chart,a=c.addEvent,l=c.wrap,g=c.color,f=c.numberFormat,u=c.objectEach,n=c.merge,w=c.noop,t=c.pick,x=c.stableSort,d=c.setOptions,v=c.arrayMin,m=c.arrayMax;d({legend:{bubbleLegend:{borderColor:void 0,
borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});c.BubbleLegend=function(d,a){this.init(d,a)};c.BubbleLegend.prototype=
{init:function(d,a){this.options=d;this.visible=!0;this.chart=a.chart;this.legend=a},setState:w,addToLegend:function(d){d.splice(this.options.legendIndex,0,this)},drawLegendSymbol:function(d){var a=this.chart,k=this.options,b=t(d.options.itemDistance,20),f,g=k.ranges;f=k.connectorDistance;this.fontMetrics=a.renderer.fontMetrics(k.labels.style.fontSize.toString()+"px");g&&g.length&&h(g[0].value)?(x(g,function(d,a){return a.value-d.value}),this.ranges=g,this.setOptions(),this.render(),a=this.getMaxLabelSize(),
g=this.ranges[0].radius,d=2*g,f=f-g+a.width,f=0<f?f:0,this.maxLabel=a,this.movementX="left"===k.labels.align?f:0,this.legendItemWidth=d+f+b,this.legendItemHeight=d+this.fontMetrics.h/2):d.options.bubbleLegend.autoRanges=!0},setOptions:function(){var d=this.ranges,a=this.options,b=this.chart.series[a.seriesIndex],f=this.legend.baseline,e={"z-index":a.zIndex,"stroke-width":a.borderWidth},c={"z-index":a.zIndex,"stroke-width":a.connectorWidth},m=this.getLabelStyles(),l=b.options.marker.fillOpacity,h=
this.chart.styledMode;d.forEach(function(k,q){h||(e.stroke=t(k.borderColor,a.borderColor,b.color),e.fill=t(k.color,a.color,1!==l?g(b.color).setOpacity(l).get("rgba"):b.color),c.stroke=t(k.connectorColor,a.connectorColor,b.color));d[q].radius=this.getRangeRadius(k.value);d[q]=n(d[q],{center:d[0].radius-d[q].radius+f});h||n(!0,d[q],{bubbleStyle:n(!1,e),connectorStyle:n(!1,c),labelStyle:m})},this)},getLabelStyles:function(){var d=this.options,a={},b="left"===d.labels.align,f=this.legend.options.rtl;
u(d.labels.style,function(d,b){"color"!==b&&"fontSize"!==b&&"z-index"!==b&&(a[b]=d)});return n(!1,a,{"font-size":d.labels.style.fontSize,fill:t(d.labels.style.color,"#000000"),"z-index":d.zIndex,align:f||b?"right":"left"})},getRangeRadius:function(d){var a=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,a.ranges[a.ranges.length-1].value,a.ranges[0].value,a.minSize,a.maxSize,d)},render:function(){var d=this.chart.renderer,a=this.options.zThreshold;this.symbols||
(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=d.g("bubble-legend");this.legendItem=d.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(d){d.value>=a&&this.renderRange(d)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()},renderRange:function(d){var a=this.options,b=a.labels,k=this.chart.renderer,f=this.symbols,g=f.labels,e=d.center,c=Math.abs(d.radius),
m=a.connectorDistance,l=b.align,h=b.style.fontSize,m=this.legend.options.rtl||"left"===l?-m:m,b=a.connectorWidth,v=this.ranges[0].radius,p=e-c-a.borderWidth/2+b/2,n,h=h/2-(this.fontMetrics.h-h)/2,u=k.styledMode;"center"===l&&(m=0,a.connectorDistance=0,d.labelStyle.align="center");l=p+a.labels.y;n=v+m+a.labels.x;f.bubbleItems.push(k.circle(v,e+((p%1?1:.5)-(b%2?0:.5)),c).attr(u?{}:d.bubbleStyle).addClass((u?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(a.className||
"")).add(this.legendSymbol));f.connectors.push(k.path(k.crispLine(["M",v,p,"L",v+m,p],a.connectorWidth)).attr(u?{}:d.connectorStyle).addClass((u?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(a.connectorClassName||"")).add(this.legendSymbol));d=k.text(this.formatLabel(d),n,l+h).attr(u?{}:d.labelStyle).addClass("highcharts-bubble-legend-labels "+(a.labels.className||"")).add(this.legendSymbol);g.push(d);d.placed=!0;d.alignAttr={x:n,y:l+h}},getMaxLabelSize:function(){var d,
a;this.symbols.labels.forEach(function(b){a=b.getBBox(!0);d=d?a.width>d.width?a:d:a});return d||{}},formatLabel:function(d){var a=this.options,b=a.labels.formatter;return(a=a.labels.format)?c.format(a,d):b?b.call(d):f(d.value,1)},hideOverlappingLabels:function(){var d=this.chart,a=this.symbols;!this.options.labels.allowOverlap&&a&&(d.hideOverlappingLabels(a.labels),a.labels.forEach(function(d,b){d.newOpacity?d.newOpacity!==d.oldOpacity&&a.connectors[b].show():a.connectors[b].hide()}))},getRanges:function(){var d=
this.legend.bubbleLegend,a,b=d.options.ranges,f,g=Number.MAX_VALUE,e=-Number.MAX_VALUE;d.chart.series.forEach(function(d){d.isBubble&&!d.ignoreSeries&&(f=d.zData.filter(h),f.length&&(g=t(d.options.zMin,Math.min(g,Math.max(v(f),!1===d.options.displayNegative?d.options.zThreshold:-Number.MAX_VALUE))),e=t(d.options.zMax,Math.max(e,m(f)))))});a=g===e?[{value:e}]:[{value:g},{value:(g+e)/2},{value:e,autoRanges:!0}];b.length&&b[0].radius&&a.reverse();a.forEach(function(d,k){b&&b[k]&&(a[k]=n(!1,b[k],d))});
return a},predictBubbleSizes:function(){var d=this.chart,a=this.fontMetrics,b=d.legend.options,f="horizontal"===b.layout,g=f?d.legend.lastLineHeight:0,e=d.plotSizeX,c=d.plotSizeY,m=d.series[this.options.seriesIndex],d=Math.ceil(m.minPxSize),l=Math.ceil(m.maxPxSize),m=m.options.maxSize,h=Math.min(c,e);if(b.floating||!/%$/.test(m))a=l;else if(m=parseFloat(m),a=(h+g-a.h/2)*m/100/(m/100+1),f&&c-a>=e||!f&&e-a>=c)a=l;return[d,Math.ceil(a)]},updateRanges:function(d,a){var b=this.legend.options.bubbleLegend;
b.minSize=d;b.maxSize=a;b.ranges=this.getRanges()},correctSizes:function(){var d=this.legend,a=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,a.maxPxSize),d.render())}};a(c.Legend,"afterGetAllItems",function(d){var a=this.bubbleLegend,b=this.options,f=b.bubbleLegend,k=this.chart.getVisibleBubbleSeriesIndex();a&&a.ranges&&a.ranges.length&&(f.ranges.length&&(f.autoRanges=!!f.ranges[0].autoRanges),this.destroyItem(a));
0<=k&&b.enabled&&f.enabled&&(f.seriesIndex=k,this.bubbleLegend=new c.BubbleLegend(f,this),this.bubbleLegend.addToLegend(d.allItems))});p.prototype.getVisibleBubbleSeriesIndex=function(){for(var d=this.series,a=0;a<d.length;){if(d[a]&&d[a].isBubble&&d[a].visible&&d[a].zData.length)return a;a++}return-1};b.prototype.getLinesHeights=function(){var d=this.allItems,a=[],b,f=d.length,g,e=0;for(g=0;g<f;g++)if(d[g].legendItemHeight&&(d[g].itemHeight=d[g].legendItemHeight),d[g]===d[f-1]||d[g+1]&&d[g]._legendItemPos[1]!==
d[g+1]._legendItemPos[1]){a.push({height:0});b=a[a.length-1];for(e;e<=g;e++)d[e].itemHeight>b.height&&(b.height=d[e].itemHeight);b.step=g}return a};b.prototype.retranslateItems=function(d){var a,b,f,g=this.options.rtl,k=0;this.allItems.forEach(function(e,m){a=e.legendGroup.translateX;b=e._legendItemPos[1];if((f=e.movementX)||g&&e.ranges)f=g?a-e.options.maxSize/2:a+f,e.legendGroup.attr({translateX:f});m>d[k].step&&k++;e.legendGroup.attr({translateY:Math.round(b+d[k].height/2)});e._legendItemPos[1]=
b+d[k].height/2})};a(e,"legendItemClick",function(){var d=this.chart,a=this.visible,b=this.chart.legend;b&&b.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,d=0<=d.getVisibleBubbleSeriesIndex(),b.bubbleLegend.visible!==d&&(b.update({bubbleLegend:{enabled:d}}),b.bubbleLegend.visible=d),this.visible=a)});l(p.prototype,"drawChartBox",function(d,a,b){var f=this.legend,g=0<=this.getVisibleBubbleSeriesIndex(),k;f&&f.options.enabled&&f.bubbleLegend&&f.options.bubbleLegend.autoRanges&&g?(k=f.bubbleLegend.options,
g=f.bubbleLegend.predictBubbleSizes(),f.bubbleLegend.updateRanges(g[0],g[1]),k.placed||(f.group.placed=!1,f.allItems.forEach(function(d){d.legendGroup.translateY=null})),f.render(),this.getMargins(),this.axes.forEach(function(d){d.render();k.placed||(d.setScale(),d.updateNames(),u(d.ticks,function(d){d.isNew=!0;d.isNewLabel=!0}))}),k.placed=!0,this.getMargins(),d.call(this,a,b),f.bubbleLegend.correctSizes(),f.retranslateItems(f.getLinesHeights())):(d.call(this,a,b),f&&f.options.enabled&&f.bubbleLegend&&
(f.render(),f.retranslateItems(f.getLinesHeights())))})});y(r,"parts-more/BubbleSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(c,e){var h=e.isNumber,b=e.pInt,p=c.arrayMax,a=c.arrayMin;e=c.Axis;var l=c.color,g=c.noop,f=c.pick,u=c.Point,n=c.Series,w=c.seriesType,t=c.seriesTypes;w("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},
symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,d){var b=this.options.marker.fillOpacity;a=n.prototype.pointAttribs.call(this,a,d);1!==b&&(a.fill=l(a.fill).setOpacity(b).get("rgba"));
return a},getRadii:function(a,d,b){var f,g=this.zData,e=b.minPxSize,c=b.maxPxSize,l=[],h;f=0;for(b=g.length;f<b;f++)h=g[f],l.push(this.getRadius(a,d,e,c,h));this.radii=l},getRadius:function(a,d,b,f,g){var k=this.options,e="width"!==k.sizeBy,c=k.zThreshold,m=d-a;k.sizeByAbsoluteValue&&null!==g&&(g=Math.abs(g-c),m=Math.max(d-c,Math.abs(a-c)),a=0);h(g)?g<a?b=b/2-1:(a=0<m?(g-a)/m:.5,e&&0<=a&&(a=Math.sqrt(a)),b=Math.ceil(b+a*(f-b))/2):b=null;return b},animate:function(a){!a&&this.points.length<this.options.animationLimit&&
(this.points.forEach(function(d){var a=d.graphic,b;a&&a.width&&(b={x:a.x,y:a.y,width:a.width,height:a.height},a.attr({x:d.plotX,y:d.plotY,width:1,height:1}),a.animate(b,this.options.animation))},this),this.animate=null)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,d=this.data,b,f,g=this.radii;t.scatter.prototype.translate.call(this);for(a=d.length;a--;)b=d[a],f=g?g[a]:0,h(f)&&f>=this.minPxSize/2?(b.marker=c.extend(b.marker,{radius:f,width:2*f,height:2*f}),b.dlBox=
{x:b.plotX-f,y:b.plotY-f,width:2*f,height:2*f}):b.shapeArgs=b.plotY=b.dlBox=void 0},alignDataLabel:t.column.prototype.alignDataLabel,buildKDTree:g,applyZones:g},{haloPath:function(a){return u.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});e.prototype.beforePadding=function(){var g=this,d=this.len,e=this.chart,c=0,k=d,l=this.isXAxis,n=l?"xData":"yData",u=this.min,t={},w=Math.min(e.plotWidth,e.plotHeight),r=Number.MAX_VALUE,y=-Number.MAX_VALUE,J=this.max-
u,I=d/J,D=[];this.series.forEach(function(d){var k=d.options;!d.bubblePadding||!d.visible&&e.options.chart.ignoreHiddenSeries||(g.allowZoomOutside=!0,D.push(d),l&&(["minSize","maxSize"].forEach(function(d){var a=k[d],f=/%$/.test(a),a=b(a);t[d]=f?w*a/100:a}),d.minPxSize=t.minSize,d.maxPxSize=Math.max(t.maxSize,t.minSize),d=d.zData.filter(h),d.length&&(r=f(k.zMin,Math.min(r,Math.max(a(d),!1===k.displayNegative?k.zThreshold:-Number.MAX_VALUE))),y=f(k.zMax,Math.max(y,p(d))))))});D.forEach(function(d){var a=
d[n],b=a.length,f;l&&d.getRadii(r,y,d);if(0<J)for(;b--;)h(a[b])&&g.dataMin<=a[b]&&a[b]<=g.dataMax&&(f=d.radii[b],c=Math.min((a[b]-u)*I-f,c),k=Math.max((a[b]-u)*I+f,k))});D.length&&0<J&&!this.isLog&&(k-=d,I*=(d+Math.max(0,c)-Math.min(k,d))/d,[["min","userMin",c],["max","userMax",k]].forEach(function(d){void 0===f(g.options[d[0]],g[d[1]])&&(g[d[0]]+=d[2]/I)}))}});y(r,"modules/networkgraph/integrations.js",[r["parts/Globals.js"]],function(c){c.networkgraphIntegrations={verlet:{attractiveForceFunction:function(e,
c){return(c-e)/e},repulsiveForceFunction:function(e,c){return(c-e)/e*(c>e?1:0)},barycenter:function(){var e=this.options.gravitationalConstant,c=this.barycenter.xFactor,b=this.barycenter.yFactor,c=(c-(this.box.left+this.box.width)/2)*e,b=(b-(this.box.top+this.box.height)/2)*e;this.nodes.forEach(function(e){e.fixedPosition||(e.plotX-=c/e.mass/e.degree,e.plotY-=b/e.mass/e.degree)})},repulsive:function(e,c,b){c=c*this.diffTemperature/e.mass/e.degree;e.fixedPosition||(e.plotX+=b.x*c,e.plotY+=b.y*c)},
attractive:function(e,c,b){var h=e.getMass(),a=-b.x*c*this.diffTemperature;c=-b.y*c*this.diffTemperature;e.fromNode.fixedPosition||(e.fromNode.plotX-=a*h.fromNode/e.fromNode.degree,e.fromNode.plotY-=c*h.fromNode/e.fromNode.degree);e.toNode.fixedPosition||(e.toNode.plotX+=a*h.toNode/e.toNode.degree,e.toNode.plotY+=c*h.toNode/e.toNode.degree)},integrate:function(e,c){var b=-e.options.friction,h=e.options.maxSpeed,a=(c.plotX+c.dispX-c.prevX)*b,b=(c.plotY+c.dispY-c.prevY)*b,l=Math.abs,g=l(a)/(a||1),l=
l(b)/(b||1),a=g*Math.min(h,Math.abs(a)),b=l*Math.min(h,Math.abs(b));c.prevX=c.plotX+c.dispX;c.prevY=c.plotY+c.dispY;c.plotX+=a;c.plotY+=b;c.temperature=e.vectorLength({x:a,y:b})},getK:function(e){return Math.pow(e.box.width*e.box.height/e.nodes.length,.5)}},euler:{attractiveForceFunction:function(e,c){return e*e/c},repulsiveForceFunction:function(c,h){return h*h/c},barycenter:function(){var c=this.options.gravitationalConstant,h=this.barycenter.xFactor,b=this.barycenter.yFactor;this.nodes.forEach(function(e){if(!e.fixedPosition){var a=
e.getDegree(),a=a*(1+a/2);e.dispX+=(h-e.plotX)*c*a/e.degree;e.dispY+=(b-e.plotY)*c*a/e.degree}})},repulsive:function(c,h,b,p){c.dispX+=b.x/p*h/c.degree;c.dispY+=b.y/p*h/c.degree},attractive:function(c,h,b,p){var a=c.getMass(),e=b.x/p*h;h*=b.y/p;c.fromNode.fixedPosition||(c.fromNode.dispX-=e*a.fromNode/c.fromNode.degree,c.fromNode.dispY-=h*a.fromNode/c.fromNode.degree);c.toNode.fixedPosition||(c.toNode.dispX+=e*a.toNode/c.toNode.degree,c.toNode.dispY+=h*a.toNode/c.toNode.degree)},integrate:function(c,
h){var b;h.dispX+=h.dispX*c.options.friction;h.dispY+=h.dispY*c.options.friction;b=h.temperature=c.vectorLength({x:h.dispX,y:h.dispY});0!==b&&(h.plotX+=h.dispX/b*Math.min(Math.abs(h.dispX),c.temperature),h.plotY+=h.dispY/b*Math.min(Math.abs(h.dispY),c.temperature))},getK:function(c){return Math.pow(c.box.width*c.box.height/c.nodes.length,.3)}}}});y(r,"modules/networkgraph/QuadTree.js",[r["parts/Globals.js"]],function(c){var e=c.QuadTreeNode=function(b){this.box=b;this.boxSize=Math.min(b.width,b.height);
this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};c.extend(e.prototype,{insert:function(b,c){this.isInternal?this.nodes[this.getBoxPosition(b)].insert(b,c-1):(this.isEmpty=!1,this.body?c?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,c-1),this.body=!0),this.nodes[this.getBoxPosition(b)].insert(b,c-1)):this.nodes.push(b):(this.isInternal=!1,this.body=b))},updateMassAndCenter:function(){var b=0,c=0,a=0;this.isInternal?(this.nodes.forEach(function(e){e.isEmpty||
(b+=e.mass,c+=e.plotX*e.mass,a+=e.plotY*e.mass)}),c/=b,a/=b):this.body&&(b=this.body.mass,c=this.body.plotX,a=this.body.plotY);this.mass=b;this.plotX=c;this.plotY=a},divideBox:function(){var b=this.box.width/2,c=this.box.height/2;this.nodes[0]=new e({left:this.box.left,top:this.box.top,width:b,height:c});this.nodes[1]=new e({left:this.box.left+b,top:this.box.top,width:b,height:c});this.nodes[2]=new e({left:this.box.left+b,top:this.box.top+c,width:b,height:c});this.nodes[3]=new e({left:this.box.left,
top:this.box.top+c,width:b,height:c})},getBoxPosition:function(b){var c=b.plotY<this.box.top+this.box.height/2;return b.plotX<this.box.left+this.box.width/2?c?0:3:c?1:2}});var h=c.QuadTree=function(b,c,a,l){this.box={left:b,top:c,width:a,height:l};this.maxDepth=25;this.root=new e(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};c.extend(h.prototype,{insertNodes:function(b){b.forEach(function(b){this.root.insert(b,this.maxDepth)},this)},visitNodeRecursive:function(b,
c,a,e,g){var f;b||(b=this.root);b===this.root&&c&&(f=c(b));!1!==f&&(b.nodes.forEach(function(b){if(b.isInternal){c&&(f=c(b));if(!1===f)return;this.visitNodeRecursive(b,c,a,e,g)}else b.body&&c&&c(b.body);a&&a(b)},this),b===this.root&&a&&a(b))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(b){b.updateMassAndCenter()})},render:function(b,c){this.visitNodeRecursive(this.root,null,null,b,c)},clear:function(b){this.render(b,!0)},renderBox:function(b,c,a){b.graphic||a?a&&(b.graphic&&
(b.graphic=b.graphic.destroy()),b.graphic2&&(b.graphic2=b.graphic2.destroy()),b.label&&(b.label=b.label.destroy())):(b.graphic=c.renderer.rect(b.box.left+c.plotLeft,b.box.top+c.plotTop,b.box.width,b.box.height).attr({stroke:"rgba(100, 100, 100, 0.5)","stroke-width":2}).add(),isNaN(b.plotX)||(b.graphic2=c.renderer.circle(b.plotX,b.plotY,b.mass/10).attr({fill:"red",translateY:c.plotTop,translateX:c.plotLeft}).add()))}})});y(r,"modules/networkgraph/layouts.js",[r["parts/Globals.js"]],function(c){var e=
c.pick,h=c.defined,b=c.addEvent,p=c.Chart;c.layouts={"reingold-fruchterman":function(){}};c.extend(c.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=c.networkgraphIntegrations[a.integration];this.attractiveForce=e(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=e(a.repulsiveForce,this.integration.repulsiveForceFunction);
this.approximation=a.approximation},start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.render()}));this.setK();this.resetSimulation(b);b.enableSimulation&&this.step()},step:function(){var a=this,b=this.series,g=this.options;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(b){a[b+"Forces"](a.temperature)});
a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();g.enableSimulation&&(b.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&c.win.cancelAnimationFrame(a.simulation),a.simulation=c.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&c.win.cancelAnimationFrame(this.simulation)},
setArea:function(a,b,c,f){this.box={left:a,top:b,width:c,height:f}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addNodes:function(a){a.forEach(function(a){-1===this.nodes.indexOf(a)&&this.nodes.push(a)},this)},removeNode:function(a){a=this.nodes.indexOf(a);-1!==a&&this.nodes.splice(a,1)},removeLink:function(a){a=this.links.indexOf(a);-1!==a&&this.links.splice(a,1)},addLinks:function(a){a.forEach(function(a){-1===this.links.indexOf(a)&&this.links.push(a)},this)},addSeries:function(a){-1===
this.series.indexOf(a)&&this.series.push(a)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},setMaxIterations:function(a){this.maxIterations=e(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=
this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new c.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;c.isFunction(a)?(a.call(this),this.nodes.forEach(function(a){h(a.prevX)||(a.prevX=a.plotX);h(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():
this.setRandomPositions()},setCircularPositions:function(){function a(b){b.linksFrom.forEach(function(d){p[d.toNode.id]||(p[d.toNode.id]=!0,n.push(d.toNode),a(d.toNode))})}var b=this.box,c=this.nodes,f=2*Math.PI/(c.length+1),h=c.filter(function(a){return 0===a.linksTo.length}),n=[],p={},t=this.options.initialPositionRadius;h.forEach(function(b){n.push(b);a(b)});n.length?c.forEach(function(a){-1===n.indexOf(a)&&n.push(a)}):n=c;n.forEach(function(a,d){a.plotX=a.prevX=e(a.plotX,b.width/2+t*Math.cos(d*
f));a.plotY=a.prevY=e(a.plotY,b.height/2+t*Math.sin(d*f));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var b=this.box,c=this.nodes,f=c.length+1;c.forEach(function(c,g){c.plotX=c.prevX=e(c.plotX,b.width*a(g));c.plotY=c.prevY=e(c.plotY,b.height*a(f+g));c.dispX=0;c.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=
0,b=0,c=0;this.nodes.forEach(function(f){b+=f.plotX*f.mass;c+=f.plotY*f.mass;a+=f.mass});return this.barycenter={x:b,y:c,xFactor:b/a,yFactor:c/a}},barnesHutApproximation:function(a,b){var c=this.getDistXY(a,b),f=this.vectorLength(c),e,l;a!==b&&0!==f&&(b.isInternal?b.boxSize/f<this.options.theta&&0!==f?(l=this.repulsiveForce(f,this.k),this.force("repulsive",a,l*b.mass,c,f),e=!1):e=!0:(l=this.repulsiveForce(f,this.k),this.force("repulsive",a,l*b.mass,c,f)));return e},repulsiveForces:function(){var a=
this;"barnes-hut"===a.approximation?a.nodes.forEach(function(b){a.quadTree.visitNodeRecursive(null,function(c){return a.barnesHutApproximation(b,c)})}):a.nodes.forEach(function(b){a.nodes.forEach(function(c){var f,g,e;b===c||b.fixedPosition||(e=a.getDistXY(b,c),g=a.vectorLength(e),0!==g&&(f=a.repulsiveForce(g,a.k),a.force("repulsive",b,f*c.mass,e,g)))})})},attractiveForces:function(){var a=this,b,c,f;a.links.forEach(function(g){g.fromNode&&g.toNode&&(b=a.getDistXY(g.fromNode,g.toNode),c=a.vectorLength(b),
0!==c&&(f=a.attractiveForce(c,a.k),a.force("attractive",g,f,b,c)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),b.dispX=0,b.dispY=0)})},applyLimitBox:function(a,b){var c=a.marker&&a.marker.radius||0;a.plotX=Math.max(Math.min(a.plotX,b.width-c),b.left+c);a.plotY=Math.max(Math.min(a.plotY,b.height-c),b.top+c)},coolDown:function(a,b,c){return a-b*c},isStable:function(){return.00001>Math.abs(this.systemTemperature-
this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);return this.vectorLength(a)},getDistXY:function(a,b){var c=a.plotX-b.plotX;a=a.plotY-b.plotY;return{x:c,y:a,absX:Math.abs(c),absY:Math.abs(a)}}});b(p,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});
b(p,"render",function(){function a(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.options.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),b=!1,g=!0)}var b,g=!1;if(this.graphLayoutsLookup){c.setAnimation(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!b;)b=!0,this.graphLayoutsLookup.forEach(a);g&&this.series.forEach(function(a){a&&a.layout&&a.render()})}})});y(r,"modules/networkgraph/draggable-nodes.js",[r["parts/Globals.js"]],function(c){var e=c.Chart,
h=c.addEvent;c.dragNodesMixin={onMouseDown:function(b,c){c=this.chart.pointer.normalize(c);b.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:b.plotX,plotY:b.plotY};b.inDragMode=!0},onMouseMove:function(b,c){if(b.fixedPosition&&b.inDragMode){var a=this.chart,e=a.pointer.normalize(c);c=b.fixedPosition.chartX-e.chartX;e=b.fixedPosition.chartY-e.chartY;if(5<Math.abs(c)||5<Math.abs(e))c=b.fixedPosition.plotX-c,e=b.fixedPosition.plotY-e,a.isInsidePlot(c,e)&&(b.plotX=c,b.plotY=e,b.hasDragged=!0,this.redrawHalo(b),
this.layout.simulation?this.layout.resetSimulation():(this.layout.setInitialRendering(!1),this.layout.enableSimulation?this.layout.start():this.layout.setMaxIterations(1),this.chart.redraw(),this.layout.setInitialRendering(!0)))}},onMouseUp:function(b){b.fixedPosition&&b.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw(),b.inDragMode=b.hasDragged=!1,this.options.fixedDraggable||delete b.fixedPosition)},redrawHalo:function(b){b&&this.halo&&this.halo.attr({d:b.haloPath(this.options.states.hover.halo.size)})}};
h(e,"load",function(){var b=this,c,a,e;b.container&&(c=h(b.container,"mousedown",function(c){var f=b.hoverPoint;f&&f.series&&f.series.hasDraggableNodes&&f.series.options.draggable&&(f.series.onMouseDown(f,c),a=h(b.container,"mousemove",function(a){return f&&f.series&&f.series.onMouseMove(f,a)}),e=h(b.container.ownerDocument,"mouseup",function(b){a();e();return f&&f.series&&f.series.onMouseUp(f,b)}))}));h(b,"destroy",function(){c()})})});y(r,"parts-more/PackedBubbleSeries.js",[r["parts/Globals.js"],
r["parts/Utilities.js"]],function(c,e){var h=e.isArray,b=e.isNumber;e=c.seriesType;var p=c.Series,a=c.Point,l=c.defined,g=c.pick,f=c.addEvent,u=c.Chart,n=c.Color,w=c.layouts["reingold-fruchterman"],t=c.seriesTypes.bubble.prototype.pointClass,r=c.dragNodesMixin;c.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(d,a,b,c){return Math.min(d,(b.marker.radius+c.marker.radius)/2)},barycenter:function(){var d=this,a=d.options.gravitationalConstant,b=d.box,c=d.nodes,f,g;c.forEach(function(e){d.options.splitSeries&&
!e.isParentNode?(f=e.series.parentNode.plotX,g=e.series.parentNode.plotY):(f=b.width/2,g=b.height/2);e.fixedPosition||(e.plotX-=(e.plotX-f)*a/(e.mass*Math.sqrt(c.length)),e.plotY-=(e.plotY-g)*a/(e.mass*Math.sqrt(c.length)))})},repulsive:function(d,a,b,c){var f=a*this.diffTemperature/d.mass/d.degree;a=b.x*f;b=b.y*f;d.fixedPosition||(d.plotX+=a,d.plotY+=b);c.fixedPosition||(c.plotX-=a,c.plotY-=b)},integrate:c.networkgraphIntegrations.verlet.integrate,getK:c.noop};c.layouts.packedbubble=c.extendClass(w,
{beforeStep:function(){this.options.marker&&this.series.forEach(function(d){d&&d.calculateParentRadius()})},setCircularPositions:function(){var d=this,a=d.box,b=d.nodes,c=2*Math.PI/(b.length+1),f,e,h=d.options.initialPositionRadius;b.forEach(function(b,k){d.options.splitSeries&&!b.isParentNode?(f=b.series.parentNode.plotX,e=b.series.parentNode.plotY):(f=a.width/2,e=a.height/2);b.plotX=b.prevX=g(b.plotX,f+h*Math.cos(b.index||k*c));b.plotY=b.prevY=g(b.plotY,e+h*Math.sin(b.index||k*c));b.dispX=0;b.dispY=
0})},repulsiveForces:function(){var d=this,a,b,c,f=d.options.bubblePadding;d.nodes.forEach(function(e){e.degree=e.mass;e.neighbours=0;d.nodes.forEach(function(g){a=0;e===g||e.fixedPosition||!d.options.seriesInteraction&&e.series!==g.series||(c=d.getDistXY(e,g),b=d.vectorLength(c)-(e.marker.radius+g.marker.radius+f),0>b&&(e.degree+=.01,e.neighbours++,a=d.repulsiveForce(-b/Math.sqrt(e.neighbours),d.k,e,g)),d.force("repulsive",e,a*g.mass,c,g,b))})})},applyLimitBox:function(a){var d,b;this.options.splitSeries&&
!a.isParentNode&&this.options.parentNodeLimit&&(d=this.getDistXY(a,a.series.parentNode),b=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(d),0>b&&b>-2*a.marker.radius&&(a.plotX-=.01*d.x,a.plotY-=.01*d.y));w.prototype.applyLimitBox.apply(this,arguments)},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature||0<this.systemTemperature&&.02>this.systemTemperature/this.nodes.length&&this.enableSimulation}});e("packedbubble","bubble",
{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,
initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}},{hasDraggableNodes:!0,forces:["barycenter","repulsive"],pointArrayMap:["value"],pointValKey:"value",isCartesian:!1,axisTypes:[],noSharedTooltip:!0,accumulateAllPoints:function(a){var d=a.chart,b=[],c,f;for(c=0;c<d.series.length;c++)if(a=
d.series[c],a.visible||!d.options.chart.ignoreHiddenSeries)for(f=0;f<a.yData.length;f++)b.push([null,null,a.yData[f],a.index,f,{id:f,marker:{radius:0}}]);return b},init:function(){p.prototype.init.apply(this,arguments);f(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)});return this},render:function(){var a=[];p.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(d){h(d.dataLabels)&&d.dataLabels.forEach(function(d){a.push(d)})}),
this.chart.hideOverlappingLabels(a))},setVisible:function(){var a=this;p.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeNode(a.parentNode),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addNodes(a.points):a.points.forEach(function(d){a.layout.removeNode(d)}))},drawDataLabels:function(){var a=this.options.dataLabels.textPath,
b=this.points;p.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,p.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)},seriesBox:function(){var a=this.chart,c=Math.max,f=Math.min,e,g=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){l(a.plotX)&&
l(a.plotY)&&a.marker.radius&&(e=a.marker.radius,g[0]=f(g[0],a.plotX-e),g[1]=c(g[1],a.plotX+e),g[2]=f(g[2],a.plotY-e),g[3]=c(g[3],a.plotY+e))});return b(g.width/g.height)?g:null},calculateParentRadius:function(){var a;a=this.seriesBox();this.parentNodeRadius=Math.min(Math.max(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20),a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNodeRadius)},
drawGraph:function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b,f=this.layout.options.parentNodeOptions.marker,f={fill:f.fillColor||n(this.color).brighten(.4).get(),opacity:f.fillOpacity,stroke:f.lineColor||this.color,"stroke-width":f.lineWidth};b=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",b,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();b=c.merge({x:this.parentNode.plotX-
this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},f);this.graph?this.graph.attr(b):this.graph=this.parentNode.graphic=a.renderer.symbol(f.symbol).attr(b).add(this.parentNodesGroup)}},createParentNodes:function(){var a=this,b=a.chart,c=a.parentNodeLayout,f,e=a.parentNode;a.parentNodeMass=0;a.points.forEach(function(b){a.parentNodeMass+=Math.PI*Math.pow(b.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(b){b.seriesIndex===
a.index&&(f=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);f||(e||(e=(new t).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(e.plotX=a.parentNode.plotX,e.plotY=a.parentNode.plotY),a.parentNode=e,c.addSeries(a),c.addNodes([e]))},addSeriesLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,f=this.chart.graphLayoutsLookup,e=
c.merge(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation}),g;g=b[a.type+"-series"];g||(b[a.type+"-series"]=g=new c.layouts[a.type],g.init(e),f.splice(g.index,0,g));this.parentNodeLayout=g;this.createParentNodes()},addLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,f=this.chart.graphLayoutsLookup,e=this.chart.options.chart,g;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=f=[]);g=b[a.type];g||(a.enableSimulation=
l(e.forExport)?!e.forExport:a.enableSimulation,b[a.type]=g=new c.layouts[a.type],g.init(a),f.splice(g.index,0,g));this.layout=g;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=1});g.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);g.addSeries(this);g.addNodes(this.points)},deferLayout:function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())},translate:function(){var a=this.chart,b=this.data,f=this.index,g,e,h,n,
t=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();l(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());t?h=a.allDataPoints:(h=this.placeBubbles(a.allDataPoints),this.options.draggable=!1);for(n=0;n<h.length;n++)h[n][3]===f&&(g=b[h[n][4]],e=h[n][2],t||(g.plotX=h[n][0]-a.plotLeft+a.diffX,g.plotY=h[n][1]-a.plotTop+a.diffY),g.marker=c.extend(g.marker,{radius:e,width:2*e,height:2*e}));t&&this.deferLayout()},checkOverlap:function(a,b){var d=
a[0]-b[0],c=a[1]-b[1];return-.001>Math.sqrt(d*d+c*c)-Math.abs(a[2]+b[2])},positionBubble:function(a,b,c){var d=Math.sqrt,f=Math.asin,g=Math.acos,e=Math.pow,h=Math.abs,d=d(e(a[0]-b[0],2)+e(a[1]-b[1],2)),g=g((e(d,2)+e(c[2]+b[2],2)-e(c[2]+a[2],2))/(2*(c[2]+b[2])*d)),f=f(h(a[0]-b[0])/d);a=(0>a[1]-b[1]?0:Math.PI)+g+f*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]},placeBubbles:function(a){var b=this.checkOverlap,d=this.positionBubble,c=
[],f=1,g=0,e=0,h;h=[];var n;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){c.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(c.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),n=2;n<a.length;n++)a[n][2]=a[n][2]||1,h=d(c[f][g],c[f-1][e],a[n]),b(h,c[f][0])?(c.push([]),e=0,c[f+1].push(d(c[f][g],c[f][0],a[n])),f++,g=0):1<f&&c[f-1][e+1]&&b(h,c[f-1][e+1])?(e++,c[f].push(d(c[f][g],c[f-1][e],a[n])),g++):(g++,c[f].push(h));this.chart.stages=c;this.chart.rawPositions=[].concat.apply([],
c);this.resizeRadius();h=this.chart.rawPositions}return h},resizeRadius:function(){var a=this.chart,b=a.rawPositions,c=Math.min,f=Math.max,g=a.plotLeft,e=a.plotTop,h=a.plotHeight,n=a.plotWidth,l,t,p,u,w,r;l=p=Number.POSITIVE_INFINITY;t=u=Number.NEGATIVE_INFINITY;for(r=0;r<b.length;r++)w=b[r][2],l=c(l,b[r][0]-w),t=f(t,b[r][0]+w),p=c(p,b[r][1]-w),u=f(u,b[r][1]+w);r=[t-l,u-p];c=c.apply([],[(n-g)/r[0],(h-e)/r[1]]);if(1e-10<Math.abs(c-1)){for(r=0;r<b.length;r++)b[r][2]*=c;this.placeBubbles(b)}else a.diffY=
h/2+e-p-(u-p)/2,a.diffX=n/2+g-l-(t-l)/2},calculateZExtremes:function(){var a=this.options.zMin,b=this.options.zMax,f=Infinity,e=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){c.defined(a)&&(a>e&&(e=a),a<f&&(f=a))})});a=g(a,f);b=g(b,e);return[a,b]},getPointRadius:function(){var a=this,b=a.chart,c=a.options,f=c.useSimulation,e=Math.min(b.plotWidth,b.plotHeight),g={},h=[],n=b.allDataPoints,l,t,p,u,w;["minSize","maxSize"].forEach(function(a){var b=parseInt(c[a],
10),d=/%$/.test(c[a]);g[a]=d?e*b/100:b*Math.sqrt(n.length)});b.minRadius=l=g.minSize/Math.sqrt(n.length);b.maxRadius=t=g.maxSize/Math.sqrt(n.length);w=f?a.calculateZExtremes():[l,t];(n||[]).forEach(function(b,c){p=f?Math.max(Math.min(b[2],w[1]),w[0]):b[2];u=a.getRadius(w[0],w[1],l,t,p);0===u&&(u=null);n[c][2]=u;h.push(u)});a.radii=h},redrawHalo:r.redrawHalo,onMouseDown:r.onMouseDown,onMouseMove:r.onMouseMove,onMouseUp:function(a){if(a.fixedPosition&&!a.removed){var b,d,f=this.layout,e=this.parentNodeLayout;
e&&f.options.dragBetweenSeries&&e.nodes.forEach(function(e){a&&a.marker&&e!==a.series.parentNode&&(b=f.getDistXY(a,e),d=f.vectorLength(b)-e.marker.radius-a.marker.radius,0>d&&(e.series.addPoint(c.merge(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),f.removeNode(a),a.remove()))});r.onMouseUp.apply(this,arguments)}},destroy:function(){this.parentNode&&(this.parentNodeLayout.removeNode(this.parentNode),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));c.Series.prototype.destroy.apply(this,
arguments)},alignDataLabel:c.Series.prototype.alignDataLabel},{destroy:function(){this.series.layout&&this.series.layout.removeNode(this);return a.prototype.destroy.apply(this,arguments)}});f(u,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints})});y(r,"parts-more/Polar.js",[r["parts/Globals.js"]],function(c){var e=c.pick,h=c.Series,b=c.seriesTypes,p=c.wrap,a=h.prototype,l=c.Pointer.prototype;a.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+
-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};a.getConnectors=function(a,b,c,e){var f,g,h,d,n,m,k,l;g=e?1:0;f=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>f-1?a.length-(1+g):f-1;g=f+1>a.length-1?g:f+1;h=a[b];g=a[g];d=h.plotX;h=h.plotY;n=g.plotX;m=g.plotY;g=a[f].plotX;f=a[f].plotY;d=(1.5*g+d)/2.5;h=(1.5*f+h)/2.5;n=(1.5*g+n)/2.5;k=(1.5*f+m)/2.5;m=Math.sqrt(Math.pow(d-g,2)+Math.pow(h-f,2));l=Math.sqrt(Math.pow(n-g,2)+Math.pow(k-f,2));d=Math.atan2(h-f,d-g);k=Math.PI/2+(d+
Math.atan2(k-f,n-g))/2;Math.abs(d-k)>Math.PI/2&&(k-=Math.PI);d=g+Math.cos(k)*m;h=f+Math.sin(k)*m;n=g+Math.cos(Math.PI+k)*l;k=f+Math.sin(Math.PI+k)*l;g={rightContX:n,rightContY:k,leftContX:d,leftContY:h,plotX:g,plotY:f};c&&(g.prevPointCont=this.getConnectors(a,b,!1,e));return g};a.toXY=function(a){var b,c=this.chart,e=a.plotX;b=a.plotY;a.rectPlotX=e;a.rectPlotY=b;b=this.xAxis.postTranslate(a.plotX,this.yAxis.len-b);a.plotX=a.polarPlotX=b.x-c.plotLeft;a.plotY=a.polarPlotY=b.y-c.plotTop;this.kdByAngle?
(c=(e/Math.PI*180+this.xAxis.pane.options.startAngle)%360,0>c&&(c+=360),a.clientX=c):a.clientX=a.plotX};b.spline&&(p(b.spline.prototype,"getPointSpline",function(a,b,c,e){this.chart.polar?e?(a=this.getConnectors(b,e,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,e);return a}),b.areasplinerange&&(b.areasplinerange.prototype.getPointSpline=b.spline.prototype.getPointSpline));c.addEvent(h,
"afterTranslate",function(){var a=this.chart,b,e;if(a.polar){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(b=this.points,e=b.length;e--;)this.toXY(b[e]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&b[e].y<this.yAxis.min&&(b[e].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!c.addEvent(this,"afterRender",function(){var b;a.polar&&(b=this.yAxis.center,this.group.clip(a.renderer.clipCircle(b[0],
b[1],b[2]/2)),this.setClip=c.noop)}))}},{order:2});p(a,"getGraphPath",function(a,b){var c=this,f,e,g;if(this.chart.polar){b=b||this.points;for(f=0;f<b.length;f++)if(!b[f].isNull){e=f;break}!1!==this.options.connectEnds&&void 0!==e&&(this.connectEnds=!0,b.splice(b.length,0,b[e]),g=!0);b.forEach(function(a){void 0===a.polarPlotY&&c.toXY(a)})}f=a.apply(this,[].slice.call(arguments,1));g&&b.pop();return f});h=function(a,b){var c=this.chart,f=this.options.animation,e=this.group,g=this.markerGroup,h=this.xAxis.center,
d=c.plotLeft,l=c.plotTop;c.polar?c.renderer.isSVG&&(!0===f&&(f={}),b?(a={translateX:h[0]+d,translateY:h[1]+l,scaleX:.001,scaleY:.001},e.attr(a),g&&g.attr(a)):(a={translateX:d,translateY:l,scaleX:1,scaleY:1},e.animate(a,f),g&&g.animate(a,f),this.animate=null)):a.call(this,b)};p(a,"animate",h);b.column&&(b=b.column.prototype,b.polarArc=function(a,b,c,h){var f=this.xAxis.center,g=this.yAxis.len;return this.chart.renderer.symbols.arc(f[0],f[1],g-b,null,{start:c,end:h,innerR:g-e(a,g)})},p(b,"animate",
h),p(b,"translate",function(a){var b=this.xAxis,c=b.startAngleRad,e,g,h;this.preventPostTranslate=!0;a.call(this);if(b.isRadial)for(e=this.points,h=e.length;h--;)g=e[h],a=g.barX+c,g.shapeType="path",g.shapeArgs={d:this.polarArc(g.yBottom,g.plotY,a,a+g.pointWidth)},this.toXY(g),g.tooltipPos=[g.plotX,g.plotY],g.ttBelow=g.plotY>b.center[1]}),p(b,"alignDataLabel",function(b,c,e,h,l,p){this.chart.polar?(b=c.rectPlotX/Math.PI*180,null===h.align&&(h.align=20<b&&160>b?"left":200<b&&340>b?"right":"center"),
null===h.verticalAlign&&(h.verticalAlign=45>b||315<b?"bottom":135<b&&225>b?"top":"middle"),a.alignDataLabel.call(this,c,e,h,l,p)):b.call(this,c,e,h,l,p)}));p(l,"getCoordinates",function(a,b){var c=this.chart,e={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var f=a.isXAxis,g=a.center,d=b.chartX-g[0]-c.plotLeft,g=b.chartY-g[1]-c.plotTop;e[f?"xAxis":"yAxis"].push({axis:a,value:a.translate(f?Math.PI-Math.atan2(d,g):Math.sqrt(Math.pow(d,2)+Math.pow(g,2)),!0)})}):e=a.call(this,b);return e});c.SVGRenderer.prototype.clipCircle=
function(a,b,e){var f=c.uniqueKey(),g=this.createElement("clipPath").attr({id:f}).add(this.defs);a=this.circle(a,b,e).add(g);a.id=f;a.clipPath=g;return a};c.addEvent(c.Chart,"getAxes",function(){this.pane||(this.pane=[]);c.splat(this.options.pane).forEach(function(a){new c.Pane(a,this)},this)});c.addEvent(c.Chart,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});p(c.Chart.prototype,"get",function(a,b){return c.find(this.pane,function(a){return a.options.id===b})||a.call(this,
b)})});y(r,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map