/*
 Highcharts JS v7.1.2-modified (2019-07-03)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
(function(u){"object"===typeof module&&module.exports?(u["default"]=u,module.exports=u):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(z){u(z);u.Highcharts=z;return u}):u("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(u){function z(b,q,u,x){b.hasOwnProperty(q)||(b[q]=x.apply(null,u))}u=u?u._modules:{};z(u,"parts-3d/Math.js",[u["parts/Globals.js"]],function(b){var q=b.deg2rad,u=b.pick;b.perspective3D=function(b,f,p){f=0<p&&p<Number.POSITIVE_INFINITY?
p/(b.z+f.z+p):1;return{x:b.x*f,y:b.y*f}};b.perspective=function(x,f,p){var A=f.options.chart.options3d,m=p?f.inverted:!1,w={x:f.plotWidth/2,y:f.plotHeight/2,z:A.depth/2,vd:u(A.depth,1)*u(A.viewDistance,0)},r=f.scale3d||1,t=q*A.beta*(m?-1:1),A=q*A.alpha*(m?-1:1),n=Math.cos(A),a=Math.cos(-t),g=Math.sin(A),h=Math.sin(-t);p||(w.x+=f.plotLeft,w.y+=f.plotTop);return x.map(function(l){var d;d=(m?l.y:l.x)-w.x;var c=(m?l.x:l.y)-w.y;l=(l.z||0)-w.z;d={x:a*d-h*l,y:-g*h*d+n*c-a*g*l,z:n*h*d+g*c+n*a*l};c=b.perspective3D(d,
w,w.vd);c.x=c.x*r+w.x;c.y=c.y*r+w.y;c.z=d.z*r+w.z;return{x:m?c.y:c.x,y:m?c.x:c.y,z:c.z}})};b.pointCameraDistance=function(b,f){var p=f.options.chart.options3d,x=f.plotWidth/2;f=f.plotHeight/2;p=u(p.depth,1)*u(p.viewDistance,0)+p.depth;return Math.sqrt(Math.pow(x-b.plotX,2)+Math.pow(f-b.plotY,2)+Math.pow(p-b.plotZ,2))};b.shapeArea=function(b){var f=0,p,q;for(p=0;p<b.length;p++)q=(p+1)%b.length,f+=b[p].x*b[q].y-b[q].x*b[p].y;return f/2};b.shapeArea3d=function(q,f,p){return b.shapeArea(b.perspective(q,
f,p))}});z(u,"parts-3d/SVGRenderer.js",[u["parts/Globals.js"]],function(b){function q(a,c,e,B,b,y,g,h){var k=[],D=y-b;return y>b&&y-b>Math.PI/2+.0001?(k=k.concat(q(a,c,e,B,b,b+Math.PI/2,g,h)),k=k.concat(q(a,c,e,B,b+Math.PI/2,y,g,h))):y<b&&b-y>Math.PI/2+.0001?(k=k.concat(q(a,c,e,B,b,b-Math.PI/2,g,h)),k=k.concat(q(a,c,e,B,b-Math.PI/2,y,g,h))):["C",a+e*Math.cos(b)-e*d*D*Math.sin(b)+g,c+B*Math.sin(b)+B*d*D*Math.cos(b)+h,a+e*Math.cos(y)+e*d*D*Math.sin(y)+g,c+B*Math.sin(y)-B*d*D*Math.cos(y)+h,a+e*Math.cos(y)+
g,c+B*Math.sin(y)+h]}var u=Math.cos,x=Math.PI,f=Math.sin,p=b.animObject,A=b.charts,m=b.color,w=b.defined,r=b.deg2rad,t=b.extend,n=b.merge,a=b.perspective,g=b.pick,h=b.SVGElement,l=b.SVGRenderer,d,c,v;d=4*(Math.sqrt(2)-1)/3/(x/2);l.prototype.toLinePath=function(a,c){var e=[];a.forEach(function(a){e.push("L",a.x,a.y)});a.length&&(e[0]="M",c&&e.push("Z"));return e};l.prototype.toLineSegments=function(a){var c=[],e=!0;a.forEach(function(a){c.push(e?"M":"L",a.x,a.y);e=!e});return c};l.prototype.face3d=
function(c){var k=this,e=this.createElement("path");e.vertexes=[];e.insidePlotArea=!1;e.enabled=!0;e.attr=function(c){if("object"===typeof c&&(w(c.enabled)||w(c.vertexes)||w(c.insidePlotArea))){this.enabled=g(c.enabled,this.enabled);this.vertexes=g(c.vertexes,this.vertexes);this.insidePlotArea=g(c.insidePlotArea,this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var e=a(this.vertexes,A[k.chartIndex],this.insidePlotArea),d=k.toLinePath(e,!0),e=b.shapeArea(e),e=this.enabled&&
0<e?"visible":"hidden";c.d=d;c.visibility=e}return h.prototype.attr.apply(this,arguments)};e.animate=function(c){if("object"===typeof c&&(w(c.enabled)||w(c.vertexes)||w(c.insidePlotArea))){this.enabled=g(c.enabled,this.enabled);this.vertexes=g(c.vertexes,this.vertexes);this.insidePlotArea=g(c.insidePlotArea,this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var e=a(this.vertexes,A[k.chartIndex],this.insidePlotArea),d=k.toLinePath(e,!0),e=b.shapeArea(e),e=this.enabled&&
0<e?"visible":"hidden";c.d=d;this.attr("visibility",e)}return h.prototype.animate.apply(this,arguments)};return e.attr(c)};l.prototype.polyhedron=function(a){var c=this,e=this.g(),k=e.destroy;this.styledMode||e.attr({"stroke-linejoin":"round"});e.faces=[];e.destroy=function(){for(var c=0;c<e.faces.length;c++)e.faces[c].destroy();return k.call(this)};e.attr=function(a,k,d,b){if("object"===typeof a&&w(a.faces)){for(;e.faces.length>a.faces.length;)e.faces.pop().destroy();for(;e.faces.length<a.faces.length;)e.faces.push(c.face3d().add(e));
for(var y=0;y<a.faces.length;y++)c.styledMode&&delete a.faces[y].fill,e.faces[y].attr(a.faces[y],null,d,b);delete a.faces}return h.prototype.attr.apply(this,arguments)};e.animate=function(a,k,d){if(a&&a.faces){for(;e.faces.length>a.faces.length;)e.faces.pop().destroy();for(;e.faces.length<a.faces.length;)e.faces.push(c.face3d().add(e));for(var b=0;b<a.faces.length;b++)e.faces[b].animate(a.faces[b],k,d);delete a.faces}return h.prototype.animate.apply(this,arguments)};return e.attr(a)};c={initArgs:function(a){var c=
this,e=c.renderer,k=e[c.pathType+"Path"](a),d=k.zIndexes;c.parts.forEach(function(a){c[a]=e.path(k[a]).attr({"class":"highcharts-3d-"+a,zIndex:d[a]||0}).add(c)});c.attr({"stroke-linejoin":"round",zIndex:d.group});c.originalDestroy=c.destroy;c.destroy=c.destroyParts},singleSetterForParts:function(a,c,e,d,g,y){var k={};d=[null,null,d||"attr",g,y];var B=e&&e.zIndexes;e?(b.objectEach(e,function(c,d){k[d]={};k[d][a]=c;B&&(k[d].zIndex=e.zIndexes[d]||0)}),d[1]=k):(k[a]=c,d[0]=k);return this.processParts.apply(this,
d)},processParts:function(a,c,e,d,g){var k=this;k.parts.forEach(function(y){c&&(a=b.pick(c[y],!1));if(!1!==a)k[y][e](a,d,g)});return k},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}};v=b.merge(c,{parts:["front","top","side"],pathType:"cuboid",attr:function(a,c,e,d){if("string"===typeof a&&"undefined"!==typeof c){var k=a;a={};a[k]=c}return a.shapeArgs||w(a.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](a.shapeArgs||a)):h.prototype.attr.call(this,
a,void 0,e,d)},animate:function(a,c,e){w(a.x)&&w(a.y)?(a=this.renderer[this.pathType+"Path"](a),this.singleSetterForParts("d",null,a,"animate",c,e),this.attr({zIndex:a.zIndexes.group})):h.prototype.animate.call(this,a,c,e);return this},fillSetter:function(a){this.singleSetterForParts("fill",null,{front:a,top:m(a).brighten(.1).get(),side:m(a).brighten(-.1).get()});this.color=this.fill=a;return this}});l.prototype.elements3d={base:c,cuboid:v};l.prototype.element3d=function(a,c){var e=this.g();b.extend(e,
this.elements3d[a]);e.initArgs(c);return e};l.prototype.cuboid=function(a){return this.element3d("cuboid",a)};b.SVGRenderer.prototype.cuboidPath=function(c){function d(a){return p[a]}var e=c.x,k=c.y,g=c.z,y=c.height,h=c.width,n=c.depth,l=A[this.chartIndex],t,v,f=l.options.chart.options3d.alpha,m=0,p=[{x:e,y:k,z:g},{x:e+h,y:k,z:g},{x:e+h,y:k+y,z:g},{x:e,y:k+y,z:g},{x:e,y:k+y,z:g+n},{x:e+h,y:k+y,z:g+n},{x:e+h,y:k,z:g+n},{x:e,y:k,z:g+n}],p=a(p,l,c.insidePlotArea);v=function(a,c){var e=[[],-1];a=a.map(d);
c=c.map(d);0>b.shapeArea(a)?e=[a,0]:0>b.shapeArea(c)&&(e=[c,1]);return e};t=v([3,2,1,0],[7,6,5,4]);c=t[0];h=t[1];t=v([1,6,7,0],[4,5,2,3]);y=t[0];n=t[1];t=v([1,2,5,6],[0,7,4,3]);v=t[0];t=t[1];1===t?m+=1E4*(1E3-e):t||(m+=1E4*e);m+=10*(!n||0<=f&&180>=f||360>f&&357.5<f?l.plotHeight-k:10+k);1===h?m+=100*g:h||(m+=100*(1E3-g));return{front:this.toLinePath(c,!0),top:this.toLinePath(y,!0),side:this.toLinePath(v,!0),zIndexes:{group:Math.round(m)},isFront:h,isTop:n}};b.SVGRenderer.prototype.arc3d=function(a){function c(a){var c=
!1,e={},d;a=n(a);for(d in a)-1!==k.indexOf(d)&&(e[d]=a[d],delete a[d],c=!0);return c?e:!1}var e=this.g(),d=e.renderer,k="x y r innerR start end".split(" ");a=n(a);a.alpha=(a.alpha||0)*r;a.beta=(a.beta||0)*r;e.top=d.path();e.side1=d.path();e.side2=d.path();e.inn=d.path();e.out=d.path();e.onAdd=function(){var a=e.parentGroup,c=e.attr("class");e.top.add(e);["out","inn","side1","side2"].forEach(function(d){e[d].attr({"class":c+" highcharts-3d-side"}).add(a)})};["addClass","removeClass"].forEach(function(a){e[a]=
function(){var c=arguments;["top","out","inn","side1","side2"].forEach(function(d){e[d][a].apply(e[d],c)})}});e.setPaths=function(a){var c=e.renderer.arc3dPath(a),d=100*c.zTop;e.attribs=a;e.top.attr({d:c.top,zIndex:c.zTop});e.inn.attr({d:c.inn,zIndex:c.zInn});e.out.attr({d:c.out,zIndex:c.zOut});e.side1.attr({d:c.side1,zIndex:c.zSide1});e.side2.attr({d:c.side2,zIndex:c.zSide2});e.zIndex=d;e.attr({zIndex:d});a.center&&(e.top.setRadialReference(a.center),delete a.center)};e.setPaths(a);e.fillSetter=
function(a){var c=m(a).brighten(-.1).get();this.fill=a;this.side1.attr({fill:c});this.side2.attr({fill:c});this.inn.attr({fill:c});this.out.attr({fill:c});this.top.attr({fill:a});return this};["opacity","translateX","translateY","visibility"].forEach(function(a){e[a+"Setter"]=function(a,c){e[c]=a;["out","inn","side1","side2","top"].forEach(function(d){e[d].attr(c,a)})}});e.attr=function(a){var d;"object"===typeof a&&(d=c(a))&&(t(e.attribs,d),e.setPaths(e.attribs));return h.prototype.attr.apply(e,
arguments)};e.animate=function(a,d,k){var l,t=this.attribs,B,y="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.depth;delete a.alpha;delete a.beta;B=p(g(d,this.renderer.globalAnimation));B.duration&&(l=c(a),e[y]=0,a[y]=1,e[y+"Setter"]=b.noop,l&&(B.step=function(a,c){function e(a){return t[a]+(g(l[a],t[a])-t[a])*c.pos}c.prop===y&&c.elem.setPaths(n(t,{x:e("x"),y:e("y"),r:e("r"),innerR:e("innerR"),start:e("start"),end:e("end")}))}),d=B);return h.prototype.animate.call(this,
a,d,k)};e.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();h.prototype.destroy.call(this)};e.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};e.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);this.side2.show(a)};return e};l.prototype.arc3dPath=function(a){function c(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var e=a.x,d=a.y,b=a.start,
k=a.end-.00001,g=a.r,h=a.innerR||0,n=a.depth||0,l=a.alpha,t=a.beta,v=Math.cos(b),m=Math.sin(b);a=Math.cos(k);var p=Math.sin(k),r=g*Math.cos(t),g=g*Math.cos(l),w=h*Math.cos(t),A=h*Math.cos(l),h=n*Math.sin(t),C=n*Math.sin(l),n=["M",e+r*v,d+g*m],n=n.concat(q(e,d,r,g,b,k,0,0)),n=n.concat(["L",e+w*a,d+A*p]),n=n.concat(q(e,d,w,A,k,b,0,0)),n=n.concat(["Z"]),F=0<t?Math.PI/2:0,t=0<l?0:Math.PI/2,F=b>-F?b:k>-F?-F:b,z=k<x-t?k:b<x-t?x-t:k,E=2*x-t,l=["M",e+r*u(F),d+g*f(F)],l=l.concat(q(e,d,r,g,F,z,0,0));k>E&&b<
E?(l=l.concat(["L",e+r*u(z)+h,d+g*f(z)+C]),l=l.concat(q(e,d,r,g,z,E,h,C)),l=l.concat(["L",e+r*u(E),d+g*f(E)]),l=l.concat(q(e,d,r,g,E,k,0,0)),l=l.concat(["L",e+r*u(k)+h,d+g*f(k)+C]),l=l.concat(q(e,d,r,g,k,E,h,C)),l=l.concat(["L",e+r*u(E),d+g*f(E)]),l=l.concat(q(e,d,r,g,E,z,0,0))):k>x-t&&b<x-t&&(l=l.concat(["L",e+r*Math.cos(z)+h,d+g*Math.sin(z)+C]),l=l.concat(q(e,d,r,g,z,k,h,C)),l=l.concat(["L",e+r*Math.cos(k),d+g*Math.sin(k)]),l=l.concat(q(e,d,r,g,k,z,0,0)));l=l.concat(["L",e+r*Math.cos(z)+h,d+g*Math.sin(z)+
C]);l=l.concat(q(e,d,r,g,z,F,h,C));l=l.concat(["Z"]);t=["M",e+w*v,d+A*m];t=t.concat(q(e,d,w,A,b,k,0,0));t=t.concat(["L",e+w*Math.cos(k)+h,d+A*Math.sin(k)+C]);t=t.concat(q(e,d,w,A,k,b,h,C));t=t.concat(["Z"]);v=["M",e+r*v,d+g*m,"L",e+r*v+h,d+g*m+C,"L",e+w*v+h,d+A*m+C,"L",e+w*v,d+A*m,"Z"];e=["M",e+r*a,d+g*p,"L",e+r*a+h,d+g*p+C,"L",e+w*a+h,d+A*p+C,"L",e+w*a,d+A*p,"Z"];p=Math.atan2(C,-h);d=Math.abs(k+p);a=Math.abs(b+p);b=Math.abs((b+k)/2+p);d=c(d);a=c(a);b=c(b);b*=1E5;k=1E5*a;d*=1E5;return{top:n,zTop:1E5*
Math.PI+1,out:l,zOut:Math.max(b,k,d),inn:t,zInn:Math.max(b,k,d),side1:v,zSide1:.99*d,side2:e,zSide2:.99*k}}});z(u,"parts-3d/Chart.js",[u["parts/Globals.js"],u["parts/Utilities.js"]],function(b,q){function u(b,n){var a=b.plotLeft,g=b.plotWidth+a,h=b.plotTop,l=b.plotHeight+h,d=a+b.plotWidth/2,c=h+b.plotHeight/2,t=Number.MAX_VALUE,k=-Number.MAX_VALUE,D=Number.MAX_VALUE,e=-Number.MAX_VALUE,m,f=1;m=[{x:a,y:h,z:0},{x:a,y:h,z:n}];[0,1].forEach(function(a){m.push({x:g,y:m[a].y,z:m[a].z})});[0,1,2,3].forEach(function(a){m.push({x:m[a].x,
y:l,z:m[a].z})});m=A(m,b,!1);m.forEach(function(a){t=Math.min(t,a.x);k=Math.max(k,a.x);D=Math.min(D,a.y);e=Math.max(e,a.y)});a>t&&(f=Math.min(f,1-Math.abs((a+d)/(t+d))%1));g<k&&(f=Math.min(f,(g-d)/(k-d)));h>D&&(f=0>D?Math.min(f,(h+c)/(-D+h+c)):Math.min(f,1-(h+c)/(D+c)%1));l<e&&(f=Math.min(f,Math.abs((l-c)/(e-c))));return f}var x=q.isArray;q=b.addEvent;var f=b.Chart,p=b.merge,A=b.perspective,m=b.pick,w=b.wrap;f.prototype.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};
f.prototype.propsRequireDirtyBox.push("chart.options3d");f.prototype.propsRequireUpdateSeries.push("chart.options3d");q(f,"afterInit",function(){var b=this.options;this.is3d()&&(b.series||[]).forEach(function(n){"scatter"===(n.type||b.chart.type||b.chart.defaultSeriesType)&&(n.type="scatter3d")})});q(f,"addSeries",function(b){this.is3d()&&"scatter"===b.options.type&&(b.options.type="scatter3d")});b.wrap(b.Chart.prototype,"isInsidePlot",function(b){return this.is3d()||b.apply(this,[].slice.call(arguments,
1))});var r=b.getOptions();p(!0,r,{chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}});q(f,"afterGetContainer",function(){this.styledMode&&(this.renderer.definition({tagName:"style",textContent:".highcharts-3d-top{filter: url(#highcharts-brighter)}\n.highcharts-3d-side{filter: url(#highcharts-darker)}\n"}),[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(b){this.renderer.definition({tagName:"filter",
id:"highcharts-"+b.name,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",type:"linear",slope:b.slope},{tagName:"feFuncG",type:"linear",slope:b.slope},{tagName:"feFuncB",type:"linear",slope:b.slope}]}]})},this))});w(f.prototype,"setClassName",function(b){b.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")});q(b.Chart,"afterSetChartSize",function(){var b=this.options.chart.options3d;if(this.is3d()){var n=this.inverted,a=this.clipBox,
g=this.margin;a[n?"y":"x"]=-(g[3]||0);a[n?"x":"y"]=-(g[0]||0);a[n?"height":"width"]=this.chartWidth+(g[3]||0)+(g[1]||0);a[n?"width":"height"]=this.chartHeight+(g[0]||0)+(g[2]||0);this.scale3d=1;!0===b.fitToPlot&&(this.scale3d=u(this,b.depth));this.frame3d=this.get3dFrame()}});q(f,"beforeRedraw",function(){this.is3d()&&(this.isDirtyBox=!0)});q(f,"beforeRender",function(){this.is3d()&&(this.frame3d=this.get3dFrame())});w(f.prototype,"renderSeries",function(b){var n=this.series.length;if(this.is3d())for(;n--;)b=
this.series[n],b.translate(),b.render();else b.call(this)});q(f,"afterDrawChartBox",function(){if(this.is3d()){var t=this.renderer,n=this.options.chart.options3d,a=this.get3dFrame(),g=this.plotLeft,h=this.plotLeft+this.plotWidth,l=this.plotTop,d=this.plotTop+this.plotHeight,n=n.depth,c=g-(a.left.visible?a.left.size:0),v=h+(a.right.visible?a.right.size:0),k=l-(a.top.visible?a.top.size:0),m=d+(a.bottom.visible?a.bottom.size:0),e=0-(a.front.visible?a.front.size:0),f=n+(a.back.visible?a.back.size:0),
p=this.hasRendered?"animate":"attr";this.frame3d=a;this.frameShapes||(this.frameShapes={bottom:t.polyhedron().add(),top:t.polyhedron().add(),left:t.polyhedron().add(),right:t.polyhedron().add(),back:t.polyhedron().add(),front:t.polyhedron().add()});this.frameShapes.bottom[p]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",zIndex:a.bottom.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:c,y:m,z:e},{x:v,y:m,z:e},{x:v,y:m,z:f},{x:c,y:m,z:f}],enabled:a.bottom.visible},
{fill:b.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:g,y:d,z:n},{x:h,y:d,z:n},{x:h,y:d,z:0},{x:g,y:d,z:0}],enabled:a.bottom.visible},{fill:b.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:c,y:m,z:e},{x:c,y:m,z:f},{x:g,y:d,z:n},{x:g,y:d,z:0}],enabled:a.bottom.visible&&!a.left.visible},{fill:b.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:v,y:m,z:f},{x:v,y:m,z:e},{x:h,y:d,z:0},{x:h,y:d,z:n}],enabled:a.bottom.visible&&!a.right.visible},{fill:b.color(a.bottom.color).get(),vertexes:[{x:v,
y:m,z:e},{x:c,y:m,z:e},{x:g,y:d,z:0},{x:h,y:d,z:0}],enabled:a.bottom.visible&&!a.front.visible},{fill:b.color(a.bottom.color).get(),vertexes:[{x:c,y:m,z:f},{x:v,y:m,z:f},{x:h,y:d,z:n},{x:g,y:d,z:n}],enabled:a.bottom.visible&&!a.back.visible}]});this.frameShapes.top[p]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:a.top.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.top.color).brighten(.1).get(),vertexes:[{x:c,y:k,z:f},{x:v,y:k,z:f},{x:v,y:k,z:e},{x:c,y:k,z:e}],enabled:a.top.visible},
{fill:b.color(a.top.color).brighten(.1).get(),vertexes:[{x:g,y:l,z:0},{x:h,y:l,z:0},{x:h,y:l,z:n},{x:g,y:l,z:n}],enabled:a.top.visible},{fill:b.color(a.top.color).brighten(-.1).get(),vertexes:[{x:c,y:k,z:f},{x:c,y:k,z:e},{x:g,y:l,z:0},{x:g,y:l,z:n}],enabled:a.top.visible&&!a.left.visible},{fill:b.color(a.top.color).brighten(-.1).get(),vertexes:[{x:v,y:k,z:e},{x:v,y:k,z:f},{x:h,y:l,z:n},{x:h,y:l,z:0}],enabled:a.top.visible&&!a.right.visible},{fill:b.color(a.top.color).get(),vertexes:[{x:c,y:k,z:e},
{x:v,y:k,z:e},{x:h,y:l,z:0},{x:g,y:l,z:0}],enabled:a.top.visible&&!a.front.visible},{fill:b.color(a.top.color).get(),vertexes:[{x:v,y:k,z:f},{x:c,y:k,z:f},{x:g,y:l,z:n},{x:h,y:l,z:n}],enabled:a.top.visible&&!a.back.visible}]});this.frameShapes.left[p]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:a.left.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.left.color).brighten(.1).get(),vertexes:[{x:c,y:m,z:e},{x:g,y:d,z:0},{x:g,y:d,z:n},{x:c,y:m,z:f}],enabled:a.left.visible&&!a.bottom.visible},
{fill:b.color(a.left.color).brighten(.1).get(),vertexes:[{x:c,y:k,z:f},{x:g,y:l,z:n},{x:g,y:l,z:0},{x:c,y:k,z:e}],enabled:a.left.visible&&!a.top.visible},{fill:b.color(a.left.color).brighten(-.1).get(),vertexes:[{x:c,y:m,z:f},{x:c,y:k,z:f},{x:c,y:k,z:e},{x:c,y:m,z:e}],enabled:a.left.visible},{fill:b.color(a.left.color).brighten(-.1).get(),vertexes:[{x:g,y:l,z:n},{x:g,y:d,z:n},{x:g,y:d,z:0},{x:g,y:l,z:0}],enabled:a.left.visible},{fill:b.color(a.left.color).get(),vertexes:[{x:c,y:m,z:e},{x:c,y:k,z:e},
{x:g,y:l,z:0},{x:g,y:d,z:0}],enabled:a.left.visible&&!a.front.visible},{fill:b.color(a.left.color).get(),vertexes:[{x:c,y:k,z:f},{x:c,y:m,z:f},{x:g,y:d,z:n},{x:g,y:l,z:n}],enabled:a.left.visible&&!a.back.visible}]});this.frameShapes.right[p]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:a.right.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.right.color).brighten(.1).get(),vertexes:[{x:v,y:m,z:f},{x:h,y:d,z:n},{x:h,y:d,z:0},{x:v,y:m,z:e}],enabled:a.right.visible&&!a.bottom.visible},
{fill:b.color(a.right.color).brighten(.1).get(),vertexes:[{x:v,y:k,z:e},{x:h,y:l,z:0},{x:h,y:l,z:n},{x:v,y:k,z:f}],enabled:a.right.visible&&!a.top.visible},{fill:b.color(a.right.color).brighten(-.1).get(),vertexes:[{x:h,y:l,z:0},{x:h,y:d,z:0},{x:h,y:d,z:n},{x:h,y:l,z:n}],enabled:a.right.visible},{fill:b.color(a.right.color).brighten(-.1).get(),vertexes:[{x:v,y:m,z:e},{x:v,y:k,z:e},{x:v,y:k,z:f},{x:v,y:m,z:f}],enabled:a.right.visible},{fill:b.color(a.right.color).get(),vertexes:[{x:v,y:k,z:e},{x:v,
y:m,z:e},{x:h,y:d,z:0},{x:h,y:l,z:0}],enabled:a.right.visible&&!a.front.visible},{fill:b.color(a.right.color).get(),vertexes:[{x:v,y:m,z:f},{x:v,y:k,z:f},{x:h,y:l,z:n},{x:h,y:d,z:n}],enabled:a.right.visible&&!a.back.visible}]});this.frameShapes.back[p]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:a.back.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.back.color).brighten(.1).get(),vertexes:[{x:v,y:m,z:f},{x:c,y:m,z:f},{x:g,y:d,z:n},{x:h,y:d,z:n}],enabled:a.back.visible&&!a.bottom.visible},
{fill:b.color(a.back.color).brighten(.1).get(),vertexes:[{x:c,y:k,z:f},{x:v,y:k,z:f},{x:h,y:l,z:n},{x:g,y:l,z:n}],enabled:a.back.visible&&!a.top.visible},{fill:b.color(a.back.color).brighten(-.1).get(),vertexes:[{x:c,y:m,z:f},{x:c,y:k,z:f},{x:g,y:l,z:n},{x:g,y:d,z:n}],enabled:a.back.visible&&!a.left.visible},{fill:b.color(a.back.color).brighten(-.1).get(),vertexes:[{x:v,y:k,z:f},{x:v,y:m,z:f},{x:h,y:d,z:n},{x:h,y:l,z:n}],enabled:a.back.visible&&!a.right.visible},{fill:b.color(a.back.color).get(),
vertexes:[{x:g,y:l,z:n},{x:h,y:l,z:n},{x:h,y:d,z:n},{x:g,y:d,z:n}],enabled:a.back.visible},{fill:b.color(a.back.color).get(),vertexes:[{x:c,y:m,z:f},{x:v,y:m,z:f},{x:v,y:k,z:f},{x:c,y:k,z:f}],enabled:a.back.visible}]});this.frameShapes.front[p]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:a.front.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.front.color).brighten(.1).get(),vertexes:[{x:c,y:m,z:e},{x:v,y:m,z:e},{x:h,y:d,z:0},{x:g,y:d,z:0}],enabled:a.front.visible&&!a.bottom.visible},
{fill:b.color(a.front.color).brighten(.1).get(),vertexes:[{x:v,y:k,z:e},{x:c,y:k,z:e},{x:g,y:l,z:0},{x:h,y:l,z:0}],enabled:a.front.visible&&!a.top.visible},{fill:b.color(a.front.color).brighten(-.1).get(),vertexes:[{x:c,y:k,z:e},{x:c,y:m,z:e},{x:g,y:d,z:0},{x:g,y:l,z:0}],enabled:a.front.visible&&!a.left.visible},{fill:b.color(a.front.color).brighten(-.1).get(),vertexes:[{x:v,y:m,z:e},{x:v,y:k,z:e},{x:h,y:l,z:0},{x:h,y:d,z:0}],enabled:a.front.visible&&!a.right.visible},{fill:b.color(a.front.color).get(),
vertexes:[{x:h,y:l,z:0},{x:g,y:l,z:0},{x:g,y:d,z:0},{x:h,y:d,z:0}],enabled:a.front.visible},{fill:b.color(a.front.color).get(),vertexes:[{x:v,y:m,z:e},{x:c,y:m,z:e},{x:c,y:k,z:e},{x:v,y:k,z:e}],enabled:a.front.visible}]})}});f.prototype.retrieveStacks=function(b){var n=this.series,a={},g,h=1;this.series.forEach(function(l){g=m(l.options.stack,b?0:n.length-1-l.index);a[g]?a[g].series.push(l):(a[g]={series:[l],position:h},h++)});a.totalStacks=h+1;return a};f.prototype.get3dFrame=function(){var f=this,
n=f.options.chart.options3d,a=n.frame,g=f.plotLeft,h=f.plotLeft+f.plotWidth,l=f.plotTop,d=f.plotTop+f.plotHeight,c=n.depth,v=function(a){a=b.shapeArea3d(a,f);return.5<a?1:-.5>a?-1:0},k=v([{x:g,y:d,z:c},{x:h,y:d,z:c},{x:h,y:d,z:0},{x:g,y:d,z:0}]),p=v([{x:g,y:l,z:0},{x:h,y:l,z:0},{x:h,y:l,z:c},{x:g,y:l,z:c}]),e=v([{x:g,y:l,z:0},{x:g,y:l,z:c},{x:g,y:d,z:c},{x:g,y:d,z:0}]),r=v([{x:h,y:l,z:c},{x:h,y:l,z:0},{x:h,y:d,z:0},{x:h,y:d,z:c}]),w=v([{x:g,y:d,z:0},{x:h,y:d,z:0},{x:h,y:l,z:0},{x:g,y:l,z:0}]),v=v([{x:g,
y:l,z:c},{x:h,y:l,z:c},{x:h,y:d,z:c},{x:g,y:d,z:c}]),y=!1,q=!1,u=!1,x=!1;[].concat(f.xAxis,f.yAxis,f.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?q=!0:y=!0:a.opposite?x=!0:u=!0)});var z=function(a,c,d){for(var e=["size","color","visible"],b={},k=0;k<e.length;k++)for(var g=e[k],l=0;l<a.length;l++)if("object"===typeof a[l]){var h=a[l][g];if(void 0!==h&&null!==h){b[g]=h;break}}a=d;!0===b.visible||!1===b.visible?a=b.visible:"auto"===b.visible&&(a=0<c);return{size:m(b.size,1),color:m(b.color,"none"),
frontFacing:0<c,visible:a}},a={bottom:z([a.bottom,a.top,a],k,y),top:z([a.top,a.bottom,a],p,q),left:z([a.left,a.right,a.side,a],e,u),right:z([a.right,a.left,a.side,a],r,x),back:z([a.back,a.front,a],v,!0),front:z([a.front,a.back,a],w,!1)};"auto"===n.axisLabelPosition?(r=function(a,c){return a.visible!==c.visible||a.visible&&c.visible&&a.frontFacing!==c.frontFacing},n=[],r(a.left,a.front)&&n.push({y:(l+d)/2,x:g,z:0,xDir:{x:1,y:0,z:0}}),r(a.left,a.back)&&n.push({y:(l+d)/2,x:g,z:c,xDir:{x:0,y:0,z:-1}}),
r(a.right,a.front)&&n.push({y:(l+d)/2,x:h,z:0,xDir:{x:0,y:0,z:1}}),r(a.right,a.back)&&n.push({y:(l+d)/2,x:h,z:c,xDir:{x:-1,y:0,z:0}}),k=[],r(a.bottom,a.front)&&k.push({x:(g+h)/2,y:d,z:0,xDir:{x:1,y:0,z:0}}),r(a.bottom,a.back)&&k.push({x:(g+h)/2,y:d,z:c,xDir:{x:-1,y:0,z:0}}),p=[],r(a.top,a.front)&&p.push({x:(g+h)/2,y:l,z:0,xDir:{x:1,y:0,z:0}}),r(a.top,a.back)&&p.push({x:(g+h)/2,y:l,z:c,xDir:{x:-1,y:0,z:0}}),e=[],r(a.bottom,a.left)&&e.push({z:(0+c)/2,y:d,x:g,xDir:{x:0,y:0,z:-1}}),r(a.bottom,a.right)&&
e.push({z:(0+c)/2,y:d,x:h,xDir:{x:0,y:0,z:1}}),d=[],r(a.top,a.left)&&d.push({z:(0+c)/2,y:l,x:g,xDir:{x:0,y:0,z:-1}}),r(a.top,a.right)&&d.push({z:(0+c)/2,y:l,x:h,xDir:{x:0,y:0,z:1}}),g=function(a,c,d){if(0===a.length)return null;if(1===a.length)return a[0];for(var e=0,b=A(a,f,!1),k=1;k<b.length;k++)d*b[k][c]>d*b[e][c]?e=k:d*b[k][c]===d*b[e][c]&&b[k].z<b[e].z&&(e=k);return a[e]},a.axes={y:{left:g(n,"x",-1),right:g(n,"x",1)},x:{top:g(p,"y",-1),bottom:g(k,"y",1)},z:{top:g(d,"y",-1),bottom:g(e,"y",1)}}):
a.axes={y:{left:{x:g,z:0,xDir:{x:1,y:0,z:0}},right:{x:h,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:l,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:d,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:u?h:g,y:l,xDir:u?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:u?h:g,y:d,xDir:u?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return a};b.Fx.prototype.matrixSetter=function(){var b;if(1>this.pos&&(x(this.start)||x(this.end))){var n=this.start||[1,0,0,1,0,0],a=this.end||[1,0,0,1,0,0];b=[];for(var g=0;6>g;g++)b.push(this.pos*a[g]+(1-this.pos)*n[g])}else b=this.end;
this.elem.attr(this.prop,b,null,!0)}});z(u,"parts-3d/Axis.js",[u["parts/Globals.js"]],function(b){function q(d,c,b){if(!d.chart.is3d()||"colorAxis"===d.coll)return c;var k=d.chart,g=A*k.options.chart.options3d.alpha,e=A*k.options.chart.options3d.beta,l=n(b&&d.options.title.position3d,d.options.labels.position3d);b=n(b&&d.options.title.skew3d,d.options.labels.skew3d);var h=k.frame3d,f=k.plotLeft,m=k.plotWidth+f,v=k.plotTop,t=k.plotHeight+v,k=!1,p=0,w=0,q={x:0,y:1,z:0};c=d.swapZ({x:c.x,y:c.y,z:0});
if(d.isZAxis)if(d.opposite){if(null===h.axes.z.top)return{};w=c.y-v;c.x=h.axes.z.top.x;c.y=h.axes.z.top.y;f=h.axes.z.top.xDir;k=!h.top.frontFacing}else{if(null===h.axes.z.bottom)return{};w=c.y-t;c.x=h.axes.z.bottom.x;c.y=h.axes.z.bottom.y;f=h.axes.z.bottom.xDir;k=!h.bottom.frontFacing}else if(d.horiz)if(d.opposite){if(null===h.axes.x.top)return{};w=c.y-v;c.y=h.axes.x.top.y;c.z=h.axes.x.top.z;f=h.axes.x.top.xDir;k=!h.top.frontFacing}else{if(null===h.axes.x.bottom)return{};w=c.y-t;c.y=h.axes.x.bottom.y;
c.z=h.axes.x.bottom.z;f=h.axes.x.bottom.xDir;k=!h.bottom.frontFacing}else if(d.opposite){if(null===h.axes.y.right)return{};p=c.x-m;c.x=h.axes.y.right.x;c.z=h.axes.y.right.z;f=h.axes.y.right.xDir;f={x:f.z,y:f.y,z:-f.x}}else{if(null===h.axes.y.left)return{};p=c.x-f;c.x=h.axes.y.left.x;c.z=h.axes.y.left.z;f=h.axes.y.left.xDir}"chart"!==l&&("flap"===l?d.horiz?(e=Math.sin(g),g=Math.cos(g),d.opposite&&(e=-e),k&&(e=-e),q={x:f.z*e,y:g,z:-f.x*e}):f={x:Math.cos(e),y:0,z:Math.sin(e)}:"ortho"===l?d.horiz?(q=
Math.cos(g),l=Math.sin(e)*q,g=-Math.sin(g),e=-q*Math.cos(e),q={x:f.y*e-f.z*g,y:f.z*l-f.x*e,z:f.x*g-f.y*l},g=1/Math.sqrt(q.x*q.x+q.y*q.y+q.z*q.z),k&&(g=-g),q={x:g*q.x,y:g*q.y,z:g*q.z}):f={x:Math.cos(e),y:0,z:Math.sin(e)}:d.horiz?q={x:Math.sin(e)*Math.sin(g),y:Math.cos(g),z:-Math.cos(e)*Math.sin(g)}:f={x:Math.cos(e),y:0,z:Math.sin(e)});c.x+=p*f.x+w*q.x;c.y+=p*f.y+w*q.y;c.z+=p*f.z+w*q.z;k=r([c],d.chart)[0];b&&(0>a(r([c,{x:c.x+f.x,y:c.y+f.y,z:c.z+f.z},{x:c.x+q.x,y:c.y+q.y,z:c.z+q.z}],d.chart))&&(f={x:-f.x,
y:-f.y,z:-f.z}),d=r([{x:c.x,y:c.y,z:c.z},{x:c.x+f.x,y:c.y+f.y,z:c.z+f.z},{x:c.x+q.x,y:c.y+q.y,z:c.z+q.z}],d.chart),k.matrix=[d[1].x-d[0].x,d[1].y-d[0].y,d[2].x-d[0].x,d[2].y-d[0].y,k.x,k.y],k.matrix[4]-=k.x*k.matrix[0]+k.y*k.matrix[2],k.matrix[5]-=k.x*k.matrix[1]+k.y*k.matrix[3]);return k}var u,x=b.addEvent,f=b.Axis,p=b.Chart,A=b.deg2rad,m=b.extend,w=b.merge,r=b.perspective,t=b.perspective3D,n=b.pick,a=b.shapeArea,g=b.splat,h=b.Tick,l=b.wrap;w(!0,f.prototype.defaultOptions,{labels:{position3d:"offset",
skew3d:!1},title:{position3d:null,skew3d:null}});x(f,"afterSetOptions",function(){var a;this.chart.is3d&&this.chart.is3d()&&"colorAxis"!==this.coll&&(a=this.options,a.tickWidth=n(a.tickWidth,0),a.gridLineWidth=n(a.gridLineWidth,1))});l(f.prototype,"getPlotLinePath",function(a){var c=a.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d()||"colorAxis"===this.coll||null===c)return c;var d=this.chart,b=d.options.chart.options3d,b=this.isZAxis?d.plotWidth:b.depth,d=d.frame3d,c=[this.swapZ({x:c[1],
y:c[2],z:0}),this.swapZ({x:c[1],y:c[2],z:b}),this.swapZ({x:c[4],y:c[5],z:0}),this.swapZ({x:c[4],y:c[5],z:b})],b=[];this.horiz?(this.isZAxis?(d.left.visible&&b.push(c[0],c[2]),d.right.visible&&b.push(c[1],c[3])):(d.front.visible&&b.push(c[0],c[2]),d.back.visible&&b.push(c[1],c[3])),d.top.visible&&b.push(c[0],c[1]),d.bottom.visible&&b.push(c[2],c[3])):(d.front.visible&&b.push(c[0],c[2]),d.back.visible&&b.push(c[1],c[3]),d.left.visible&&b.push(c[0],c[1]),d.right.visible&&b.push(c[2],c[3]));b=r(b,this.chart,
!1);return this.chart.renderer.toLineSegments(b)});l(f.prototype,"getLinePath",function(a){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))});l(f.prototype,"getPlotBandPath",function(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var c=arguments,d=c[2],b=[],c=this.getPlotLinePath({value:c[1]}),d=this.getPlotLinePath({value:d});if(c&&d)for(var g=0;g<c.length;g+=6)b.push("M",c[g+1],c[g+2],"L",c[g+4],c[g+
5],"L",d[g+4],d[g+5],"L",d[g+1],d[g+2],"Z");return b});l(h.prototype,"getMarkPath",function(a){var c=a.apply(this,[].slice.call(arguments,1)),c=[q(this.axis,{x:c[1],y:c[2],z:0}),q(this.axis,{x:c[4],y:c[5],z:0})];return this.axis.chart.renderer.toLineSegments(c)});x(h,"afterGetLabelPosition",function(a){m(a.pos,q(this.axis,a.pos))});l(f.prototype,"getTitlePosition",function(a){var c=a.apply(this,[].slice.call(arguments,1));return q(this,c,!0)});x(f,"drawCrosshair",function(a){this.chart.is3d()&&"colorAxis"!==
this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)});x(f,"destroy",function(){["backFrame","bottomFrame","sideFrame"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this)});f.prototype.swapZ=function(a,c){return this.isZAxis?(c=c?0:this.chart.plotLeft,{x:c+a.z,y:a.y,z:a.x-c}):a};u=b.ZAxis=function(){this.init.apply(this,arguments)};m(u.prototype,f.prototype);m(u.prototype,{isZAxis:!0,setOptions:function(a){a=w({offset:0,lineWidth:0},a);f.prototype.setOptions.call(this,
a);this.coll="zAxis"},setAxisSize:function(){f.prototype.setAxisSize.call(this);this.width=this.len=this.chart.options.chart.options3d.depth;this.right=this.chart.chartWidth-this.width-this.left},getSeriesExtremes:function(){var a=this,c=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=null;a.buildStacks&&a.buildStacks();a.series.forEach(function(b){if(b.visible||!c.options.chart.ignoreHiddenSeries)a.hasVisibleSeries=!0,b=b.zData,b.length&&(a.dataMin=Math.min(n(a.dataMin,
b[0]),Math.min.apply(null,b)),a.dataMax=Math.max(n(a.dataMax,b[0]),Math.max.apply(null,b)))})}});x(p,"afterGetAxes",function(){var a=this,c=this.options,c=c.zAxis=g(c.zAxis||{});a.is3d()&&(this.zAxis=[],c.forEach(function(c,b){c.index=b;c.isX=!0;(new u(a,c)).setScale()}))});l(f.prototype,"getSlotWidth",function(a,c){if(this.chart.is3d()&&c&&c.label&&this.categories&&this.chart.frameShapes){var b=this.chart,d=this.ticks,g=this.gridGroup.element.childNodes[0].getBBox(),e=b.frameShapes.left.getBBox(),
h=b.options.chart.options3d,b={x:b.plotWidth/2,y:b.plotHeight/2,z:h.depth/2,vd:n(h.depth,1)*n(h.viewDistance,0)},l,f,h=c.pos,m=d[h-1],d=d[h+1];0!==h&&m&&m.label.xy&&(l=t({x:m.label.xy.x,y:m.label.xy.y,z:null},b,b.vd));d&&d.label.xy&&(f=t({x:d.label.xy.x,y:d.label.xy.y,z:null},b,b.vd));d={x:c.label.xy.x,y:c.label.xy.y,z:null};d=t(d,b,b.vd);return Math.abs(l?d.x-l.x:f?f.x-d.x:g.x-e.x)}return a.apply(this,[].slice.call(arguments,1))})});z(u,"parts-3d/Series.js",[u["parts/Globals.js"]],function(b){var q=
b.addEvent,u=b.perspective,x=b.pick;q(b.Series,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});b.Series.prototype.translate3dPoints=function(){var b=this.chart,p=x(this.zAxis,b.options.zAxis[0]),q=[],m,w,r;for(r=0;r<this.data.length;r++)m=this.data[r],p&&p.translate?(w=p.isLog&&p.val2lin?p.val2lin(m.z):m.z,m.plotZ=p.translate(w),m.isInside=m.isInside?w>=p.min&&w<=p.max:!1):m.plotZ=0,m.axisXpos=m.plotX,m.axisYpos=m.plotY,m.axisZpos=m.plotZ,q.push({x:m.plotX,y:m.plotY,z:m.plotZ});
b=u(q,b,!0);for(r=0;r<this.data.length;r++)m=this.data[r],p=b[r],m.plotX=p.x,m.plotY=p.y,m.plotZ=p.z}});z(u,"parts-3d/Column.js",[u["parts/Globals.js"]],function(b){function q(b){var f=b.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(f.stroke=this.options.edgeColor||f.fill,f["stroke-width"]=p(this.options.edgeWidth,1));return f}function u(b,f,a){var g=this.chart.is3d&&this.chart.is3d();g&&(this.options.inactiveOtherPoints=!0);b.call(this,f,a);g&&(this.options.inactiveOtherPoints=
!1)}var x=b.addEvent,f=b.perspective,p=b.pick,A=b.Series,m=b.seriesTypes,w=b.svg,r=b.wrap;r(m.column.prototype,"translate",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});r(b.Series.prototype,"alignDataLabel",function(b){arguments[3].outside3dPlot=arguments[1].outside3dPlot;b.apply(this,[].slice.call(arguments,1))});r(b.Series.prototype,"justifyDataLabel",function(b){return arguments[2].outside3dPlot?!1:b.apply(this,[].slice.call(arguments,1))});
m.column.prototype.translate3dPoints=function(){};m.column.prototype.translate3dShapes=function(){var b=this,m=b.chart,a=b.options,g=a.depth||25,h=(a.stacking?a.stack||0:b.index)*(g+(a.groupZPadding||1)),l=b.borderWidth%2?.5:0;m.inverted&&!b.yAxis.reversed&&(l*=-1);!1!==a.grouping&&(h=0);h+=a.groupZPadding||1;b.data.forEach(function(a){a.outside3dPlot=null;if(null!==a.y){var c=a.shapeArgs,d=a.tooltipPos,k;[["x","width"],["y","height"]].forEach(function(d){k=c[d[0]]-l;0>k&&(c[d[1]]+=c[d[0]]+l,c[d[0]]=
-l,k=0);k+c[d[1]]>b[d[0]+"Axis"].len&&0!==c[d[1]]&&(c[d[1]]=b[d[0]+"Axis"].len-c[d[0]]);if(0!==c[d[1]]&&(c[d[0]]>=b[d[0]+"Axis"].len||c[d[0]]+c[d[1]]<=l)){for(var e in c)c[e]=0;a.outside3dPlot=!0}});"rect"===a.shapeType&&(a.shapeType="cuboid");c.z=h;c.depth=g;c.insidePlotArea=!0;d=f([{x:d[0],y:d[1],z:h}],m,!0)[0];a.tooltipPos=[d.x,d.y]}});b.z=h};r(m.column.prototype,"animate",function(b){if(this.chart.is3d()){var f=arguments[1],a=this.yAxis,g=this,h=this.yAxis.reversed;w&&(f?g.data.forEach(function(b){null!==
b.y&&(b.height=b.shapeArgs.height,b.shapey=b.shapeArgs.y,b.shapeArgs.height=1,h||(b.shapeArgs.y=b.stackY?b.plotY+a.translate(b.stackY):b.plotY+(b.negative?-b.height:b.height)))}):(g.data.forEach(function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,g.options.animation))}),this.drawDataLabels(),g.animate=null))}else b.apply(this,[].slice.call(arguments,1))});r(m.column.prototype,"plotGroup",function(b,f,a,g,h,l){this.chart.is3d()&&(this[f]&&
delete this[f],l&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(l)),this[f]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[f].survive=!0,"group"===f||"markerGroup"===f))&&(arguments[3]="visible");return b.apply(this,Array.prototype.slice.call(arguments,1))});r(m.column.prototype,"setVisible",function(b,f){var a=this,g;a.chart.is3d()&&a.data.forEach(function(b){g=(b.visible=b.options.visible=f=void 0===f?!p(a.visible,b.visible):
f)?"visible":"hidden";a.options.data[a.data.indexOf(b)]=b.options;b.graphic&&b.graphic.attr({visibility:g})});b.apply(this,Array.prototype.slice.call(arguments,1))});m.column.prototype.handle3dGrouping=!0;x(A,"afterInit",function(){if(this.chart.is3d()&&this.handle3dGrouping){var b=this.options,f=b.grouping,a=b.stacking,g=p(this.yAxis.options.reversedStacks,!0),h=0;if(void 0===f||f){f=this.chart.retrieveStacks(a);h=b.stack||0;for(a=0;a<f[h].series.length&&f[h].series[a]!==this;a++);h=10*(f.totalStacks-
f[h].position)+(g?a:-a);this.xAxis.reversed||(h=10*f.totalStacks-h)}b.zIndex=h}});r(m.column.prototype,"pointAttribs",q);r(m.column.prototype,"setState",u);m.columnrange&&(r(m.columnrange.prototype,"pointAttribs",q),r(m.columnrange.prototype,"setState",u),m.columnrange.prototype.plotGroup=m.column.prototype.plotGroup,m.columnrange.prototype.setVisible=m.column.prototype.setVisible);r(A.prototype,"alignDataLabel",function(b){if(this.chart.is3d()&&this instanceof m.column){var n=arguments,a=n[4],n=
n[1],g={x:a.x,y:a.y,z:this.z},g=f([g],this.chart,!0)[0];a.x=g.x;a.y=n.outside3dPlot?-9E9:g.y}b.apply(this,[].slice.call(arguments,1))});r(b.StackItem.prototype,"getStackBox",function(f,m){var a=f.apply(this,[].slice.call(arguments,1));if(m.is3d()){var g={x:a.x,y:a.y,z:0},g=b.perspective([g],m,!0)[0];a.x=g.x;a.y=g.y}return a})});z(u,"parts-3d/Pie.js",[u["parts/Globals.js"]],function(b){var q=b.deg2rad,u=b.pick,x=b.seriesTypes,f=b.svg;b=b.wrap;b(x.pie.prototype,"translate",function(b){b.apply(this,
[].slice.call(arguments,1));if(this.chart.is3d()){var f=this,m=f.options,p=m.depth||0,r=f.chart.options.chart.options3d,t=r.alpha,n=r.beta,a=m.stacking?(m.stack||0)*p:f._i*p,a=a+p/2;!1!==m.grouping&&(a=0);f.data.forEach(function(b){var g=b.shapeArgs;b.shapeType="arc3d";g.z=a;g.depth=.75*p;g.alpha=t;g.beta=n;g.center=f.center;g=(g.end+g.start)/2;b.slicedTranslation={translateX:Math.round(Math.cos(g)*m.slicedOffset*Math.cos(t*q)),translateY:Math.round(Math.sin(g)*m.slicedOffset*Math.cos(t*q))}})}});
b(x.pie.prototype.pointClass.prototype,"haloPath",function(b){var f=arguments;return this.series.chart.is3d()?[]:b.call(this,f[1])});b(x.pie.prototype,"pointAttribs",function(b,f,m){b=b.call(this,f,m);m=this.options;this.chart.is3d()&&!this.chart.styledMode&&(b.stroke=m.edgeColor||f.color||this.color,b["stroke-width"]=u(m.edgeWidth,1));return b});b(x.pie.prototype,"drawDataLabels",function(b){if(this.chart.is3d()){var f=this.chart.options.chart.options3d;this.data.forEach(function(b){var m=b.shapeArgs,
p=m.r,t=(m.start+m.end)/2;b=b.labelPosition;var n=b.connectorPosition,a=-p*(1-Math.cos((m.alpha||f.alpha)*q))*Math.sin(t),g=p*(Math.cos((m.beta||f.beta)*q)-1)*Math.cos(t);[b.natural,n.breakAt,n.touchingSliceAt].forEach(function(b){b.x+=g;b.y+=a})})}b.apply(this,[].slice.call(arguments,1))});b(x.pie.prototype,"addPoint",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.update(this.userOptions,!0)});b(x.pie.prototype,"animate",function(b){if(this.chart.is3d()){var p=arguments[1],
m=this.options.animation,q=this.center,r=this.group,t=this.markerGroup;f&&(!0===m&&(m={}),p?(r.oldtranslateX=r.translateX,r.oldtranslateY=r.translateY,p={translateX:q[0],translateY:q[1],scaleX:.001,scaleY:.001},r.attr(p),t&&(t.attrSetters=r.attrSetters,t.attr(p))):(p={translateX:r.oldtranslateX,translateY:r.oldtranslateY,scaleX:1,scaleY:1},r.animate(p,m),t&&t.animate(p,m),this.animate=null))}else b.apply(this,[].slice.call(arguments,1))})});z(u,"parts-3d/Scatter.js",[u["parts/Globals.js"]],function(b){var q=
b.Point,u=b.seriesType,x=b.seriesTypes;u("scatter3d","scatter",{tooltip:{pointFormat:"x: \x3cb\x3e{point.x}\x3c/b\x3e\x3cbr/\x3ey: \x3cb\x3e{point.y}\x3c/b\x3e\x3cbr/\x3ez: \x3cb\x3e{point.z}\x3c/b\x3e\x3cbr/\x3e"}},{pointAttribs:function(f){var p=x.scatter.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&f&&(p.zIndex=b.pointCameraDistance(f,this.chart));return p},axisTypes:["xAxis","yAxis","zAxis"],pointArrayMap:["x","y","z"],parallelArrays:["x","y","z"],directTouch:!0},{applyOptions:function(){q.prototype.applyOptions.apply(this,
arguments);void 0===this.z&&(this.z=0);return this}})});z(u,"parts-3d/VMLRenderer.js",[u["parts/Globals.js"]],function(b){var q=b.addEvent,u=b.Axis,x=b.SVGRenderer,f=b.VMLRenderer;f&&(b.setOptions({animate:!1}),f.prototype.face3d=x.prototype.face3d,f.prototype.polyhedron=x.prototype.polyhedron,f.prototype.elements3d=x.prototype.elements3d,f.prototype.element3d=x.prototype.element3d,f.prototype.cuboid=x.prototype.cuboid,f.prototype.cuboidPath=x.prototype.cuboidPath,f.prototype.toLinePath=x.prototype.toLinePath,
f.prototype.toLineSegments=x.prototype.toLineSegments,f.prototype.arc3d=function(b){b=x.prototype.arc3d.call(this,b);b.css({zIndex:b.zIndex});return b},b.VMLRenderer.prototype.arc3dPath=b.SVGRenderer.prototype.arc3dPath,q(u,"render",function(){this.sideFrame&&(this.sideFrame.css({zIndex:0}),this.sideFrame.front.attr({fill:this.sideFrame.color}));this.bottomFrame&&(this.bottomFrame.css({zIndex:1}),this.bottomFrame.front.attr({fill:this.bottomFrame.color}));this.backFrame&&(this.backFrame.css({zIndex:0}),
this.backFrame.front.attr({fill:this.backFrame.color}))}))});z(u,"masters/highcharts-3d.src.js",[],function(){})});
//# sourceMappingURL=highcharts-3d.js.map