/*
 Highstock JS v7.1.2-modified (2019-07-03)

 All technical indicators for Highstock

 (c) 2010-2019 Pawel Fus

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators-all",["highcharts","highcharts/modules/stock"],function(t){f(t);f.Highcharts=t;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function t(d,n,q,m){d.hasOwnProperty(n)||(d[n]=m.apply(null,q))}f=f?f._modules:{};t(f,"mixins/indicator-required.js",[f["parts/Globals.js"]],function(d){var n=d.error;return{isParentLoaded:function(d,
m,g,e,b){if(d)return e?e(d):!0;n(b||this.generateMessage(g,m));return!1},generateMessage:function(d,m){return'Error: "'+d+'" indicator type requires "'+m+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+d}}});t(f,"indicators/indicators.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["mixins/indicator-required.js"]],function(d,n,q){var m=n.isArray,g=d.pick,e=d.error,b=d.Series,a=d.addEvent;n=d.seriesType;var c=d.seriesTypes,r=d.seriesTypes.ohlc.prototype,
h=q.generateMessage;a(d.Series,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==a.id&&d.extend(this,{pointValKey:r.pointValKey,keys:r.keys,pointArrayMap:r.pointArrayMap,toYData:r.toYData})});a(b,"afterSetOptions",function(a){a=a.options;var b=a.dataGrouping;b&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(b.approximation="ohlc")});n("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},{processData:function(){var a=
this.options.compareToMain,c=this.linkedParent;b.prototype.processData.apply(this,arguments);c&&c.compareValue&&a&&(this.compareValue=c.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(b){c[b]?c[b].prototype.requireIndicators():(a.allLoaded=!1,a.needed=b)});return a},init:function(c,
g){function r(){var a=k.points||[],b=(k.xData||[]).length,c=k.getValues(k.linkedParent,k.options.params)||{values:[],xData:[],yData:[]},e=[],h=!0,r,g;if(b&&!k.hasGroupedData&&k.visible&&k.points)if(k.cropped){k.xAxis&&(r=k.xAxis.min,g=k.xAxis.max);b=k.cropData(c.xData,c.yData,r,g);for(r=0;r<b.xData.length;r++)e.push([b.xData[r]].concat(d.splat(b.yData[r])));b=c.xData.indexOf(k.xData[0]);r=c.xData.indexOf(k.xData[k.xData.length-1]);-1===b&&r===c.xData.length-2&&e[0][0]===a[0].x&&e.shift();k.updateData(e)}else c.xData.length!==
b-1&&c.xData.length!==b+1&&(h=!1,k.updateData(c.values));h&&(k.xData=c.xData,k.yData=c.yData,k.options.data=c.values);!1===k.bindTo.series&&(delete k.processedXData,k.isDirty=!0,k.redraw());k.isDirtyData=!1}var k=this,u=k.requireIndicators();if(!u.allLoaded)return e(h(k.type,u.needed));b.prototype.init.call(k,c,g);c.linkSeries();k.dataEventsToUnbind=[];if(!k.linkedParent)return e("Series "+k.options.linkedTo+" not found! Check `linkedTo`.",!1,c);k.dataEventsToUnbind.push(a(k.bindTo.series?k.linkedParent:
k.linkedParent.xAxis,k.bindTo.eventName,r));if("init"===k.calculateOn)r();else var p=a(k.chart,k.calculateOn,function(){r();p()});return k},getName:function(){var a=this.name,c=[];a||((this.nameComponents||[]).forEach(function(a,b){c.push(this.options.params[a]+g(this.nameSuffixes[b],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+c.join(", ")+")":""));return a},getValues:function(a,c){var b=c.period,k=a.xData;a=a.yData;var e=a.length,h=0,r=0,g=[],p=[],D=[],d=-1,n;
if(k.length<b)return!1;for(m(a[0])&&(d=c.index?c.index:0);h<b-1;)r+=0>d?a[h]:a[h][d],h++;for(c=h;c<e;c++)r+=0>d?a[c]:a[c][d],n=[k[c],r/b],g.push(n),p.push(n[0]),D.push(n[1]),r-=0>d?a[c-h]:a[c-h][d];return{values:g,xData:p,yData:D}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});b.prototype.destroy.call(this)}})});t(f,"indicators/accumulation-distribution.src.js",[f["parts/Globals.js"]],function(d){var n=d.seriesType;n("ad","sma",{params:{volumeSeriesID:"volume"}},{nameComponents:!1,
nameBase:"Accumulation/Distribution",getValues:function(n,m){var g=m.period,e=n.xData,b=n.yData,a=m.volumeSeriesID,c=n.chart.get(a);m=c&&c.yData;var r=b?b.length:0,h=[],D=[],p=[];if(e.length<=g&&r&&4!==b[0].length)return!1;if(!c)return d.error("Series "+a+" not found! Check `volumeSeriesID`.",!0,n.chart);for(;g<r;g++){n=h.length;var a=b[g][1],c=b[g][2],l=b[g][3],k=m[g],a=[e[g],l===a&&l===c||a===c?0:(2*l-c-a)/(a-c)*k];0<n&&(a[1]+=h[n-1][1]);h.push(a);D.push(a[0]);p.push(a[1])}return{values:h,xData:D,
yData:p}}})});t(f,"indicators/ao.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,n){var f=n.isArray,m=d.correctFloat;d.seriesType("ao","sma",{greaterBarColor:"#06B535",lowerBarColor:"#F21313",threshold:0,groupPadding:.2,pointPadding:.2,states:{hover:{halo:{size:0}}}},{nameBase:"AO",nameComponents:!1,markerAttribs:d.noop,getColumnMetrics:d.seriesTypes.column.prototype.getColumnMetrics,crispCol:d.seriesTypes.column.prototype.crispCol,translate:d.seriesTypes.column.prototype.translate,
drawPoints:d.seriesTypes.column.prototype.drawPoints,drawGraph:function(){var g=this.options,e=this.points,b=g.greaterBarColor,g=g.lowerBarColor,a=e[0];if(!this.userOptions.color&&a)for(a.color=b,a=1;a<e.length;a++)e[a].color=e[a].y>e[a-1].y?b:e[a].y<e[a-1].y?g:e[a-1].color},getValues:function(g){var e=g.xData||[];g=g.yData||[];var b=g.length,a=[],c=[],r=[],h=0,D=0,p,l,k;if(34>=e.length||!f(g[0])||4!==g[0].length)return!1;for(k=0;33>k;k++)p=(g[k][1]+g[k][2])/2,29<=k&&(h=m(h+p)),D=m(D+p);for(k=33;k<
b;k++)p=(g[k][1]+g[k][2])/2,h=m(h+p),D=m(D+p),p=h/5,l=D/34,p=m(p-l),a.push([e[k],p]),c.push(e[k]),r.push(p),p=k+1-5,l=k+1-34,h=m(h-(g[p][1]+g[p][2])/2),D=m(D-(g[l][1]+g[l][2])/2);return{values:a,xData:c,yData:r}}})});t(f,"mixins/multipe-lines.js",[f["parts/Globals.js"]],function(d){var n=d.each,f=d.merge,m=d.error,g=d.defined,e=d.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(b){var a=[];n(this.pointArrayMap,function(c){c!==
b&&a.push("plot"+c.charAt(0).toUpperCase()+c.slice(1))});return a},toYData:function(b){var a=[];n(this.pointArrayMap,function(c){a.push(b[c])});return a},translate:function(){var b=this,a=b.pointArrayMap,c=[],r,c=b.getTranslatedLinesNames();e.prototype.translate.apply(b,arguments);n(b.points,function(e){n(a,function(a,h){r=e[a];null!==r&&(e[c[h]]=b.yAxis.toPixels(r,!0))})})},drawGraph:function(){var b=this,a=b.linesApiNames,c=b.points,r=c.length,h=b.options,D=b.graph,p={options:{gapSize:h.gapSize}},
l=[],k=b.getTranslatedLinesNames(b.pointValKey),u;n(k,function(a,b){for(l[b]=[];r--;)u=c[r],l[b].push({x:u.x,plotX:u.plotX,plotY:u[a],isNull:!g(u[a])});r=c.length});n(a,function(a,c){l[c]?(b.points=l[c],h[a]?b.options=f(h[a].styles,p):m('Error: "There is no '+a+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),b.graph=b["graph"+a],e.prototype.drawGraph.call(b),b["graph"+a]=b.graph):m('Error: "'+a+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});
b.points=c;b.options=h;b.graph=D;e.prototype.drawGraph.call(b)}}});t(f,"indicators/aroon.src.js",[f["parts/Globals.js"],f["mixins/multipe-lines.js"]],function(d,n){function f(d,g){var e=d[0],b=0,a;for(a=1;a<d.length;a++)if("max"===g&&d[a]>=e||"min"===g&&d[a]<=e)e=d[a],b=a;return b}d.seriesType("aroon","sma",{params:{period:25},marker:{enabled:!1},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e\x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eAroon Up: {point.y}\x3cbr/\x3eAroon Down: {point.aroonDown}\x3cbr/\x3e'},
aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},d.merge(n,{nameBase:"Aroon",pointArrayMap:["y","aroonDown"],pointValKey:"y",linesApiNames:["aroonDown"],getValues:function(m,g){g=g.period;var e=m.xData,b=(m=m.yData)?m.length:0,a=[],c=[],r=[],h,D,p;for(p=g-1;p<b;p++)h=m.slice(p-g+1,p+2),D=f(h.map(function(a){return d.pick(a[2],a)}),"min"),h=f(h.map(function(a){return d.pick(a[1],a)}),"max"),h=h/g*100,D=D/g*100,e[p+1]&&(a.push([e[p+1],h,D]),c.push(e[p+1]),r.push([h,
D]));return{values:a,xData:c,yData:r}}}))});t(f,"indicators/aroon-oscillator.src.js",[f["parts/Globals.js"],f["mixins/multipe-lines.js"],f["mixins/indicator-required.js"]],function(d,n,f){var m=d.seriesTypes.aroon;d.seriesType("aroonoscillator","aroon",{params:{period:25},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e\x3cb\x3e {series.name}\x3c/b\x3e: {point.y}'}},d.merge(n,{nameBase:"Aroon Oscillator",pointArrayMap:["y"],pointValKey:"y",linesApiNames:[],init:function(){var g=
arguments,e=this;f.isParentLoaded(m,"aroon",e.type,function(b){b.prototype.init.apply(e,g)})},getValues:function(g,e){var b=[],a=[],c=[],r,h;g=m.prototype.getValues.call(this,g,e);for(e=0;e<g.yData.length;e++)r=g.yData[e][0],h=g.yData[e][1],r-=h,b.push([g.xData[e],r]),a.push(g.xData[e]),c.push(r);return{values:b,xData:a,yData:c}}}))});t(f,"indicators/atr.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,n){function f(e,b){return Math.max(e[1]-e[2],b===g?0:Math.abs(e[1]-b[3]),b===
g?0:Math.abs(e[2]-b[3]))}var m=n.isArray;d=d.seriesType;var g;d("atr","sma",{params:{period:14}},{getValues:function(e,b){b=b.period;var a=e.xData,c=(e=e.yData)?e.length:0,r=1,h=0,g=0,p=[],l=[],k=[],u,d,y;y=[[a[0],e[0]]];if(a.length<=b||!m(e[0])||4!==e[0].length)return!1;for(d=1;d<=c;d++)if(y.push([a[d],e[d]]),b<r){u=b;var n=a[d-1],v=f(e[d-1],e[d-2]);u=[n,(h*(u-1)+v)/u];h=u[1];p.push(u);l.push(u[0]);k.push(u[1])}else b===r?(h=g/(d-1),p.push([a[d-1],h]),l.push(a[d-1]),k.push(h)):g+=f(e[d-1],e[d-2]),
r++;return{values:p,xData:l,yData:k}}})});t(f,"indicators/bollinger-bands.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["mixins/multipe-lines.js"]],function(d,n,f){var m=n.isArray,g=d.merge,e=d.seriesTypes.sma;d.seriesType("bb","sma",{params:{period:20,standardDeviation:2,index:3},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e\x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eTop: {point.top}\x3cbr/\x3eMiddle: {point.middle}\x3cbr/\x3eBottom: {point.bottom}\x3cbr/\x3e'},
marker:{enabled:!1},dataGrouping:{approximation:"averages"}},d.merge(f,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],init:function(){e.prototype.init.apply(this,arguments);this.options=g({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(b,a){var c=a.period,r=a.standardDeviation,h=b.xData,g=(b=b.yData)?b.length:0,d=[],l,k,u,I,n=[],
f=[],v,q;if(h.length<c)return!1;v=m(b[0]);for(q=c;q<=g;q++){I=h.slice(q-c,q);k=b.slice(q-c,q);l=e.prototype.getValues.call(this,{xData:I,yData:k},a);I=l.xData[0];l=l.yData[0];u=0;for(var x=k.length,w=0,A;w<x;w++)A=(v?k[w][a.index]:k[w])-l,u+=A*A;u=Math.sqrt(u/(x-1));k=l+r*u;u=l-r*u;d.push([I,k,l,u]);n.push(I);f.push([k,l,u])}return{values:d,xData:n,yData:f}}}))});t(f,"indicators/cci.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,n){function f(g){return g.reduce(function(e,b){return e+
b},0)}var m=n.isArray;d=d.seriesType;d("cci","sma",{params:{period:14}},{getValues:function(g,e){e=e.period;var b=g.xData,a=(g=g.yData)?g.length:0,c=[],r,h=1,d=[],p=[],l=[],k,u;if(b.length<=e||!m(g[0])||4!==g[0].length)return!1;for(;h<e;)k=g[h-1],c.push((k[1]+k[2]+k[3])/3),h++;for(h=e;h<=a;h++){k=g[h-1];k=(k[1]+k[2]+k[3])/3;u=c.push(k);r=c.slice(u-e);u=f(r)/e;var I=r.length,n=0,q;for(q=0;q<I;q++)n+=Math.abs(u-r[q]);r=n/e;k=(k-u)/(.015*r);d.push([b[h-1],k]);p.push(b[h-1]);l.push(k)}return{values:d,
xData:p,yData:l}}})});t(f,"indicators/cmf.src.js",[f["parts/Globals.js"]],function(d){d.seriesType("cmf","sma",{params:{period:14,volumeSeriesID:"volume"}},{nameBase:"Chaikin Money Flow",isValid:function(){var d=this.chart,f=this.options,m=this.linkedParent,d=this.volumeSeries||(this.volumeSeries=d.get(f.params.volumeSeriesID)),g=m&&m.yData&&4===m.yData[0].length;return!!(m&&d&&m.xData&&m.xData.length>=f.params.period&&d.xData&&d.xData.length>=f.params.period&&g)},getValues:function(d,f){return this.isValid()?
this.getMoneyFlow(d.xData,d.yData,this.volumeSeries.yData,f.period):!1},getMoneyFlow:function(d,f,m,g){function e(a,c){var b=a[1],k=a[2];a=a[3];return null!==c&&null!==b&&null!==k&&null!==a&&b!==k?(a-k-(b-a))/(b-k)*c:(u=l,null)}var b=f.length,a=[],c=0,r=0,h=[],D=[],p=[],l,k,u=-1;if(0<g&&g<=b){for(l=0;l<g;l++)a[l]=e(f[l],m[l]),c+=m[l],r+=a[l];h.push(d[l-1]);D.push(l-u>=g&&0!==c?r/c:null);for(p.push([h[0],D[0]]);l<b;l++)a[l]=e(f[l],m[l]),c-=m[l-g],c+=m[l],r-=a[l-g],r+=a[l],k=[d[l],l-u>=g?r/c:null],
h.push(k[0]),D.push(k[1]),p.push([k[0],k[1]])}return{values:p,xData:h,yData:D}}})});t(f,"indicators/dpo.src.js",[f["parts/Globals.js"]],function(d){function f(g,e,b,a,c){e=m(e[b][a],e[b]);return c?q(g-e):q(g+e)}var q=d.correctFloat,m=d.pick;d.seriesType("dpo","sma",{params:{period:21}},{nameBase:"DPO",getValues:function(g,e){var b=e.period;e=e.index;var a=b+Math.floor(b/2+1),c=g.xData||[];g=g.yData||[];var r=g.length,h=[],d=[],p=[],l=0,k,u,I;if(c.length<=a)return!1;for(u=0;u<b-1;u++)l=f(l,g,u,e);
for(I=0;I<=r-a;I++)k=I+b-1,u=I+a-1,l=f(l,g,k,e),k=m(g[u][e],g[u]),k-=l/b,l=f(l,g,I,e,!0),h.push([c[u],k]),d.push(c[u]),p.push(k);return{values:h,xData:d,yData:p}}})});t(f,"indicators/ema.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){var n=f.isArray;f=d.seriesType;var m=d.correctFloat;f("ema","sma",{params:{index:3,period:9}},{accumulatePeriodPoints:function(g,e,b){for(var a=0,c=0,r;c<g;)r=0>e?b[c]:b[c][e],a+=r,c++;return a},calculateEma:function(g,e,b,a,c,r,h){g=g[b-1];e=0>
r?e[b-1]:e[b-1][r];a=void 0===c?h:m(e*a+c*(1-a));return[g,a]},getValues:function(g,e){var b=e.period,a=g.xData,c=(g=g.yData)?g.length:0,r=2/(b+1),h=[],d=[],p=[],l=-1,k;if(c<b)return!1;n(g[0])&&(l=e.index?e.index:0);for(e=this.accumulatePeriodPoints(b,l,g)/b;b<c+1;b++)k=this.calculateEma(a,g,b,r,k,l,e),h.push(k),d.push(k[0]),p.push(k[1]),k=k[1];return{values:h,xData:d,yData:p}}})});t(f,"indicators/chaikin.src.js",[f["parts/Globals.js"],f["mixins/indicator-required.js"]],function(d,f){var n=d.seriesTypes.ema,
m=d.seriesTypes.ad,g=d.error,e=d.correctFloat;d.seriesType("chaikin","ema",{params:{volumeSeriesID:"volume",periods:[3,10]}},{nameBase:"Chaikin Osc",nameComponents:["periods"],init:function(){var b=arguments,a=this;f.isParentLoaded(n,"ema",a.type,function(c){c.prototype.init.apply(a,b)})},getValues:function(b,a){var c=a.periods,r=a.period,h=[],d=[],p=[],l;if(2!==c.length||c[1]<=c[0])return g('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."'),!1;a=m.prototype.getValues.call(this,
b,{volumeSeriesID:a.volumeSeriesID,period:r});if(!a)return!1;b=n.prototype.getValues.call(this,a,{period:c[0]});a=n.prototype.getValues.call(this,a,{period:c[1]});if(!b||!a)return!1;c=c[1]-c[0];for(l=0;l<a.yData.length;l++)r=e(b.yData[l+c]-a.yData[l]),h.push([a.xData[l],r]),d.push(a.xData[l]),p.push(r);return{values:h,xData:d,yData:p}}})});t(f,"indicators/dema.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["mixins/indicator-required.js"]],function(d,f,q){var m=f.isArray,g=d.seriesTypes.ema,
e=d.correctFloat;d.seriesType("dema","ema",{},{init:function(){var b=arguments,a=this;q.isParentLoaded(g,"ema",a.type,function(c){c.prototype.init.apply(a,b)})},getEMA:function(b,a,c,e,h,d){return g.prototype.calculateEma(d||[],b,void 0===h?1:h,this.chart.series[0].EMApercent,a,void 0===e?-1:e,c)},getValues:function(b,a){var c=a.period,r=2*c,h=b.xData,d=b.yData,p=d?d.length:0,l=-1,k=[],u=[],I=[],f=0,n,v,q=[],x,w;b.EMApercent=2/(c+1);if(p<2*c-1)return!1;m(d[0])&&(l=a.index?a.index:0);b=g.prototype.accumulatePeriodPoints(c,
l,d);a=b/c;b=0;for(x=c;x<p+2;x++)x<p+1&&(f=this.getEMA(d,v,a,l,x)[1],q.push(f)),v=f,x<r?b+=f:(x===r&&(a=b/c),f=q[x-c-1],n=this.getEMA([f],n,a)[1],w=[h[x-2],e(2*f-n)],k.push(w),u.push(w[0]),I.push(w[1]));return{values:k,xData:u,yData:I}}})});t(f,"indicators/tema.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["mixins/indicator-required.js"]],function(d,f,q){var m=f.isArray,g=d.seriesTypes.ema,e=d.correctFloat;d.seriesType("tema","ema",{},{init:function(){var b=arguments,a=this;q.isParentLoaded(g,
"ema",a.type,function(c){c.prototype.init.apply(a,b)})},getEMA:function(b,a,c,e,h,d){return g.prototype.calculateEma(d||[],b,void 0===h?1:h,this.chart.series[0].EMApercent,a,void 0===e?-1:e,c)},getTemaPoint:function(b,a,c,g){return[b[g-3],e(3*c.level1-3*c.level2+c.level3)]},getValues:function(b,a){var c=a.period,e=2*c,h=3*c,d=b.xData,p=b.yData,l=p?p.length:0,k=-1,u=[],I=[],f=[],n,v,q=[],x=[],w,A,F={};b.EMApercent=2/(c+1);if(l<3*c-2)return!1;m(p[0])&&(k=a.index?a.index:0);b=g.prototype.accumulatePeriodPoints(c,
k,p);a=b/c;b=0;for(w=c;w<l+3;w++)if(w<l+1&&(F.level1=this.getEMA(p,n,a,k,w)[1],q.push(F.level1)),n=F.level1,w<e)b+=F.level1;else if(w===e&&(a=b/c,b=0),F.level1=q[w-c-1],F.level2=this.getEMA([F.level1],v,a)[1],x.push(F.level2),v=F.level2,w<h)b+=F.level2;else{w===h&&(a=b/c);w===l+1&&(F.level1=q[w-c-1],F.level2=this.getEMA([F.level1],v,a)[1],x.push(F.level2));F.level1=q[w-c-2];F.level2=x[w-2*c-1];F.level3=this.getEMA([F.level2],F.prevLevel3,a)[1];if(A=this.getTemaPoint(d,h,F,w))u.push(A),I.push(A[0]),
f.push(A[1]);F.prevLevel3=F.level3}return{values:u,xData:I,yData:f}}})});t(f,"indicators/trix.src.js",[f["parts/Globals.js"],f["mixins/indicator-required.js"]],function(d,f){var n=d.correctFloat,m=d.seriesTypes.tema;d.seriesType("trix","tema",{},{init:function(){var g=arguments,e=this;f.isParentLoaded(m,"tema",e.type,function(b){b.prototype.init.apply(e,g)})},getTemaPoint:function(g,e,b,a){if(a>e)var c=[g[a-3],0!==b.prevLevel3?n(b.level3-b.prevLevel3)/b.prevLevel3*100:null];return c}})});t(f,"indicators/apo.src.js",
[f["parts/Globals.js"],f["mixins/indicator-required.js"]],function(d,f){var n=d.seriesTypes.ema,m=d.error;d.seriesType("apo","ema",{params:{periods:[10,20]}},{nameBase:"APO",nameComponents:["periods"],init:function(){var g=arguments,e=this;f.isParentLoaded(n,"ema",e.type,function(b){b.prototype.init.apply(e,g)})},getValues:function(g,e){var b=e.periods,a=e.index;e=[];var c=[],r=[],h,d;if(2!==b.length||b[1]<=b[0])return m('Error: "APO requires two periods. Notice, first period should be lower than the second one."'),
!1;h=n.prototype.getValues.call(this,g,{index:a,period:b[0]});g=n.prototype.getValues.call(this,g,{index:a,period:b[1]});if(!h||!g)return!1;b=b[1]-b[0];for(d=0;d<g.yData.length;d++)a=h.yData[d+b]-g.yData[d],e.push([g.xData[d],a]),c.push(g.xData[d]),r.push(a);return{values:e,xData:c,yData:r}}})});t(f,"indicators/ichimoku-kinko-hyo.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){function n(a){return a.reduce(function(a,c){return Math.max(a,c[1])},-Infinity)}function m(a){return a.reduce(function(a,
c){return Math.min(a,c[2])},Infinity)}function g(a){return{high:n(a),low:m(a)}}function e(a){var c,b,k,e,h;a.series.forEach(function(a){if(a.xData)for(e=a.xData,h=b=a.xIncrement?1:e.length-1;0<h;h--)if(k=e[h]-e[h-1],c===r||k<c)c=k});return c}function b(a,c,b,e){if(a&&c&&b&&e){var k=c.plotX-a.plotX;c=c.plotY-a.plotY;var h=e.plotX-b.plotX;e=e.plotY-b.plotY;var g=a.plotX-b.plotX,d=a.plotY-b.plotY;b=(-c*g+k*d)/(-h*c+k*e);h=(h*d-e*g)/(-h*c+k*e);if(0<=b&&1>=b&&0<=h&&1>=h)return{plotX:a.plotX+h*k,plotY:a.plotY+
h*c}}return!1}function a(a){var c=a.indicator;c.points=a.points;c.nextPoints=a.nextPoints;c.color=a.color;c.options=h(a.options.senkouSpan.styles,a.gap);c.graph=a.graph;c.fillGraph=!0;l.prototype.drawGraph.call(c)}var c=f.isArray,r;f=d.seriesType;var h=d.merge,D=d.color,p=d.defined,l=d.seriesTypes.sma;d.approximations["ichimoku-averages"]=function(){var a=[],c;[].forEach.call(arguments,function(b,e){a.push(d.approximations.average(b));c=!c&&void 0===a[e]});return c?void 0:a};f("ikh","sma",{params:{period:26,
periodTenkan:9,periodSenkouSpanB:52},marker:{enabled:!1},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eTENKAN SEN: {point.tenkanSen:.3f}\x3cbr/\x3eKIJUN SEN: {point.kijunSen:.3f}\x3cbr/\x3eCHIKOU SPAN: {point.chikouSpan:.3f}\x3cbr/\x3eSENKOU SPAN A: {point.senkouSpanA:.3f}\x3cbr/\x3eSENKOU SPAN B: {point.senkouSpanB:.3f}\x3cbr/\x3e'},tenkanLine:{styles:{lineWidth:1,lineColor:void 0}},kijunLine:{styles:{lineWidth:1,
lineColor:void 0}},chikouLine:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanA:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanB:{styles:{lineWidth:1,lineColor:void 0}},senkouSpan:{styles:{fill:"rgba(255, 0, 0, 0.5)"}},dataGrouping:{approximation:"ichimoku-averages"}},{pointArrayMap:["tenkanSen","kijunSen","chikouSpan","senkouSpanA","senkouSpanB"],pointValKey:"tenkanSen",nameComponents:["periodSenkouSpanB","period","periodTenkan"],init:function(){l.prototype.init.apply(this,arguments);this.options=
h({tenkanLine:{styles:{lineColor:this.color}},kijunLine:{styles:{lineColor:this.color}},chikouLine:{styles:{lineColor:this.color}},senkouSpanA:{styles:{lineColor:this.color,fill:D(this.color).setOpacity(.5).get()}},senkouSpanB:{styles:{lineColor:this.color,fill:D(this.color).setOpacity(.5).get()}},senkouSpan:{styles:{fill:D(this.color).setOpacity(.2).get()}}},this.options)},toYData:function(a){return[a.tenkanSen,a.kijunSen,a.chikouSpan,a.senkouSpanA,a.senkouSpanB]},translate:function(){var a=this;
l.prototype.translate.apply(a);a.points.forEach(function(c){a.pointArrayMap.forEach(function(b){p(c[b])&&(c["plot"+b]=a.yAxis.toPixels(c[b],!0),c.plotY=c["plot"+b],c.tooltipPos=[c.plotX,c["plot"+b]],c.isNull=!1)})})},drawGraph:function(){var c=this,e=c.points,g=e.length,r=c.options,m=c.graph,f=c.color,D={options:{gapSize:r.gapSize}},n=c.pointArrayMap.length,q=[[],[],[],[],[],[]],A={tenkanLine:q[0],kijunLine:q[1],chikouLine:q[2],senkouSpanA:q[3],senkouSpanB:q[4],senkouSpan:q[5]},F=[],C=c.options.senkouSpan,
G=C.color||C.styles.fill,t=C.negativeColor,E=[[],[]],K=[[],[]],M=0,H,J,N,L;for(c.ikhMap=A;g--;){H=e[g];for(J=0;J<n;J++)C=c.pointArrayMap[J],p(H[C])&&q[J].push({plotX:H.plotX,plotY:H["plot"+C],isNull:!1});t&&g!==e.length-1&&(C=A.senkouSpanB.length-1,H=b(A.senkouSpanA[C-1],A.senkouSpanA[C],A.senkouSpanB[C-1],A.senkouSpanB[C]),J={plotX:H.plotX,plotY:H.plotY,isNull:!1,intersectPoint:!0},H&&(A.senkouSpanA.splice(C,0,J),A.senkouSpanB.splice(C,0,J),F.push(C)))}d.objectEach(A,function(a,b){r[b]&&"senkouSpan"!==
b&&(c.points=q[M],c.options=h(r[b].styles,D),c.graph=c["graph"+b],c.fillGraph=!1,c.color=f,l.prototype.drawGraph.call(c),c["graph"+b]=c.graph);M++});c.graphCollection&&c.graphCollection.forEach(function(a){c[a].destroy();delete c[a]});c.graphCollection=[];if(t&&A.senkouSpanA[0]&&A.senkouSpanB[0]){F.unshift(0);F.push(A.senkouSpanA.length-1);for(n=0;n<F.length-1;n++){C=F[n];H=F[n+1];g=A.senkouSpanB.slice(C,H+1);C=A.senkouSpanA.slice(C,H+1);if(1<=Math.floor(g.length/2))if(H=Math.floor(g.length/2),g[H].plotY===
C[H].plotY){for(L=J=H=0;L<g.length;L++)H+=g[L].plotY,J+=C[L].plotY;H=H>J?0:1}else H=g[H].plotY>C[H].plotY?0:1;else H=g[0].plotY>C[0].plotY?0:1;E[H]=E[H].concat(g);K[H]=K[H].concat(C)}["graphsenkouSpanColor","graphsenkouSpanNegativeColor"].forEach(function(b,e){E[e].length&&K[e].length&&(N=0===e?G:t,a({indicator:c,points:E[e],nextPoints:K[e],color:N,options:r,gap:D,graph:c[b]}),c[b]=c.graph,c.graphCollection.push(b))})}else a({indicator:c,points:A.senkouSpanB,nextPoints:A.senkouSpanA,color:G,options:r,
gap:D,graph:c.graphsenkouSpan}),c.graphsenkouSpan=c.graph;delete c.nextPoints;delete c.fillGraph;c.points=e;c.options=r;c.graph=m},getGraphPath:function(a){var c,b,e=[];a=a||this.points;if(this.fillGraph&&this.nextPoints){b=l.prototype.getGraphPath.call(this,this.nextPoints);b[0]="L";c=l.prototype.getGraphPath.call(this,a);b=b.slice(0,c.length);for(var h=b.length-1;0<h;h-=3)e.push(b[h-2],b[h-1],b[h]);c=c.concat(e)}else c=l.prototype.getGraphPath.apply(this,arguments);return c},getValues:function(a,
b){var h=b.period,k=b.periodTenkan;b=b.periodSenkouSpanB;var d=a.xData,l=a.yData,p=l&&l.length||0;a=e(a.xAxis);var m=[],f=[],u,D,n,q,t,E,K;if(d.length<=h||!c(l[0])||4!==l[0].length)return!1;u=d[0]-h*a;for(E=0;E<h;E++)f.push(u+E*a);for(E=0;E<p;E++)E>=k&&(n=l.slice(E-k,E),n=g(n),n=(n.high+n.low)/2),E>=h&&(q=l.slice(E-h,E),q=g(q),q=(q.high+q.low)/2,K=(n+q)/2),E>=b&&(t=l.slice(E-b,E),t=g(t),t=(t.high+t.low)/2),u=l[E][3],D=d[E],m[E]===r&&(m[E]=[]),m[E+h]===r&&(m[E+h]=[]),m[E+h][0]=n,m[E+h][1]=q,m[E+h][2]=
r,m[E][2]=u,E<=h&&(m[E+h][3]=r,m[E+h][4]=r),m[E+2*h]===r&&(m[E+2*h]=[]),m[E+2*h][3]=K,m[E+2*h][4]=t,f.push(D);for(E=1;E<=h;E++)f.push(D+E*a);return{values:m,xData:f,yData:m}}})});t(f,"indicators/keltner-channels.src.js",[f["parts/Globals.js"],f["mixins/multipe-lines.js"]],function(d,f){var n=d.seriesTypes.sma,m=d.seriesTypes.ema,g=d.seriesTypes.atr,e=d.merge,b=d.correctFloat;d.seriesType("keltnerchannels","sma",{params:{period:20,periodATR:10,multiplierATR:2},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},
topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e\x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eUpper Channel: {point.top}\x3cbr/\x3eEMA({series.options.params.period}): {point.middle}\x3cbr/\x3eLower Channel: {point.bottom}\x3cbr/\x3e'},marker:{enabled:!1},dataGrouping:{approximation:"averages"},lineWidth:1},e(f,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Keltner Channels",nameComponents:["period",
"periodATR","multiplierATR"],linesApiNames:["topLine","bottomLine"],requiredIndicators:["ema","atr"],init:function(){n.prototype.init.apply(this,arguments);this.options=e({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(a,c){var e=c.period,h=c.periodATR,d=c.multiplierATR,p=a.yData,p=p?p.length:0,l=[],k,f,n;c=m.prototype.getValues(a,{period:e,index:c.index});var q=g.prototype.getValues(a,{period:h}),B=[],v=[],z;if(p<e)return!1;for(z=
e;z<=p;z++)k=c.values[z-e],f=q.values[z-h],n=k[0],a=b(k[1]+d*f[1]),f=b(k[1]-d*f[1]),k=k[1],l.push([n,a,k,f]),B.push(n),v.push([a,k,f]);return{values:l,xData:B,yData:v}}}))});t(f,"indicators/macd.src.js",[f["parts/Globals.js"]],function(d){var f=d.seriesType,q=d.merge,m=d.defined,g=d.seriesTypes.sma,e=d.seriesTypes.ema,b=d.correctFloat;f("macd","sma",{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,
lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eValue: {point.MACD}\x3cbr/\x3eSignal: {point.signal}\x3cbr/\x3eHistogram: {point.y}\x3cbr/\x3e'},dataGrouping:{approximation:"averages"},minPointLength:0},{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y","signal","MACD"],
parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:d.noop,getColumnMetrics:d.seriesTypes.column.prototype.getColumnMetrics,crispCol:d.seriesTypes.column.prototype.crispCol,init:function(){g.prototype.init.apply(this,arguments);this.options&&(this.options=q({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones={zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),
startIndex:this.macdZones.zones.length},this.resetZones=!0)},toYData:function(a){return[a.y,a.signal,a.MACD]},translate:function(){var a=this,c=["plotSignal","plotMACD"];d.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(b){[b.signal,b.MACD].forEach(function(e,g){null!==e&&(b[c[g]]=a.yAxis.toPixels(e,!0))})})},destroy:function(){this.graph=null;this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();g.prototype.destroy.apply(this,
arguments)},drawPoints:d.seriesTypes.column.prototype.drawPoints,drawGraph:function(){for(var a=this,c=a.points,b=c.length,e=a.options,d=a.zones,p={options:{gapSize:e.gapSize}},l=[[],[]],k;b--;)k=c[b],m(k.plotMACD)&&l[0].push({plotX:k.plotX,plotY:k.plotMACD,isNull:!m(k.plotMACD)}),m(k.plotSignal)&&l[1].push({plotX:k.plotX,plotY:k.plotSignal,isNull:!m(k.plotMACD)});["macd","signal"].forEach(function(c,b){a.points=l[b];a.options=q(e[c+"Line"].styles,p);a.graph=a["graph"+c];a.currentLineZone=c+"Zones";
a.zones=a[a.currentLineZone].zones;g.prototype.drawGraph.call(a);a["graph"+c]=a.graph});a.points=c;a.options=e;a.zones=d;a.currentLineZone=null},getZonesGraphs:function(a){var c=g.prototype.getZonesGraphs.call(this,a),b=c;this.currentLineZone&&(b=c.splice(this[this.currentLineZone].startIndex+1),b.length?b.splice(0,0,a[0]):b=[a[0]]);return b},applyZones:function(){var a=this.zones;this.zones=this.signalZones.zones;g.prototype.applyZones.call(this);this.options.macdLine.zones.length&&this.graphmacd.hide();
this.zones=a},getValues:function(a,c){var g=0,h=[],d=[],p=[],l,k;if(a.xData.length<c.longPeriod+c.signalPeriod)return!1;l=e.prototype.getValues(a,{period:c.shortPeriod});k=e.prototype.getValues(a,{period:c.longPeriod});l=l.values;k=k.values;for(a=1;a<=l.length;a++)m(k[a-1])&&m(k[a-1][1])&&m(l[a+c.shortPeriod+1])&&m(l[a+c.shortPeriod+1][0])&&h.push([l[a+c.shortPeriod+1][0],0,null,l[a+c.shortPeriod+1][1]-k[a-1][1]]);for(a=0;a<h.length;a++)d.push(h[a][0]),p.push([0,null,h[a][3]]);c=e.prototype.getValues({xData:d,
yData:p},{period:c.signalPeriod,index:2});c=c.values;for(a=0;a<h.length;a++)h[a][0]>=c[0][0]&&(h[a][2]=c[g][1],p[a]=[0,c[g][1],h[a][3]],null===h[a][3]?(h[a][1]=0,p[a][0]=0):(h[a][1]=b(h[a][3]-c[g][1]),p[a][0]=b(h[a][3]-c[g][1])),g++);return{values:h,xData:d,yData:p}}})});t(f,"indicators/mfi.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){function n(e){return e.reduce(function(b,a){return b+a})}function m(e){return(e[1]+e[2]+e[3])/3}var g=f.isArray;d.seriesType("mfi","sma",{params:{period:14,
volumeSeriesID:"volume",decimals:4}},{nameBase:"Money Flow Index",getValues:function(e,b){var a=b.period,c=e.xData,r=e.yData,h=r?r.length:0,f=b.decimals,p=1,l=e.chart.get(b.volumeSeriesID),k=l&&l.yData,u=[],q=[],y=[],B=[],v=[];if(!l)return d.error("Series "+b.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,e.chart);if(c.length<=a||!g(r[0])||4!==r[0].length||!k)return!1;for(e=m(r[p]);p<a+1;)b=e,e=m(r[p]),b=e>=b,l=e*k[p],B.push(b?l:0),v.push(b?0:l),p++;for(a=p-1;a<h;a++)a>p-1&&(B.shift(),v.shift(),
b=e,e=m(r[a]),b=e>b,l=e*k[a],B.push(b?l:0),v.push(b?0:l)),b=n(v),l=n(B),b=l/b,b=parseFloat((100-100/(1+b)).toFixed(f)),u.push([c[a],b]),q.push(c[a]),y.push(b);return{values:u,xData:q,yData:y}}})});t(f,"indicators/momentum.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){function n(g,e,b,a,c){b=b[a-1][3]-b[a-c-1][3];e=e[a-1];g.shift();return[e,b]}var m=f.isArray;d=d.seriesType;d("momentum","sma",{params:{period:14}},{nameBase:"Momentum",getValues:function(g,e){e=e.period;var b=
g.xData,a=(g=g.yData)?g.length:0,c=b[0],d=[],h=[],f=[],p,l;if(b.length<=e||!m(g[0]))return!1;p=[[c,g[0][3]]];for(c=e+1;c<a;c++)l=n(p,b,g,c,e,void 0),d.push(l),h.push(l[0]),f.push(l[1]);l=n(p,b,g,c,e,void 0);d.push(l);h.push(l[0]);f.push(l[1]);return{values:d,xData:h,yData:f}}})});t(f,"indicators/natr.src.js",[f["parts/Globals.js"]],function(d){var f=d.seriesTypes.atr;d.seriesType("natr","sma",{tooltip:{valueSuffix:"%"}},{requiredIndicators:["atr"],getValues:function(d,m){for(var g=f.prototype.getValues.apply(this,
arguments),e=g.values.length,b=m.period-1,a=d.yData,c=0;c<e;c++)g.yData[c]=g.values[c][1]/a[b][3]*100,g.values[c][1]=g.yData[c],b++;return g}})});t(f,"indicators/pivot-points.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){function n(b,a){var c=b.series.pointArrayMap,g=c.length;for(e.prototype.pointClass.prototype[a].call(b);g--;)a="dataLabel"+c[g],b[a]&&b[a].element&&b[a].destroy(),b[a]=null}var m=f.isArray,g=d.defined,e=d.seriesTypes.sma;d.seriesType("pivotpoints","sma",{params:{period:28,
algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}},{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),pointValKey:"P",toYData:function(b){return[b.P]},translate:function(){var b=this;e.prototype.translate.apply(b);b.points.forEach(function(a){b.pointArrayMap.forEach(function(c){g(a[c])&&(a["plot"+c]=b.yAxis.toPixels(a[c],!0))})});b.plotEndPoint=b.xAxis.toPixels(b.endPoint,
!0)},getGraphPath:function(b){for(var a=this,c=b.length,d=[[],[],[],[],[],[],[],[],[]],h=[],f=a.plotEndPoint,p=a.pointArrayMap.length,l,k,m;c--;){k=b[c];for(m=0;m<p;m++)l=a.pointArrayMap[m],g(k[l])&&d[m].push({plotX:k.plotX,plotY:k["plot"+l],isNull:!1},{plotX:f,plotY:k["plot"+l],isNull:!1},{plotX:f,plotY:null,isNull:!0});f=k.plotX}d.forEach(function(c){h=h.concat(e.prototype.getGraphPath.call(a,c))});return h},drawDataLabels:function(){var b=this,a=b.pointArrayMap,c,g,h,d;b.options.dataLabels.enabled&&
(g=b.points.length,a.concat([!1]).forEach(function(r,l){for(d=g;d--;)h=b.points[d],r?(h.y=h[r],h.pivotLine=r,h.plotY=h["plot"+r],c=h["dataLabel"+r],l&&(h["dataLabel"+a[l-1]]=h.dataLabel),h.dataLabels||(h.dataLabels=[]),h.dataLabels[0]=h.dataLabel=c=c&&c.element?c:null):h["dataLabel"+a[l-1]]=h.dataLabel;e.prototype.drawDataLabels.apply(b,arguments)}))},getValues:function(b,a){var c=a.period,e=b.xData,h=(b=b.yData)?b.length:0;a=this[a.algorithm+"Placement"];var g=[],d,l=[],k=[],f,n,q,B;if(e.length<
c||!m(b[0])||4!==b[0].length)return!1;for(B=c+1;B<=h+c;B+=c)n=e.slice(B-c-1,B),q=b.slice(B-c-1,B),f=n.length,d=n[f-1],q=this.getPivotAndHLC(q),q=a(q),q=g.push([d].concat(q)),l.push(d),k.push(g[q-1].slice(1));this.endPoint=n[0]+(d-n[0])/f*c;return{values:g,xData:l,yData:k}},getPivotAndHLC:function(b){var a=-Infinity,c=Infinity,e=b[b.length-1][3];b.forEach(function(b){a=Math.max(a,b[1]);c=Math.min(c,b[2])});return[(a+c+e)/3,a,c,e]},standardPlacement:function(b){var a=b[1]-b[2];return[null,null,b[0]+
a,2*b[0]-b[2],b[0],2*b[0]-b[1],b[0]-a,null,null]},camarillaPlacement:function(b){var a=b[1]-b[2];return[b[3]+1.5*a,b[3]+1.25*a,b[3]+1.1666*a,b[3]+1.0833*a,b[0],b[3]-1.0833*a,b[3]-1.1666*a,b[3]-1.25*a,b[3]-1.5*a]},fibonacciPlacement:function(b){var a=b[1]-b[2];return[null,b[0]+a,b[0]+.618*a,b[0]+.382*a,b[0],b[0]-.382*a,b[0]-.618*a,b[0]-a,null]}},{destroyElements:function(){n(this,"destroyElements")},destroy:function(){n(this,"destroyElements")}})});t(f,"indicators/ppo.src.js",[f["parts/Globals.js"],
f["mixins/indicator-required.js"]],function(d,f){var n=d.seriesTypes.ema,m=d.error,g=d.correctFloat;d.seriesType("ppo","ema",{params:{periods:[12,26]}},{nameBase:"PPO",nameComponents:["periods"],init:function(){var e=arguments,b=this;f.isParentLoaded(n,"ema",b.type,function(a){a.prototype.init.apply(b,e)})},getValues:function(e,b){var a=b.periods,c=b.index;b=[];var d=[],h=[],f,p;if(2!==a.length||a[1]<=a[0])return m('Error: "PPO requires two periods. Notice, first period should be lower than the second one."'),
!1;f=n.prototype.getValues.call(this,e,{index:c,period:a[0]});e=n.prototype.getValues.call(this,e,{index:c,period:a[1]});if(!f||!e)return!1;a=a[1]-a[0];for(p=0;p<e.yData.length;p++)c=g((f.yData[p+a]-e.yData[p])/e.yData[p]*100),b.push([e.xData[p],c]),d.push(e.xData[p]),h.push(c);return{values:b,xData:d,yData:h}}})});t(f,"mixins/reduce-array.js",[f["parts/Globals.js"]],function(d){var f=d.reduce;return{minInArray:function(d,m){return f(d,function(d,e){return Math.min(d,e[m])},Number.MAX_VALUE)},maxInArray:function(d,
m){return f(d,function(d,e){return Math.max(d,e[m])},-Number.MAX_VALUE)},getArrayExtremes:function(d,m,g){return f(d,function(e,b){return[Math.min(e[0],b[m]),Math.max(e[1],b[g])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});t(f,"indicators/price-channel.src.js",[f["parts/Globals.js"],f["mixins/reduce-array.js"],f["mixins/multipe-lines.js"]],function(d,f,q){var m=f.getArrayExtremes;f=d.merge;d.seriesType("pc","sma",{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:"#90ed7d",lineWidth:1}},bottomLine:{styles:{lineColor:"#f45b5b",
lineWidth:1}},dataGrouping:{approximation:"averages"}},f(q,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],getValues:function(d,e){e=e.period;var b=d.xData,a=(d=d.yData)?d.length:0,c=[],g,h,f,p,l=[],k=[],u;if(a<e)return!1;for(u=e;u<=a;u++)p=b[u-1],h=d.slice(u-e,u),g=m(h,2,1),h=g[1],f=g[0],g=(h+f)/2,c.push([p,h,g,f]),l.push(p),k.push([h,g,f]);return{values:c,xData:l,yData:k}}}))});t(f,"indicators/price-envelopes.src.js",
[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){var n=f.isArray,m=d.merge,g=d.seriesTypes.sma;d.seriesType("priceenvelopes","sma",{marker:{enabled:!1},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e\x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eTop: {point.top}\x3cbr/\x3eMiddle: {point.middle}\x3cbr/\x3eBottom: {point.bottom}\x3cbr/\x3e'},params:{period:20,topBand:.1,bottomBand:.1},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1}},
dataGrouping:{approximation:"averages"}},{nameComponents:["period","topBand","bottomBand"],nameBase:"Price envelopes",pointArrayMap:["top","middle","bottom"],parallelArrays:["x","y","top","bottom"],pointValKey:"middle",init:function(){g.prototype.init.apply(this,arguments);this.options=m({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},toYData:function(e){return[e.top,e.middle,e.bottom]},translate:function(){var e=this,b=["plotTop","plotMiddle","plotBottom"];
g.prototype.translate.apply(e);e.points.forEach(function(a){[a.top,a.middle,a.bottom].forEach(function(c,d){null!==c&&(a[b[d]]=e.yAxis.toPixels(c,!0))})})},drawGraph:function(){for(var e=this,b=e.points,a=b.length,c=e.options,d=e.graph,h={options:{gapSize:c.gapSize}},f=[[],[]],p;a--;)p=b[a],f[0].push({plotX:p.plotX,plotY:p.plotTop,isNull:p.isNull}),f[1].push({plotX:p.plotX,plotY:p.plotBottom,isNull:p.isNull});["topLine","bottomLine"].forEach(function(a,b){e.points=f[b];e.options=m(c[a].styles,h);
e.graph=e["graph"+a];g.prototype.drawGraph.call(e);e["graph"+a]=e.graph});e.points=b;e.options=c;e.graph=d;g.prototype.drawGraph.call(e)},getValues:function(e,b){var a=b.period,c=b.topBand,d=b.bottomBand,h=e.xData,f=(e=e.yData)?e.length:0,m=[],l,k,u,q,y=[],B=[],v;if(h.length<a||!n(e[0])||4!==e[0].length)return!1;for(v=a;v<=f;v++)q=h.slice(v-a,v),l=e.slice(v-a,v),l=g.prototype.getValues.call(this,{xData:q,yData:l},b),q=l.xData[0],l=l.yData[0],k=l*(1+c),u=l*(1-d),m.push([q,k,l,u]),y.push(q),B.push([k,
l,u]);return{values:m,xData:y,yData:B}}})});t(f,"indicators/psar.src.js",[f["parts/Globals.js"]],function(d){d.seriesType("psar","sma",{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}},{nameComponents:!1,getValues:function(d,f){var m=d.xData;d=d.yData;var g=d[0][1],e=f.maxAccelerationFactor,b=f.increment,a=f.initialAccelerationFactor,c=d[0][2],r=f.decimals,h=f.index,n=[],p=[],l=[],k=1,
u,q,y,B,v,z,x,w;if(h>=d.length)return!1;for(w=0;w<h;w++)g=Math.max(d[w][1],g),c=Math.min(d[w][2],parseFloat(c.toFixed(r)));u=d[w][1]>c?1:-1;f=f.initialAccelerationFactor;q=f*(g-c);n.push([m[h],c]);p.push(m[h]);l.push(parseFloat(c.toFixed(r)));for(w=h+1;w<d.length;w++)h=d[w-1][2],B=d[w-2][2],v=d[w-1][1],z=d[w-2][1],y=d[w][1],x=d[w][2],null!==B&&null!==z&&null!==h&&null!==v&&null!==y&&null!==x&&(c=u===k?1===u?c+q<Math.min(B,h)?c+q:Math.min(B,h):c+q>Math.max(z,v)?c+q:Math.max(z,v):g,h=1===u?y>g?y:g:
x<g?x:g,y=1===k&&x>c||-1===k&&y>c?1:-1,k=y,q=h,x=b,B=e,v=a,f=k===u?1===k&&q>g?f===B?B:parseFloat((f+x).toFixed(2)):-1===k&&q<g?f===B?B:parseFloat((f+x).toFixed(2)):f:v,g=h-c,q=f*g,n.push([m[w],parseFloat(c.toFixed(r))]),p.push(m[w]),l.push(parseFloat(c.toFixed(r))),k=u,u=y,g=h);return{values:n,xData:p,yData:l}}})});t(f,"indicators/roc.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){var n=f.isArray;d=d.seriesType;d("roc","sma",{params:{index:3,period:9}},{nameBase:"Rate of Change",
getValues:function(d,g){var e=g.period,b=d.xData,a=(d=d.yData)?d.length:0,c=[],f=[],h=[],m=-1,p;if(b.length<=e)return!1;n(d[0])&&(m=g.index);for(g=e;g<a;g++)p=0>m?(p=d[g-e])?(d[g]-p)/p*100:null:(p=d[g-e][m])?(d[g][m]-p)/p*100:null,p=[b[g],p],c.push(p),f.push(p[0]),h.push(p[1]);return{values:c,xData:f,yData:h}}})});t(f,"indicators/rsi.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){var n=f.isArray;d.seriesType("rsi","sma",{params:{period:14,decimals:4}},{getValues:function(d,
g){var e=g.period,b=d.xData,a=(d=d.yData)?d.length:0;g=g.decimals;var c=1,f=[],h=[],m=[],p=0,l=0,k,u,q;if(b.length<e||!n(d[0])||4!==d[0].length)return!1;for(;c<e;)k=parseFloat((d[c][3]-d[c-1][3]).toFixed(g)),0<k?p+=k:l+=Math.abs(k),c++;u=parseFloat((p/(e-1)).toFixed(g));for(q=parseFloat((l/(e-1)).toFixed(g));c<a;c++)k=parseFloat((d[c][3]-d[c-1][3]).toFixed(g)),0<k?(p=k,l=0):(p=0,l=Math.abs(k)),u=parseFloat(((u*(e-1)+p)/e).toFixed(g)),q=parseFloat(((q*(e-1)+l)/e).toFixed(g)),p=0===q?100:0===u?0:parseFloat((100-
100/(1+u/q)).toFixed(g)),f.push([b[c],p]),h.push(b[c]),m.push(p);return{values:f,xData:h,yData:m}}})});t(f,"indicators/stochastic.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["mixins/reduce-array.js"],f["mixins/multipe-lines.js"]],function(d,f,q,m){var g=f.isArray,e=d.merge,b=d.seriesTypes.sma,a=q.getArrayExtremes;d.seriesType("stochastic","sma",{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e\x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3e%K: {point.y}\x3cbr/\x3e%D: {point.smoothed}\x3cbr/\x3e'},
smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},d.merge(m,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],init:function(){b.prototype.init.apply(this,arguments);this.options=e({smoothedLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(c,e){var d=e.periods[0];e=e.periods[1];var f=c.xData,r=(c=c.yData)?c.length:0,l=[],
k=[],m=[],n,q,B=null,v,z;if(r<d||!g(c[0])||4!==c[0].length)return!1;for(z=d-1;z<r;z++)n=c.slice(z-d+1,z+1),v=a(n,2,1),q=v[0],n=c[z][3]-q,q=v[1]-q,n=n/q*100,k.push(f[z]),m.push([n,null]),z>=d-1+(e-1)&&(B=b.prototype.getValues.call(this,{xData:k.slice(-e),yData:m.slice(-e)},{period:e}),B=B.yData[0]),l.push([f[z],n,B]),m[m.length-1][1]=B;return{values:l,xData:k,yData:m}}}))});t(f,"indicators/supertrend.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){function n(a,b,e){return{index:b,
close:a.yData[b][e],x:a.xData[b]}}var m=f.isArray,g=d.seriesTypes.atr,e=d.seriesTypes.sma,b=d.merge,a=d.correctFloat;d.seriesType("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:"#06B535",fallingTrendColor:"#F21313",changeTrendLine:{styles:{lineWidth:1,lineColor:"#333333",dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){var a;e.prototype.init.apply(this,arguments);a=this.options;a.cropThreshold=this.linkedParent.options.cropThreshold-
(a.params.period-1)},drawGraph:function(){for(var a=this,g=a.options,h=a.linkedParent,f=h?h.points:[],m=a.points,l=a.graph,k=m.length,u=f.length-k,u=0<u?u:0,q={options:{gapSize:g.gapSize}},y={top:[],bottom:[],intersect:[]},B={top:{styles:{lineWidth:g.lineWidth,lineColor:g.fallingTrendColor,dashStyle:g.dashStyle}},bottom:{styles:{lineWidth:g.lineWidth,lineColor:g.risingTrendColor,dashStyle:g.dashStyle}},intersect:g.changeTrendLine},v,z,x,w,A,t,C,G;k--;)v=m[k],z=m[k-1],x=f[k-1+u],w=f[k-2+u],A=f[k+u],
t=f[k+u+1],C=v.options.color,G={x:v.x,plotX:v.plotX,plotY:v.plotY,isNull:!1},!w&&x&&h.yData[x.index-1]&&(w=n(h,x.index-1,3)),!t&&A&&h.yData[A.index+1]&&(t=n(h,A.index+1,3)),!x&&w&&h.yData[w.index+1]?x=n(h,w.index+1,3):!x&&A&&h.yData[A.index-1]&&(x=n(h,A.index-1,3)),v&&x&&A&&w&&v.x!==x.x&&(v.x===A.x?(w=x,x=A):v.x===w.x?(x=w,w={close:h.yData[x.index-1][3],x:h.xData[x.index-1]}):t&&v.x===t.x&&(x=t,w=A)),z&&w&&x?(A={x:z.x,plotX:z.plotX,plotY:z.plotY,isNull:!1},v.y>=x.close&&z.y>=w.close?(v.color=C||g.fallingTrendColor,
y.top.push(G)):v.y<x.close&&z.y<w.close?(v.color=C||g.risingTrendColor,y.bottom.push(G)):(y.intersect.push(G),y.intersect.push(A),y.intersect.push(b(A,{isNull:!0})),v.y>=x.close&&z.y<w.close?(v.color=C||g.fallingTrendColor,z.color=C||g.risingTrendColor,y.top.push(G),y.top.push(b(A,{isNull:!0}))):v.y<x.close&&z.y>=w.close&&(v.color=C||g.risingTrendColor,z.color=C||g.fallingTrendColor,y.bottom.push(G),y.bottom.push(b(A,{isNull:!0}))))):x&&(v.y>=x.close?(v.color=C||g.fallingTrendColor,y.top.push(G)):
(v.color=C||g.risingTrendColor,y.bottom.push(G)));d.objectEach(y,function(c,d){a.points=c;a.options=b(B[d].styles,q);a.graph=a["graph"+d+"Line"];e.prototype.drawGraph.call(a);a["graph"+d+"Line"]=a.graph});a.points=m;a.options=g;a.graph=l},getValues:function(c,b){var e=b.period;b=b.multiplier;var d=c.xData,f=c.yData,l=[],k=[],r=[],n=0===e?0:e-1,q,B=[],v=[],t,x,w,A,F,C,G;if(d.length<=e||!m(f[0])||4!==f[0].length||0>e)return!1;c=g.prototype.getValues.call(this,c,{period:e}).yData;for(G=0;G<c.length;G++){C=
f[n+G];F=f[n+G-1]||[];x=B[G-1];w=v[G-1];A=r[G-1];0===G&&(x=w=A=0);e=a((C[1]+C[2])/2+b*c[G]);q=a((C[1]+C[2])/2-b*c[G]);B[G]=e<x||F[3]>x?e:x;v[G]=q>w||F[3]<w?q:w;if(A===x&&C[3]<B[G]||A===w&&C[3]<v[G])t=B[G];else if(A===x&&C[3]>B[G]||A===w&&C[3]>v[G])t=v[G];l.push([d[n+G],t]);k.push(d[n+G]);r.push(t)}return{values:l,xData:k,yData:r}}})});t(f,"indicators/volume-by-price.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){var n=f.isArray,m=Math.abs;f=d.noop;var g=d.addEvent,e=d.correctFloat,
b=d.seriesType,a=d.seriesTypes.column.prototype;b("vbp","sma",{params:{ranges:12,volumeSeriesID:"volume"},zoneLines:{enabled:!0,styles:{color:"#0A9AC9",dashStyle:"LongDash",lineWidth:1}},volumeDivision:{enabled:!0,styles:{positiveColor:"rgba(144, 237, 125, 0.8)",negativeColor:"rgba(244, 91, 91, 0.8)"}},animationLimit:1E3,enableMouseTracking:!1,pointPadding:0,zIndex:-1,crisp:!0,dataGrouping:{enabled:!1},dataLabels:{allowOverlap:!0,enabled:!0,format:"P: {point.volumePos:.2f} | N: {point.volumeNeg:.2f}",
padding:0,style:{fontSize:"7px"},verticalAlign:"top"}},{nameBase:"Volume by Price",bindTo:{series:!1,eventName:"afterSetExtremes"},calculateOn:"render",markerAttribs:f,drawGraph:f,getColumnMetrics:a.getColumnMetrics,crispCol:a.crispCol,init:function(a){var c,b;d.seriesTypes.sma.prototype.init.apply(this,arguments);c=this.options.params;b=this.linkedParent;c=a.get(c.volumeSeriesID);this.addCustomEvents(b,c);return this},addCustomEvents:function(a,b){function c(){e.chart.redraw();e.setData([]);e.zoneStarts=
[];e.zoneLinesSVG&&(e.zoneLinesSVG.destroy(),delete e.zoneLinesSVG)}var e=this;e.dataEventsToUnbind.push(g(a,"remove",function(){c()}));b&&e.dataEventsToUnbind.push(g(b,"remove",function(){c()}));return e},animate:function(a){var c=this,b={};d.svg&&!a&&(b.translateX=c.yAxis.pos,c.group.animate(b,d.extend(d.animObject(c.options.animation),{step:function(a,b){c.group.attr({scaleX:Math.max(.001,b.pos)})}})),c.animate=null)},drawPoints:function(){this.options.volumeDivision.enabled&&(this.posNegVolume(!0,
!0),a.drawPoints.apply(this,arguments),this.posNegVolume(!1,!1));a.drawPoints.apply(this,arguments)},posNegVolume:function(a,b){var c=b?["positive","negative"]:["negative","positive"],e=this.options.volumeDivision,d=this.points.length,g=[],f=[],m=0,r,n,q,v;a?(this.posWidths=g,this.negWidths=f):(g=this.posWidths,f=this.negWidths);for(;m<d;m++)v=this.points[m],v[c[0]+"Graphic"]=v.graphic,v.graphic=v[c[1]+"Graphic"],a&&(r=v.shapeArgs.width,n=this.priceZones[m],(q=n.wholeVolumeData)?(g.push(r/q*n.positiveVolumeData),
f.push(r/q*n.negativeVolumeData)):(g.push(0),f.push(0))),v.color=b?e.styles.positiveColor:e.styles.negativeColor,v.shapeArgs.width=b?this.posWidths[m]:this.negWidths[m],v.shapeArgs.x=b?v.shapeArgs.x:this.posWidths[m]},translate:function(){var b=this,g=b.options,f=b.chart,n=b.yAxis,p=n.min,l=b.options.zoneLines,k=b.priceZones,u=0,q,y,t,v,z,x,w,A,F,C;a.translate.apply(b);q=b.points;q.length&&(w=.5>g.pointPadding?g.pointPadding:.1,g=b.volumeDataArray,y=d.arrayMax(g),t=f.plotWidth/2,A=f.plotTop,v=m(n.toPixels(p)-
n.toPixels(p+b.rangeStep)),z=m(n.toPixels(p)-n.toPixels(p+b.rangeStep)),w&&(p=m(v*(1-2*w)),u=m((v-p)/2),v=m(p)),q.forEach(function(a,c){F=a.barX=a.plotX=0;C=a.plotY=n.toPixels(k[c].start)-A-(n.reversed?v-z:v)-u;x=e(t*k[c].wholeVolumeData/y);a.pointWidth=x;a.shapeArgs=b.crispCol.apply(b,[F,C,x,v]);a.volumeNeg=k[c].negativeVolumeData;a.volumePos=k[c].positiveVolumeData;a.volumeAll=k[c].wholeVolumeData}),l.enabled&&b.drawZones(f,n,b.zoneStarts,l.styles))},getValues:function(a,b){var c=a.processedXData,
e=a.processedYData,g=this.chart,f=b.ranges,k=[],m=[],r=[],q;if(!a.chart)return d.error("Base series not found! In case it has been removed, add a new one.",!0,g);if(!(q=g.get(b.volumeSeriesID)))return d.error("Series "+b.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,g);if((b=n(e[0]))&&4!==e[0].length)return d.error("Type of "+a.name+" series is different than line, OHLC or candlestick.",!0,g);(this.priceZones=this.specifyZones(b,c,e,f,q)).forEach(function(a,b){k.push([a.x,a.end]);m.push(k[b][0]);
r.push(k[b][1])});return{values:k,xData:m,yData:r}},specifyZones:function(a,b,g,f,m){var c;if(a){c=g.length;for(var h=g[0][3],p=h,n=1,r;n<c;n++)r=g[n][3],r<h&&(h=r),r>p&&(p=r);c={min:h,max:p}}else c=!1;c=(h=c)?h.min:d.arrayMin(g);r=h?h.max:d.arrayMax(g);var h=this.zoneStarts=[],p=[],q=0,n=1,v;if(!c||!r)return this.points.length&&(this.setData([]),this.zoneStarts=[],this.zoneLinesSVG.destroy()),[];v=this.rangeStep=e(r-c)/f;for(h.push(c);q<f-1;q++)h.push(e(h[q]+v));h.push(r);for(f=h.length;n<f;n++)p.push({index:n-
1,x:b[0],start:h[n-1],end:h[n]});return this.volumePerZone(a,p,m,b,g)},volumePerZone:function(a,b,e,d,g){var c=this,f=e.processedXData,h=e.processedYData,p=b.length-1,n=g.length;e=h.length;var r,q,D,t,w;m(n-e)&&(d[0]!==f[0]&&h.unshift(0),d[n-1]!==f[e-1]&&h.push(0));c.volumeDataArray=[];b.forEach(function(b){b.wholeVolumeData=0;b.positiveVolumeData=0;for(w=b.negativeVolumeData=0;w<n;w++)D=q=!1,t=a?g[w][3]:g[w],r=w?a?g[w-1][3]:g[w-1]:t,t<=b.start&&0===b.index&&(q=!0),t>=b.end&&b.index===p&&(D=!0),(t>
b.start||q)&&(t<b.end||D)&&(b.wholeVolumeData+=h[w],r>t?b.negativeVolumeData+=h[w]:b.positiveVolumeData+=h[w]);c.volumeDataArray.push(b.wholeVolumeData)});return b},drawZones:function(a,b,e,d){var c=a.renderer,g=this.zoneLinesSVG,f=[],h=a.plotWidth,m=a.plotTop,n;e.forEach(function(c){n=b.toPixels(c)-m;f=f.concat(a.renderer.crispLine(["M",0,n,"L",h,n],d.lineWidth))});g?g.animate({d:f}):g=this.zoneLinesSVG=c.path(f).attr({"stroke-width":d.lineWidth,stroke:d.color,dashstyle:d.dashStyle,zIndex:this.group.zIndex+
.1}).add(this.group)}},{destroy:function(){this.negativeGraphic&&(this.negativeGraphic=this.negativeGraphic.destroy());return d.Point.prototype.destroy.apply(this,arguments)}})});t(f,"indicators/vwap.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){var n=f.isArray;f=d.seriesType;f("vwap","sma",{params:{period:30,volumeSeriesID:"volume"}},{getValues:function(f,g){var e=f.chart,b=f.xData;f=f.yData;var a=g.period,c=!0,m;if(!(m=e.get(g.volumeSeriesID)))return d.error("Series "+g.volumeSeriesID+
" not found! Check `volumeSeriesID`.",!0,e);n(f[0])||(c=!1);return this.calculateVWAPValues(c,b,f,m,a)},calculateVWAPValues:function(d,g,e,b,a){var c=b.yData,f=b.xData.length,h=g.length;b=[];var m=[],n=[],l=[],k=[],q,t,y,f=h<=f?h:f;for(y=h=0;h<f;h++)q=d?(e[h][1]+e[h][2]+e[h][3])/3:e[h],q*=c[h],q=y?b[h-1]+q:q,t=y?m[h-1]+c[h]:c[h],b.push(q),m.push(t),k.push([g[h],q/t]),n.push(k[h][0]),l.push(k[h][1]),y++,y===a&&(y=0);return{values:k,xData:n,yData:l}}})});t(f,"indicators/williams-r.src.js",[f["parts/Globals.js"],
f["parts/Utilities.js"],f["mixins/reduce-array.js"]],function(d,f,q){var m=f.isArray,g=q.getArrayExtremes;d.seriesType("williamsr","sma",{params:{period:14}},{nameBase:"Williams %R",getValues:function(e,b){b=b.period;var a=e.xData,c=(e=e.yData)?e.length:0,d=[],f=[],n=[],p,l,k,q;if(a.length<b||!m(e[0])||4!==e[0].length)return!1;for(q=b-1;q<c;q++)p=e.slice(q-b+1,q+1),l=g(p,2,1),p=l[0],l=l[1],k=e[q][3],p=(l-k)/(l-p)*-100,a[q]&&(d.push([a[q],p]),f.push(a[q]),n.push(p));return{values:d,xData:f,yData:n}}})});
t(f,"indicators/wma.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){function n(e,b){b*=(b+1)/2;return e.reduce(function(a,b,e){return[null,a[1]+b[1]*(e+1)]})[1]/b}function m(e,b,a,c){a=n(e,e.length);b=b[c-1];e.shift();return[b,a]}var g=f.isArray;d=d.seriesType;d("wma","sma",{params:{index:3,period:9}},{getValues:function(e,b){var a=b.period,c=e.xData,d=(e=e.yData)?e.length:0,f=1,n=c[0],p=e[0],l=[],k=[],q=[],t=-1;if(c.length<a)return!1;g(e[0])&&(t=b.index,p=e[0][t]);for(b=[[n,
p]];f!==a;)b.push([c[f],0>t?e[f]:e[f][t]]),f++;for(a=f;a<d;a++)f=m(b,c,e,a),l.push(f),k.push(f[0]),q.push(f[1]),b.push([c[a],0>t?e[a]:e[a][t]]);f=m(b,c,e,a);l.push(f);k.push(f[0]);q.push(f[1]);return{values:l,xData:k,yData:q}}})});t(f,"indicators/zigzag.src.js",[f["parts/Globals.js"]],function(d){d=d.seriesType;d("zigzag","sma",{params:{lowIndex:2,highIndex:1,deviation:1}},{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag",getValues:function(d,f){var m=f.lowIndex,g=f.highIndex,e=
f.deviation/100;f=1+e;var b=1-e,e=d.xData,a=d.yData;d=a?a.length:0;var c=[],n=[],h=[],q,p,l,k,u,t,y=!1,B=!1;if(1>=e.length||d&&(void 0===a[0][m]||void 0===a[0][g]))return!1;k=a[0][m];u=a[0][g];for(q=1;q<d;q++)a[q][m]<=u*b?(c.push([e[0],u]),l=[e[q],a[q][m]],y=t=!0):a[q][g]>=k*f&&(c.push([e[0],k]),l=[e[q],a[q][g]],t=!1,y=!0),y&&(n.push(c[0][0]),h.push(c[0][1]),p=q++,q=d);for(q=p;q<d;q++)t?(a[q][m]<=l[1]&&(l=[e[q],a[q][m]]),a[q][g]>=l[1]*f&&(B=g)):(a[q][g]>=l[1]&&(l=[e[q],a[q][g]]),a[q][m]<=l[1]*b&&
(B=m)),!1!==B&&(c.push(l),n.push(l[0]),h.push(l[1]),l=[e[q],a[q][B]],t=!t,B=!1);m=c.length;0!==m&&c[m-1][0]<e[d-1]&&(c.push(l),n.push(l[0]),h.push(l[1]));return{values:c,xData:n,yData:h}}})});t(f,"indicators/regressions.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,f){var n=f.isArray;d=d.seriesType;d("linearRegression","sma",{params:{xAxisUnit:void 0},tooltip:{valueDecimals:4}},{nameBase:"Linear Regression Indicator",getRegressionLineParameters:function(d,f){var e=this.options.params.index,
b=function(a,b){return n(a)?a[b]:a},a=d.reduce(function(a,b){return b+a},0),c=f.reduce(function(a,c){return b(c,e)+a},0),a=a/d.length,c=c/f.length,g,h,m=0,p=0,l;for(l=0;l<d.length;l++)g=d[l]-a,h=b(f[l],e)-c,m+=g*h,p+=Math.pow(g,2);d=p?m/p:0;return{slope:d,intercept:c-d*a}},getEndPointY:function(d,f){return d.slope*f+d.intercept},transformXData:function(d,f){var e=d[0];return d.map(function(b){return(b-e)/f})},findClosestDistance:function(d){var f,e,b;for(b=1;b<d.length-1;b++)f=d[b]-d[b-1],0<f&&(void 0===
e||f<e)&&(e=f);return e},getValues:function(d,f){var e=d.xData;d=d.yData;f=f.period;var b,a,c,g,h={xData:[],yData:[],values:[]},m,n=this.options.params.xAxisUnit||this.findClosestDistance(e);for(a=f-1;a<=e.length-1;a++)c=a-f+1,g=a+1,m=e[a],b=e.slice(c,g),c=d.slice(c,g),g=this.transformXData(b,n),b=this.getRegressionLineParameters(g,c),c=this.getEndPointY(b,g[g.length-1]),h.values.push({regressionLineParameters:b,x:m,y:c}),h.xData.push(m),h.yData.push(c);return h}});d("linearRegressionSlope","linearRegression",
{},{nameBase:"Linear Regression Slope Indicator",getEndPointY:function(d){return d.slope}});d("linearRegressionIntercept","linearRegression",{},{nameBase:"Linear Regression Intercept Indicator",getEndPointY:function(d){return d.intercept}});d("linearRegressionAngle","linearRegression",{tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e{series.name}: \x3cb\x3e{point.y}\u00b0\x3c/b\x3e\x3cbr/\x3e'}},{nameBase:"Linear Regression Angle Indicator",slopeToAngle:function(d){return 180/
Math.PI*Math.atan(d)},getEndPointY:function(d){return this.slopeToAngle(d.slope)}})});t(f,"indicators/acceleration-bands.src.js",[f["parts/Globals.js"],f["mixins/multipe-lines.js"]],function(d,f){var n=d.seriesTypes.sma,m=d.merge,g=d.correctFloat;d.seriesType("abands","sma",{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},m(f,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Acceleration Bands",
nameComponents:["period","factor"],linesApiNames:["topLine","bottomLine"],getValues:function(d,b){var a=b.period,c=b.factor;b=b.index;var e=d.xData,f=(d=d.yData)?d.length:0,m=[],p=[],l=[],k,q,t,y,B=[],v=[],z;if(f<a)return!1;for(z=0;z<=f;z++)z<f&&(y=d[z][2],t=d[z][1],q=c,y=g(t-y)/(g(t+y)/2)*1E3*q,m.push(d[z][1]*g(1+2*y)),p.push(d[z][2]*g(1-2*y))),z>=a&&(y=e.slice(z-a,z),k=d.slice(z-a,z),q=n.prototype.getValues.call(this,{xData:y,yData:m.slice(z-a,z)},{period:a}),t=n.prototype.getValues.call(this,{xData:y,
yData:p.slice(z-a,z)},{period:a}),k=n.prototype.getValues.call(this,{xData:y,yData:k},{period:a,index:b}),y=k.xData[0],q=q.yData[0],t=t.yData[0],k=k.yData[0],l.push([y,q,k,t]),B.push(y),v.push([q,k,t]));return{values:l,xData:B,yData:v}}}))});t(f,"masters/indicators/indicators-all.src.js",[],function(){})});
//# sourceMappingURL=indicators-all.js.map