/*
 Highstock JS v7.1.2-modified (2019-07-03)

 Indicator series type for Highstock

 (c) 2010-2019 Pawel Fus, Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators",["highcharts","highcharts/modules/stock"],function(c){a(c);a.Highcharts=c;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function c(a,e,r,p){a.hasOwnProperty(e)||(a[e]=p.apply(null,r))}a=a?a._modules:{};c(a,"mixins/indicator-required.js",[a["parts/Globals.js"]],function(a){var l=a.error;return{isParentLoaded:function(a,
p,c,e,h){if(a)return e?e(a):!0;l(h||this.generateMessage(c,p));return!1},generateMessage:function(a,l){return'Error: "'+a+'" indicator type requires "'+l+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});c(a,"indicators/indicators.src.js",[a["parts/Globals.js"],a["parts/Utilities.js"],a["mixins/indicator-required.js"]],function(a,e,c){var p=e.isArray,l=a.pick,t=a.error,h=a.Series,m=a.addEvent;e=a.seriesType;var u=a.seriesTypes,n=a.seriesTypes.ohlc.prototype,
r=c.generateMessage;m(a.Series,"init",function(f){f=f.options;f.useOhlcData&&"highcharts-navigator-series"!==f.id&&a.extend(this,{pointValKey:n.pointValKey,keys:n.keys,pointArrayMap:n.pointArrayMap,toYData:n.toYData})});m(h,"afterSetOptions",function(a){a=a.options;var f=a.dataGrouping;f&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(f.approximation="ohlc")});e("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},{processData:function(){var a=
this.options.compareToMain,d=this.linkedParent;h.prototype.processData.apply(this,arguments);d&&d.compareValue&&a&&(this.compareValue=d.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(f){u[f]?u[f].prototype.requireIndicators():(a.allLoaded=!1,a.needed=f)});return a},init:function(f,
d){function c(){var f=b.points||[],d=(b.xData||[]).length,c=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},e=[],k=!0,g,q;if(d&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){b.xAxis&&(g=b.xAxis.min,q=b.xAxis.max);d=b.cropData(c.xData,c.yData,g,q);for(g=0;g<d.xData.length;g++)e.push([d.xData[g]].concat(a.splat(d.yData[g])));d=c.xData.indexOf(b.xData[0]);g=c.xData.indexOf(b.xData[b.xData.length-1]);-1===d&&g===c.xData.length-2&&e[0][0]===f[0].x&&e.shift();b.updateData(e)}else c.xData.length!==
d-1&&c.xData.length!==d+1&&(k=!1,b.updateData(c.values));k&&(b.xData=c.xData,b.yData=c.yData,b.options.data=c.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,e=b.requireIndicators();if(!e.allLoaded)return t(r(b.type,e.needed));h.prototype.init.call(b,f,d);f.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return t("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",!1,f);b.dataEventsToUnbind.push(m(b.bindTo.series?b.linkedParent:
b.linkedParent.xAxis,b.bindTo.eventName,c));if("init"===b.calculateOn)c();else var q=m(b.chart,b.calculateOn,function(){c();q()});return b},getName:function(){var a=this.name,d=[];a||((this.nameComponents||[]).forEach(function(a,b){d.push(this.options.params[a]+l(this.nameSuffixes[b],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return a},getValues:function(a,d){var c=d.period,b=a.xData;a=a.yData;var f=a.length,e=0,h=0,l=[],m=[],n=[],k=-1,g;
if(b.length<c)return!1;for(p(a[0])&&(k=d.index?d.index:0);e<c-1;)h+=0>k?a[e]:a[e][k],e++;for(d=e;d<f;d++)h+=0>k?a[d]:a[d][k],g=[b[d],h/c],l.push(g),m.push(g[0]),n.push(g[1]),h-=0>k?a[d-e]:a[d-e][k];return{values:l,xData:m,yData:n}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});h.prototype.destroy.call(this)}})});c(a,"masters/indicators/indicators.src.js",[],function(){})});
//# sourceMappingURL=indicators.js.map