/*
 Highstock JS v7.1.2-modified (2019-07-03)

 Indicator series type for Highstock

 (c) 2010-2019 Pawe Fus

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/indicators/pivot-points",["highcharts","highcharts/modules/stock"],function(d){c(d);c.Highcharts=d;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function d(c,d,m,t){c.hasOwnProperty(d)||(c[d]=t.apply(null,m))}c=c?c._modules:{};d(c,"indicators/pivot-points.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,
d){function m(a,b){var f=a.series.pointArrayMap,c=f.length;for(r.prototype.pointClass.prototype[b].call(a);c--;)b="dataLabel"+f[c],a[b]&&a[b].element&&a[b].destroy(),a[b]=null}var t=d.isArray,u=c.defined,r=c.seriesTypes.sma;c.seriesType("pivotpoints","sma",{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}},{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),
pointValKey:"P",toYData:function(a){return[a.P]},translate:function(){var a=this;r.prototype.translate.apply(a);a.points.forEach(function(b){a.pointArrayMap.forEach(function(f){u(b[f])&&(b["plot"+f]=a.yAxis.toPixels(b[f],!0))})});a.plotEndPoint=a.xAxis.toPixels(a.endPoint,!0)},getGraphPath:function(a){for(var b=this,f=a.length,c=[[],[],[],[],[],[],[],[],[]],e=[],g=b.plotEndPoint,p=b.pointArrayMap.length,h,d,k;f--;){d=a[f];for(k=0;k<p;k++)h=b.pointArrayMap[k],u(d[h])&&c[k].push({plotX:d.plotX,plotY:d["plot"+
h],isNull:!1},{plotX:g,plotY:d["plot"+h],isNull:!1},{plotX:g,plotY:null,isNull:!0});g=d.plotX}c.forEach(function(a){e=e.concat(r.prototype.getGraphPath.call(b,a))});return e},drawDataLabels:function(){var a=this,b=a.pointArrayMap,c,d,e,g;a.options.dataLabels.enabled&&(d=a.points.length,b.concat([!1]).forEach(function(f,h){for(g=d;g--;)e=a.points[g],f?(e.y=e[f],e.pivotLine=f,e.plotY=e["plot"+f],c=e["dataLabel"+f],h&&(e["dataLabel"+b[h-1]]=e.dataLabel),e.dataLabels||(e.dataLabels=[]),e.dataLabels[0]=
e.dataLabel=c=c&&c.element?c:null):e["dataLabel"+b[h-1]]=e.dataLabel;r.prototype.drawDataLabels.apply(a,arguments)}))},getValues:function(a,b){var c=b.period,d=a.xData,e=(a=a.yData)?a.length:0;b=this[b.algorithm+"Placement"];var g=[],p,h=[],m=[],k,q,l,n;if(d.length<c||!t(a[0])||4!==a[0].length)return!1;for(n=c+1;n<=e+c;n+=c)q=d.slice(n-c-1,n),l=a.slice(n-c-1,n),k=q.length,p=q[k-1],l=this.getPivotAndHLC(l),l=b(l),l=g.push([p].concat(l)),h.push(p),m.push(g[l-1].slice(1));this.endPoint=q[0]+(p-q[0])/
k*c;return{values:g,xData:h,yData:m}},getPivotAndHLC:function(a){var b=-Infinity,c=Infinity,d=a[a.length-1][3];a.forEach(function(a){b=Math.max(b,a[1]);c=Math.min(c,a[2])});return[(b+c+d)/3,b,c,d]},standardPlacement:function(a){var b=a[1]-a[2];return[null,null,a[0]+b,2*a[0]-a[2],a[0],2*a[0]-a[1],a[0]-b,null,null]},camarillaPlacement:function(a){var b=a[1]-a[2];return[a[3]+1.5*b,a[3]+1.25*b,a[3]+1.1666*b,a[3]+1.0833*b,a[0],a[3]-1.0833*b,a[3]-1.1666*b,a[3]-1.25*b,a[3]-1.5*b]},fibonacciPlacement:function(a){var b=
a[1]-a[2];return[null,a[0]+b,a[0]+.618*b,a[0]+.382*b,a[0],a[0]-.382*b,a[0]-.618*b,a[0]-b,null]}},{destroyElements:function(){m(this,"destroyElements")},destroy:function(){m(this,"destroyElements")}})});d(c,"masters/indicators/pivot-points.src.js",[],function(){})});
//# sourceMappingURL=pivot-points.js.map