/*
 Highstock JS v7.1.2-modified (2019-07-03)

 Indicator series type for Highstock

 (c) 2010-2019 Wojciech Chmiel

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/indicators/supertrend",["highcharts","highcharts/modules/stock"],function(k){b(k);b.Highcharts=k;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function k(b,k,u,z){b.hasOwnProperty(k)||(b[k]=z.apply(null,u))}b=b?b._modules:{};k(b,"indicators/supertrend.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,k){function u(e,
d,b){return{index:d,close:e.yData[d][b],x:e.xData[d]}}var z=k.isArray,C=b.seriesTypes.atr,A=b.seriesTypes.sma,y=b.merge,B=b.correctFloat;b.seriesType("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:"#06B535",fallingTrendColor:"#F21313",changeTrendLine:{styles:{lineWidth:1,lineColor:"#333333",dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){var e;A.prototype.init.apply(this,arguments);e=this.options;
e.cropThreshold=this.linkedParent.options.cropThreshold-(e.params.period-1)},drawGraph:function(){for(var e=this,d=e.options,p=e.linkedParent,k=p?p.points:[],v=e.points,D=e.graph,q=v.length,r=k.length-q,r=0<r?r:0,x={options:{gapSize:d.gapSize}},m={top:[],bottom:[],intersect:[]},w={top:{styles:{lineWidth:d.lineWidth,lineColor:d.fallingTrendColor,dashStyle:d.dashStyle}},bottom:{styles:{lineWidth:d.lineWidth,lineColor:d.risingTrendColor,dashStyle:d.dashStyle}},intersect:d.changeTrendLine},f,n,c,g,h,
t,l,a;q--;)f=v[q],n=v[q-1],c=k[q-1+r],g=k[q-2+r],h=k[q+r],t=k[q+r+1],l=f.options.color,a={x:f.x,plotX:f.plotX,plotY:f.plotY,isNull:!1},!g&&c&&p.yData[c.index-1]&&(g=u(p,c.index-1,3)),!t&&h&&p.yData[h.index+1]&&(t=u(p,h.index+1,3)),!c&&g&&p.yData[g.index+1]?c=u(p,g.index+1,3):!c&&h&&p.yData[h.index-1]&&(c=u(p,h.index-1,3)),f&&c&&h&&g&&f.x!==c.x&&(f.x===h.x?(g=c,c=h):f.x===g.x?(c=g,g={close:p.yData[c.index-1][3],x:p.xData[c.index-1]}):t&&f.x===t.x&&(c=t,g=h)),n&&g&&c?(h={x:n.x,plotX:n.plotX,plotY:n.plotY,
isNull:!1},f.y>=c.close&&n.y>=g.close?(f.color=l||d.fallingTrendColor,m.top.push(a)):f.y<c.close&&n.y<g.close?(f.color=l||d.risingTrendColor,m.bottom.push(a)):(m.intersect.push(a),m.intersect.push(h),m.intersect.push(y(h,{isNull:!0})),f.y>=c.close&&n.y<g.close?(f.color=l||d.fallingTrendColor,n.color=l||d.risingTrendColor,m.top.push(a),m.top.push(y(h,{isNull:!0}))):f.y<c.close&&n.y>=g.close&&(f.color=l||d.risingTrendColor,n.color=l||d.fallingTrendColor,m.bottom.push(a),m.bottom.push(y(h,{isNull:!0}))))):
c&&(f.y>=c.close?(f.color=l||d.fallingTrendColor,m.top.push(a)):(f.color=l||d.risingTrendColor,m.bottom.push(a)));b.objectEach(m,function(c,a){e.points=c;e.options=y(w[a].styles,x);e.graph=e["graph"+a+"Line"];A.prototype.drawGraph.call(e);e["graph"+a+"Line"]=e.graph});e.points=v;e.options=d;e.graph=D},getValues:function(e,b){var d=b.period;b=b.multiplier;var k=e.xData,v=e.yData,u=[],q=[],r=[],x=0===d?0:d-1,m,w=[],f=[],n,c,g,h,t,l,a;if(k.length<=d||!z(v[0])||4!==v[0].length||0>d)return!1;e=C.prototype.getValues.call(this,
e,{period:d}).yData;for(a=0;a<e.length;a++){l=v[x+a];t=v[x+a-1]||[];c=w[a-1];g=f[a-1];h=r[a-1];0===a&&(c=g=h=0);d=B((l[1]+l[2])/2+b*e[a]);m=B((l[1]+l[2])/2-b*e[a]);w[a]=d<c||t[3]>c?d:c;f[a]=m>g||t[3]<g?m:g;if(h===c&&l[3]<w[a]||h===g&&l[3]<f[a])n=w[a];else if(h===c&&l[3]>w[a]||h===g&&l[3]>f[a])n=f[a];u.push([k[x+a],n]);q.push(k[x+a]);r.push(n)}return{values:u,xData:q,yData:r}}})});k(b,"masters/indicators/supertrend.src.js",[],function(){})});
//# sourceMappingURL=supertrend.js.map